<?php
/**   ___ ___       ___ _______     ______                        __
 *   |   Y   .-----|   |   _   |   |   _  \ .-----.--------.---.-|__.-----.
 *   |.  |   |  _  |.  |.  1   |   |.  |   \|  _  |        |  _  |  |     |
 *   |.  |   |_____|.  |.  ____|   |.  |    |_____|__|__|__|___._|__|__|__|
 *   |:  1   |     |:  |:  |       |:  1    /
 *    \:.. ./      |::.|::.|       |::.. . /
 *     `---'       `---`---'       `------'
 *
 * Copyright (C) 2016-2025 Ernani José Camargo Azevedo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * VoIP Domain main framework interface module language file.
 *
 * @author     Ernani José Camargo Azevedo <azevedo@voipdomain.io>
 * @version    1.0
 * @package    VoIP Domain
 * @subpackage Interface
 * @copyright  2016-2025 Ernani José Camargo Azevedo. All rights reserved
 * @license    https://www.gnu.org/licenses/gpl-3.0.en.html
 */

/**
 * Add basic language structure (english)
 */
i18n_add ( "Warning!");
i18n_add ( "You must have");
i18n_add ( "enabled to use this system.");
i18n_add ( "Toggle navigation");
i18n_add ( "Administrator");
i18n_add ( "User");
i18n_add ( "Since");
i18n_add ( "m/d/Y");
i18n_add ( "Profile");
i18n_add ( "Logout");
i18n_add ( "Start");
i18n_add ( "Finish");
i18n_add ( "Entries");
i18n_add ( "Reports");
i18n_add ( "Online");
i18n_add ( "Search");
i18n_add ( "Add");
i18n_add ( "Change");
i18n_add ( "Remove");
i18n_add ( "View");
i18n_add ( "Report");
i18n_add ( "Edit");
i18n_add ( "Return");
i18n_add ( "New");
i18n_add ( "Version");
i18n_add ( "Developed by");
i18n_add ( "Published under %s license.");
i18n_add ( "Authentication");
i18n_add ( "Password");
i18n_add ( "Forgot your password?");
i18n_add ( "Login");
i18n_add ( "Error authorizing user.");
i18n_add ( "Dashboard");
i18n_add ( "system dashboard");
i18n_add ( "Answered calls");
i18n_add ( "Calls total");
i18n_add ( "Answer-Seizure Ratio");
i18n_add ( "of");
i18n_add ( "Answered or not answered or busy calls");
i18n_add ( "Network Efficiency Ratio");
i18n_add ( "Busy calls");
i18n_add ( "Answered or busy calls");
i18n_add ( "Subscriber Busy Ratio");
i18n_add ( "seconds");
i18n_add ( "Short Calls Ratio");
i18n_add ( "minutes");
i18n_add ( "Long Calls Ratio");
i18n_add ( "Registered extensions");
i18n_add ( "Extensions total");
i18n_add ( "Allocation Ratio");
i18n_add ( "MM/DD/YYYY");
i18n_add ( "MM/DD/YYYY HH:mm:ss");
i18n_add ( "through");
i18n_add ( "Apply");
i18n_add ( "Cancel");
i18n_add ( "From");
i18n_add ( "To");
i18n_add ( "Customize");
i18n_add ( "January");
i18n_add ( "February");
i18n_add ( "March");
i18n_add ( "April");
i18n_add ( "May");
i18n_add ( "June");
i18n_add ( "July");
i18n_add ( "August");
i18n_add ( "September");
i18n_add ( "October");
i18n_add ( "November");
i18n_add ( "December");
i18n_add ( "Error requesting statistics!");
i18n_add ( "Invalid username and/or password.");
i18n_add ( "Message not found.");
i18n_add ( "Session expired.");
i18n_add ( "Actions");
i18n_add ( "Description");
i18n_add ( "Su");
i18n_add ( "Mo");
i18n_add ( "Tu");
i18n_add ( "We");
i18n_add ( "Th");
i18n_add ( "Fr");
i18n_add ( "Sa");
i18n_add ( ",");
i18n_add ( ".");
i18n_add ( "en-us");
i18n_add ( "Yes");
i18n_add ( "No");
i18n_add ( "Low");
i18n_add ( "Medium");
i18n_add ( "High");
i18n_add ( "Resources");
i18n_add ( "Configurations");
i18n_add ( "Date/Time");
i18n_add ( "Direction");
i18n_add ( "Source");
i18n_add ( "Destination");
i18n_add ( "Duration ([[DD:]HH:]MM:SS)");
i18n_add ( "Result");
i18n_add ( "Cost");
i18n_add ( "Type");
i18n_add ( "Quality");
i18n_add ( "Observations");
i18n_add ( "Totals");
i18n_add ( "Received");
i18n_add ( "received");
i18n_add ( "Called");
i18n_add ( "called");
i18n_add ( "Answered");
i18n_add ( "Not answered");
i18n_add ( "Voice mail");
i18n_add ( "Busy");
i18n_add ( "Call failure");
i18n_add ( "Unknown");
i18n_add ( "Valid password!");
i18n_add ( "Cached password!");
i18n_add ( "Wrong password!");
i18n_add ( "Exception (call without password)");
i18n_add ( "Blocked");
i18n_add ( "Do not disturb!");
i18n_add ( "Picked up call");
i18n_add ( "Transhipped");
i18n_add ( "Central");
i18n_add ( "Call details");
i18n_add ( "Basic");
i18n_add ( "QOS");
i18n_add ( "Flow");
i18n_add ( "Download");
i18n_add ( "Server");
i18n_add ( "Source number");
i18n_add ( "Destination number");
i18n_add ( "Date and time");
i18n_add ( "Duration");
i18n_add ( "Call duration");
i18n_add ( "Billed");
i18n_add ( "Billing duration");
i18n_add ( "Cost center");
i18n_add ( "Gateway");
i18n_add ( "Caller SSRC");
i18n_add ( "Called SSRC");
i18n_add ( "RX packets");
i18n_add ( "Received packets");
i18n_add ( "TX packets");
i18n_add ( "Sent packets");
i18n_add ( "RX packet lost");
i18n_add ( "Receive packet lost");
i18n_add ( "TX packet lost");
i18n_add ( "Sent packet lost");
i18n_add ( "RX jitter");
i18n_add ( "Receive jitter");
i18n_add ( "TX jitter");
i18n_add ( "Sent jitter");
i18n_add ( "Round Trip Time");
i18n_add ( "PCAP");
i18n_add ( "Text");
i18n_add ( "Audio");
i18n_add ( "Close");
i18n_add ( "Call view");
i18n_add ( "Error requesting call information!");
i18n_add ( "Details");
i18n_add ( "%s call");
i18n_add ( "%s calls");
i18n_add ( "%s called");
i18n_add ( "%s calleds");
i18n_add ( "%s received");
i18n_add ( "%s receiveds");
i18n_add ( "and");
i18n_add ( "International");
i18n_add ( "Interstate");
i18n_add ( "Special");
i18n_add ( "Toll free");
i18n_add ( "Jitter");
i18n_add ( "Landline");
i18n_add ( "Latency");
i18n_add ( "Mobile");
i18n_add ( "Packet loss");
i18n_add ( "rx");
i18n_add ( "The finish date is required.");
i18n_add ( "The start date is required.");
i18n_add ( "tx");
i18n_add ( "Fast search");
i18n_add ( "results");
i18n_add ( "Number");
i18n_add ( "Local");
i18n_add ( "Marine");
i18n_add ( "Passworded");
i18n_add ( "Permissions");
i18n_add ( "Permitted");
i18n_add ( "Premium rate numbers");
i18n_add ( "Satellite");
i18n_add ( "Today");
i18n_add ( "Yesterday");
i18n_add ( "Last 7 days");
i18n_add ( "Last 30 days");
i18n_add ( "This month");
i18n_add ( "Previous month");
i18n_add ( "An error occurred while processing the request. An object with field name and a text error message will be returned to all inconsistency found.");
i18n_add ( "The text description of this field error.");
i18n_add ( "A comma delimited list of fields that should be returned.");
i18n_add ( "filter");
i18n_add ( "About");
i18n_add ( "system information");
i18n_add ( "VoIP Domain was created in 2016 by Ernani Azevedo, with the intention to create a simpler way to deploy a medium to big VoIP telephony system. The system tries to keep complex tasks as simpler they can be, with the least computational terms and automatized everything possible, so any manager with a little knowledge of VoIP can deploy a big, stable and feature rich PBX.");
i18n_add ( "This project was published as Open Source under GPL version 3 license. Fell free to contribute and make this a great tool to every company.");
i18n_add ( "English (United States)");
i18n_add ( "Portuguese (Brazil)");
i18n_add ( "An object containing the call dates and timestamps.");
i18n_add ( "An object containing the start date time and timestamp of the call.");
i18n_add ( "The UNIX timestamp for the start of the call.");
i18n_add ( "The ISO8601 date and time for the start of the call.");
i18n_add ( "An object containing the date time and timestamp when the call was answered.");
i18n_add ( "The UNIX timestamp for the time the call was answered (empty if not answered).");
i18n_add ( "The ISO8601 date and time for the time the call was answered (empty if not answered).");
i18n_add ( "An object containing the finish date time and timestamp of the call.");
i18n_add ( "The server information of the call.");
i18n_add ( "The server unique identifier of the call.");
i18n_add ( "The server description of the call.");
i18n_add ( "Warehouse 1");
i18n_add ( "The flow of the call, if is an outbound or inbound call.");
i18n_add ( "The total duration of call in seconds.");
i18n_add ( "The total ringing duration of call in seconds.");
i18n_add ( "The total billing duration of call in seconds.");
i18n_add ( "The result state of the call.");
i18n_add ( "Failed");
i18n_add ( "Congestion");
i18n_add ( "The translated result state of the call.");
i18n_add ( "If call has any cost, the value will be available here.");
i18n_add ( "If call has any cost, the translated value will be available here.");
i18n_add ( "The gateway information of the call.");
i18n_add ( "The gateway unique identifier that routed the call.");
i18n_add ( "The gateway description that routed the call.");
i18n_add ( "VoIP Provider");
i18n_add ( "The cost center information of the call.");
i18n_add ( "The cost center unique identifier of the call.");
i18n_add ( "The cost center description of the call.");
i18n_add ( "IT Department");
i18n_add ( "The cost center code of the call.");
i18n_add ( "The call source information.");
i18n_add ( "The type of call source endpoint.");
i18n_add ( "The translated type of call source endpoint.");
i18n_add ( "The description of call source endpoint.");
i18n_add ( "Extension");
i18n_add ( "Tollfree");
i18n_add ( "Services");
i18n_add ( "The translated description of call source endpoint.");
i18n_add ( "The source name.");
i18n_add ( "John Doe");
i18n_add ( "The source number.");
i18n_add ( "The call destination information.");
i18n_add ( "The type of call destination endpoint.");
i18n_add ( "The translated type of call destination endpoint.");
i18n_add ( "The description of call destination endpoint.");
i18n_add ( "The translated description of call destination endpoint.");
i18n_add ( "The destination name.");
i18n_add ( "The destination number.");
i18n_add ( "Who hung up the call, if was the caller or the called party.");
i18n_add ( "The call quality analysis.");
i18n_add ( "The MOS (Mean Opinion Score) of the call based on call statistics.");
i18n_add ( "The quality semaphore of the call quality.");
i18n_add ( "If available, the QOS (Quality Of Service) statistics of the call.");
i18n_add ( "Synchronization Source address.");
i18n_add ( "Our synchronization source (SSRC).");
i18n_add ( "Their synchronization source (SSRC).");
i18n_add ( "Statistics of sent packets.");
i18n_add ( "The number of sent packets.");
i18n_add ( "The number of sent packets lost.");
i18n_add ( "The percentage of sent packets lost.");
i18n_add ( "The sent packets jitter.");
i18n_add ( "Statistics of received packets.");
i18n_add ( "The number of received packets.");
i18n_add ( "The number of received packets lost.");
i18n_add ( "The percentage of received packets lost.");
i18n_add ( "The received packets jitter.");
i18n_add ( "The round trip time (RTT).");
i18n_add ( "The CODEC used on the call.");
i18n_add ( "The native codec used on the call.");
i18n_add ( "The read codec used on the call.");
i18n_add ( "The write codec used on the call.");
i18n_add ( "The call unique identifier.");
i18n_add ( "The call linked unique identifier, if any.");
i18n_add ( "The SIP unique identification number of the call.");
i18n_add ( "If the call was recorded.");
i18n_add ( "If the call SIP flow was captured.");
i18n_add ( "The flags of the call.");
i18n_add ( "The flag itself.");
i18n_add ( "Result code of operation.");
i18n_add ( "An object with result.");
i18n_add ( "The result of operation.");
i18n_add ( "System remote task pingback endpoint.");
i18n_add ( "Return result of a remote server operation task to the system.");
i18n_add ( "System remote server task unique identifier.");
i18n_add ( "The username of user to login.");
i18n_add ( "johndoe");
i18n_add ( "The password of user to login.");
i18n_add ( "mypassword");
i18n_add ( "The second factor authentication code of user to login.");
i18n_add ( "New system user session created sucessfully.");
i18n_add ( "System access cookie token.");
i18n_add ( "The status of session creation request.");
i18n_add ( "The login error message, if failed.");
i18n_add ( "User requires second factor authentication to login.");
i18n_add ( "System user authentication.");
i18n_add ( "Create a new system user session.");
i18n_add ( "Invalid second factor authentication code.");
i18n_add ( "User session was successfully destroyed.");
i18n_add ( "Empty system access cookie token.");
i18n_add ( "Destroy system user session.");
i18n_add ( "Destroy the system user session.");
i18n_add ( "The date of report start. If empty, 1 month early will be set.<br />**Format**: *MM/DD/YYYY*");
i18n_add ( "The date of report end. If empty, will be set today.<br />**Format**: *MM/DD/YYYY*");
i18n_add ( "An array containing the system dashboard data.");
i18n_add ( "Answer-Seizure Ratio (ASR).");
i18n_add ( "ASR percentage.");
i18n_add ( "ASR read value.");
i18n_add ( "ASR total value.");
i18n_add ( "Network Efficiency Ratio (NER).");
i18n_add ( "NER percentage.");
i18n_add ( "NER read value.");
i18n_add ( "NER total value.");
i18n_add ( "Subscriber Busy Ratio (SBR).");
i18n_add ( "SBR percentage.");
i18n_add ( "SBR read value.");
i18n_add ( "SBR total value.");
i18n_add ( "Short Calls Ratio (SCR).");
i18n_add ( "SCR percentage.");
i18n_add ( "SCR read value.");
i18n_add ( "SCR total value.");
i18n_add ( "Long Calls Ratio (LCR).");
i18n_add ( "LCR percentage.");
i18n_add ( "LCR read value.");
i18n_add ( "LCR total value.");
i18n_add ( "Allocation Ratio.");
i18n_add ( "Allocation percentage.");
i18n_add ( "Allocation read value.");
i18n_add ( "Allocation total value.");
i18n_add ( "System dashboard");
i18n_add ( "Generate the system dashboard statistics.");
i18n_add ( "An object containing information about the call.");
i18n_add ( "View call information");
i18n_add ( "Get detailed information about a call.");
i18n_add ( "An object containing information about the call SIP dump.");
i18n_add ( "If the SIP dump of the call is available.");
i18n_add ( "The SIP dump of the call.");
i18n_add ( "The call flow diagram with brief description.");
i18n_add ( "The call flow packets into text format.");
i18n_add ( "The call SIP dump PCAP file encoded with base64.");
i18n_add ( "View call SIP dump information");
i18n_add ( "Get detailed SIP dump information about a call.");
i18n_add ( "An object containing information about the call recording.");
i18n_add ( "If the recording of the call is available.");
i18n_add ( "The call recording MP3 file encoded with base64.");
i18n_add ( "View call recording information");
i18n_add ( "Get recording information about a call.");
i18n_add ( "An array containing the system objects.");
i18n_add ( "The internal unique identification number of the object.");
i18n_add ( "The extension number associated to object.");
i18n_add ( "The type of the object.");
i18n_add ( "The description of the object.");
i18n_add ( "Interface objects search.");
i18n_add ( "Search for all system objects (that's available at fastsearch).");
i18n_add ( "Filter search with this string. If not provided, return all objects.");
i18n_add ( "VoIP PBX management system.");
i18n_add ( "VoIP Domain debugging");
i18n_add ( "Code");
i18n_add ( "Remember me");
i18n_add ( "Please provide your second factor authentication code.");
i18n_add ( "List");
i18n_add ( "LOADING", "LOADING");
i18n_add ( "Filter...");
i18n_add ( "Clear data");
i18n_add ( "Copy");
i18n_add ( "PDF");
i18n_add ( "Excel");
i18n_add ( "CSV");
i18n_add ( "JSON");
i18n_add ( "Print");
i18n_add ( "No records found");
i18n_add ( "Showing _START_ to _END_ of _TOTAL_ records");
i18n_add ( "Showing 0 to 0 of 0 records");
i18n_add ( "(filtered out of _MAX_ total records)");
i18n_add ( "per page");
i18n_add ( "Wait...");
i18n_add ( "Processing...");
i18n_add ( "Filter");
i18n_add ( "Next");
i18n_add ( "Previous");
i18n_add ( "First");
i18n_add ( "Last");
i18n_add ( "Sort columns ascending");
i18n_add ( "Sort columns descending");
i18n_add ( "Added to clipboard");
i18n_add ( "Press <i>Ctrl</i> or </i>\u2318</i> + <i>C</i> to copy table to clipboard.<br />To cancel, click on this message or press ESC key.");
i18n_add ( "Total of %d records");
i18n_add ( "Total of 1 record");

/**
 * Add Brazilian Portuguese support
 */
i18n_add ( "Warning!", "Aviso!", "pt_BR");
i18n_add ( "You must have", "Você tem que ter", "pt_BR");
i18n_add ( "enabled to use this system.", "habilitado para utilizar este sistema.", "pt_BR");
i18n_add ( "Toggle navigation", "Alternar navegação", "pt_BR");
i18n_add ( "Administrator", "Administrador", "pt_BR");
i18n_add ( "User", "Usuário", "pt_BR");
i18n_add ( "Since", "Desde", "pt_BR");
i18n_add ( "m/d/Y", "d/m/Y", "pt_BR");
i18n_add ( "Profile", "Perfil", "pt_BR");
i18n_add ( "Logout", "Encerrar", "pt_BR");
i18n_add ( "Start", "Início", "pt_BR");
i18n_add ( "Finish", "Término", "pt_BR");
i18n_add ( "Entries", "Cadastros", "pt_BR");
i18n_add ( "Reports", "Relatórios", "pt_BR");
i18n_add ( "Online", "Online", "pt_BR");
i18n_add ( "Search", "Pesquisar", "pt_BR");
i18n_add ( "Add", "Adicionar", "pt_BR");
i18n_add ( "Change", "Alterar", "pt_BR");
i18n_add ( "Remove", "Remover", "pt_BR");
i18n_add ( "View", "Visualizar", "pt_BR");
i18n_add ( "Report", "Relatório", "pt_BR");
i18n_add ( "Edit", "Editar", "pt_BR");
i18n_add ( "Return", "Retornar", "pt_BR");
i18n_add ( "New", "Novo", "pt_BR");
i18n_add ( "Version", "Versão", "pt_BR");
i18n_add ( "Developed by", "Desenvolvido por", "pt_BR");
i18n_add ( "Published under %s license.", "Disponibilizado sob licença %s.", "pt_BR");
i18n_add ( "Authentication", "Autenticação", "pt_BR");
i18n_add ( "Password", "Senha", "pt_BR");
i18n_add ( "Forgot your password?", "Esqueceu a senha?", "pt_BR");
i18n_add ( "Login", "Autenticar", "pt_BR");
i18n_add ( "Error authorizing user.", "Erro ao autorizar usuário.", "pt_BR");
i18n_add ( "Dashboard", "Dashboard", "pt_BR");
i18n_add ( "system dashboard", "painel do sistema", "pt_BR");
i18n_add ( "Answered calls", "Ligações antendidas", "pt_BR");
i18n_add ( "Calls total", "Total de ligações", "pt_BR");
i18n_add ( "Answer-Seizure Ratio", "Answer-Seizure Ratio", "pt_BR");
i18n_add ( "of", "de", "pt_BR");
i18n_add ( "Answered or not answered or busy calls", "Ligações antendidas ou não atendidas ou ocupadas", "pt_BR");
i18n_add ( "Network Efficiency Ratio", "Network Efficiency Ratio", "pt_BR");
i18n_add ( "Busy calls", "Ligações ocupadas", "pt_BR");
i18n_add ( "Answered or busy calls", "Ligações atendidas ou ocupadas", "pt_BR");
i18n_add ( "Subscriber Busy Ratio", "Subscriber Busy Ratio", "pt_BR");
i18n_add ( "seconds", "segundos", "pt_BR");
i18n_add ( "Short Calls Ratio", "Short Calls Ratio", "pt_BR");
i18n_add ( "minutes", "minutos", "pt_BR");
i18n_add ( "Long Calls Ratio", "Long Calls Ratio", "pt_BR");
i18n_add ( "Registered extensions", "Ramais registrados", "pt_BR");
i18n_add ( "Extensions total", "Total de ramais", "pt_BR");
i18n_add ( "Allocation Ratio", "Allocation Ratio", "pt_BR");
i18n_add ( "MM/DD/YYYY", "DD/MM/YYYY", "pt_BR");
i18n_add ( "MM/DD/YYYY HH:mm:ss", "DD/MM/YYYY HH:mm:ss", "pt_BR");
i18n_add ( "through", "até", "pt_BR");
i18n_add ( "Apply", "Aplicar", "pt_BR");
i18n_add ( "Cancel", "Cancelar", "pt_BR");
i18n_add ( "From", "De", "pt_BR");
i18n_add ( "To", "A", "pt_BR");
i18n_add ( "Customize", "Customizar", "pt_BR");
i18n_add ( "January", "Janeiro", "pt_BR");
i18n_add ( "February", "Fevereiro", "pt_BR");
i18n_add ( "March", "Março", "pt_BR");
i18n_add ( "April", "Abril", "pt_BR");
i18n_add ( "May", "Maio", "pt_BR");
i18n_add ( "June", "Junho", "pt_BR");
i18n_add ( "July", "Júlio", "pt_BR");
i18n_add ( "August", "Agosto", "pt_BR");
i18n_add ( "September", "Setembro", "pt_BR");
i18n_add ( "October", "Outubro", "pt_BR");
i18n_add ( "November", "Novembro", "pt_BR");
i18n_add ( "December", "Dezembro", "pt_BR");
i18n_add ( "Error requesting statistics!", "Erro ao requisitar estatísticas!", "pt_BR");
i18n_add ( "Invalid username and/or password.", "Usuário e/ou senha inválidos", "pt_BR");
i18n_add ( "Message not found.", "Mensagem não encontrada.", "pt_BR");
i18n_add ( "Session expired.", "Sessão expirada.", "pt_BR");
i18n_add ( "Actions", "Ações", "pt_BR");
i18n_add ( "Description", "Descrição", "pt_BR");
i18n_add ( "Su", "Do", "pt_BR");
i18n_add ( "Mo", "2ª", "pt_BR");
i18n_add ( "Tu", "3ª", "pt_BR");
i18n_add ( "We", "4ª", "pt_BR");
i18n_add ( "Th", "5ª", "pt_BR");
i18n_add ( "Fr", "6ª", "pt_BR");
i18n_add ( "Sa", "Sá", "pt_BR");
i18n_add ( ",", ".", "pt_BR");
i18n_add ( ".", ",", "pt_BR");
i18n_add ( "en-us", "pt-br", "pt_BR");
i18n_add ( "Yes", "Sim", "pt_BR");
i18n_add ( "No", "Não", "pt_BR");
i18n_add ( "Low", "Baixo", "pt_BR");
i18n_add ( "Medium", "Médio", "pt_BR");
i18n_add ( "High", "Alto", "pt_BR");
i18n_add ( "Resources", "Recursos", "pt_BR");
i18n_add ( "Configurations", "Configurações", "pt_BR");
i18n_add ( "Date/Time", "Data/Hora", "pt_BR");
i18n_add ( "Direction", "Direção", "pt_BR");
i18n_add ( "Source", "Origem", "pt_BR");
i18n_add ( "Destination", "Destino", "pt_BR");
i18n_add ( "Duration ([[DD:]HH:]MM:SS)", "Duração ([[DD:]HH:]MM:SS)", "pt_BR");
i18n_add ( "Result", "Resultado", "pt_BR");
i18n_add ( "Cost", "Custo", "pt_BR");
i18n_add ( "Type", "Tipo", "pt_BR");
i18n_add ( "Quality", "Qualidade", "pt_BR");
i18n_add ( "Observations", "Observações", "pt_BR");
i18n_add ( "Totals", "Totais", "pt_BR");
i18n_add ( "Received", "Recebida", "pt_BR");
i18n_add ( "received", "recebida", "pt_BR");
i18n_add ( "Called", "Efetuada", "pt_BR");
i18n_add ( "called", "efetuada", "pt_BR");
i18n_add ( "Answered", "Atendida", "pt_BR");
i18n_add ( "Not answered", "Não atendida", "pt_BR");
i18n_add ( "Voice mail", "Correio de voz", "pt_BR");
i18n_add ( "Busy", "Ocupado", "pt_BR");
i18n_add ( "Call failure", "Falha na ligação", "pt_BR");
i18n_add ( "Unknown", "Desconhecido", "pt_BR");
i18n_add ( "Valid password!", "Senha válida!", "pt_BR");
i18n_add ( "Cached password!", "Senha em cache!", "pt_BR");
i18n_add ( "Wrong password!", "Senha errada!", "pt_BR");
i18n_add ( "Exception (call without password)", "Excessão (sem senha)", "pt_BR");
i18n_add ( "Blocked", "Bloqueado", "pt_BR");
i18n_add ( "Do not disturb!", "Não perturbe!", "pt_BR");
i18n_add ( "Picked up call", "Ligação capturada", "pt_BR");
i18n_add ( "Transhipped", "Transbordada", "pt_BR");
i18n_add ( "Central", "Central", "pt_BR");
i18n_add ( "Call details", "Detalhes da ligação", "pt_BR");
i18n_add ( "Basic", "Básico", "pt_BR");
i18n_add ( "QOS", "QOS", "pt_BR");
i18n_add ( "Flow", "Fluxo", "pt_BR");
i18n_add ( "Download", "Baixar", "pt_BR");
i18n_add ( "Server", "Servidor", "pt_BR");
i18n_add ( "Source number", "Número de origem", "pt_BR");
i18n_add ( "Destination number", "Número de destino", "pt_BR");
i18n_add ( "Date and time", "Data e hora", "pt_BR");
i18n_add ( "Duration", "Duração", "pt_BR");
i18n_add ( "Call duration", "Duração da ligação", "pt_BR");
i18n_add ( "Billed", "Bilhetado", "pt_BR");
i18n_add ( "Billing duration", "Duração da bilhetagem", "pt_BR");
i18n_add ( "Cost center", "Centro de custo", "pt_BR");
i18n_add ( "Gateway", "Gateway", "pt_BR");
i18n_add ( "Caller SSRC", "SSRC originador", "pt_BR");
i18n_add ( "Called SSRC", "SSRC destinatário", "pt_BR");
i18n_add ( "RX packets", "Pacotes recebidos", "pt_BR");
i18n_add ( "Received packets", "Pacotes recebidos", "pt_BR");
i18n_add ( "TX packets", "Pacotes enviados", "pt_BR");
i18n_add ( "Sent packets", "Pacotes enviados", "pt_BR");
i18n_add ( "RX packet lost", "Perda de pacotes recebidos", "pt_BR");
i18n_add ( "Receive packet lost", "Perda de pacotes recebidos", "pt_BR");
i18n_add ( "TX packet lost", "Perda de pacotes enviados", "pt_BR");
i18n_add ( "Sent packet lost", "Perda de pacotes enviados", "pt_BR");
i18n_add ( "RX jitter", "Jitter recebido", "pt_BR");
i18n_add ( "Receive jitter", "Jitter recebido", "pt_BR");
i18n_add ( "TX jitter", "Jitter enviado", "pt_BR");
i18n_add ( "Sent jitter", "Jitter enviado", "pt_BR");
i18n_add ( "Round Trip Time", "Tempo médio de envio", "pt_BR");
i18n_add ( "PCAP", "PCAP", "pt_BR");
i18n_add ( "Text", "Texto", "pt_BR");
i18n_add ( "Audio", "Áudio", "pt_BR");
i18n_add ( "Close", "Fechar", "pt_BR");
i18n_add ( "Call view", "Visualização de ligação", "pt_BR");
i18n_add ( "Error requesting call information!", "Erro ao requisitar informações da ligação!", "pt_BR");
i18n_add ( "Details", "Detalhes", "pt_BR");
i18n_add ( "%s call", "%s ligação", "pt_BR");
i18n_add ( "%s calls", "%s ligações", "pt_BR");
i18n_add ( "%s called", "%s efetuada", "pt_BR");
i18n_add ( "%s calleds", "%s efetuadas", "pt_BR");
i18n_add ( "%s received", "%s recebida", "pt_BR");
i18n_add ( "%s receiveds", "%s recebidas", "pt_BR");
i18n_add ( "and", "e", "pt_BR");
i18n_add ( "International", "Internacional", "pt_BR");
i18n_add ( "Interstate", "Interestadual", "pt_BR");
i18n_add ( "Toll free", "Gratuíta", "pt_BR");
i18n_add ( "Special", "Especial", "pt_BR");
i18n_add ( "Jitter", "Jitter", "pt_BR");
i18n_add ( "Landline", "Fixo", "pt_BR");
i18n_add ( "Latency", "Latência", "pt_BR");
i18n_add ( "Mobile", "Móvel", "pt_BR");
i18n_add ( "Packet loss", "Perda de pacotes", "pt_BR");
i18n_add ( "rx", "rx", "pt_BR");
i18n_add ( "The finish date is required.", "A data final é obrigatória.", "pt_BR");
i18n_add ( "The start date is required.", "A data inicial é obrigatória.", "pt_BR");
i18n_add ( "tx", "tx", "pt_BR");
i18n_add ( "Fast search", "Pesquisa rápida", "pt_BR");
i18n_add ( "results", "resultados", "pt_BR");
i18n_add ( "Number", "Número", "pt_BR");
i18n_add ( "Local", "Local", "pt_BR");
i18n_add ( "Marine", "Marítimo", "pt_BR");
i18n_add ( "Passworded", "Com senha", "pt_BR");
i18n_add ( "Permissions", "Permissões", "pt_BR");
i18n_add ( "Permitted", "Permitido", "pt_BR");
i18n_add ( "Premium rate numbers", "Tarifação especial", "pt_BR");
i18n_add ( "Satellite", "Satélite", "pt_BR");
i18n_add ( "Today", "Hoje", "pt_BR");
i18n_add ( "Yesterday", "Ontem", "pt_BR");
i18n_add ( "Last 7 days", "Últimos 7 dias", "pt_BR");
i18n_add ( "Last 30 days", "Últimos 30 dias", "pt_BR");
i18n_add ( "This month", "Este mês", "pt_BR");
i18n_add ( "Previous month", "Mês anterior", "pt_BR");
i18n_add ( "An error occurred while processing the request. An object with field name and a text error message will be returned to all inconsistency found.", "Ocorreu um erro ao processar a solicitação. Um objeto com o nome do campo e uma mensagem de erro de texto serão retornados para todas as inconsistências encontradas.", "pt_BR");
i18n_add ( "The text description of this field error.", "O texto descrevendo o erro deste campo.", "pt_BR");
i18n_add ( "A comma delimited list of fields that should be returned.", "Uma lista separada por vírgula dos campos que devem ser retornados.", "pt_BR");
i18n_add ( "filter", "filtro", "pt_BR");
i18n_add ( "About", "Sobre", "pt_BR");
i18n_add ( "system information", "informações do sistema", "pt_BR");
i18n_add ( "VoIP Domain was created in 2016 by Ernani Azevedo, with the intention to create a simpler way to deploy a medium to big VoIP telephony system. The system tries to keep complex tasks as simpler they can be, with the least computational terms and automatized everything possible, so any manager with a little knowledge of VoIP can deploy a big, stable and feature rich PBX.", "O VoIP Domain foi criado em 2016 por Ernani Azevedo, com a intenção de criar uma maneira simples de instalar um sistema de telefonia VoIP médio a grande. O sistema tenta manter tarefas complexas o mais simples que elas possam ser, com o mínimo de termos computacionais e automatizando tudo que seja possível, para que quaisquer gerente com pouco conhecimento de VoIP possa instalar um PABX grande, estável e repleto de recursos.", "pt_BR");
i18n_add ( "This project was published as Open Source under GPL version 3 license. Fell free to contribute and make this a great tool to every company.", "Este projeto foi publicado com Código Aberto, sob a licença GPL versão 3. Sinta-se a vontade para contribuir e fazer deste uma grande ferramenta para todas empresas.", "pt_BR");
i18n_add ( "English (United States)", "Inglês (Estados Unidos)", "pt_BR");
i18n_add ( "Portuguese (Brazil)", "Português (Brasil)", "pt_BR");
i18n_add ( "An object containing the call dates and timestamps.", "Um objeto contendo a data e hora das ligações.", "pt_BR");
i18n_add ( "An object containing the start date time and timestamp of the call.", "Um objeto contendo a data e hora do início da ligação.", "pt_BR");
i18n_add ( "The UNIX timestamp for the start of the call.", "O timestamp UNIX do início da ligação.", "pt_BR");
i18n_add ( "The ISO8601 date and time for the start of the call.", "A data e hora no formato ISO8601 do início da ligação.", "pt_BR");
i18n_add ( "An object containing the date time and timestamp when the call was answered.", "Um objeto contendo a data, hora e timestamp de quando a ligação foi atendida.", "pt_BR");
i18n_add ( "The UNIX timestamp for the time the call was answered (empty if not answered).", "O timestamp UNIX para o momento que a ligação foi atendida (vazio se não atendida).", "pt_BR");
i18n_add ( "The ISO8601 date and time for the time the call was answered (empty if not answered).", "A data e hora no formato ISO9601 para o momento que a ligação foi atendida (vazio se não atendida).", "pt_BR");
i18n_add ( "An object containing the finish date time and timestamp of the call.", "Um objeto contendo a data, hora e timestamp do término da ligação.", "pt_BR");
i18n_add ( "The server information of the call.", "As informações do servidor da ligação.", "pt_BR");
i18n_add ( "The server unique identifier of the call.", "O identificador único do servidor da ligação.", "pt_BR");
i18n_add ( "The server description of the call.", "A descrição do servidor da ligação.", "pt_BR");
i18n_add ( "Warehouse 1", "Depósito 1", "pt_BR");
i18n_add ( "The flow of the call, if is an outbound or inbound call.", "O fluxo da ligação, se é uma chamada sainte ou entrate.", "pt_BR");
i18n_add ( "The total duration of call in seconds.", "A duração total da chamada em segundos.", "pt_BR");
i18n_add ( "The total ringing duration of call in seconds.", "A duração do toque de chamada da ligação em segundos.", "pt_BR");
i18n_add ( "The total billing duration of call in seconds.", "A duração total de bilhetagem da ligação em segundos.", "pt_BR");
i18n_add ( "The result state of the call.", "O estado final da ligação.", "pt_BR");
i18n_add ( "Failed", "Falhou", "pt_BR");
i18n_add ( "Congestion", "Congestionamento", "pt_BR");
i18n_add ( "The translated result state of the call.", "O estado final da ligação traduzido.", "pt_BR");
i18n_add ( "If call has any cost, the value will be available here.", "Se a ligação teve algum custo, ele estará aqui.", "pt_BR");
i18n_add ( "If call has any cost, the translated value will be available here.", "Se a ligação teve algum custo, o valor traduzido estará aqui.", "pt_BR");
i18n_add ( "The gateway information of the call.", "As informações do gateway da chamada.", "pt_BR");
i18n_add ( "The gateway unique identifier that routed the call.", "O identificador único do gateway que realizou a chamada.", "pt_BR");
i18n_add ( "The gateway description that routed the call.", "A descrição do gateway que realizou a chamada.", "pt_BR");
i18n_add ( "VoIP Provider", "Provedor VoIP", "pt_BR");
i18n_add ( "The cost center information of the call.", "Informações do centro de custo da chamada.", "pt_BR");
i18n_add ( "The cost center unique identifier of the call.", "O identificador único do centro de custo da chamada.", "pt_BR");
i18n_add ( "The cost center description of the call.", "A descrição do centro de custo da chamada.", "pt_BR");
i18n_add ( "IT Department", "Departamento de TI", "pt_BR");
i18n_add ( "The cost center code of the call.", "O código do centro de custo da chamada.", "pt_BR");
i18n_add ( "The call source information.", "Informações da origem da chamada.", "pt_BR");
i18n_add ( "The type of call source endpoint.", "O tipo de dispositivo de origem da chamada.", "pt_BR");
i18n_add ( "The translated type of call source endpoint.", "O tipo de dispositivo de origem da chamada traduzido.", "pt_BR");
i18n_add ( "The description of call source endpoint.", "A descrição do dispositivo de origem da chamada.", "pt_BR");
i18n_add ( "Extension", "Extensão", "pt_BR");
i18n_add ( "Tollfree", "Ligação gratuíta", "pt_BR");
i18n_add ( "Services", "Serviços", "pt_BR");
i18n_add ( "The translated description of call source endpoint.", "A descrição do dispositivo de origem da chamada traduzido.", "pt_BR");
i18n_add ( "The source name.", "O nome da origem.", "pt_BR");
i18n_add ( "John Doe", "Zé Ninguém", "pt_BR");
i18n_add ( "The source number.", "O número de origem.", "pt_BR");
i18n_add ( "The call destination information.", "Informações do destino da chamada.", "pt_BR");
i18n_add ( "The type of call destination endpoint.", "O tipo de dispositivo de destino da chamada.", "pt_BR");
i18n_add ( "The translated type of call destination endpoint.", "O tipo de dispositivo de destino da chamada traduzido.", "pt_BR");
i18n_add ( "The description of call destination endpoint.", "A descrição do dispositivo de destino da chamada.", "pt_BR");
i18n_add ( "The translated description of call destination endpoint.", "A descrição do dispositivo de destino da chamada traduzida.", "pt_BR");
i18n_add ( "The destination name.", "O nome do destinatário.", "pt_BR");
i18n_add ( "The destination number.", "O número do destinatário.", "pt_BR");
i18n_add ( "Who hung up the call, if was the caller or the called party.", "Quem finalizou a ligação, se foi o chamador ou o destinatário.", "pt_BR");
i18n_add ( "The call quality analysis.", "A análise de qualidade da ligação.", "pt_BR");
i18n_add ( "The MOS (Mean Opinion Score) of the call based on call statistics.", "O MOS (Mean Opinion Score/Pontuação de Opinião Média) da chamada baseado nas estatísticas da ligação.", "pt_BR");
i18n_add ( "The quality semaphore of the call quality.", "O semáforo de qualidade da qualidade da ligação.", "pt_BR");
i18n_add ( "If available, the QOS (Quality Of Service) statistics of the call.", "Se disponível, as estatísticas do QOS (Quality Of Service/Qualidade De Serviço) da ligação.", "pt_BR");
i18n_add ( "Synchronization Source address.", "Endereço de origem de sincronização.", "pt_BR");
i18n_add ( "Our synchronization source (SSRC).", "Nossa origem de sincronização (SSRC).", "pt_BR");
i18n_add ( "Their synchronization source (SSRC).", "A origem de sincronização deles (SSRC).", "pt_BR");
i18n_add ( "Statistics of sent packets.", "Estatíticas de pacotes enviados.", "pt_BR");
i18n_add ( "The number of sent packets.", "O número de pacotes enviados.", "pt_BR");
i18n_add ( "The number of sent packets lost.", "O número de pacotes enviados perdidos.", "pt_BR");
i18n_add ( "The percentage of sent packets lost.", "A porcentagem de pacotes enviados perdidos.", "pt_BR");
i18n_add ( "The sent packets jitter.", "O jitter dos pacotes enviados.", "pt_BR");
i18n_add ( "Statistics of received packets.", "Estatísticas de pacotes recebidos.", "pt_BR");
i18n_add ( "The number of received packets.", "", "pt_BR");
i18n_add ( "The number of received packets lost.", "", "pt_BR");
i18n_add ( "The percentage of received packets lost.", "", "pt_BR");
i18n_add ( "The received packets jitter.", "", "pt_BR");
i18n_add ( "The round trip time (RTT).", "", "pt_BR");
i18n_add ( "The CODEC used on the call.", "", "pt_BR");
i18n_add ( "The native codec used on the call.", "", "pt_BR");
i18n_add ( "The read codec used on the call.", "", "pt_BR");
i18n_add ( "The write codec used on the call.", "", "pt_BR");
i18n_add ( "The call unique identifier.", "", "pt_BR");
i18n_add ( "The call linked unique identifier, if any.", "", "pt_BR");
i18n_add ( "The SIP unique identification number of the call.", "", "pt_BR");
i18n_add ( "If the call was recorded.", "", "pt_BR");
i18n_add ( "If the call SIP flow was captured.", "", "pt_BR");
i18n_add ( "The flags of the call.", "", "pt_BR");
i18n_add ( "The flag itself.", "", "pt_BR");
i18n_add ( "Result code of operation.", "O código resultante da operação.", "pt_BR");
i18n_add ( "An object with result.", "Um objeto com o resultado.", "pt_BR");
i18n_add ( "The result of operation.", "O resultado da operação.", "pt_BR");
i18n_add ( "System remote task pingback endpoint.", "Endpoint para retorno de tarefa remota do sistema.", "pt_BR");
i18n_add ( "Return result of a remote server operation task to the system.", "Retorna o resultado de uma tarefa realizada por um servidor remoto do sistema.", "pt_BR");
i18n_add ( "System remote server task unique identifier.", "O identificador único da tarefa do sistema para o servidor remoto.", "pt_BR");
i18n_add ( "The username of user to login.", "O nome de usuário para acessar.", "pt_BR");
i18n_add ( "johndoe", "zéninguém", "pt_BR");
i18n_add ( "The password of user to login.", "A senha do usuário para acessar.", "pt_BR");
i18n_add ( "mypassword", "minhasenha", "pt_BR");
i18n_add ( "The second factor authentication code of user to login.", "O código da autenticação de dois fatores do usuário para acessar.", "pt_BR");
i18n_add ( "New system user session created sucessfully.", "Nova sessão do usuário do sistema criada com sucesso.", "pt_BR");
i18n_add ( "System access cookie token.", "Cookie contendo código de acesso ao sistema.", "pt_BR");
i18n_add ( "The status of session creation request.", "O estado da requisićão de criação de sessão.", "pt_BR");
i18n_add ( "The login error message, if failed.", "A mensagem de erro de autenticação, se falhou.", "pt_BR");
i18n_add ( "User requires second factor authentication to login.", "Usuário requer autenticação de dois fatores para acessar.", "pt_BR");
i18n_add ( "System user authentication.", "Autenticação de usuário do sistema.", "pt_BR");
i18n_add ( "Create a new system user session.", "Criar uma nova sessão de usuário no sistema.", "pt_BR");
i18n_add ( "Invalid second factor authentication code.", "Código de autenticação de dois fatores inválido.", "pt_BR");
i18n_add ( "User session was successfully destroyed.", "Sessão de usuário foi destruída com sucesso.", "pt_BR");
i18n_add ( "Empty system access cookie token.", "Cookie de acesso ao sistema vazia.", "pt_BR");
i18n_add ( "Destroy system user session.", "Destruir sessão de usuário do sistema.", "pt_BR");
i18n_add ( "Destroy the system user session.", "Destrói a sessão do usuário do sistema.", "pt_BR");
i18n_add ( "The date of report start. If empty, 1 month early will be set.<br />**Format**: *MM/DD/YYYY*", "", "pt_BR");
i18n_add ( "The date of report end. If empty, will be set today.<br />**Format**: *MM/DD/YYYY*", "", "pt_BR");
i18n_add ( "An array containing the system dashboard data.", "", "pt_BR");
i18n_add ( "Answer-Seizure Ratio (ASR).", "", "pt_BR");
i18n_add ( "ASR percentage.", "", "pt_BR");
i18n_add ( "ASR read value.", "", "pt_BR");
i18n_add ( "ASR total value.", "", "pt_BR");
i18n_add ( "Network Efficiency Ratio (NER).", "", "pt_BR");
i18n_add ( "NER percentage.", "", "pt_BR");
i18n_add ( "NER read value.", "", "pt_BR");
i18n_add ( "NER total value.", "", "pt_BR");
i18n_add ( "Subscriber Busy Ratio (SBR).", "", "pt_BR");
i18n_add ( "SBR percentage.", "", "pt_BR");
i18n_add ( "SBR read value.", "", "pt_BR");
i18n_add ( "SBR total value.", "", "pt_BR");
i18n_add ( "Short Calls Ratio (SCR).", "", "pt_BR");
i18n_add ( "SCR percentage.", "", "pt_BR");
i18n_add ( "SCR read value.", "", "pt_BR");
i18n_add ( "SCR total value.", "", "pt_BR");
i18n_add ( "Long Calls Ratio (LCR).", "", "pt_BR");
i18n_add ( "LCR percentage.", "", "pt_BR");
i18n_add ( "LCR read value.", "", "pt_BR");
i18n_add ( "LCR total value.", "", "pt_BR");
i18n_add ( "Allocation Ratio.", "", "pt_BR");
i18n_add ( "Allocation percentage.", "", "pt_BR");
i18n_add ( "Allocation read value.", "", "pt_BR");
i18n_add ( "Allocation total value.", "", "pt_BR");
i18n_add ( "System dashboard", "", "pt_BR");
i18n_add ( "Generate the system dashboard statistics.", "", "pt_BR");
i18n_add ( "An object containing information about the call.", "", "pt_BR");
i18n_add ( "View call information", "", "pt_BR");
i18n_add ( "Get detailed information about a call.", "", "pt_BR");
i18n_add ( "An object containing information about the call SIP dump.", "", "pt_BR");
i18n_add ( "If the SIP dump of the call is available.", "", "pt_BR");
i18n_add ( "The SIP dump of the call.", "", "pt_BR");
i18n_add ( "The call flow diagram with brief description.", "", "pt_BR");
i18n_add ( "The call flow packets into text format.", "", "pt_BR");
i18n_add ( "The call SIP dump PCAP file encoded with base64.", "", "pt_BR");
i18n_add ( "View call SIP dump information", "", "pt_BR");
i18n_add ( "Get detailed SIP dump information about a call.", "", "pt_BR");
i18n_add ( "An object containing information about the call recording.", "", "pt_BR");
i18n_add ( "If the recording of the call is available.", "", "pt_BR");
i18n_add ( "The call recording MP3 file encoded with base64.", "", "pt_BR");
i18n_add ( "View call recording information", "", "pt_BR");
i18n_add ( "Get recording information about a call.", "", "pt_BR");
i18n_add ( "An array containing the system objects.", "", "pt_BR");
i18n_add ( "The internal unique identification number of the object.", "", "pt_BR");
i18n_add ( "The extension number associated to object.", "", "pt_BR");
i18n_add ( "The type of the object.", "O tipo do objeto.", "pt_BR");
i18n_add ( "The description of the object.", "A descrição do objeto.", "pt_BR");
i18n_add ( "Interface objects search.", "Pequisa de objetos de interface.", "pt_BR");
i18n_add ( "Search for all system objects (that's available at fastsearch).", "Pesquisa por todos objetos do sistema (que estejam disponíveis na pesquisa rápida).", "pt_BR");
i18n_add ( "Filter search with this string. If not provided, return all objects.", "Filtrar a pesquisa por esta string. Se não informada, retorna todos objetos.", "pt_BR");
i18n_add ( "VoIP PBX management system.", "Sistema de gerenciamento de PABX VoIP.", "pt_BR");
i18n_add ( "VoIP Domain debugging", "Depuração do VoIP Domain", "pt_BR");
i18n_add ( "Code", "Código", "pt_BR");
i18n_add ( "Remember me", "Lembrar-me", "pt_BR");
i18n_add ( "Please provide your second factor authentication code.", "Favor informar o seu código de autenticação de dois fatores.", "pt_BR");
i18n_add ( "List", "Listar", "pt_BR");
i18n_add ( "LOADING", "CARREGANDO", "pt_BR");
i18n_add ( "Clear data", "Limpar dados", "pt_BR", "I18N_GLOBAL");
i18n_add ( "Filter...", "Filtro...", "pt_BR", "I18N_GLOBAL");
i18n_add ( "Copy", "Copiar", "pt_BR", "I18N_GLOBAL");
i18n_add ( "PDF", "PDF", "pt_BR", "I18N_GLOBAL");
i18n_add ( "Excel", "Excel", "pt_BR", "I18N_GLOBAL");
i18n_add ( "CSV", "CSV", "pt_BR", "I18N_GLOBAL");
i18n_add ( "JSON", "JSON", "pt_BR", "I18N_GLOBAL");
i18n_add ( "Print", "Imprimir", "pt_BR", "I18N_GLOBAL");
i18n_add ( "Showing _START_ to _END_ of _TOTAL_ records", "Exibindo _START_ a _END_ de _TOTAL_ registros", "pt_BR", "I18N_GLOBAL");
i18n_add ( "Showing 0 to 0 of 0 records", "Exibindo 0 a 0 de 0 registros", "pt_BR", "I18N_GLOBAL");
i18n_add ( "(filtered out of _MAX_ total records)", "(filtrado de _MAX_ registros no total)", "pt_BR", "I18N_GLOBAL");
i18n_add ( "per page", "por página", "pt_BR", "I18N_GLOBAL");
i18n_add ( "Wait...", "Aguarde...", "pt_BR", "I18N_GLOBAL");
i18n_add ( "Processing...", "Processando...", "pt_BR", "I18N_GLOBAL");
i18n_add ( "No records found", "Nenhum registro encontrado", "pt_BR", "I18N_GLOBAL");
i18n_add ( "Filter", "Filtro", "pt_BR", "I18N_GLOBAL");
i18n_add ( "Next", "Seguinte", "pt_BR", "I18N_GLOBAL");
i18n_add ( "Previous", "Anterior", "pt_BR", "I18N_GLOBAL");
i18n_add ( "First", "Primeira", "pt_BR", "I18N_GLOBAL");
i18n_add ( "Last", "Última", "pt_BR", "I18N_GLOBAL");
i18n_add ( "Sort columns ascending", "Ordenar colunas de forma ascendente", "pt_BR", "I18N_GLOBAL");
i18n_add ( "Sort columns descending", "Ordenar colunas de forma descendente", "pt_BR", "I18N_GLOBAL");
i18n_add ( "Added to clipboard", "Adicionado para área de tranferência", "pt_BR", "I18N_GLOBAL");
i18n_add ( "Press <i>Ctrl</i> or </i>\u2318</i> + <i>C</i> to copy table to clipboard.<br />To cancel, click on this message or press ESC key.", "Pressione <i>Ctrl</i> ou <i>\u2318</i> + <i>C</i> para copiar os dados da tabela para a área de transferência.<br />Para cancelar, clique sobre esta mensagem ou pressione a tecla ESC.", "pt_BR", "I18N_GLOBAL");
i18n_add ( "Total of %d records", "Total de %d registros", "pt_BR", "I18N_GLOBAL");
i18n_add ( "Total of 1 record", "Total de 1 registro", "pt_BR", "I18N_GLOBAL");
?>
