<?php
/**   ___ ___       ___ _______     ______                        __
 *   |   Y   .-----|   |   _   |   |   _  \ .-----.--------.---.-|__.-----.
 *   |.  |   |  _  |.  |.  1   |   |.  |   \|  _  |        |  _  |  |     |
 *   |.  |   |_____|.  |.  ____|   |.  |    |_____|__|__|__|___._|__|__|__|
 *   |:  1   |     |:  |:  |       |:  1    /
 *    \:.. ./      |::.|::.|       |::.. . /
 *     `---'       `---`---'       `------'
 *
 * Copyright (C) 2016-2025 Ernani José Camargo Azevedo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * VoIP Domain IVRs module language file.
 *
 * @author     Ernani José Camargo Azevedo <azevedo@voipdomain.io>
 * @version    1.0
 * @package    VoIP Domain
 * @subpackage IVR
 * @copyright  2016-2025 Ernani José Camargo Azevedo. All rights reserved
 * @license    https://www.gnu.org/licenses/gpl-3.0.en.html
 */

/**
 * Add basic language structure (english)
 */
i18n_add ( "IVRs");
i18n_add ( "IVR search");
i18n_add ( "Name");
i18n_add ( "IVR addition");
i18n_add ( "IVR visualization");
i18n_add ( "IVR edition");
i18n_add ( "IVR name");
i18n_add ( "IVR description");
i18n_add ( "Start options");
i18n_add ( "Auto answer");
i18n_add ( "Delay");
i18n_add ( "Wait seconds before answer");
i18n_add ( "In");
i18n_add ( "Out");
i18n_add ( "The IVR operator ID.");
i18n_add ( "The IVR operator left distance on the workflow.");
i18n_add ( "The IVR operator top distance on the workflow.");
i18n_add ( "The output name of IVR operator.");
i18n_add ( "The output label of IVR operator.");
i18n_add ( "Output");
i18n_add ( "The IVR operator ID link origin.");
i18n_add ( "The IVR operator connector link origin.");
i18n_add ( "The IVR operator ID link target.");
i18n_add ( "Filter search with this string. If not provided, return all IVRs.");
i18n_add ( "An array containing the system IVRs.");
i18n_add ( "The internal unique identification number of the IVRs.");
i18n_add ( "The name of the IVRs.");
i18n_add ( "Sales");
i18n_add ( "The description of the IVR.");
i18n_add ( "Sales IVR workflow.");
i18n_add ( "How many times this IVR are in use into the system.");
i18n_add ( "Search IVRs");
i18n_add ( "Search for system IVRs.");
i18n_add ( "An object containing information about the system IVR.");
i18n_add ( "The name of the IVR.");
i18n_add ( "call-center");
i18n_add ( "Main Call Center IVR workflow");
i18n_add ( "View IVRs information");
i18n_add ( "View IVRs");
i18n_add ( "Get a system IVR information.");
i18n_add ( "The IVR internal system unique identifier.");
i18n_add ( "The name of the system IVR.");
i18n_add ( "The description of the system IVR.");
i18n_add ( "New system IVR added sucessfully.");
i18n_add ( "The IVR name is required.");
i18n_add ( "The IVR description is required.");
i18n_add ( "The IVR workflow is required.");
i18n_add ( "Add IVRs");
i18n_add ( "Add a new system IVR.");
i18n_add ( "The name could only contain lower case characters, numbers, hifen and dot.");
i18n_add ( "The IVR workflow cannot be empty.");
i18n_add ( "The IVR name is already in use.");
i18n_add ( "The system IVR was sucessfully updated.");
i18n_add ( "Edit IVRs");
i18n_add ( "Change a system IVR information.");
i18n_add ( "The system IVR was removed.");
i18n_add ( "Remove IVRs");
i18n_add ( "Remove a IVR from system.");
i18n_add ( "Other");
i18n_add ( "Time");
i18n_add ( "Time options");
i18n_add ( "Conditions");
i18n_add ( "Start time");
i18n_add ( "Finish time");
i18n_add ( "Cond.");
i18n_add ( "You need at least one condition.");
i18n_add ( "Invalid start time of condition %d.");
i18n_add ( "Invalid finish time of condition %d.");
i18n_add ( "Start time later than finish time at condition %d.");
i18n_add ( "Date");
i18n_add ( "Date options");
i18n_add ( "Start date");
i18n_add ( "Finish date");
i18n_add ( "Invalid start date of condition %d.");
i18n_add ( "Invalid finish date of condition %d.");
i18n_add ( "Start date later than finish date at condition %d.");
i18n_add ( "Sunday");
i18n_add ( "Monday");
i18n_add ( "Tuesday");
i18n_add ( "Wednesday");
i18n_add ( "Thursday");
i18n_add ( "Friday");
i18n_add ( "Saturday");
i18n_add ( "Week day");
i18n_add ( "OK");
i18n_add ( "Timed out");
i18n_add ( "Read");
i18n_add ( "Read options");
i18n_add ( "Variable");
i18n_add ( "Variable name");
i18n_add ( "Digits");
i18n_add ( "Number of digits");
i18n_add ( "Timeout");
i18n_add ( "Read timeout");
i18n_add ( "Echo");
i18n_add ( "Variable name missing.");
i18n_add ( "Number of digits missing.");
i18n_add ( "Menu");
i18n_add ( "Menu options");
i18n_add ( "Play file");
i18n_add ( "Audio file to play");
i18n_add ( "Invalid file");
i18n_add ( "Audio file to play when timedout or invalid option selected");
i18n_add ( "Retries");
i18n_add ( "Retries limit");
i18n_add ( "Enabled options");
i18n_add ( "Option");
i18n_add ( "Timeout value missing.");
i18n_add ( "Retries value missing.");
i18n_add ( "At least one output option should be enabled.");
i18n_add ( "File not selected.");
i18n_add ( "Record filename");
i18n_add ( "You can insert some substitutions as follow");
i18n_add ( "Current date in YYYYMMDD format");
i18n_add ( "Current time in HHMMSS format");
i18n_add ( "The content of IVR variable <i>VARIABLE</i>");
i18n_add ( "File name missing.");
i18n_add ( "Discard");
i18n_add ( "Wait time (in seconds)");
i18n_add ( "Waiting time missing.");
i18n_add ( "True");
i18n_add ( "False");
i18n_add ( "Filter variable");
i18n_add ( "Variable condition logic");
i18n_add ( "Equal");
i18n_add ( "Different");
i18n_add ( "Contains");
i18n_add ( "Not contains");
i18n_add ( "Lower than");
i18n_add ( "Lower or equal than");
i18n_add ( "Greater than");
i18n_add ( "Greater or equal than");
i18n_add ( "Condition value");
i18n_add ( "Missing variable name.");
i18n_add ( "You must select the condition logic of condition %d.");
i18n_add ( "You must provide a value comparison of condition %d.");
i18n_add ( "Value");
i18n_add ( "Variable value");
i18n_add ( "Variable value missing.");
i18n_add ( "Refused");
i18n_add ( "Dial timeout");
i18n_add ( "Variable destination missing.");
i18n_add ( "Script name");
i18n_add ( "Script output variable");
i18n_add ( "Subject");
i18n_add ( "Body");
i18n_add ( "Variable to missing.");
i18n_add ( "Variable subject missing.");
i18n_add ( "Variable body missing.");
i18n_add ( "IVR");
i18n_add ( "IVR removal");
i18n_add ( "Are sure you want to remove the IVR %s (%s)?");
i18n_add ( "Uses");
i18n_add ( "IVR removed sucessfully!");
i18n_add ( "Error removing IVR!");
i18n_add ( "Zoom out");
i18n_add ( "Zoom to fit");
i18n_add ( "Zoom in");
i18n_add ( "Delete selected");
i18n_add ( "Action validation error");
i18n_add ( "Delay can't be empty when enabled.");
i18n_add ( "Error adding IVR!");
i18n_add ( "IVR added sucessfully!");
i18n_add ( "IVR view");
i18n_add ( "Error viewing IVR!");
i18n_add ( "Error editing IVR!");
i18n_add ( "IVR edited sucessfully!");
i18n_add ( "IVR edit");
i18n_add ( "The IVR module operator type.");
i18n_add ( "Any property related to the IVR module operator type.");
i18n_add ( "The output label parameters (if used) of IVR operator.");
i18n_add ( "Variables when operator type is \"start\".");
i18n_add ( "If the call should be answered at the IVR start.");
i18n_add ( "The number of seconds to wait before answer (if AutoAnswer is true).");
i18n_add ( "AutoAnswer field is required.");
i18n_add ( "AutoAnswer must be true or false.");
i18n_add ( "Delay is required when Auto Start is enabled.");
i18n_add ( "Delay must be a number.");
i18n_add ( "Operator must have an output.");
i18n_add ( "Operator must have an output with name \"output\".");
i18n_add ( "Variables when operator type is \"answer\".");
i18n_add ( "Variables when operator type is \"wait\".");
i18n_add ( "The description of the operator.");
i18n_add ( "Wait 4 seconds.");
i18n_add ( "The number of seconds to wait.");
i18n_add ( "Time field is required.");
i18n_add ( "Time must be a number.");
i18n_add ( "Variables when operator type is \"hangup\".");
i18n_add ( "Operator does not must have an output.");
i18n_add ( "Variables when operator type is \"time\".");
i18n_add ( "Check for working hours.");
i18n_add ( "The array containing object of start and finish time conditions.");
i18n_add ( "The start time of the condition.");
i18n_add ( "The finish time of the condition.");
i18n_add ( "At least one condition is required.");
i18n_add ( "Conditions must be an array.");
i18n_add ( "Condition %d Start is required.");
i18n_add ( "Condition %d Start value is invalid.");
i18n_add ( "Condition %d Finish is required.");
i18n_add ( "Condition %d Finish value is invalid.");
i18n_add ( "Operator must have an output for each condition plus the other output.");
i18n_add ( "Operator must have an output with name \"other\".");
i18n_add ( "Variables when operator type is \"date\".");
i18n_add ( "Check for holiday dates.");
i18n_add ( "The array containing object of start and finish date conditions.");
i18n_add ( "The start date of the condition. Format YYYY-MM-DD.");
i18n_add ( "The finish date of the condition. Format YYYY-MM-DD.");
i18n_add ( "Variables when operator type is \"weekday\".");
i18n_add ( "Operator must have 7 outputs.");
i18n_add ( "Operator must have an output for each week day.");
i18n_add ( "Variables when operator type is \"play\".");
i18n_add ( "Play welcome message.");
i18n_add ( "The audio file internal system unique identifier.");
i18n_add ( "Filename is required.");
i18n_add ( "Invalid Filename.");
i18n_add ( "Variables when operator type is \"record\".");
i18n_add ( "Record customer audio message.");
i18n_add ( "The audio filename to be written.");
i18n_add ( "customeraudio");
i18n_add ( "Filename cannot contains / or ,.");
i18n_add ( "Variables when operator type is \"stop\".");
i18n_add ( "Stop recording audio.");
i18n_add ( "If the recorded audio must be discarded.");
i18n_add ( "Option Discard is required.");
i18n_add ( "Option Discard must be true or false.");
i18n_add ( "Variables when operator type is \"read\".");
i18n_add ( "Read destination extension number.");
i18n_add ( "The variable name to store the digits.");
i18n_add ( "extension");
i18n_add ( "The number of digits to read.");
i18n_add ( "The time in seconds to wait for digits.");
i18n_add ( "If the system should say back the dialed digits.");
i18n_add ( "Variable is required.");
i18n_add ( "Variable must have only lowercase letters, numbers and underscore.");
i18n_add ( "Variable cannot have more than 128 digits.");
i18n_add ( "Digits is required.");
i18n_add ( "Digits must be a number.");
i18n_add ( "Digits must be at least 1.");
i18n_add ( "Timeout is required.");
i18n_add ( "Timeout must be a number.");
i18n_add ( "Timeout must be at least 1.");
i18n_add ( "Echo field is required.");
i18n_add ( "Echo must be true or false.");
i18n_add ( "Operator must have two outputs.");
i18n_add ( "Operator must have two outputs, \"ok\" and \"timedout\".");
i18n_add ( "Variables when operator type is \"menu\".");
i18n_add ( "Main IVR menu.");
i18n_add ( "The variable name to store the selected option.");
i18n_add ( "mainmenu");
i18n_add ( "The audio file internal system unique identifier to play at menu start.");
i18n_add ( "The audio file internal system unique identifier to play when selected invalid option.");
i18n_add ( "If the system should say back the dialed option.");
i18n_add ( "The maximum retries to get a valid response.");
i18n_add ( "If the digit 0 is considered a valid option.");
i18n_add ( "If the digit 1 is considered a valid option.");
i18n_add ( "If the digit 2 is considered a valid option.");
i18n_add ( "If the digit 3 is considered a valid option.");
i18n_add ( "If the digit 4 is considered a valid option.");
i18n_add ( "If the digit 5 is considered a valid option.");
i18n_add ( "If the digit 6 is considered a valid option.");
i18n_add ( "If the digit 7 is considered a valid option.");
i18n_add ( "If the digit 8 is considered a valid option.");
i18n_add ( "If the digit 9 is considered a valid option.");
i18n_add ( "If the digit * is considered a valid option.");
i18n_add ( "If the digit # is considered a valid option.");
i18n_add ( "Invalid InvalidFile.");
i18n_add ( "Retries is required.");
i18n_add ( "Retries must be a number.");
i18n_add ( "Retries must be at least 1.");
i18n_add ( "Option0 field is required.");
i18n_add ( "Option0 must be true or false.");
i18n_add ( "Option1 field is required.");
i18n_add ( "Option1 must be true or false.");
i18n_add ( "Option2 field is required.");
i18n_add ( "Option2 must be true or false.");
i18n_add ( "Option3 field is required.");
i18n_add ( "Option3 must be true or false.");
i18n_add ( "Option4 field is required.");
i18n_add ( "Option4 must be true or false.");
i18n_add ( "Option5 field is required.");
i18n_add ( "Option5 must be true or false.");
i18n_add ( "Option6 field is required.");
i18n_add ( "Option6 must be true or false.");
i18n_add ( "Option7 field is required.");
i18n_add ( "Option7 must be true or false.");
i18n_add ( "Option8 field is required.");
i18n_add ( "Option8 must be true or false.");
i18n_add ( "Option9 field is required.");
i18n_add ( "Option9 must be true or false.");
i18n_add ( "OptionA field is required.");
i18n_add ( "OptionA must be true or false.");
i18n_add ( "OptionS field is required.");
i18n_add ( "OptionS must be true or false.");
i18n_add ( "At least one option must be enabled.");
i18n_add ( "Operator must have at least two outputs.");
i18n_add ( "Operator must have outputs to \"timedout\" and each enabled option.");
i18n_add ( "Variables when operator type is \"router\".");
i18n_add ( "Route call based on caller action.");
i18n_add ( "The array containing object of conditions.");
i18n_add ( "The condition logic.");
i18n_add ( "The condition value.");
i18n_add ( "Condition %d condition is required.");
i18n_add ( "Condition %d condition is invalid.");
i18n_add ( "Condition %d value is required.");
i18n_add ( "Operator must have two outputs \"true\" and \"false\".");
i18n_add ( "Variables when operator type is \"setvar\".");
i18n_add ( "Set call type variable.");
i18n_add ( "The variable name.");
i18n_add ( "The value to be assigned.");
i18n_add ( "Value is required.");
i18n_add ( "Variables when operator type is \"dial\".");
i18n_add ( "Dial to the extension.");
i18n_add ( "The number of destination extension (allow use of {var_VARIABLE}).");
i18n_add ( "The number of seconds to timeout dial.");
i18n_add ( "Destination is required.");
i18n_add ( "Operator must have 4 outputs.");
i18n_add ( "Operator must have four outputs \"ok\", \"timedout\", \"busy\" and \"refused\".");
i18n_add ( "Variables when operator type is \"script\".");
i18n_add ( "Call internal script.");
i18n_add ( "The name of the script to run.");
i18n_add ( "The variable name to store the script output.");
i18n_add ( "script");
i18n_add ( "The array containing object of parameters.");
i18n_add ( "The parameter to be passed to the script.");
i18n_add ( "Name is required.");
i18n_add ( "Name cannot contain a directory.");
i18n_add ( "Variables when operator type is \"email\".");
i18n_add ( "Send email to adminstrator.");
i18n_add ( "The destination email address.");
i18n_add ( "The email subject.");
i18n_add ( "New call at main IVR.");
i18n_add ( "The email body.");
i18n_add ( "Hi admin! We received a new call at our main IVR.");
i18n_add ( "To is required.");
i18n_add ( "Invalid email address.");
i18n_add ( "Subject is required.");
i18n_add ( "Body is required.");
i18n_add ( "Invalid IVR ID.");
i18n_add ( "Play");
i18n_add ( "Play options");
i18n_add ( "Record");
i18n_add ( "Record options");
i18n_add ( "Number of caller telephone (digits only)");
i18n_add ( "Stop");
i18n_add ( "Stop recording options");
i18n_add ( "Wait");
i18n_add ( "Wait options");
i18n_add ( "Router");
i18n_add ( "Router options");
i18n_add ( "Set variable");
i18n_add ( "Set variable options");
i18n_add ( "Dial");
i18n_add ( "Dial options");
i18n_add ( "Dial destination (number or {var_VARIABLE})");
i18n_add ( "Variable timeout missing.");
i18n_add ( "Script");
i18n_add ( "Script options");
i18n_add ( "Parameters");
i18n_add ( "Script execution parameter");
i18n_add ( "Email");
i18n_add ( "Email options");
i18n_add ( "Destination email");
i18n_add ( "Message body");
i18n_add ( "required field.");
i18n_add ( "IVR cloning");
i18n_add ( "Error requesting IVR data!");

/**
 * Add Brazilian Portuguese support
 */
i18n_add ( "IVRs", "URAs", "pt_BR");
i18n_add ( "IVR search", "pesquisa de URA's", "pt_BR");
i18n_add ( "Name", "Nome", "pt_BR");
i18n_add ( "IVR addition", "adição de usuários", "pt_BR");
i18n_add ( "IVR visualization", "visualização de usuários", "pt_BR");
i18n_add ( "IVR edition", "edição de usuários", "pt_BR");
i18n_add ( "IVR name", "Nome da URA", "pt_BR");
i18n_add ( "IVR description", "Descrição da URA", "pt_BR");
i18n_add ( "Start options", "Opções de início", "pt_BR");
i18n_add ( "Auto answer", "Auto atendimento", "pt_BR");
i18n_add ( "Delay", "Atraso", "pt_BR");
i18n_add ( "Wait seconds before answer", "Segundos a aguardar antes de atender", "pt_BR");
i18n_add ( "In", "Entra", "pt_BR");
i18n_add ( "Out", "Sai", "pt_BR");
i18n_add ( "The IVR operator ID.", "O identificador do operador da URA.", "pt_BR");
i18n_add ( "The IVR operator left distance on the workflow.", "A distância da esquerda do operador da URA no workflow.", "pt_BR");
i18n_add ( "The IVR operator top distance on the workflow.", "A distância do topo do operador da URA no workflow.", "pt_BR");
i18n_add ( "The output name of IVR operator.", "O nome da saída do operador da URA.", "pt_BR");
i18n_add ( "The output label of IVR operator.", "A etiqueta de saída do operador da URA.", "pt_BR");
i18n_add ( "Output", "Saída", "pt_BR");
i18n_add ( "The IVR operator ID link origin.", "O identificador do operador da URA de origem do link.", "pt_BR");
i18n_add ( "The IVR operator connector link origin.", "O link de origem da conexão do operador da URA.", "pt_BR");
i18n_add ( "The IVR operator ID link target.", "O identificador do operador da URA de destino do link.", "pt_BR");
i18n_add ( "Filter search with this string. If not provided, return all IVRs.", "Filtra a pesquisa pela string. Se não informada, retorna todas as URAs.", "pt_BR");
i18n_add ( "An array containing the system IVRs.", "Um array contendo as URAs do sistema.", "pt_BR");
i18n_add ( "The internal unique identification number of the IVRs.", "O número interno único de identificação das URAs.", "pt_BR");
i18n_add ( "The name of the IVRs.", "O nome das URAs.", "pt_BR");
i18n_add ( "Sales", "Vendas", "pt_BR");
i18n_add ( "The description of the IVR.", "A descrição da URA.", "pt_BR");
i18n_add ( "Sales IVR workflow.", "Workflow de vendas da URA.", "pt_BR");
i18n_add ( "How many times this IVR are in use into the system.", "Quantas vezes esta URA está em uso no sistema.", "pt_BR");
i18n_add ( "Search IVRs", "Pesquisa URAs", "pt_BR");
i18n_add ( "Search for system IVRs.", "Pequisa por URAs do sistema.", "pt_BR");
i18n_add ( "An object containing information about the system IVR.", "Um objeto contendo informações sobre a URA do sistema.", "pt_BR");
i18n_add ( "The name of the IVR.", "O nome da URA.", "pt_BR");
i18n_add ( "call-center", "call-center", "pt_BR");
i18n_add ( "Main Call Center IVR workflow", "Workflow da URA do Call Center", "pt_BR");
i18n_add ( "View IVRs information", "Visualizar informações das URAs", "pt_BR");
i18n_add ( "View IVRs", "Visualizar URAs", "pt_BR");
i18n_add ( "Get a system IVR information.", "Requisitar informações de URA do sistema.", "pt_BR");
i18n_add ( "The IVR internal system unique identifier.", "O identificador interno único da URA do sistema.", "pt_BR");
i18n_add ( "The name of the system IVR.", "O nome da URA do sistema.", "pt_BR");
i18n_add ( "The description of the system IVR.", "A descrição da URA do sistema.", "pt_BR");
i18n_add ( "New system IVR added sucessfully.", "A nova URA do sistema foi adicionada com sucesso.", "pt_BR");
i18n_add ( "The IVR name is required.", "O nome da URA é obrigatório.", "pt_BR");
i18n_add ( "The IVR description is required.", "A descrição da URA é obrigatória.", "pt_BR");
i18n_add ( "The IVR workflow is required.", "O fluxo da URA é obrigatório.", "pt_BR");
i18n_add ( "Add IVRs", "Adicionar URAs", "pt_BR");
i18n_add ( "Add a new system IVR.", "Adicionar uma nova URA no sistema.", "pt_BR");
i18n_add ( "The name could only contain lower case characters, numbers, hifen and dot.", "O nome deve conter apenas caracteres minúsculos, números, hífen e ponto.", "pt_BR");
i18n_add ( "The IVR workflow cannot be empty.", "O fluxo da URA não pode ser vazio.", "pt_BR");
i18n_add ( "The IVR name is already in use.", "O nome da URA já está em uso.", "pt_BR");
i18n_add ( "The system IVR was sucessfully updated.", "A URA do sistema foi atualizada com sucesso.", "pt_BR");
i18n_add ( "Edit IVRs", "Editar URAs", "pt_BR");
i18n_add ( "Change a system IVR information.", "Alterar informações de URA do sistema.", "pt_BR");
i18n_add ( "The system IVR was removed.", "A URA do sistema foi removida.", "pt_BR");
i18n_add ( "Remove IVRs", "Remove URAs", "pt_BR");
i18n_add ( "Remove a IVR from system.", "Remover uma URA do sistema.", "pt_BR");
i18n_add ( "Other", "Outro", "pt_BR");
i18n_add ( "Time", "Horas", "pt_BR");
i18n_add ( "Time options", "Opções de horas", "pt_BR");
i18n_add ( "Conditions", "Condições", "pt_BR");
i18n_add ( "Start time", "Horário de início", "pt_BR");
i18n_add ( "Finish time", "Horário de término", "pt_BR");
i18n_add ( "Cond.", "Cond.", "pt_BR");
i18n_add ( "You need at least one condition.", "Você precisa de ao menos uma condição.", "pt_BR");
i18n_add ( "Invalid start time of condition %d.", "Horário de início da condição %d é inválido.", "pt_BR");
i18n_add ( "Invalid finish time of condition %d.", "Horário de término da condição %s é inválido.", "pt_BR");
i18n_add ( "Start time later than finish time at condition %d.", "Horário de início maior que horário de fim na condição %d.", "pt_BR");
i18n_add ( "Date", "Data", "pt_BR");
i18n_add ( "Date options", "Opções de data", "pt_BR");
i18n_add ( "Start date", "Data de início", "pt_BR");
i18n_add ( "Finish date", "Data de término", "pt_BR");
i18n_add ( "Invalid start date of condition %d.", "Data de início da condição %d é inválida.", "pt_BR");
i18n_add ( "Invalid finish date of condition %d.", "Data de término da condição %d é inválida.", "pt_BR");
i18n_add ( "Start date later than finish date at condition %d.", "Data de início maior que data de fim na condição %d.", "pt_BR");
i18n_add ( "Sunday", "Domingo", "pt_BR");
i18n_add ( "Monday", "Segunda", "pt_BR");
i18n_add ( "Tuesday", "Terça", "pt_BR");
i18n_add ( "Wednesday", "Quarta", "pt_BR");
i18n_add ( "Thursday", "Quinta", "pt_BR");
i18n_add ( "Friday", "Sexta", "pt_BR");
i18n_add ( "Saturday", "Sábado", "pt_BR");
i18n_add ( "Week day", "Dia da semana", "pt_BR");
i18n_add ( "OK", "OK", "pt_BR");
i18n_add ( "Timed out", "Expirado", "pt_BR");
i18n_add ( "Read", "Ler", "pt_BR");
i18n_add ( "Read options", "Opções de leitura", "pt_BR");
i18n_add ( "Variable", "Variável", "pt_BR");
i18n_add ( "Variable name", "Nome da variável", "pt_BR");
i18n_add ( "Digits", "Dígitos", "pt_BR");
i18n_add ( "Number of digits", "Número de dígitos", "pt_BR");
i18n_add ( "Timeout", "Expiração", "pt_BR");
i18n_add ( "Read timeout", "Tempo de expiração", "pt_BR");
i18n_add ( "Echo", "Eco", "pt_BR");
i18n_add ( "Variable name missing.", "Falta nome da variável.", "pt_BR");
i18n_add ( "Number of digits missing.", "Falta número de dígitos.", "pt_BR");
i18n_add ( "Menu", "Menu", "pt_BR");
i18n_add ( "Menu options", "Opções de menu", "pt_BR");
i18n_add ( "Play file", "Tocar arquivo", "pt_BR");
i18n_add ( "Audio file to play", "Arquivo de áudio para tocar", "pt_BR");
i18n_add ( "Invalid file", "Arquivo inválido", "pt_BR");
i18n_add ( "Audio file to play when timedout or invalid option selected", "Arquivo de áudio para tocar quando expirado o tempo ou selecionado uma opção inválida", "pt_BR");
i18n_add ( "Retries", "Tentativas", "pt_BR");
i18n_add ( "Retries limit", "Limite de tentativas", "pt_BR");
i18n_add ( "Enabled options", "Opções habilitadas", "pt_BR");
i18n_add ( "Option", "Opção", "pt_BR");
i18n_add ( "Timeout value missing.", "Falta valor de expiração.", "pt_BR");
i18n_add ( "Retries value missing.", "Falta valor de tentativas.", "pt_BR");
i18n_add ( "At least one output option should be enabled.", "Ao menos uma opção de saída deve ser habilitada.", "pt_BR");
i18n_add ( "File not selected.", "Arquivo não selecionado.", "pt_BR");
i18n_add ( "Record filename", "Arquivo de gravação", "pt_BR");
i18n_add ( "You can insert some substitutions as follow", "Você pode inserir algumas substituições como as seguintes", "pt_BR");
i18n_add ( "Current date in YYYYMMDD format", "Data atual no formato AAAAMMDD", "pt_BR");
i18n_add ( "Current time in HHMMSS format", "Hora atual no formato HHMMSS", "pt_BR");
i18n_add ( "The content of IVR variable <i>VARIABLE</i>", "O conteúdo da variável <i>VARIÁVEL</i> da URA", "pt_BR");
i18n_add ( "File name missing.", "Falta nome do arquivo.", "pt_BR");
i18n_add ( "Discard", "Descartar", "pt_BR");
i18n_add ( "Wait time (in seconds)", "Tempo de espera (em segundos)", "pt_BR");
i18n_add ( "Waiting time missing.", "Falta tempo de espera.", "pt_BR");
i18n_add ( "True", "Verdadeiro", "pt_BR");
i18n_add ( "False", "Falso", "pt_BR");
i18n_add ( "Filter variable", "Filtrar variável", "pt_BR");
i18n_add ( "Variable condition logic", "Condição lógica da variável", "pt_BR");
i18n_add ( "Equal", "Igual", "pt_BR");
i18n_add ( "Different", "Diferente", "pt_BR");
i18n_add ( "Contains", "Contém", "pt_BR");
i18n_add ( "Not contains", "Não contém", "pt_BR");
i18n_add ( "Lower than", "Menor que", "pt_BR");
i18n_add ( "Lower or equal than", "Menor ou igual a", "pt_BR");
i18n_add ( "Greater than", "Maior que", "pt_BR");
i18n_add ( "Greater or equal than", "Maior ou igual a", "pt_BR");
i18n_add ( "Condition value", "Valor da condição", "pt_BR");
i18n_add ( "Missing variable name.", "Falta nome da variável.", "pt_BR");
i18n_add ( "You must select the condition logic of condition %d.", "Você deve selecionar a condição lógica da condição %d.", "pt_BR");
i18n_add ( "You must provide a value comparison of condition %d.", "Você deve informar um valor comparativo para a condição %d.", "pt_BR");
i18n_add ( "Value", "Valor", "pt_BR");
i18n_add ( "Variable value", "Valor da variável", "pt_BR");
i18n_add ( "Variable value missing.", "Falta valor da variável.", "pt_BR");
i18n_add ( "Refused", "Recusado", "pt_BR");
i18n_add ( "Dial timeout", "Expiração de discagem", "pt_BR");
i18n_add ( "Variable destination missing.", "Falta variável de destino.", "pt_BR");
i18n_add ( "Script name", "Nome do script", "pt_BR");
i18n_add ( "Script output variable", "Variável de saída do script", "pt_BR");
i18n_add ( "Subject", "Assunto", "pt_BR");
i18n_add ( "Body", "Conteúdo", "pt_BR");
i18n_add ( "Variable to missing.", "Falta variável para.", "pt_BR");
i18n_add ( "Variable subject missing.", "Falta variável de assunto.", "pt_BR");
i18n_add ( "Variable body missing.", "Falta variável de corpo.", "pt_BR");
i18n_add ( "IVR", "URA", "pt_BR");
i18n_add ( "IVR removal", "Remoção de URA", "pt_BR");
i18n_add ( "Are sure you want to remove the IVR %s (%s)?", "Você tem certeza que deseja remover a URA %s (%s)?", "pt_BR");
i18n_add ( "Uses", "Usos", "pt_BR");
i18n_add ( "IVR removed sucessfully!", "URA removida com sucesso!", "pt_BR");
i18n_add ( "Error removing IVR!", "Erro removendo URA!", "pt_BR");
i18n_add ( "Zoom out", "Menos zoom", "pt_BR");
i18n_add ( "Zoom to fit", "Zoom padrão", "pt_BR");
i18n_add ( "Zoom in", "Mais zoom", "pt_BR");
i18n_add ( "Delete selected", "Remover selecionado", "pt_BR");
i18n_add ( "Action validation error", "Erro validando ação", "pt_BR");
i18n_add ( "Delay can't be empty when enabled.", "Atraso não pode ser vazio quando habilitado.", "pt_BR");
i18n_add ( "Error adding IVR!", "Erro adicionando URA!", "pt_BR");
i18n_add ( "IVR added sucessfully!", "URA adicionada com sucesso!", "pt_BR");
i18n_add ( "IVR view", "Visualizar URA", "pt_BR");
i18n_add ( "Error viewing IVR!", "Erro ao visualizar URA!", "pt_BR");
i18n_add ( "Error editing IVR!", "Erro ao editar URA!", "pt_BR");
i18n_add ( "IVR edited sucessfully!", "URA editada com sucesso!", "pt_BR");
i18n_add ( "IVR edit", "Editar URA", "pt_BR");
i18n_add ( "The IVR module operator type.", "O tipo de operador do módulo de URA.", "pt_BR");
i18n_add ( "Any property related to the IVR module operator type.", "Quaisquer propriedade relacionada ao tipo de operador de URA.", "pt_BR");
i18n_add ( "The output label parameters (if used) of IVR operator.", "Os parâmetros de etiquetas de saída (se utilizado) do operador de URA.", "pt_BR");
i18n_add ( "Variables when operator type is \"start\".", "Variáveis quando o tipo de operador é \"início\".", "pt_BR");
i18n_add ( "If the call should be answered at the IVR start.", "Se a chamada deve ser atendida no início da URA.", "pt_BR");
i18n_add ( "The number of seconds to wait before answer (if AutoAnswer is true).", "O número de segundos a aguardar antes de atender (se AutoAtender estiver habilitado).", "pt_BR");
i18n_add ( "AutoAnswer field is required.", "Campo AutoAtender é obrigatório.", "pt_BR");
i18n_add ( "AutoAnswer must be true or false.", "AutoAtender deve ser verdadeiro ou falso.", "pt_BR");
i18n_add ( "Delay is required when Auto Start is enabled.", "O atraso é obrigatório quando o AutoAtender estiver habilitado.", "pt_BR");
i18n_add ( "Delay must be a number.", "Atraso deve ser um número.", "pt_BR");
i18n_add ( "Operator must have an output.", "Operador deve conter uma saída.", "pt_BR");
i18n_add ( "Operator must have an output with name \"output\".", "Operador deve conter uma saída com o nome \"saída\".", "pt_BR");
i18n_add ( "Variables when operator type is \"answer\".", "Variáveis quando o tipo de operador é \"atender\".", "pt_BR");
i18n_add ( "Variables when operator type is \"wait\".", "Variáveis quando o tipo de operador é \"aguardar\".", "pt_BR");
i18n_add ( "The description of the operator.", "A descrição do operador.", "pt_BR");
i18n_add ( "Wait 4 seconds.", "Aguardar 4 segundos.", "pt_BR");
i18n_add ( "The number of seconds to wait.", "O número de segundos a aguardar.", "pt_BR");
i18n_add ( "Time field is required.", "O campo de tempo é obrigatório.", "pt_BR");
i18n_add ( "Time must be a number.", "Tempo deve ser um número.", "pt_BR");
i18n_add ( "Variables when operator type is \"hangup\".", "Variáveis quando o tipo de operador for \"desligar\".", "pt_BR");
i18n_add ( "Operator does not must have an output.", "Operador não deve conter uma saída.", "pt_BR");
i18n_add ( "Variables when operator type is \"time\".", "Variáveis quando o tipo de operador for \"hora\".", "pt_BR");
i18n_add ( "Check for working hours.", "Verifica horário de trabalho.", "pt_BR");
i18n_add ( "The array containing object of start and finish time conditions.", "Um objeto array contendo as condições de início e fim de horário.", "pt_BR");
i18n_add ( "The start time of the condition.", "A hora inicial da condição.", "pt_BR");
i18n_add ( "The finish time of the condition.", "A hora final da condição.", "pt_BR");
i18n_add ( "At least one condition is required.", "Ao menos uma condição é requerida.", "pt_BR");
i18n_add ( "Conditions must be an array.", "Condições deve ser um array.", "pt_BR");
i18n_add ( "Condition %d Start is required.", "O início da condição %d é obrigatório.", "pt_BR");
i18n_add ( "Condition %d Start value is invalid.", "O valor do início da condição %d é inválido.", "pt_BR");
i18n_add ( "Condition %d Finish is required.", "O final da condição %d é obrigatório.", "pt_BR");
i18n_add ( "Condition %d Finish value is invalid.", "O valor do final da condição %d é inválido.", "pt_BR");
i18n_add ( "Operator must have an output for each condition plus the other output.", "O operador deve conter uma saída para cada condição mais uma para outro.", "pt_BR");
i18n_add ( "Operator must have an output with name \"other\".", "Operador deve ter uma saída com o nome \"outro\".", "pt_BR");
i18n_add ( "Variables when operator type is \"date\".", "Variáveis quando o tipo de operador for \"data\".", "pt_BR");
i18n_add ( "Check for holiday dates.", "Verifica por data de feriados.", "pt_BR");
i18n_add ( "The array containing object of start and finish date conditions.", "Um objeto array contendo as condições de início e fim de data.", "pt_BR");
i18n_add ( "The start date of the condition. Format YYYY-MM-DD.", "A data inicial da condição. Formato AAAA-MM-DD.", "pt_BR");
i18n_add ( "The finish date of the condition. Format YYYY-MM-DD.", "A data final da condição. Formato AAAA-MM-DD.", "pt_BR");
i18n_add ( "Variables when operator type is \"weekday\".", "Variáveis quando o tipo de operador for \"diadasemana\".", "pt_BR");
i18n_add ( "Operator must have 7 outputs.", "Operador deve conter 7 saídas.", "pt_BR");
i18n_add ( "Operator must have an output for each week day.", "Operador deve conter uma saída para cada dia da semana.", "pt_BR");
i18n_add ( "Variables when operator type is \"play\".", "Variávies quando o tipo de operador for \"tocar\".", "pt_BR");
i18n_add ( "Play welcome message.", "Tocar uma mensagem de boas vindas.", "pt_BR");
i18n_add ( "The audio file internal system unique identifier.", "O identificador interno único do arquivo de áudio do sistema.", "pt_BR");
i18n_add ( "Filename is required.", "Nome do arquivo é obrigatório.", "pt_BR");
i18n_add ( "Invalid Filename.", "Nome do arquivo inválido.", "pt_BR");
i18n_add ( "Variables when operator type is \"record\".", "Variávies quando o tipo de operador for \"gravar\".", "pt_BR");
i18n_add ( "Record customer audio message.", "Gravar mensagem de áudio do usuário.", "pt_BR");
i18n_add ( "The audio filename to be written.", "O nome do arquivo de áudio a ser gravado.", "pt_BR");
i18n_add ( "customeraudio", "audiodousuario", "pt_BR");
i18n_add ( "Filename cannot contains / or ,.", "O nome do arquivo não pode conter / ou ,.", "pt_BR");
i18n_add ( "Variables when operator type is \"stop\".", "Variávies quando o tipo de operador for \"parar\".", "pt_BR");
i18n_add ( "Stop recording audio.", "Encerra a gravação de áudio.", "pt_BR");
i18n_add ( "If the recorded audio must be discarded.", "Se o arquivo de áudio deve ser descartado.", "pt_BR");
i18n_add ( "Option Discard is required.", "Opção de descarte é obrigatória.", "pt_BR");
i18n_add ( "Option Discard must be true or false.", "Opção de descarte deve ser verdadeiro ou falso.", "pt_BR");
i18n_add ( "Variables when operator type is \"read\".", "Variávies quando o tipo de operador for \"ler\".", "pt_BR");
i18n_add ( "Read destination extension number.", "Lê o número da extensão de destino.", "pt_BR");
i18n_add ( "The variable name to store the digits.", "O nome da variável para gravar os dígitos.", "pt_BR");
i18n_add ( "extension", "extensao", "pt_BR");
i18n_add ( "The number of digits to read.", "Número de dígitos a ler.", "pt_BR");
i18n_add ( "The time in seconds to wait for digits.", "O número de segundos para aguardar dígitos.", "pt_BR");
i18n_add ( "If the system should say back the dialed digits.", "Se o sistema deve ecoar de volta os dígitos recebidos.", "pt_BR");
i18n_add ( "Variable is required.", "Variável é obrigatória.", "pt_BR");
i18n_add ( "Variable must have only lowercase letters, numbers and underscore.", "Variável deve conter apenas caracteres minúsculos, números e sublinhado.", "pt_BR");
i18n_add ( "Variable cannot have more than 128 digits.", "Nome da variável não pode ter mais de 128 dígitos.", "pt_BR");
i18n_add ( "Digits is required.", "Dígitos é obrigatório.", "pt_BR");
i18n_add ( "Digits must be a number.", "Dígitos deve ser um número.", "pt_BR");
i18n_add ( "Digits must be at least 1.", "Dígitos deve ser no mínimo 1.", "pt_BR");
i18n_add ( "Timeout is required.", "O tempo limite é obrigatório.", "pt_BR");
i18n_add ( "Timeout must be a number.", "O tempo limite deve ser um número.", "pt_BR");
i18n_add ( "Timeout must be at least 1.", "O tempo limite deve ser maior que 1.", "pt_BR");
i18n_add ( "Echo field is required.", "Eco é obrigatório.", "pt_BR");
i18n_add ( "Echo must be true or false.", "Eco deve ser verdadeiro ou falso.", "pt_BR");
i18n_add ( "Operator must have two outputs.", "Operador deve ter duas saídas.", "pt_BR");
i18n_add ( "Operator must have two outputs, \"ok\" and \"timedout\".", "Operador deve ter duas saídas, \"ok\" e \"expirado\".", "pt_BR");
i18n_add ( "Variables when operator type is \"menu\".", "Variávies quando o tipo de operador for \"menu\".", "pt_BR");
i18n_add ( "Main IVR menu.", "Menu principal da URA.", "pt_BR");
i18n_add ( "The variable name to store the selected option.", "O nome da variável para guardar a opção selecionada.", "pt_BR");
i18n_add ( "mainmenu", "menuprincipal", "pt_BR");
i18n_add ( "The audio file internal system unique identifier to play at menu start.", "O identificador interno único do arquivo de áudio do sistema para tocar ao iniciar o menu.", "pt_BR");
i18n_add ( "The audio file internal system unique identifier to play when selected invalid option.", "O identificador interno único do arquivo de áudio do sistema para tocar quando uma opção inválida é selecionada.", "pt_BR");
i18n_add ( "If the system should say back the dialed option.", "Se o sistema deve falar de volta a opção discada.", "pt_BR");
i18n_add ( "The maximum retries to get a valid response.", "O máximo de tentativas para obter uma resposta válida.", "pt_BR");
i18n_add ( "If the digit 0 is considered a valid option.", "Se o dígito 0 é considerado uma opção válida.", "pt_BR");
i18n_add ( "If the digit 1 is considered a valid option.", "Se o dígito 1 é considerado uma opção válida.", "pt_BR");
i18n_add ( "If the digit 2 is considered a valid option.", "Se o dígito 2 é considerado uma opção válida.", "pt_BR");
i18n_add ( "If the digit 3 is considered a valid option.", "Se o dígito 3 é considerado uma opção válida.", "pt_BR");
i18n_add ( "If the digit 4 is considered a valid option.", "Se o dígito 4 é considerado uma opção válida.", "pt_BR");
i18n_add ( "If the digit 5 is considered a valid option.", "Se o dígito 5 é considerado uma opção válida.", "pt_BR");
i18n_add ( "If the digit 6 is considered a valid option.", "Se o dígito 6 é considerado uma opção válida.", "pt_BR");
i18n_add ( "If the digit 7 is considered a valid option.", "Se o dígito 7 é considerado uma opção válida.", "pt_BR");
i18n_add ( "If the digit 8 is considered a valid option.", "Se o dígito 8 é considerado uma opção válida.", "pt_BR");
i18n_add ( "If the digit 9 is considered a valid option.", "Se o dígito 9 é considerado uma opção válida.", "pt_BR");
i18n_add ( "If the digit * is considered a valid option.", "Se o dígito * é considerado uma opção válida.", "pt_BR");
i18n_add ( "If the digit # is considered a valid option.", "Se o dígito # é considerado uma opção válida.", "pt_BR");
i18n_add ( "Invalid InvalidFile.", "ArquivoInválido é inválido.", "pt_BR");
i18n_add ( "Retries is required.", "Tentativas é obrigatório.", "pt_BR");
i18n_add ( "Retries must be a number.", "Tentativas deve ser um número.", "pt_BR");
i18n_add ( "Retries must be at least 1.", "Tentativas deve ser no mínimo 1.", "pt_BR");
i18n_add ( "Option0 field is required.", "O campo Opcao0 é obrigatório.", "pt_BR");
i18n_add ( "Option0 must be true or false.", "Opcao0 deve ser verdadeiro ou falso.", "pt_BR");
i18n_add ( "Option1 field is required.", "O campo Opcao1 é obrigatório.", "pt_BR");
i18n_add ( "Option1 must be true or false.", "Opcao1 deve ser verdadeiro ou falso.", "pt_BR");
i18n_add ( "Option2 field is required.", "O campo Opcao2 é obrigatório.", "pt_BR");
i18n_add ( "Option2 must be true or false.", "Opcao2 deve ser verdadeiro ou falso.", "pt_BR");
i18n_add ( "Option3 field is required.", "O campo Opcao3 é obrigatório.", "pt_BR");
i18n_add ( "Option3 must be true or false.", "Opcao3 deve ser verdadeiro ou falso.", "pt_BR");
i18n_add ( "Option4 field is required.", "O campo Opcao4 é obrigatório.", "pt_BR");
i18n_add ( "Option4 must be true or false.", "Opcao4 deve ser verdadeiro ou falso.", "pt_BR");
i18n_add ( "Option5 field is required.", "O campo Opcao5 é obrigatório.", "pt_BR");
i18n_add ( "Option5 must be true or false.", "Opcao5 deve ser verdadeiro ou falso.", "pt_BR");
i18n_add ( "Option6 field is required.", "O campo Opcao6 é obrigatório.", "pt_BR");
i18n_add ( "Option6 must be true or false.", "Opcao6 deve ser verdadeiro ou falso.", "pt_BR");
i18n_add ( "Option7 field is required.", "O campo Opcao7 é obrigatório.", "pt_BR");
i18n_add ( "Option7 must be true or false.", "Opcao7 deve ser verdadeiro ou falso.", "pt_BR");
i18n_add ( "Option8 field is required.", "O campo Opcao8 é obrigatório.", "pt_BR");
i18n_add ( "Option8 must be true or false.", "Opcao8 deve ser verdadeiro ou falso.", "pt_BR");
i18n_add ( "Option9 field is required.", "O campo Opcao9 é obrigatório.", "pt_BR");
i18n_add ( "Option9 must be true or false.", "Opcao9 deve ser verdadeiro ou falso.", "pt_BR");
i18n_add ( "OptionA field is required.", "O campo OpcaoA é obrigatório.", "pt_BR");
i18n_add ( "OptionA must be true or false.", "OpcaoA deve ser verdadeiro ou falso.", "pt_BR");
i18n_add ( "OptionS field is required.", "O campo OpcaoS é obrigatório.", "pt_BR");
i18n_add ( "OptionS must be true or false.", "OpcaoS deve ser verdadeiro ou falso.", "pt_BR");
i18n_add ( "At least one option must be enabled.", "Ao menos uma opção deve ser habilitada.", "pt_BR");
i18n_add ( "Operator must have at least two outputs.", "Operador deve conter no mínimo duas saídas.", "pt_BR");
i18n_add ( "Operator must have outputs to \"timedout\" and each enabled option.", "Operador deve ter saídas para \"expirou\" e para cada opção habilitada.", "pt_BR");
i18n_add ( "Variables when operator type is \"router\".", "Variáveis quando o tipo de operador for \"roteador\".", "pt_BR");
i18n_add ( "Route call based on caller action.", "Rotear ligação baseado em ação do chamador.", "pt_BR");
i18n_add ( "The array containing object of conditions.", "O array contendo objeto de condições.", "pt_BR");
i18n_add ( "The condition logic.", "A lógica da condição.", "pt_BR");
i18n_add ( "The condition value.", "O valor da condição.", "pt_BR");
i18n_add ( "Condition %d condition is required.", "Condição %d lógica é obrigatória.", "pt_BR");
i18n_add ( "Condition %d condition is invalid.", "Condição %d lógica é inválida.", "pt_BR");
i18n_add ( "Condition %d value is required.", "Condição %d valor é obrigatório.", "pt_BR");
i18n_add ( "Operator must have two outputs \"true\" and \"false\".", "O operador deve ter duas saídas \"verdadeiro\" ou \"falso\".", "pt_BR");
i18n_add ( "Variables when operator type is \"setvar\".", "Variáveis quando o tipo de operador for \"setvar\".", "pt_BR");
i18n_add ( "Set call type variable.", "Altera variável de tipo de chamada.", "pt_BR");
i18n_add ( "The variable name.", "O nome da variável.", "pt_BR");
i18n_add ( "The value to be assigned.", "O valor a ser assinalado.", "pt_BR");
i18n_add ( "Value is required.", "Valor é obrigatório.", "pt_BR");
i18n_add ( "Variables when operator type is \"dial\".", "Variáveis quando o tipo de operador for \"discar\".", "pt_BR");
i18n_add ( "Dial to the extension.", "Discar para uma extensão.", "pt_BR");
i18n_add ( "The number of destination extension (allow use of {var_VARIABLE}).", "O número da extensão de destino (permitido uso de {var_VARIÁVEL}).", "pt_BR");
i18n_add ( "The number of seconds to timeout dial.", "O número de segundos limite da discagem.", "pt_BR");
i18n_add ( "Destination is required.", "Destino é obrigatório.", "pt_BR");
i18n_add ( "Operator must have 4 outputs.", "Operador deve ter 4 saídas.", "pt_BR");
i18n_add ( "Operator must have four outputs \"ok\", \"timedout\", \"busy\" and \"refused\".", "Operador deve ter quatro saídas \"ok\", \"expirado\", \"ocupado\" e \"recusado\".", "pt_BR");
i18n_add ( "Variables when operator type is \"script\".", "Variáveis quando o tipo de operador for \"script\".", "pt_BR");
i18n_add ( "Call internal script.", "Executa script interno.", "pt_BR");
i18n_add ( "The name of the script to run.", "O nome do script a ser executado.", "pt_BR");
i18n_add ( "The variable name to store the script output.", "O nome da variável para gravar a saída do script.", "pt_BR");
i18n_add ( "script", "script", "pt_BR");
i18n_add ( "The array containing object of parameters.", "O array contendo objeto dos parâmetros.", "pt_BR");
i18n_add ( "The parameter to be passed to the script.", "Os parâmetros a serem providos para o script.", "pt_BR");
i18n_add ( "Name is required.", "Nome é obrigatório.", "pt_BR");
i18n_add ( "Name cannot contain a directory.", "Nome não pode conter um diretório.", "pt_BR");
i18n_add ( "Variables when operator type is \"email\".", "Variáveis quando o tipo de operador for \"email\".", "pt_BR");
i18n_add ( "Send email to adminstrator.", "Envia email para o administrador.", "pt_BR");
i18n_add ( "The destination email address.", "O endereço de email de destino.", "pt_BR");
i18n_add ( "The email subject.", "O assunto do email.", "pt_BR");
i18n_add ( "New call at main IVR.", "Nova chamada na URA principal.", "pt_BR");
i18n_add ( "The email body.", "O corpo do email.", "pt_BR");
i18n_add ( "Hi admin! We received a new call at our main IVR.", "Olá admin! Nós recebemos uma nova ligação na nossa URA principal.", "pt_BR");
i18n_add ( "To is required.", "Destino é obrigatório.", "pt_BR");
i18n_add ( "Invalid email address.", "Endereço de email inválido.", "pt_BR");
i18n_add ( "Subject is required.", "Assunto é obrigatório.", "pt_BR");
i18n_add ( "Body is required.", "Corpo é obrigatório.", "pt_BR");
i18n_add ( "Invalid IVR ID.", "ID da URA inválido.", "pt_BR");
i18n_add ( "Play", "Tocar", "pt_BR");
i18n_add ( "Play options", "Opções de toque", "pt_BR");
i18n_add ( "Record", "Gravar", "pt_BR");
i18n_add ( "Record options", "Opções de gravação", "pt_BR");
i18n_add ( "Number of caller telephone (digits only)", "Número do telefone do chamador (dígitos apenas)", "pt_BR");
i18n_add ( "Stop", "Parar", "pt_BR");
i18n_add ( "Stop recording options", "Opções de parar gravação", "pt_BR");
i18n_add ( "Wait", "Aguardar", "pt_BR");
i18n_add ( "Wait options", "Opções de aguardo", "pt_BR");
i18n_add ( "Router", "Roteador", "pt_BR");
i18n_add ( "Router options", "Opções de roteamento", "pt_BR");
i18n_add ( "Set variable", "Setar variável", "pt_BR");
i18n_add ( "Set variable options", "Opções para setar variável", "pt_BR");
i18n_add ( "Dial", "Discar", "pt_BR");
i18n_add ( "Dial options", "Opções de discagem", "pt_BR");
i18n_add ( "Dial destination (number or {var_VARIABLE})", "Destino de discagem (número ou {var_VARIÁVEL})", "pt_BR");
i18n_add ( "Variable timeout missing.", "Variável de expiração não encontrada.", "pt_BR");
i18n_add ( "Script", "Script", "pt_BR");
i18n_add ( "Script options", "Opções de script", "pt_BR");
i18n_add ( "Parameters", "Parâmetros", "pt_BR");
i18n_add ( "Script execution parameter", "Parâmetros para execução de script", "pt_BR");
i18n_add ( "Email", "Email", "pt_BR");
i18n_add ( "Email options", "Opções de email", "pt_BR");
i18n_add ( "Destination email", "Destino do email", "pt_BR");
i18n_add ( "Message body", "Corpo da mensagem", "pt_BR");
i18n_add ( "required field.", "campo obrigatório.", "pt_BR");
i18n_add ( "IVR cloning", "Clonagem de URA", "pt_BR");
i18n_add ( "Error requesting IVR data!", "Erro ao requisitar dados da URA!", "pt_BR");
?>
