<?php
/**   ___ ___       ___ _______     ______                        __
 *   |   Y   .-----|   |   _   |   |   _  \ .-----.--------.---.-|__.-----.
 *   |.  |   |  _  |.  |.  1   |   |.  |   \|  _  |        |  _  |  |     |
 *   |.  |   |_____|.  |.  ____|   |.  |    |_____|__|__|__|___._|__|__|__|
 *   |:  1   |     |:  |:  |       |:  1    /
 *    \:.. ./      |::.|::.|       |::.. . /
 *     `---'       `---`---'       `------'
 *
 * Copyright (C) 2016-2025 Ernani José Camargo Azevedo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * VoIP Domain reports module language file.
 *
 * @author     Ernani José Camargo Azevedo <azevedo@voipdomain.io>
 * @version    1.0
 * @package    VoIP Domain
 * @subpackage Reports
 * @copyright  2016-2025 Ernani José Camargo Azevedo. All rights reserved
 * @license    https://www.gnu.org/licenses/gpl-3.0.en.html
 */

/**
 * Add basic language structure (english)
 */
i18n_add ( "Request extensions listing");
i18n_add ( "Request ranges listing");
i18n_add ( "Request financial cost centers report");
i18n_add ( "Request financial groups report");
i18n_add ( "Request financial gateways report");
i18n_add ( "Request server health");
i18n_add ( "Request extensions activity report");
i18n_add ( "Heat map");
i18n_add ( "Graphical reports");
i18n_add ( "heat map graph");
i18n_add ( "Heat map graph");
i18n_add ( "Call type");
i18n_add ( "All types");
i18n_add ( "Internal calls");
i18n_add ( "External calls");
i18n_add ( "External calls (With no cost)");
i18n_add ( "External calls (With cost)");
i18n_add ( "Mobile calls");
i18n_add ( "Interstate calls");
i18n_add ( "International calls");
i18n_add ( "Error requesting information!");
i18n_add ( "extensions listing");
i18n_add ( "Name");
i18n_add ( "Group");
i18n_add ( "ranges listing");
i18n_add ( "Range");
i18n_add ( "financial by cost center");
i18n_add ( "Calls");
i18n_add ( "Time");
i18n_add ( "The cost center is required.");
i18n_add ( "financial by group");
i18n_add ( "The group is required.");
i18n_add ( "financial by gateway");
i18n_add ( "server health");
i18n_add ( "Automatic update");
i18n_add ( "Disabled");
i18n_add ( "1 second");
i18n_add ( "%d seconds");
i18n_add ( "Used memory * 100 / Total memory");
i18n_add ( "Memory");
i18n_add ( "Processors usage sum (percentage) / Number of processors");
i18n_add ( "CPU");
i18n_add ( "processor(s)");
i18n_add ( "Used space * 100 / Total space");
i18n_add ( "Storage");
i18n_add ( "Server health");
i18n_add ( "activity listing");
i18n_add ( "Last dialed");
i18n_add ( "Last received");
i18n_add ( "Never dialed");
i18n_add ( "Never received");
i18n_add ( "call");
i18n_add ( "calls");
i18n_add ( "Export to");
i18n_add ( "calls made by all");
i18n_add ( "calls made by gateway");
i18n_add ( "calls made by group");
i18n_add ( "calls made by user");
i18n_add ( "calls received by all");
i18n_add ( "calls received by gateway");
i18n_add ( "calls received by group");
i18n_add ( "calls received by user");
i18n_add ( "Gateway made calls report");
i18n_add ( "Gateway received calls report");
i18n_add ( "Group made calls report");
i18n_add ( "Group received calls report");
i18n_add ( "All made calls report");
i18n_add ( "All received calls report");
i18n_add ( "The extension is required.");
i18n_add ( "The gateway is required.");
i18n_add ( "User made calls report");
i18n_add ( "User received calls report");
i18n_add ( "Calls made");
i18n_add ( "Per user");
i18n_add ( "Per group");
i18n_add ( "Per gateway");
i18n_add ( "All");
i18n_add ( "Calls received");
i18n_add ( "Financial");
i18n_add ( "Cost Centers");
i18n_add ( "Groups");
i18n_add ( "Gateways");
i18n_add ( "Graphs");
i18n_add ( "Per server");
i18n_add ( "Costs");
i18n_add ( "Monitory");
i18n_add ( "Extensions listing");
i18n_add ( "Ranges listing");
i18n_add ( "Activity listing");
i18n_add ( "Server status");
i18n_add ( "All durations are billing time in [[DD:]HH:]MM:SS format.");
i18n_add ( "Month/Year");
i18n_add ( "Others");
i18n_add ( "MM/YYYY");
i18n_add ( "The month/year is required.");
i18n_add ( "Consolidated");
i18n_add ( "Consolidated extensions calls report");
i18n_add ( "Consolidated gateways calls report");
i18n_add ( "Consolidated groups calls report");
i18n_add ( "Consolidated servers calls report");
i18n_add ( "consolidated per extension");
i18n_add ( "consolidated per gateway");
i18n_add ( "consolidated per group");
i18n_add ( "consolidated per server");
i18n_add ( "The type of calls. If not specified, will compute all type of calls. 1 = All calls, 2 = Internal calls, 3 = External calls, 4 = External calls (With no cost), 5 = External calls (With cost), 6 = Mobile calls, 7 = Interstate calls, 8 = International calls");
i18n_add ( "The date and time of report start calls.");
i18n_add ( "An array matrix with hourly calls for 7 days and 0 to 23 hours of each day.");
i18n_add ( "An array with 7 arrays, starting at `sunday` *0* to `saturday` *6*.");
i18n_add ( "An array with 24 integers, starting at *0* to *23* of numbers of calls for each hour.");
i18n_add ( "The type is invalid.");
i18n_add ( "The start date is invalid.");
i18n_add ( "Request week hourly usage count report");
i18n_add ( "Week hourly usage count report");
i18n_add ( "Generate a week call week hourly usage count report.");
i18n_add ( "Missing start date.");
i18n_add ( "Invalid start date.");
i18n_add ( "Invalid type.");
i18n_add ( "Filter search extensions description based on this value.");
i18n_add ( "Filter search type description based on this value.");
i18n_add ( "An array containing the extension list.");
i18n_add ( "Extension unique system internal identification.");
i18n_add ( "Extension number.");
i18n_add ( "Extension description.");
i18n_add ( "Extension type.");
i18n_add ( "Extensions list report");
i18n_add ( "Extensions list report.");
i18n_add ( "The ID of range to be filtered. If not specified, return all ranges.");
i18n_add ( "Extension range.");
i18n_add ( "Headquarter");
i18n_add ( "Extension range ID.");
i18n_add ( "Extension server.");
i18n_add ( "Main server");
i18n_add ( "Extension server ID.");
i18n_add ( "The range is invalid.");
i18n_add ( "Generate range extension listings.");
i18n_add ( "Invalid range.");
i18n_add ( "The date and time of report end calls.");
i18n_add ( "An array containing the cost center extension list.");
i18n_add ( "Extension information.");
i18n_add ( "Total of calls.");
i18n_add ( "Total duration of calls in seconds.");
i18n_add ( "Total duration of calls formatted in [[DD:]HH:]MM:SS.");
i18n_add ( "Total cost of calls.");
i18n_add ( "Cost center financial reports");
i18n_add ( "Generate cost center financial reports.");
i18n_add ( "The cost center internal system unique identifier.");
i18n_add ( "Missing end date.");
i18n_add ( "Invalid end date.");
i18n_add ( "An array containing the range extension list.");
i18n_add ( "Group financial reports");
i18n_add ( "Generate group financial reports.");
i18n_add ( "The group internal system unique identifier.");
i18n_add ( "Gateway information.");
i18n_add ( "Gateway unique system internal identification.");
i18n_add ( "Gateway description.");
i18n_add ( "My SIP Provider");
i18n_add ( "Gateways financial reports");
i18n_add ( "Generate gateways financial reports.");
i18n_add ( "An object containing information about the system health.");
i18n_add ( "An object containing memory usage information.");
i18n_add ( "The percentage of used memory (rounded).");
i18n_add ( "The total of used memory.");
i18n_add ( "The total of memory.");
i18n_add ( "An object containing CPU usage information.");
i18n_add ( "The percentage of used CPU (rounded).");
i18n_add ( "The number of processors in server.");
i18n_add ( "An object containing storage usage information.");
i18n_add ( "The percentage of used storage (rounded).");
i18n_add ( "The total of used storage.");
i18n_add ( "The total of storage.");
i18n_add ( "System usage health report");
i18n_add ( "Provide the system usage health of server (Memory, CPU and Storage).");
i18n_add ( "An array containing the report results.");
i18n_add ( "Last date and time that extension did a call.");
i18n_add ( "The date and time of last placed call. Empty if none.");
i18n_add ( "The timestamp of last placed call. Empty if none.");
i18n_add ( "Last date and time that extension received a call.");
i18n_add ( "The date and time of last received call. Empty if none.");
i18n_add ( "The timestamp of last received call. Empty if none.");
i18n_add ( "Call activity report");
i18n_add ( "Generate an activity report with all extensions with latest received and dialed date time.");
i18n_add ( "An array containing the calls.");
i18n_add ( "Generate user received calls reports.");
i18n_add ( "The extension internal system unique identifier.");
i18n_add ( "Generate group received calls reports.");
i18n_add ( "Generate gateway received calls reports.");
i18n_add ( "The gateway internal system unique identifier.");
i18n_add ( "System received calls report");
i18n_add ( "Generate system received calls reports.");
i18n_add ( "Generate user made calls reports.");
i18n_add ( "Generate group made calls reports.");
i18n_add ( "Generate gateway made calls reports.");
i18n_add ( "System made calls report");
i18n_add ( "Generate system made calls reports.");
i18n_add ( "The month and year to generate consolidate report.");
i18n_add ( "An array containing report extensions.");
i18n_add ( "Local calls made by extension.");
i18n_add ( "Interstate calls made by extension.");
i18n_add ( "International calls made by extension.");
i18n_add ( "Others calls made by extension.");
i18n_add ( "Requested month date is invalid.");
i18n_add ( "Generate a consolidated calls report grouped by extensions.");
i18n_add ( "Group unique system internal identification.");
i18n_add ( "Group description.");
i18n_add ( "IT Team");
i18n_add ( "Generate a consolidated calls report grouped by groups.");
i18n_add ( "Generate a consolidated calls report grouped by gateways.");
i18n_add ( "Server unique system internal identification.");
i18n_add ( "Server description.");
i18n_add ( "Consolidated server calls report");
i18n_add ( "Generate a consolidated calls report grouped by servers.");
i18n_add ( "MM/DD/YYYY LTS");

/**
 * Add Brazilian Portuguese support
 */
i18n_add ( "Request extensions listing", "Requisitar listagem de ramais", "pt_BR");
i18n_add ( "Request ranges listing", "Requisitar listagem de faixas", "pt_BR");
i18n_add ( "Request financial cost centers report", "Requisitar relatório financeiro de centros de custo", "pt_BR");
i18n_add ( "Request financial groups report", "Requisitar relatório financeiro de grupos", "pt_BR");
i18n_add ( "Request financial gateways report", "Requisitar relatório financeiro de gateways", "pt_BR");
i18n_add ( "Request server health", "Requisitar estado do servidor", "pt_BR");
i18n_add ( "Request extensions activity report", "Requisitar listagem de atividade de ramais", "pt_BR");
i18n_add ( "Heat map", "Calor", "pt_BR");
i18n_add ( "Graphical reports", "Relatórios gráficos", "pt_BR");
i18n_add ( "heat map graph", "gráfico de calor", "pt_BR");
i18n_add ( "Heat map graph", "Gráfico de calor", "pt_BR");
i18n_add ( "Call type", "Tipo de ligação", "pt_BR");
i18n_add ( "All types", "Todos tipos", "pt_BR");
i18n_add ( "Internal calls", "Ligações internas", "pt_BR");
i18n_add ( "External calls", "Ligações externas", "pt_BR");
i18n_add ( "External calls (With no cost)", "Ligações externas (Sem custo)", "pt_BR");
i18n_add ( "External calls (With cost)", "Ligações externas (Com custo)", "pt_BR");
i18n_add ( "Mobile calls", "Ligações para celulares", "pt_BR");
i18n_add ( "Interstate calls", "Ligações interurbanas", "pt_BR");
i18n_add ( "International calls", "Ligações internacionais", "pt_BR");
i18n_add ( "Error requesting information!", "Erro ao requisitar informações!", "pt_BR");
i18n_add ( "extensions listing", "listagem de ramais", "pt_BR");
i18n_add ( "Name", "Nome", "pt_BR");
i18n_add ( "Group", "Grupo", "pt_BR");
i18n_add ( "ranges listing", "listagem de faixas", "pt_BR");
i18n_add ( "Range", "Faixa", "pt_BR");
i18n_add ( "financial by cost center", "financeiro por centro de custo", "pt_BR");
i18n_add ( "Calls", "Ligações", "pt_BR");
i18n_add ( "Time", "Tempo", "pt_BR");
i18n_add ( "The cost center is required.", "O centro de custo é obrigatório.", "pt_BR");
i18n_add ( "financial by group", "financeiro por grupo", "pt_BR");
i18n_add ( "The group is required.", "O grupo é obrigatório.", "pt_BR");
i18n_add ( "financial by gateway", "financeiro por gateway", "pt_BR");
i18n_add ( "server health", "estado do servidor", "pt_BR");
i18n_add ( "Automatic update", "Atualização automática", "pt_BR");
i18n_add ( "Disabled", "Desativado", "pt_BR");
i18n_add ( "1 second", "1 segundo", "pt_BR");
i18n_add ( "%d seconds", "%d segundos", "pt_BR");
i18n_add ( "Used memory * 100 / Total memory", "Memória em uso * 100 / Memória total", "pt_BR");
i18n_add ( "Memory", "Memória", "pt_BR");
i18n_add ( "Processors usage sum (percentage) / Number of processors", "Soma de uso dos processadores (porcentagem) / Número de processadores", "pt_BR");
i18n_add ( "CPU", "CPU", "pt_BR");
i18n_add ( "processor(s)", "processador(es)", "pt_BR");
i18n_add ( "Used space * 100 / Total space", "Espaço utilizado * 100 / Espaço total", "pt_BR");
i18n_add ( "Storage", "Armazenamento", "pt_BR");
i18n_add ( "Server health", "Estado do servidor", "pt_BR");
i18n_add ( "activity listing", "listagem por atividade", "pt_BR");
i18n_add ( "Last dialed", "Última discada", "pt_BR");
i18n_add ( "Last received", "Última recebida", "pt_BR");
i18n_add ( "Never dialed", "Nunca discado", "pt_BR");
i18n_add ( "Never received", "Nunca recebido", "pt_BR");
i18n_add ( "call", "ligação", "pt_BR");
i18n_add ( "calls", "ligações", "pt_BR");
i18n_add ( "Export to", "Exportar para", "pt_BR");
i18n_add ( "calls made by all", "chamadas realizadas por todos", "pt_BR");
i18n_add ( "calls made by gateway", "chamadas realizadas por gateway", "pt_BR");
i18n_add ( "calls made by group", "chamadas realizadas por grupo", "pt_BR");
i18n_add ( "calls made by user", "chamadas realizadas por usuário", "pt_BR");
i18n_add ( "calls received by all", "chamadas recebidas por todos", "pt_BR");
i18n_add ( "calls received by gateway", "chamadas recebidas por gateway", "pt_BR");
i18n_add ( "calls received by group", "chamadas recebidas por grupo", "pt_BR");
i18n_add ( "calls received by user", "chamadas recebidas por usuário", "pt_BR");
i18n_add ( "Gateway made calls report", "Relatório de chamadas realizadas por gateway", "pt_BR");
i18n_add ( "Gateway received calls report", "Relatório de chamadas recebidas por gateway", "pt_BR");
i18n_add ( "Group made calls report", "Relatório de chamadas realizadas por grupo", "pt_BR");
i18n_add ( "Group received calls report", "Relatório de chamadas recebidas por grupo", "pt_BR");
i18n_add ( "All made calls report", "Relatório de chamadas realizadas por todos", "pt_BR");
i18n_add ( "All received calls report", "Relatório de chamadas recebidas por todos", "pt_BR");
i18n_add ( "The extension is required.", "O ramal é obrigatório.", "pt_BR");
i18n_add ( "The gateway is required.", "O gateway é obrigatório.", "pt_BR");
i18n_add ( "User made calls report", "Relatório de chamadas realizadas por usuário", "pt_BR");
i18n_add ( "User received calls report", "Relatório de chamadas recebidas por usuário", "pt_BR");
i18n_add ( "Calls made", "Ligações efetuadas", "pt_BR");
i18n_add ( "Per user", "Por usuário", "pt_BR");
i18n_add ( "Per group", "Por grupo", "pt_BR");
i18n_add ( "Per gateway", "Por gateway", "pt_BR");
i18n_add ( "All", "Todas", "pt_BR");
i18n_add ( "Calls received", "Ligações recebidas", "pt_BR");
i18n_add ( "Financial", "Financeiros", "pt_BR");
i18n_add ( "Cost Centers", "Centros de Custo", "pt_BR");
i18n_add ( "Groups", "Grupos", "pt_BR");
i18n_add ( "Gateways", "Gateways", "pt_BR");
i18n_add ( "Graphs", "Gráficos", "pt_BR");
i18n_add ( "Per server", "Por servidor", "pt_BR");
i18n_add ( "Costs", "Custos", "pt_BR");
i18n_add ( "Monitory", "Monitoria", "pt_BR");
i18n_add ( "Extensions listing", "Listagem de ramais", "pt_BR");
i18n_add ( "Ranges listing", "Listagem de faixas", "pt_BR");
i18n_add ( "Activity listing", "Listagem por atividade", "pt_BR");
i18n_add ( "Server status", "Estado do servidor", "pt_BR");
i18n_add ( "All durations are billing time in [[DD:]HH:]MM:SS format.", "Todas durações são bilhetagem no formato [[DD:][HH:]MM:SS.", "pt_BR");
i18n_add ( "Others", "Outros", "pt_BR");
i18n_add ( "MM/YYYY", "MM/YYYY", "pt_BR");
i18n_add ( "The month/year is required.", "O mês/ano é obrigatório.", "pt_BR");
i18n_add ( "Consolidated", "Consolidado", "pt_BR");
i18n_add ( "Consolidated extensions calls report", "Relatório consolidado de ligações por ramal", "pt_BR");
i18n_add ( "Consolidated gateways calls report", "Relatório consolidado de ligações por gateway", "pt_BR");
i18n_add ( "Consolidated groups calls report", "Relatório consolidado de ligações por grupo", "pt_BR");
i18n_add ( "Consolidated servers calls report", "Relatório consolidado de ligações por servidor", "pt_BR");
i18n_add ( "consolidated per extension", "consolidado por ramal", "pt_BR");
i18n_add ( "consolidated per gateway", "consolidado por gateway", "pt_BR");
i18n_add ( "consolidated per group", "consolidado por grupo", "pt_BR");
i18n_add ( "consolidated per server", "consolidado por servidor", "pt_BR");
i18n_add ( "The type of calls. If not specified, will compute all type of calls. 1 = All calls, 2 = Internal calls, 3 = External calls, 4 = External calls (With no cost), 5 = External calls (With cost), 6 = Mobile calls, 7 = Interstate calls, 8 = International calls", "O tipo das chamadas. Se não especificado, será compilado todos os tipos de chamadas. 1 = Todas chamadas, 2 = Chamadas internas, 3 = Chamadas externas, 4 = Chamadas externas (Sem custo), 5 = Chamadas externas (Com custo), 6 = Chamadas para dispositivos móveis, 7 = Chamadas interestaduais, 8 = Chamadas internacionais", "pt_BR");
i18n_add ( "The date and time of report start calls.", "A data e hora do início do relatório de ligações.", "pt_BR");
i18n_add ( "An array matrix with hourly calls for 7 days and 0 to 23 hours of each day.", "Uma matriz de array de ligações por hora para 7 dias e 0 a 23 horas cada dia.", "pt_BR");
i18n_add ( "An array with 7 arrays, starting at `sunday` *0* to `saturday` *6*.", "Um array com 7 arrays, começando por `domingo` *0* até `sábado` *6*.", "pt_BR");
i18n_add ( "An array with 24 integers, starting at *0* to *23* of numbers of calls for each hour.", "Um array com 24 inteiros, iniciando em *0* até *23* com o número de chamadas por hora.", "pt_BR");
i18n_add ( "The type is invalid.", "O tipo é inválido.", "pt_BR");
i18n_add ( "The start date is invalid.", "A data de início é inválida.", "pt_BR");
i18n_add ( "Request week hourly usage count report", "Requisita relatório de utilização semanal de ligações por hora", "pt_BR");
i18n_add ( "Week hourly usage count report", "Relatório semanal de uso por hora", "pt_BR");
i18n_add ( "Generate a week call week hourly usage count report.", "Gerar um relatório de utilização por hora e por semana.", "pt_BR");
i18n_add ( "Missing start date.", "Data de início obrigatória.", "pt_BR");
i18n_add ( "Invalid start date.", "Data de início inválida.", "pt_BR");
i18n_add ( "Invalid type.", "Tipo inválido.", "pt_BR");
i18n_add ( "Filter search extensions description based on this value.", "Filtrar a descrição das extensões baseada neste valor.", "pt_BR");
i18n_add ( "Filter search type description based on this value.", "Filtrar a descrição do tipo baseada neste valor.", "pt_BR");
i18n_add ( "An array containing the extension list.", "Um array contendo a lista de extensões.", "pt_BR");
i18n_add ( "Extension unique system internal identification.", "Identificador interno único da extensão do sistema.", "pt_BR");
i18n_add ( "Extension number.", "Número da extensão.", "pt_BR");
i18n_add ( "Extension description.", "Descrição da extensão.", "pt_BR");
i18n_add ( "Extension type.", "Tipo da extensão.", "pt_BR");
i18n_add ( "Extensions list report", "Relatório de extensões", "pt_BR");
i18n_add ( "Extensions list report.", "Relatório de extensões.", "pt_BR");
i18n_add ( "The ID of range to be filtered. If not specified, return all ranges.", "O ID da faixa a ser filtrada. Se não especificado, retorna todas faixas.", "pt_BR");
i18n_add ( "Extension range.", "Faixa da extensão.", "pt_BR");
i18n_add ( "Headquarter", "Quartel general", "pt_BR");
i18n_add ( "Extension range ID.", "ID da faixa da extensão.", "pt_BR");
i18n_add ( "Extension server.", "Servidor da extensão.", "pt_BR");
i18n_add ( "Main server", "Servidor principal", "pt_BR");
i18n_add ( "Extension server ID.", "ID do servidor da extensão.", "pt_BR");
i18n_add ( "The range is invalid.", "A faixa é inválida.", "pt_BR");
i18n_add ( "Generate range extension listings.", "Gerar listagem de extensões por faixa.", "pt_BR");
i18n_add ( "Invalid range.", "Faixa inválida.", "pt_BR");
i18n_add ( "The date and time of report end calls.", "A data e hora de término do relatório de chamadas.", "pt_BR");
i18n_add ( "An array containing the cost center extension list.", "Um array contendo a listagem de extensões do centro de custo.", "pt_BR");
i18n_add ( "Extension information.", "Informações da extensão.", "pt_BR");
i18n_add ( "Total of calls.", "Total de chamadas.", "pt_BR");
i18n_add ( "Total duration of calls in seconds.", "Duração total das chamadas em segundos.", "pt_BR");
i18n_add ( "Total duration of calls formatted in [[DD:]HH:]MM:SS.", "Duração total das chamadas formatada em [[DD:]HH:]MM:SS.", "pt_BR");
i18n_add ( "Total cost of calls.", "O custo total das chamadas.", "pt_BR");
i18n_add ( "Cost center financial reports", "Relatório financeiro por centro de custo", "pt_BR");
i18n_add ( "Generate cost center financial reports.", "Gerar relatórios financeiros por centro de custo.", "pt_BR");
i18n_add ( "The cost center internal system unique identifier.", "O identificador único interno do sistema do centro de custo.", "pt_BR");
i18n_add ( "Missing end date.", "Data final obrigatória.", "pt_BR");
i18n_add ( "Invalid end date.", "Data final inválida.", "pt_BR");
i18n_add ( "An array containing the range extension list.", "Um array contendo a listagem de extensões por faixa.", "pt_BR");
i18n_add ( "Group financial reports", "Relatórios financeiros por grupo", "pt_BR");
i18n_add ( "Generate group financial reports.", "Gerar relatórios financeiros por grupo.", "pt_BR");
i18n_add ( "The group internal system unique identifier.", "O identificador interno único do sistema do grupo.", "pt_BR");
i18n_add ( "Gateway information.", "Informações do gateway.", "pt_BR");
i18n_add ( "Gateway unique system internal identification.", "O identificador interno único do sistema do gateway.", "pt_BR");
i18n_add ( "Gateway description.", "Descrição do gateway.", "pt_BR");
i18n_add ( "My SIP Provider", "Meu Provedor SIP", "pt_BR");
i18n_add ( "Gateways financial reports", "Relatórios financeiros por gateway", "pt_BR");
i18n_add ( "Generate gateways financial reports.", "Gerar relatórios financeiros por gateway.", "pt_BR");
i18n_add ( "An object containing information about the system health.", "Um objeto contendo informações sobre a saúde do sistema.", "pt_BR");
i18n_add ( "An object containing memory usage information.", "Um objeto contento informações do uso de memória.", "pt_BR");
i18n_add ( "The percentage of used memory (rounded).", "A porcentagem do uso de memória (arrendondado).", "pt_BR");
i18n_add ( "The total of used memory.", "Total do uso de memória.", "pt_BR");
i18n_add ( "The total of memory.", "Total de memória.", "pt_BR");
i18n_add ( "An object containing CPU usage information.", "Um objeto contendo informações do uso de CPU.", "pt_BR");
i18n_add ( "The percentage of used CPU (rounded).", "A porcentagem do uso de CPU (arredondado).", "pt_BR");
i18n_add ( "The number of processors in server.", "O número de processadores no servidor.", "pt_BR");
i18n_add ( "An object containing storage usage information.", "Um objeto contendo informações do uso de armazenamento.", "pt_BR");
i18n_add ( "The percentage of used storage (rounded).", "A porcentagem de uso de armazenamento (arredondado).", "pt_BR");
i18n_add ( "The total of used storage.", "O uso total de armazenamento.", "pt_BR");
i18n_add ( "The total of storage.", "O total de armazenamento.", "pt_BR");
i18n_add ( "System usage health report", "Relatório de saúde da utilização do sistema", "pt_BR");
i18n_add ( "Provide the system usage health of server (Memory, CPU and Storage).", "Provê a saúde de utilização do servidor (Memória, CPU e Armazenamento).", "pt_BR");
i18n_add ( "An array containing the report results.", "Um array contendo os resultados do relatório.", "pt_BR");
i18n_add ( "Last date and time that extension did a call.", "Última data e hora que a extensão realizou uma chamada.", "pt_BR");
i18n_add ( "The date and time of last placed call. Empty if none.", "A data e hora da última chamada efetuada. Vazio se nenhuma.", "pt_BR");
i18n_add ( "The timestamp of last placed call. Empty if none.", "O timestamp da última chamada efetuada. Vazio se nenhuma.", "pt_BR");
i18n_add ( "Last date and time that extension received a call.", "Última data e hora que a extensão recebeu uma chamada.", "pt_BR");
i18n_add ( "The date and time of last received call. Empty if none.", "A data e hora da última ligação recebida. Vazio se nenhuma.", "pt_BR");
i18n_add ( "The timestamp of last received call. Empty if none.", "O timestamp da última chamada recebida. Vazio se nenhuma.", "pt_BR");
i18n_add ( "Call activity report", "Relatório de atividade de chamadas", "pt_BR");
i18n_add ( "Generate an activity report with all extensions with latest received and dialed date time.", "Gerar um relatório de atividades de todas extensões com data e hora de discagem.", "pt_BR");
i18n_add ( "An array containing the calls.", "Um array contendo as chamadas.", "pt_BR");
i18n_add ( "Generate user received calls reports.", "Gerar relatório de chamadas recebidas de usuários.", "pt_BR");
i18n_add ( "The extension internal system unique identifier.", "O identificador interno único do sistema da extensão.", "pt_BR");
i18n_add ( "Generate group received calls reports.", "Gerar relatório de chamadas recebidas por grupo.", "pt_BR");
i18n_add ( "Generate gateway received calls reports.", "Gerar relatório de chamadas recebidas por gateway.", "pt_BR");
i18n_add ( "The gateway internal system unique identifier.", "O identificador interno único do sistema do gateway.", "pt_BR");
i18n_add ( "System received calls report", "Relatório de chamadas recebidas do sistema", "pt_BR");
i18n_add ( "Generate system received calls reports.", "Gerar relatório de chamadas recebidas do sistema.", "pt_BR");
i18n_add ( "Generate user made calls reports.", "Gerar relatório de chamadas efetuadas por usuários.", "pt_BR");
i18n_add ( "Generate group made calls reports.", "Gerar relatório de chamadas efetuadas por grupos.", "pt_BR");
i18n_add ( "Generate gateway made calls reports.", "Gerar relatório de chamadas efetuadas do sistema.", "pt_BR");
i18n_add ( "System made calls report", "Relatório de chamadas efetuadas do sistema", "pt_BR");
i18n_add ( "Generate system made calls reports.", "Gerar relatório de chamadas efetuadas do sistema.", "pt_BR");
i18n_add ( "The month and year to generate consolidate report.", "O mês e ano para gerar o relatório consolidado.", "pt_BR");
i18n_add ( "An array containing report extensions.", "Um array contendo relatório de extensões.", "pt_BR");
i18n_add ( "Local calls made by extension.", "Chamadas locais efetuadas por extensão.", "pt_BR");
i18n_add ( "Interstate calls made by extension.", "Chamadas interestaduais efetuadas por extensão.", "pt_BR");
i18n_add ( "International calls made by extension.", "Chamadas internacionais efetuadas por extensão.", "pt_BR");
i18n_add ( "Others calls made by extension.", "Outras chamadas efetuadas por extensão.", "pt_BR");
i18n_add ( "Requested month date is invalid.", "A data de mês requisitada é inválida.", "pt_BR");
i18n_add ( "Generate a consolidated calls report grouped by extensions.", "Gerar relatório consolidado de chamadas agrupadas por extensão.", "pt_BR");
i18n_add ( "Group unique system internal identification.", "Identificador interno único do sistema do grupo.", "pt_BR");
i18n_add ( "Group description.", "Descrição do grupo.", "pt_BR");
i18n_add ( "IT Team", "Time de TI", "pt_BR");
i18n_add ( "Generate a consolidated calls report grouped by groups.", "Gerar relatório consolidado de chamadas agrupado por grupos.", "pt_BR");
i18n_add ( "Generate a consolidated calls report grouped by gateways.", "Gerar relatório consolidado de chamadas agrupado por gateways.", "pt_BR");
i18n_add ( "Server unique system internal identification.", "Identificador interno único do sistema do servidor.", "pt_BR");
i18n_add ( "Server description.", "Descrição do servidor.", "pt_BR");
i18n_add ( "Consolidated server calls report", "Relatório consolidado de chamadas do servidor", "pt_BR");
i18n_add ( "Generate a consolidated calls report grouped by servers.", "Gerar relatório consolidado de chamadas agrupado por servidores.", "pt_BR");
i18n_add ( "MM/DD/YYYY LTS", "DD/MM/YYYY LTS", "pt_BR");
?>
