<?php
/**   ___ ___       ___ _______     ______                        __
 *   |   Y   .-----|   |   _   |   |   _  \ .-----.--------.---.-|__.-----.
 *   |.  |   |  _  |.  |.  1   |   |.  |   \|  _  |        |  _  |  |     |
 *   |.  |   |_____|.  |.  ____|   |.  |    |_____|__|__|__|___._|__|__|__|
 *   |:  1   |     |:  |:  |       |:  1    /
 *    \:.. ./      |::.|::.|       |::.. . /
 *     `---'       `---`---'       `------'
 *
 * Copyright (C) 2016-2025 Ernani José Camargo Azevedo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * VoIP Domain country database module filters. This module add the filter calls
 * related to country database of Zimbabwe.
 *
 * Reference: https://www.itu.int/oth/T02020000E9/en (2019-02-14)
 *
 * Glossary:
 *  CC - Country Code
 *  NDC - National Destination Code (also known as area code)
 *  N(S)N - National (Significant) Number
 *  SN - Subscriber Number
 *
 * @author     Ernani José Camargo Azevedo <azevedo@voipdomain.io>
 * @version    1.0
 * @package    VoIP Domain
 * @subpackage CountryDB
 * @copyright  2016-2025 Ernani José Camargo Azevedo. All rights reserved.
 * @license    https://www.gnu.org/licenses/gpl-3.0.en.html
 */

/**
 * E.164 Zimbabwe country hook
 */
framework_add_filter ( "e164_identify_country_ZWE", "e164_identify_country_ZWE");

/**
 * E.164 Zimbabwian area number identification hook. This hook is an
 * e164_identify sub hook, called when the ISO3166 Alpha3 are "ZWE" (code for
 * Zimbabwe). This hook will verify if phone number is valid, returning the area
 * code, area name, phone number, others number related information and if
 * possible, the number type (mobile, landline, Premium Rate Number, etc).
 *
 * @param string $buffer Buffer from plugin system if processed by other function
 *                       before
 * @param array $parameters Parameters to the function. Number provided as
 *                          $parameters["Number"]
 * @return array Array contaning many information about the requested number
 */
function e164_identify_country_ZWE ( $buffer, $parameters)
{
  /**
   * Check if number country code is from Zimbabwe
   */
  if ( substr ( $parameters["Number"], 0, 4) != "+263")
  {
    return ( is_array ( $buffer) ? $buffer : false);
  }

  /**
   * All numbers in Zimbabwe has 11, 13 or 14 digits E.164 format
   */
  if ( ! ( strlen ( $parameters["Number"]) == 11 || strlen ( $parameters["Number"]) == 13 || strlen ( $parameters["Number"]) == 14))
  {
    return ( is_array ( $buffer) ? $buffer : false);
  }

  /**
   * Check for mobile network with 2 digits NDC and 7 digits SN
   */
  $prefixes = array (
    "787" => "Econet Wireless Zimbabwe",
    "786" => "Econet Wireless Zimbabwe",
    "785" => "Econet Wireless Zimbabwe",
    "784" => "Econet Wireless Zimbabwe",
    "783" => "Econet Wireless Zimbabwe",
    "782" => "Econet Wireless Zimbabwe",
    "779" => "Econet Wireless Zimbabwe",
    "778" => "Econet Wireless Zimbabwe",
    "777" => "Econet Wireless Zimbabwe",
    "776" => "Econet Wireless Zimbabwe",
    "775" => "Econet Wireless Zimbabwe",
    "774" => "Econet Wireless Zimbabwe",
    "773" => "Econet Wireless Zimbabwe",
    "772" => "Econet Wireless Zimbabwe",
    "771" => "Econet Wireless Zimbabwe",
    "739" => "Telecel Zimbabwe",
    "738" => "Telecel Zimbabwe",
    "737" => "Telecel Zimbabwe",
    "736" => "Telecel Zimbabwe",
    "735" => "Telecel Zimbabwe",
    "734" => "Telecel Zimbabwe",
    "733" => "Telecel Zimbabwe",
    "732" => "Telecel Zimbabwe",
    "719" => "NetOne Cellular",
    "718" => "NetOne Cellular",
    "717" => "NetOne Cellular",
    "716" => "NetOne Cellular",
    "715" => "NetOne Cellular",
    "714" => "NetOne Cellular",
    "713" => "NetOne Cellular",
    "712" => "NetOne Cellular",
    "79" => "",
    "76" => "",
    "75" => "",
    "74" => "",
    "72" => "",
    "70" => ""
  );
  foreach ( $prefixes as $prefix => $operator)
  {
    if ( strlen ( $parameters["Number"]) == 13 && (int) substr ( $parameters["Number"], 4, strlen ( $prefix)) == $prefix)
    {
      return array_merge_recursive ( ( is_array ( $buffer) ? $buffer : array ()), array ( "CC" => "263", "NDC" => substr ( $parameters["Number"], 4, 2), "Country" => "Zimbabwe", "Area" => "", "City" => "", "Operator" => $operator, "SN" => substr ( $parameters["Number"], 6), "Type" => VD_PHONETYPE_MOBILE, "CallFormats" => array ( "Local" => "0" . substr ( $parameters["Number"], 4, 2) . " " . substr ( $parameters["Number"], 6), "International" => "+263 " . substr ( $parameters["Number"], 4, 2) . " " . substr ( $parameters["Number"], 6))));
    }
  }

  /**
   * Check for fixed line network with 2 digits NDC and 7 digits SN
   */
  $prefixes = array (
    "8428351" => array ( "Area" => "Matabeleland", "City" => "Collen Bawn (CBN)"),
    "8428350" => array ( "Area" => "Matabeleland", "City" => "Collen Bawn (CBN)"),
    "8428088" => array ( "Area" => "Matabeleland", "City" => "West Nicholson"),
    "8428087" => array ( "Area" => "Matabeleland", "City" => "West Nicholson"),
    "8428086" => array ( "Area" => "Matabeleland", "City" => "West Nicholson"),
    "8428085" => array ( "Area" => "Matabeleland", "City" => "West Nicholson"),
    "8428084" => array ( "Area" => "Matabeleland", "City" => "West Nicholson"),
    "8428083" => array ( "Area" => "Matabeleland", "City" => "West Nicholson"),
    "8428082" => array ( "Area" => "Matabeleland", "City" => "West Nicholson"),
    "8128478" => array ( "Area" => "Matabeleland", "City" => "Binga"),
    "8128477" => array ( "Area" => "Matabeleland", "City" => "Binga"),
    "8128476" => array ( "Area" => "Matabeleland", "City" => "Binga"),
    "8128475" => array ( "Area" => "Matabeleland", "City" => "Binga"),
    "8128474" => array ( "Area" => "Matabeleland", "City" => "Binga"),
    "8128473" => array ( "Area" => "Matabeleland", "City" => "Binga"),
    "8128472" => array ( "Area" => "Matabeleland", "City" => "Binga"),
    "8128358" => array ( "Area" => "Matabeleland", "City" => "Dete"),
    "8128357" => array ( "Area" => "Matabeleland", "City" => "Dete"),
    "8128356" => array ( "Area" => "Matabeleland", "City" => "Dete"),
    "8128355" => array ( "Area" => "Matabeleland", "City" => "Dete"),
    "8128354" => array ( "Area" => "Matabeleland", "City" => "Dete"),
    "8128353" => array ( "Area" => "Matabeleland", "City" => "Dete"),
    "8128352" => array ( "Area" => "Matabeleland", "City" => "Dete"),
    "6821898" => array ( "Area" => "Mashonaland", "City" => "Chakari"),
    "6821897" => array ( "Area" => "Mashonaland", "City" => "Chakari"),
    "6821896" => array ( "Area" => "Mashonaland", "City" => "Chakari"),
    "6821895" => array ( "Area" => "Mashonaland", "City" => "Chakari"),
    "6821894" => array ( "Area" => "Mashonaland", "City" => "Chakari"),
    "6821893" => array ( "Area" => "Mashonaland", "City" => "Chakari"),
    "6821892" => array ( "Area" => "Mashonaland", "City" => "Chakari"),
    "6821554" => array ( "Area" => "Mashonaland", "City" => "Chegutu"),
    "6821553" => array ( "Area" => "Mashonaland", "City" => "Chegutu"),
    "6821552" => array ( "Area" => "Mashonaland", "City" => "Chegutu"),
    "6821551" => array ( "Area" => "Mashonaland", "City" => "Chegutu"),
    "6821550" => array ( "Area" => "Mashonaland", "City" => "Chegutu"),
    "6821529" => array ( "Area" => "Mashonaland", "City" => "Chegutu"),
    "6821528" => array ( "Area" => "Mashonaland", "City" => "Chegutu"),
    "6821527" => array ( "Area" => "Mashonaland", "City" => "Chegutu"),
    "6821526" => array ( "Area" => "Mashonaland", "City" => "Chegutu"),
    "6821525" => array ( "Area" => "Mashonaland", "City" => "Chegutu"),
    "6821524" => array ( "Area" => "Mashonaland", "City" => "Chegutu"),
    "6821523" => array ( "Area" => "Mashonaland", "City" => "Chegutu"),
    "6821522" => array ( "Area" => "Mashonaland", "City" => "Chegutu"),
    "6820105" => array ( "Area" => "Mashonaland", "City" => "Selous"),
    "6820104" => array ( "Area" => "Mashonaland", "City" => "Selous"),
    "6820103" => array ( "Area" => "Mashonaland", "City" => "Selous"),
    "6820102" => array ( "Area" => "Mashonaland", "City" => "Selous"),
    "6820101" => array ( "Area" => "Mashonaland", "City" => "Selous"),
    "6820100" => array ( "Area" => "Mashonaland", "City" => "Selous"),
    "6820089" => array ( "Area" => "Mashonaland", "City" => "Selous"),
    "6820088" => array ( "Area" => "Mashonaland", "City" => "Selous"),
    "6820087" => array ( "Area" => "Mashonaland", "City" => "Selous"),
    "6820086" => array ( "Area" => "Mashonaland", "City" => "Selous"),
    "6820085" => array ( "Area" => "Mashonaland", "City" => "Selous"),
    "6721988" => array ( "Area" => "Mashonaland", "City" => "Raffingora"),
    "6721987" => array ( "Area" => "Mashonaland", "City" => "Raffingora"),
    "6721986" => array ( "Area" => "Mashonaland", "City" => "Raffingora"),
    "6721985" => array ( "Area" => "Mashonaland", "City" => "Raffingora"),
    "6721984" => array ( "Area" => "Mashonaland", "City" => "Raffingora"),
    "6721983" => array ( "Area" => "Mashonaland", "City" => "Raffingora"),
    "6721982" => array ( "Area" => "Mashonaland", "City" => "Raffingora"),
    "6721968" => array ( "Area" => "Mashonaland", "City" => "Mutorashanga"),
    "6721967" => array ( "Area" => "Mashonaland", "City" => "Mutorashanga"),
    "6721966" => array ( "Area" => "Mashonaland", "City" => "Mutorashanga"),
    "6721965" => array ( "Area" => "Mashonaland", "City" => "Mutorashanga"),
    "6721964" => array ( "Area" => "Mashonaland", "City" => "Mutorashanga"),
    "6721963" => array ( "Area" => "Mashonaland", "City" => "Mutorashanga"),
    "6721962" => array ( "Area" => "Mashonaland", "City" => "Mutorashanga"),
    "6721927" => array ( "Area" => "Mashonaland", "City" => "Darwendale"),
    "6721926" => array ( "Area" => "Mashonaland", "City" => "Darwendale"),
    "6721925" => array ( "Area" => "Mashonaland", "City" => "Darwendale"),
    "6721924" => array ( "Area" => "Mashonaland", "City" => "Darwendale"),
    "6721923" => array ( "Area" => "Mashonaland", "City" => "Darwendale"),
    "6721922" => array ( "Area" => "Mashonaland", "City" => "Darwendale"),
    "6721368" => array ( "Area" => "Mashonaland", "City" => "Trelawney"),
    "6721367" => array ( "Area" => "Mashonaland", "City" => "Trelawney"),
    "6721366" => array ( "Area" => "Mashonaland", "City" => "Trelawney"),
    "6721365" => array ( "Area" => "Mashonaland", "City" => "Trelawney"),
    "6721364" => array ( "Area" => "Mashonaland", "City" => "Trelawney"),
    "6721363" => array ( "Area" => "Mashonaland", "City" => "Trelawney"),
    "6721362" => array ( "Area" => "Mashonaland", "City" => "Trelawney"),
    "6621959" => array ( "Area" => "Mashonaland", "City" => "Christon Bank"),
    "6621958" => array ( "Area" => "Mashonaland", "City" => "Christon Bank"),
    "6621957" => array ( "Area" => "Mashonaland", "City" => "Christon Bank"),
    "6621956" => array ( "Area" => "Mashonaland", "City" => "Christon Bank"),
    "6621955" => array ( "Area" => "Mashonaland", "City" => "Christon Bank"),
    "6621954" => array ( "Area" => "Mashonaland", "City" => "Mazowe"),
    "6621953" => array ( "Area" => "Mashonaland", "City" => "Mazowe"),
    "6621952" => array ( "Area" => "Mashonaland", "City" => "Mazowe"),
    "6621951" => array ( "Area" => "Mashonaland", "City" => "Mazowe"),
    "6621950" => array ( "Area" => "Mashonaland", "City" => "Mazowe"),
    "6621928" => array ( "Area" => "Mashonaland", "City" => "Concession"),
    "6621828" => array ( "Area" => "Mashonaland", "City" => "Glendale"),
    "6621827" => array ( "Area" => "Mashonaland", "City" => "Glendale"),
    "6621826" => array ( "Area" => "Mashonaland", "City" => "Glendale"),
    "6621825" => array ( "Area" => "Mashonaland", "City" => "Glendale"),
    "6621824" => array ( "Area" => "Mashonaland", "City" => "Glendale"),
    "6621823" => array ( "Area" => "Mashonaland", "City" => "Glendale"),
    "6621822" => array ( "Area" => "Mashonaland", "City" => "Glendale"),
    "6621821" => array ( "Area" => "Mashonaland", "City" => "Glendale"),
    "6621820" => array ( "Area" => "Mashonaland", "City" => "Glendale"),
    "6621378" => array ( "Area" => "Mashonaland", "City" => "Shamva"),
    "6621377" => array ( "Area" => "Mashonaland", "City" => "Shamva"),
    "6621376" => array ( "Area" => "Mashonaland", "City" => "Shamva"),
    "6621375" => array ( "Area" => "Mashonaland", "City" => "Shamva"),
    "6621374" => array ( "Area" => "Mashonaland", "City" => "Shamva"),
    "6621373" => array ( "Area" => "Mashonaland", "City" => "Shamva"),
    "6621372" => array ( "Area" => "Mashonaland", "City" => "Shamva"),
    "6621241" => array ( "Area" => "Mashonaland", "City" => "Mount Darwin"),
    "6621240" => array ( "Area" => "Mashonaland", "City" => "Mount Darwin"),
    "6621229" => array ( "Area" => "Mashonaland", "City" => "Mount Darwin"),
    "6621228" => array ( "Area" => "Mashonaland", "City" => "Mount Darwin"),
    "6621227" => array ( "Area" => "Mashonaland", "City" => "Mount Darwin"),
    "6621226" => array ( "Area" => "Mashonaland", "City" => "Mount Darwin"),
    "6621225" => array ( "Area" => "Mashonaland", "City" => "Mount Darwin"),
    "6621224" => array ( "Area" => "Mashonaland", "City" => "Mount Darwin"),
    "6621223" => array ( "Area" => "Mashonaland", "City" => "Mount Darwin"),
    "6621222" => array ( "Area" => "Mashonaland", "City" => "Mount Darwin"),
    "6520808" => array ( "Area" => "Mashonaland", "City" => "Macheke"),
    "6520807" => array ( "Area" => "Mashonaland", "City" => "Macheke"),
    "6520806" => array ( "Area" => "Mashonaland", "City" => "Macheke"),
    "6520805" => array ( "Area" => "Mashonaland", "City" => "Macheke"),
    "6520804" => array ( "Area" => "Mashonaland", "City" => "Macheke"),
    "6520803" => array ( "Area" => "Mashonaland", "City" => "Macheke"),
    "6520802" => array ( "Area" => "Mashonaland", "City" => "Macheke"),
    "6121467" => array ( "Area" => "Mashonaland", "City" => "Kariba"),
    "6121466" => array ( "Area" => "Mashonaland", "City" => "Kariba"),
    "6121465" => array ( "Area" => "Mashonaland", "City" => "Kariba"),
    "6121464" => array ( "Area" => "Mashonaland", "City" => "Kariba"),
    "6121463" => array ( "Area" => "Mashonaland", "City" => "Kariba"),
    "6121462" => array ( "Area" => "Mashonaland", "City" => "Kariba"),
    "6121461" => array ( "Area" => "Mashonaland", "City" => "Kariba"),
    "6121460" => array ( "Area" => "Mashonaland", "City" => "Kariba"),
    "6121436" => array ( "Area" => "Mashonaland", "City" => "Karoi"),
    "6121435" => array ( "Area" => "Mashonaland", "City" => "Karoi"),
    "6121434" => array ( "Area" => "Mashonaland", "City" => "Karoi"),
    "6121433" => array ( "Area" => "Mashonaland", "City" => "Karoi"),
    "6121432" => array ( "Area" => "Mashonaland", "City" => "Karoi"),
    "6121431" => array ( "Area" => "Mashonaland", "City" => "Karoi"),
    "6121430" => array ( "Area" => "Mashonaland", "City" => "Karoi"),
    "6121418" => array ( "Area" => "Mashonaland", "City" => "Makuti"),
    "6121417" => array ( "Area" => "Mashonaland", "City" => "Makuti"),
    "6121416" => array ( "Area" => "Mashonaland", "City" => "Makuti"),
    "6121415" => array ( "Area" => "Mashonaland", "City" => "Makuti"),
    "6121414" => array ( "Area" => "Mashonaland", "City" => "Makuti"),
    "6121413" => array ( "Area" => "Mashonaland", "City" => "Makuti"),
    "6121412" => array ( "Area" => "Mashonaland", "City" => "Makuti"),
    "6121408" => array ( "Area" => "Mashonaland", "City" => "Chirundu"),
    "6121407" => array ( "Area" => "Mashonaland", "City" => "Chirundu"),
    "6121406" => array ( "Area" => "Mashonaland", "City" => "Chirundu"),
    "6121405" => array ( "Area" => "Mashonaland", "City" => "Chirundu"),
    "6121404" => array ( "Area" => "Mashonaland", "City" => "Chirundu"),
    "6121403" => array ( "Area" => "Mashonaland", "City" => "Chirundu"),
    "6121402" => array ( "Area" => "Mashonaland", "City" => "Chirundu"),
    "5525588" => array ( "Area" => "Midlands", "City" => "Nkayi"),
    "5525587" => array ( "Area" => "Midlands", "City" => "Nkayi"),
    "5525586" => array ( "Area" => "Midlands", "City" => "Nkayi"),
    "5525585" => array ( "Area" => "Midlands", "City" => "Nkayi"),
    "5525584" => array ( "Area" => "Midlands", "City" => "Nkayi"),
    "5525583" => array ( "Area" => "Midlands", "City" => "Nkayi"),
    "5525582" => array ( "Area" => "Midlands", "City" => "Nkayi"),
    "5525578" => array ( "Area" => "Midlands", "City" => "Munyati"),
    "5525577" => array ( "Area" => "Midlands", "City" => "Munyati"),
    "5525576" => array ( "Area" => "Midlands", "City" => "Munyati"),
    "5525575" => array ( "Area" => "Midlands", "City" => "Munyati"),
    "5525574" => array ( "Area" => "Midlands", "City" => "Munyati"),
    "5525573" => array ( "Area" => "Midlands", "City" => "Munyati"),
    "5525572" => array ( "Area" => "Midlands", "City" => "Munyati"),
    "5425488" => array ( "Area" => "Midlands", "City" => "Lalapanzi"),
    "5425487" => array ( "Area" => "Midlands", "City" => "Lalapanzi"),
    "5425486" => array ( "Area" => "Midlands", "City" => "Lalapanzi"),
    "5425485" => array ( "Area" => "Midlands", "City" => "Lalapanzi"),
    "5425484" => array ( "Area" => "Midlands", "City" => "Lalapanzi"),
    "5425483" => array ( "Area" => "Midlands", "City" => "Lalapanzi"),
    "5425482" => array ( "Area" => "Midlands", "City" => "Lalapanzi"),
    "5425328" => array ( "Area" => "Midlands", "City" => "Mvuma"),
    "5425327" => array ( "Area" => "Midlands", "City" => "Mvuma"),
    "5425326" => array ( "Area" => "Midlands", "City" => "Mvuma"),
    "5425325" => array ( "Area" => "Midlands", "City" => "Mvuma"),
    "5425324" => array ( "Area" => "Midlands", "City" => "Mvuma"),
    "5425323" => array ( "Area" => "Midlands", "City" => "Mvuma"),
    "5425322" => array ( "Area" => "Midlands", "City" => "Mvuma"),
    "3923809" => array ( "Area" => "Masvingo", "City" => "Nyaningwe"),
    "3923808" => array ( "Area" => "Masvingo", "City" => "Nyaningwe"),
    "3923807" => array ( "Area" => "Masvingo", "City" => "Nyaningwe"),
    "3923806" => array ( "Area" => "Masvingo", "City" => "Nyaningwe"),
    "3923805" => array ( "Area" => "Masvingo", "City" => "Nyaningwe"),
    "3923804" => array ( "Area" => "Masvingo", "City" => "Nyaningwe"),
    "3923803" => array ( "Area" => "Masvingo", "City" => "Nyaningwe"),
    "3923802" => array ( "Area" => "Masvingo", "City" => "Nyaningwe"),
    "3923668" => array ( "Area" => "Masvingo", "City" => "Mataga"),
    "3923667" => array ( "Area" => "Masvingo", "City" => "Mataga"),
    "3923666" => array ( "Area" => "Masvingo", "City" => "Mataga"),
    "3923665" => array ( "Area" => "Masvingo", "City" => "Mataga"),
    "3923664" => array ( "Area" => "Masvingo", "City" => "Mataga"),
    "3923663" => array ( "Area" => "Masvingo", "City" => "Mataga"),
    "3923662" => array ( "Area" => "Masvingo", "City" => "Mataga"),
    "3923608" => array ( "Area" => "Masvingo", "City" => "Mberengwa"),
    "3923607" => array ( "Area" => "Masvingo", "City" => "Mberengwa"),
    "3923606" => array ( "Area" => "Masvingo", "City" => "Mberengwa"),
    "3923605" => array ( "Area" => "Masvingo", "City" => "Mberengwa"),
    "3923604" => array ( "Area" => "Masvingo", "City" => "Mberengwa"),
    "3923603" => array ( "Area" => "Masvingo", "City" => "Mberengwa"),
    "3923602" => array ( "Area" => "Masvingo", "City" => "Mberengwa"),
    "3923559" => array ( "Area" => "Masvingo", "City" => "Zvishavane"),
    "3923558" => array ( "Area" => "Masvingo", "City" => "Zvishavane"),
    "3923557" => array ( "Area" => "Masvingo", "City" => "Zvishavane"),
    "3923556" => array ( "Area" => "Masvingo", "City" => "Zvishavane"),
    "3923555" => array ( "Area" => "Masvingo", "City" => "Zvishavane"),
    "3923238" => array ( "Area" => "Masvingo", "City" => "Nyika"),
    "3923237" => array ( "Area" => "Masvingo", "City" => "Nyika"),
    "3923236" => array ( "Area" => "Masvingo", "City" => "Nyika"),
    "3923235" => array ( "Area" => "Masvingo", "City" => "Nyika"),
    "3923234" => array ( "Area" => "Masvingo", "City" => "Nyika"),
    "3923233" => array ( "Area" => "Masvingo", "City" => "Nyika"),
    "3923232" => array ( "Area" => "Masvingo", "City" => "Nyika"),
    "3923088" => array ( "Area" => "Masvingo", "City" => "Chatsworth"),
    "3923087" => array ( "Area" => "Masvingo", "City" => "Chatsworth"),
    "3923086" => array ( "Area" => "Masvingo", "City" => "Chatsworth"),
    "3923085" => array ( "Area" => "Masvingo", "City" => "Chatsworth"),
    "3923084" => array ( "Area" => "Masvingo", "City" => "Chatsworth"),
    "3923083" => array ( "Area" => "Masvingo", "City" => "Chatsworth"),
    "3923082" => array ( "Area" => "Masvingo", "City" => "Chatsworth"),
    "3922696" => array ( "Area" => "Masvingo", "City" => "Masvingo"),
    "3922695" => array ( "Area" => "Masvingo", "City" => "Masvingo"),
    "3922694" => array ( "Area" => "Masvingo", "City" => "Masvingo"),
    "3922693" => array ( "Area" => "Masvingo", "City" => "Masvingo"),
    "3922692" => array ( "Area" => "Masvingo", "City" => "Masvingo"),
    "3922691" => array ( "Area" => "Masvingo", "City" => "Masvingo"),
    "3922690" => array ( "Area" => "Masvingo", "City" => "Masvingo"),
    "3922609" => array ( "Area" => "Masvingo", "City" => "Masvingo"),
    "3922608" => array ( "Area" => "Masvingo", "City" => "Masvingo"),
    "3922607" => array ( "Area" => "Masvingo", "City" => "Masvingo"),
    "3123708" => array ( "Area" => "Masvingo", "City" => "Ngundu"),
    "3123707" => array ( "Area" => "Masvingo", "City" => "Ngundu"),
    "3123706" => array ( "Area" => "Masvingo", "City" => "Ngundu"),
    "3123705" => array ( "Area" => "Masvingo", "City" => "Ngundu"),
    "3123704" => array ( "Area" => "Masvingo", "City" => "Ngundu"),
    "3123703" => array ( "Area" => "Masvingo", "City" => "Ngundu"),
    "3123702" => array ( "Area" => "Masvingo", "City" => "Ngundu"),
    "3123378" => array ( "Area" => "Masvingo", "City" => "Rutenga"),
    "3123377" => array ( "Area" => "Masvingo", "City" => "Rutenga"),
    "3123376" => array ( "Area" => "Masvingo", "City" => "Rutenga"),
    "3123375" => array ( "Area" => "Masvingo", "City" => "Rutenga"),
    "3123374" => array ( "Area" => "Masvingo", "City" => "Rutenga"),
    "3123373" => array ( "Area" => "Masvingo", "City" => "Rutenga"),
    "3123372" => array ( "Area" => "Masvingo", "City" => "Rutenga"),
    "3123174" => array ( "Area" => "Masvingo", "City" => "Chiredzi"),
    "3123173" => array ( "Area" => "Masvingo", "City" => "Chiredzi"),
    "3123172" => array ( "Area" => "Masvingo", "City" => "Chiredzi"),
    "3123171" => array ( "Area" => "Masvingo", "City" => "Chiredzi"),
    "3123170" => array ( "Area" => "Masvingo", "City" => "Chiredzi"),
    "3123141" => array ( "Area" => "Masvingo", "City" => "Chiredzi"),
    "3123140" => array ( "Area" => "Masvingo", "City" => "Chiredzi"),
    "2928618" => array ( "Area" => "Bulawayo", "City" => "Tsholotsho"),
    "2928617" => array ( "Area" => "Bulawayo", "City" => "Tsholotsho"),
    "2928616" => array ( "Area" => "Bulawayo", "City" => "Tsholotsho"),
    "2928615" => array ( "Area" => "Bulawayo", "City" => "Tsholotsho"),
    "2928614" => array ( "Area" => "Bulawayo", "City" => "Tsholotsho"),
    "2928613" => array ( "Area" => "Bulawayo", "City" => "Tsholotsho"),
    "2928612" => array ( "Area" => "Bulawayo", "City" => "Tsholotsho"),
    "2928218" => array ( "Area" => "Bulawayo", "City" => "Nyamandlovu"),
    "2928217" => array ( "Area" => "Bulawayo", "City" => "Nyamandlovu"),
    "2928216" => array ( "Area" => "Bulawayo", "City" => "Nyamandlovu"),
    "2928215" => array ( "Area" => "Bulawayo", "City" => "Nyamandlovu"),
    "2928214" => array ( "Area" => "Bulawayo", "City" => "Nyamandlovu"),
    "2928213" => array ( "Area" => "Bulawayo", "City" => "Nyamandlovu"),
    "2928212" => array ( "Area" => "Bulawayo", "City" => "Nyamandlovu"),
    "2928098" => array ( "Area" => "Bulawayo", "City" => "Matopos"),
    "2928097" => array ( "Area" => "Bulawayo", "City" => "Matopos"),
    "2928096" => array ( "Area" => "Bulawayo", "City" => "Matopos"),
    "2928095" => array ( "Area" => "Bulawayo", "City" => "Matopos"),
    "2928094" => array ( "Area" => "Bulawayo", "City" => "Matopos"),
    "2928093" => array ( "Area" => "Bulawayo", "City" => "Matopos"),
    "2928092" => array ( "Area" => "Bulawayo", "City" => "Matopos"),
    "2928078" => array ( "Area" => "Bulawayo", "City" => "Kezi"),
    "2928077" => array ( "Area" => "Bulawayo", "City" => "Kezi"),
    "2928076" => array ( "Area" => "Bulawayo", "City" => "Kezi"),
    "2928075" => array ( "Area" => "Bulawayo", "City" => "Kezi"),
    "2928074" => array ( "Area" => "Bulawayo", "City" => "Kezi"),
    "2928073" => array ( "Area" => "Bulawayo", "City" => "Kezi"),
    "2928072" => array ( "Area" => "Bulawayo", "City" => "Kezi"),
    "2928048" => array ( "Area" => "Bulawayo", "City" => "Figtree"),
    "2928047" => array ( "Area" => "Bulawayo", "City" => "Figtree"),
    "2928046" => array ( "Area" => "Bulawayo", "City" => "Figtree"),
    "2928045" => array ( "Area" => "Bulawayo", "City" => "Figtree"),
    "2928044" => array ( "Area" => "Bulawayo", "City" => "Figtree"),
    "2928043" => array ( "Area" => "Bulawayo", "City" => "Figtree"),
    "2928042" => array ( "Area" => "Bulawayo", "City" => "Figtree"),
    "2928041" => array ( "Area" => "Bulawayo", "City" => "Figtree"),
    "2928040" => array ( "Area" => "Bulawayo", "City" => "Figtree"),
    "2928038" => array ( "Area" => "Bulawayo", "City" => "Turkmine"),
    "2928037" => array ( "Area" => "Bulawayo", "City" => "Turkmine"),
    "2928036" => array ( "Area" => "Bulawayo", "City" => "Turkmine"),
    "2928035" => array ( "Area" => "Bulawayo", "City" => "Turkmine"),
    "2928034" => array ( "Area" => "Bulawayo", "City" => "Turkmine"),
    "2928033" => array ( "Area" => "Bulawayo", "City" => "Turkmine"),
    "2928032" => array ( "Area" => "Bulawayo", "City" => "Turkmine"),
    "2928028" => array ( "Area" => "Bulawayo", "City" => "Shangani"),
    "2928027" => array ( "Area" => "Bulawayo", "City" => "Shangani"),
    "2928026" => array ( "Area" => "Bulawayo", "City" => "Shangani"),
    "2928025" => array ( "Area" => "Bulawayo", "City" => "Shangani"),
    "2928024" => array ( "Area" => "Bulawayo", "City" => "Shangani"),
    "2928023" => array ( "Area" => "Bulawayo", "City" => "Shangani"),
    "2928022" => array ( "Area" => "Bulawayo", "City" => "Shangani"),
    "2928008" => array ( "Area" => "Bulawayo", "City" => "Esigodini"),
    "2928007" => array ( "Area" => "Bulawayo", "City" => "Esigodini"),
    "2928006" => array ( "Area" => "Bulawayo", "City" => "Esigodini"),
    "2928005" => array ( "Area" => "Bulawayo", "City" => "Esigodini"),
    "2928004" => array ( "Area" => "Bulawayo", "City" => "Esigodini"),
    "2928003" => array ( "Area" => "Bulawayo", "City" => "Esigodini"),
    "2928002" => array ( "Area" => "Bulawayo", "City" => "Esigodini"),
    "2928001" => array ( "Area" => "Bulawayo", "City" => "Esigodini"),
    "2928000" => array ( "Area" => "Bulawayo", "City" => "Esigodini"),
    "2723178" => array ( "Area" => "Manicaland", "City" => "Checheche"),
    "2723177" => array ( "Area" => "Manicaland", "City" => "Checheche"),
    "2723176" => array ( "Area" => "Manicaland", "City" => "Checheche"),
    "2723175" => array ( "Area" => "Manicaland", "City" => "Checheche"),
    "2723174" => array ( "Area" => "Manicaland", "City" => "Checheche"),
    "2723173" => array ( "Area" => "Manicaland", "City" => "Checheche"),
    "2723172" => array ( "Area" => "Manicaland", "City" => "Checheche"),
    "2720468" => array ( "Area" => "Manicaland", "City" => "Chipangayi"),
    "2720467" => array ( "Area" => "Manicaland", "City" => "Chipangayi"),
    "2720466" => array ( "Area" => "Manicaland", "City" => "Chipangayi"),
    "2720465" => array ( "Area" => "Manicaland", "City" => "Chipangayi"),
    "2720464" => array ( "Area" => "Manicaland", "City" => "Chipangayi"),
    "2720463" => array ( "Area" => "Manicaland", "City" => "Chipangayi"),
    "2720462" => array ( "Area" => "Manicaland", "City" => "Chipangayi"),
    "2720457" => array ( "Area" => "Manicaland", "City" => "Chipinge"),
    "2720456" => array ( "Area" => "Manicaland", "City" => "Chipinge"),
    "2720445" => array ( "Area" => "Manicaland", "City" => "Chipinge"),
    "2720444" => array ( "Area" => "Manicaland", "City" => "Chipinge"),
    "2720434" => array ( "Area" => "Manicaland", "City" => "Chipinge"),
    "2720433" => array ( "Area" => "Manicaland", "City" => "Chipinge"),
    "2720432" => array ( "Area" => "Manicaland", "City" => "Chipinge"),
    "2720431" => array ( "Area" => "Manicaland", "City" => "Chipinge"),
    "2720430" => array ( "Area" => "Manicaland", "City" => "Chipinge"),
    "2620987" => array ( "Area" => "Manicaland", "City" => "Nyanga"),
    "2620986" => array ( "Area" => "Manicaland", "City" => "Nyanga"),
    "2620985" => array ( "Area" => "Manicaland", "City" => "Nyanga"),
    "2620984" => array ( "Area" => "Manicaland", "City" => "Nyanga"),
    "2620983" => array ( "Area" => "Manicaland", "City" => "Nyanga"),
    "2620982" => array ( "Area" => "Manicaland", "City" => "Nyanga"),
    "2620981" => array ( "Area" => "Manicaland", "City" => "Nyanga"),
    "2620980" => array ( "Area" => "Manicaland", "City" => "Nyanga"),
    "2620841" => array ( "Area" => "Manicaland", "City" => "Juliasdale"),
    "2620840" => array ( "Area" => "Manicaland", "City" => "Juliasdale"),
    "2620829" => array ( "Area" => "Manicaland", "City" => "Juliasdale"),
    "2620828" => array ( "Area" => "Manicaland", "City" => "Juliasdale"),
    "2620827" => array ( "Area" => "Manicaland", "City" => "Juliasdale"),
    "2620826" => array ( "Area" => "Manicaland", "City" => "Juliasdale"),
    "2620825" => array ( "Area" => "Manicaland", "City" => "Juliasdale"),
    "2620824" => array ( "Area" => "Manicaland", "City" => "Juliasdale"),
    "2620823" => array ( "Area" => "Manicaland", "City" => "Juliasdale"),
    "2620822" => array ( "Area" => "Manicaland", "City" => "Juliasdale"),
    "2520584" => array ( "Area" => "Manicaland", "City" => "Murambinda"),
    "2520583" => array ( "Area" => "Manicaland", "City" => "Murambinda"),
    "2520582" => array ( "Area" => "Manicaland", "City" => "Murambinda"),
    "2520581" => array ( "Area" => "Manicaland", "City" => "Murambinda"),
    "2520580" => array ( "Area" => "Manicaland", "City" => "Murambinda"),
    "2520558" => array ( "Area" => "Manicaland", "City" => "Nyazura"),
    "2520557" => array ( "Area" => "Manicaland", "City" => "Nyazura"),
    "2520556" => array ( "Area" => "Manicaland", "City" => "Nyazura"),
    "2520555" => array ( "Area" => "Manicaland", "City" => "Nyazura"),
    "2520554" => array ( "Area" => "Manicaland", "City" => "Nyazura"),
    "2520553" => array ( "Area" => "Manicaland", "City" => "Nyazura"),
    "2520552" => array ( "Area" => "Manicaland", "City" => "Nyazura"),
    "2520544" => array ( "Area" => "Manicaland", "City" => "Rusape MSAN"),
    "2520543" => array ( "Area" => "Manicaland", "City" => "Rusape MSAN"),
    "2520542" => array ( "Area" => "Manicaland", "City" => "Rusape MSAN"),
    "2520541" => array ( "Area" => "Manicaland", "City" => "Rusape MSAN"),
    "2520540" => array ( "Area" => "Manicaland", "City" => "Rusape MSAN"),
    "2426184" => array ( "Area" => "Harare", "City" => "Waterfalls"),
    "2426183" => array ( "Area" => "Harare", "City" => "Waterfalls"),
    "2426182" => array ( "Area" => "Harare", "City" => "Waterfalls"),
    "2426181" => array ( "Area" => "Harare", "City" => "Waterfalls"),
    "2426180" => array ( "Area" => "Harare", "City" => "Waterfalls"),
    "2425274" => array ( "Area" => "Harare", "City" => "Hillside"),
    "2425273" => array ( "Area" => "Harare", "City" => "Hillside"),
    "2425272" => array ( "Area" => "Harare", "City" => "Hillside"),
    "2425271" => array ( "Area" => "Harare", "City" => "Hillside"),
    "2425270" => array ( "Area" => "Harare", "City" => "Hillside"),
    "2424949" => array ( "Area" => "Harare", "City" => "Kambanje"),
    "2424948" => array ( "Area" => "Harare", "City" => "Kambanje"),
    "2424947" => array ( "Area" => "Harare", "City" => "Kambanje"),
    "2424946" => array ( "Area" => "Harare", "City" => "Kambanje"),
    "2424945" => array ( "Area" => "Harare", "City" => "Kambanje"),
    "2424944" => array ( "Area" => "Harare", "City" => "Highlands Host"),
    "2424943" => array ( "Area" => "Harare", "City" => "Highlands Host"),
    "2424942" => array ( "Area" => "Harare", "City" => "Highlands Host"),
    "2424941" => array ( "Area" => "Harare", "City" => "Highlands Host"),
    "2424940" => array ( "Area" => "Harare", "City" => "Highlands Host"),
    "2424624" => array ( "Area" => "Harare", "City" => "Mabvuku"),
    "2424623" => array ( "Area" => "Harare", "City" => "Mabvuku"),
    "2424622" => array ( "Area" => "Harare", "City" => "Mabvuku"),
    "2424621" => array ( "Area" => "Harare", "City" => "Mabvuku"),
    "2424620" => array ( "Area" => "Harare", "City" => "Mabvuku"),
    "2423124" => array ( "Area" => "Harare", "City" => "Meyrick Park"),
    "2423123" => array ( "Area" => "Harare", "City" => "Meyrick Park"),
    "2423122" => array ( "Area" => "Harare", "City" => "Meyrick Park"),
    "2423121" => array ( "Area" => "Harare", "City" => "Meyrick Park"),
    "2423120" => array ( "Area" => "Harare", "City" => "Meyrick Park"),
    "2423109" => array ( "Area" => "Harare", "City" => "Meyrick Park"),
    "2423108" => array ( "Area" => "Harare", "City" => "Meyrick Park"),
    "2423107" => array ( "Area" => "Harare", "City" => "Meyrick Park"),
    "2423106" => array ( "Area" => "Harare", "City" => "Meyrick Park"),
    "2423105" => array ( "Area" => "Harare", "City" => "Meyrick Park"),
    "2421554" => array ( "Area" => "Harare", "City" => "Norton, Knowe"),
    "2421553" => array ( "Area" => "Harare", "City" => "Norton, Knowe"),
    "2421552" => array ( "Area" => "Harare", "City" => "Norton, Knowe"),
    "2421551" => array ( "Area" => "Harare", "City" => "Norton, Knowe"),
    "2421550" => array ( "Area" => "Harare", "City" => "Norton, Knowe"),
    "2421508" => array ( "Area" => "Harare", "City" => "Beatrice"),
    "2421507" => array ( "Area" => "Harare", "City" => "Beatrice"),
    "2421506" => array ( "Area" => "Harare", "City" => "Beatrice"),
    "2421505" => array ( "Area" => "Harare", "City" => "Beatrice"),
    "2421504" => array ( "Area" => "Harare", "City" => "Beatrice"),
    "2421503" => array ( "Area" => "Harare", "City" => "Beatrice"),
    "2421502" => array ( "Area" => "Harare", "City" => "Beatrice"),
    "2421364" => array ( "Area" => "Harare", "City" => "Ruwa"),
    "2421363" => array ( "Area" => "Harare", "City" => "Ruwa"),
    "2421362" => array ( "Area" => "Harare", "City" => "Ruwa"),
    "2421361" => array ( "Area" => "Harare", "City" => "Ruwa"),
    "2421360" => array ( "Area" => "Harare", "City" => "Ruwa"),
    "2421336" => array ( "Area" => "Harare", "City" => "Ruwa"),
    "2421335" => array ( "Area" => "Harare", "City" => "Ruwa"),
    "2421334" => array ( "Area" => "Harare", "City" => "Ruwa"),
    "2421333" => array ( "Area" => "Harare", "City" => "Ruwa"),
    "2421332" => array ( "Area" => "Harare", "City" => "Ruwa"),
    "2421331" => array ( "Area" => "Harare", "City" => "Ruwa"),
    "2421330" => array ( "Area" => "Harare", "City" => "Ruwa"),
    "2420111" => array ( "Area" => "Harare", "City" => "Harare Soft Client"),
    "2420110" => array ( "Area" => "Harare", "City" => "Norton"),
    "2420110" => array ( "Area" => "Harare", "City" => "Harare Soft Client"),
    "2420109" => array ( "Area" => "Harare", "City" => "Norton"),
    "2420108" => array ( "Area" => "Harare", "City" => "Norton"),
    "2420107" => array ( "Area" => "Harare", "City" => "Norton"),
    "2420106" => array ( "Area" => "Harare", "City" => "Norton"),
    "2024229" => array ( "Area" => "Manicaland", "City" => "Penhalonga"),
    "2024228" => array ( "Area" => "Manicaland", "City" => "Penhalonga"),
    "2024227" => array ( "Area" => "Manicaland", "City" => "Penhalonga"),
    "2024226" => array ( "Area" => "Manicaland", "City" => "Penhalonga"),
    "2024225" => array ( "Area" => "Manicaland", "City" => "Penhalonga"),
    "2024224" => array ( "Area" => "Manicaland", "City" => "Penhalonga"),
    "2024223" => array ( "Area" => "Manicaland", "City" => "Penhalonga"),
    "2024222" => array ( "Area" => "Manicaland", "City" => "Penhalonga"),
    "2020320" => array ( "Area" => "Manicaland", "City" => "Dangamvura MSAN"),
    "2020115" => array ( "Area" => "Manicaland", "City" => "Chikanga MSAN"),
    "2020114" => array ( "Area" => "Manicaland", "City" => "Chikanga MSAN"),
    "2020113" => array ( "Area" => "Manicaland", "City" => "Chikanga MSAN"),
    "2020112" => array ( "Area" => "Manicaland", "City" => "Chikanga MSAN"),
    "2020111" => array ( "Area" => "Manicaland", "City" => "Chikanga MSAN"),
    "2020110" => array ( "Area" => "Manicaland", "City" => "Chikanga MSAN"),
    "892807" => array ( "Area" => "Matabeleland", "City" => "Plumtree"),
    "892806" => array ( "Area" => "Matabeleland", "City" => "Plumtree"),
    "892805" => array ( "Area" => "Matabeleland", "City" => "Plumtree"),
    "852323" => array ( "Area" => "Matabeleland", "City" => "BeitBridge"),
    "852322" => array ( "Area" => "Matabeleland", "City" => "BeitBridge"),
    "842829" => array ( "Area" => "Matabeleland", "City" => "Gwanda"),
    "842825" => array ( "Area" => "Matabeleland", "City" => "Gwanda"),
    "842824" => array ( "Area" => "Matabeleland", "City" => "Gwanda"),
    "842823" => array ( "Area" => "Matabeleland", "City" => "Gwanda"),
    "842822" => array ( "Area" => "Matabeleland", "City" => "Gwanda"),
    "842821" => array ( "Area" => "Matabeleland", "City" => "Gwanda"),
    "842820" => array ( "Area" => "Matabeleland", "City" => "Gwanda"),
    "842801" => array ( "Area" => "Matabeleland", "City" => "Filabusi"),
    "812875" => array ( "Area" => "Matabeleland", "City" => "Jotsholo"),
    "812857" => array ( "Area" => "Matabeleland", "City" => "Lupane"),
    "812856" => array ( "Area" => "Matabeleland", "City" => "Lupane"),
    "812834" => array ( "Area" => "Matabeleland", "City" => "Baobab"),
    "812833" => array ( "Area" => "Matabeleland", "City" => "Baobab"),
    "812832" => array ( "Area" => "Matabeleland", "City" => "Baobab"),
    "812831" => array ( "Area" => "Matabeleland", "City" => "Baobab"),
    "812830" => array ( "Area" => "Matabeleland", "City" => "Baobab"),
    "812824" => array ( "Area" => "Matabeleland", "City" => "Hwange"),
    "812823" => array ( "Area" => "Matabeleland", "City" => "Hwange"),
    "812822" => array ( "Area" => "Matabeleland", "City" => "Hwange"),
    "812821" => array ( "Area" => "Matabeleland", "City" => "Hwange"),
    "812820" => array ( "Area" => "Matabeleland", "City" => "Hwange"),
    "682162" => array ( "Area" => "Mashonaland", "City" => "Sanyati"),
    "682154" => array ( "Area" => "Mashonaland", "City" => "Chegutu"),
    "682153" => array ( "Area" => "Mashonaland", "City" => "Chegutu"),
    "682144" => array ( "Area" => "Mashonaland", "City" => "Selous"),
    "682134" => array ( "Area" => "Mashonaland", "City" => "Kadoma Ngezi"),
    "682132" => array ( "Area" => "Mashonaland", "City" => "Kadoma"),
    "682131" => array ( "Area" => "Mashonaland", "City" => "Kadoma"),
    "682127" => array ( "Area" => "Mashonaland", "City" => "Kadoma Rimuka"),
    "682126" => array ( "Area" => "Mashonaland", "City" => "Kadoma Rimuka"),
    "682125" => array ( "Area" => "Mashonaland", "City" => "Kadoma Rimuka"),
    "682124" => array ( "Area" => "Mashonaland", "City" => "Kadoma Rimuka"),
    "682123" => array ( "Area" => "Mashonaland", "City" => "Kadoma Rimuka"),
    "682122" => array ( "Area" => "Mashonaland", "City" => "Kadoma Rimuka"),
    "682009" => array ( "Area" => "Mashonaland", "City" => "Selous"),
    "672152" => array ( "Area" => "Mashonaland", "City" => "Murombedzi"),
    "672145" => array ( "Area" => "Mashonaland", "City" => "Mhangura"),
    "672143" => array ( "Area" => "Mashonaland", "City" => "Banket"),
    "672142" => array ( "Area" => "Mashonaland", "City" => "Banket"),
    "672129" => array ( "Area" => "Mashonaland", "City" => "Chinhoyi"),
    "672128" => array ( "Area" => "Mashonaland", "City" => "Chinhoyi"),
    "672127" => array ( "Area" => "Mashonaland", "City" => "Chinhoyi"),
    "672126" => array ( "Area" => "Mashonaland", "City" => "Chinhoyi"),
    "672125" => array ( "Area" => "Mashonaland", "City" => "Chinhoyi"),
    "672124" => array ( "Area" => "Mashonaland", "City" => "Chinhoyi"),
    "672123" => array ( "Area" => "Mashonaland", "City" => "Chinhoyi"),
    "672122" => array ( "Area" => "Mashonaland", "City" => "Chinhoyi"),
    "672121" => array ( "Area" => "Mashonaland", "City" => "Chinhoyi"),
    "662196" => array ( "Area" => "Mashonaland", "City" => "Christon Bank"),
    "662172" => array ( "Area" => "Mashonaland", "City" => "Guruve"),
    "662162" => array ( "Area" => "Mashonaland", "City" => "Mvurwi"),
    "662123" => array ( "Area" => "Mashonaland", "City" => "Mount Darwin"),
    "662107" => array ( "Area" => "Mashonaland", "City" => "Bindura"),
    "662106" => array ( "Area" => "Mashonaland", "City" => "Bindura"),
    "662102" => array ( "Area" => "Mashonaland", "City" => "Centenary"),
    "652729" => array ( "Area" => "Mashonaland", "City" => "Marondera"),
    "652728" => array ( "Area" => "Mashonaland", "City" => "Marondera"),
    "652328" => array ( "Area" => "Mashonaland", "City" => "Marondera"),
    "652327" => array ( "Area" => "Mashonaland", "City" => "Marondera"),
    "652326" => array ( "Area" => "Mashonaland", "City" => "Marondera"),
    "652325" => array ( "Area" => "Mashonaland", "City" => "Marondera"),
    "652324" => array ( "Area" => "Mashonaland", "City" => "Marondera"),
    "652323" => array ( "Area" => "Mashonaland", "City" => "Marondera"),
    "652322" => array ( "Area" => "Mashonaland", "City" => "Marondera"),
    "652321" => array ( "Area" => "Mashonaland", "City" => "Marondera"),
    "652320" => array ( "Area" => "Mashonaland", "City" => "Marondera"),
    "652132" => array ( "Area" => "Mashonaland", "City" => "Mutoko"),
    "652124" => array ( "Area" => "Mashonaland", "City" => "Murewa"),
    "652123" => array ( "Area" => "Mashonaland", "City" => "Murewa"),
    "652122" => array ( "Area" => "Mashonaland", "City" => "Murewa"),
    "652082" => array ( "Area" => "Mashonaland", "City" => "Wedza"),
    "612145" => array ( "Area" => "Mashonaland", "City" => "Kariba"),
    "612142" => array ( "Area" => "Mashonaland", "City" => "Karoi"),
    "552593" => array ( "Area" => "Midlands", "City" => "Gokwe"),
    "552592" => array ( "Area" => "Midlands", "City" => "Gokwe"),
    "552570" => array ( "Area" => "Midlands", "City" => "Battle Fields"),
    "552569" => array ( "Area" => "Midlands", "City" => "Redcliff"),
    "552568" => array ( "Area" => "Midlands", "City" => "Redcliff"),
    "552563" => array ( "Area" => "Midlands", "City" => "Redcliff"),
    "552562" => array ( "Area" => "Midlands", "City" => "Redcliff"),
    "552547" => array ( "Area" => "Midlands", "City" => "Mbizo 1 & 2"),
    "552546" => array ( "Area" => "Midlands", "City" => "Mbizo 1 & 2"),
    "552545" => array ( "Area" => "Midlands", "City" => "Mbizo 1 & 2"),
    "552544" => array ( "Area" => "Midlands", "City" => "Mbizo 1 & 2"),
    "552543" => array ( "Area" => "Midlands", "City" => "Mbizo 1 & 2"),
    "552542" => array ( "Area" => "Midlands", "City" => "Mbizo 1 & 2"),
    "552541" => array ( "Area" => "Midlands", "City" => "Mbizo 1 & 2"),
    "552540" => array ( "Area" => "Midlands", "City" => "Mbizo 1 & 2"),
    "552526" => array ( "Area" => "Midlands", "City" => "Kwekwe Main"),
    "552525" => array ( "Area" => "Midlands", "City" => "Kwekwe Main"),
    "552524" => array ( "Area" => "Midlands", "City" => "Kwekwe Main"),
    "552523" => array ( "Area" => "Midlands", "City" => "Kwekwe Main"),
    "552522" => array ( "Area" => "Midlands", "City" => "Kwekwe Main"),
    "552521" => array ( "Area" => "Midlands", "City" => "Kwekwe Main"),
    "552520" => array ( "Area" => "Midlands", "City" => "Kwekwe Main"),
    "542528" => array ( "Area" => "Midlands", "City" => "Shurugwi"),
    "542527" => array ( "Area" => "Midlands", "City" => "Shurugwi"),
    "542526" => array ( "Area" => "Midlands", "City" => "Shurugwi"),
    "542262" => array ( "Area" => "Midlands", "City" => "Senga"),
    "542261" => array ( "Area" => "Midlands", "City" => "Senga"),
    "542260" => array ( "Area" => "Midlands", "City" => "Senga"),
    "542258" => array ( "Area" => "Midlands", "City" => "Mkoba 2"),
    "542257" => array ( "Area" => "Midlands", "City" => "Mkoba 2"),
    "542256" => array ( "Area" => "Midlands", "City" => "Mkoba 2"),
    "542255" => array ( "Area" => "Midlands", "City" => "Mkoba 2"),
    "542253" => array ( "Area" => "Midlands", "City" => "Mkoba 1"),
    "542252" => array ( "Area" => "Midlands", "City" => "Mkoba 1"),
    "542251" => array ( "Area" => "Midlands", "City" => "Mkoba 1"),
    "542250" => array ( "Area" => "Midlands", "City" => "Mkoba 1"),
    "542233" => array ( "Area" => "Midlands", "City" => "Gweru Host"),
    "542232" => array ( "Area" => "Midlands", "City" => "Gweru Host"),
    "542231" => array ( "Area" => "Midlands", "City" => "Gweru Host"),
    "542230" => array ( "Area" => "Midlands", "City" => "Gweru Host"),
    "542123" => array ( "Area" => "Midlands", "City" => "Chivhu"),
    "542122" => array ( "Area" => "Midlands", "City" => "Chivhu"),
    "392452" => array ( "Area" => "Masvingo", "City" => "Mashava"),
    "392381" => array ( "Area" => "Masvingo", "City" => "Nyaningwe"),
    "392357" => array ( "Area" => "Masvingo", "City" => "Zvishavane"),
    "392356" => array ( "Area" => "Masvingo", "City" => "Zvishavane"),
    "392354" => array ( "Area" => "Masvingo", "City" => "Zvishavane"),
    "392353" => array ( "Area" => "Masvingo", "City" => "Zvishavane"),
    "392352" => array ( "Area" => "Masvingo", "City" => "Zvishavane"),
    "392342" => array ( "Area" => "Masvingo", "City" => "Jerera"),
    "392303" => array ( "Area" => "Masvingo", "City" => "Gutu"),
    "392302" => array ( "Area" => "Masvingo", "City" => "Gutu"),
    "392277" => array ( "Area" => "Masvingo", "City" => "Masvingo"),
    "392268" => array ( "Area" => "Masvingo", "City" => "Masvingo"),
    "392267" => array ( "Area" => "Masvingo", "City" => "Masvingo"),
    "392266" => array ( "Area" => "Masvingo", "City" => "Masvingo"),
    "392265" => array ( "Area" => "Masvingo", "City" => "Masvingo"),
    "392264" => array ( "Area" => "Masvingo", "City" => "Masvingo"),
    "392263" => array ( "Area" => "Masvingo", "City" => "Masvingo"),
    "392262" => array ( "Area" => "Masvingo", "City" => "Masvingo"),
    "392261" => array ( "Area" => "Masvingo", "City" => "Masvingo"),
    "392255" => array ( "Area" => "Masvingo", "City" => "Mucheke RSM"),
    "392254" => array ( "Area" => "Masvingo", "City" => "Mucheke RSM"),
    "392253" => array ( "Area" => "Masvingo", "City" => "Mucheke RSM"),
    "392252" => array ( "Area" => "Masvingo", "City" => "Mucheke RSM"),
    "312336" => array ( "Area" => "Masvingo", "City" => "Triangle"),
    "312335" => array ( "Area" => "Masvingo", "City" => "Triangle"),
    "312316" => array ( "Area" => "Masvingo", "City" => "Chiredzi"),
    "312315" => array ( "Area" => "Masvingo", "City" => "Chiredzi"),
    "312313" => array ( "Area" => "Masvingo", "City" => "Chiredzi"),
    "312312" => array ( "Area" => "Masvingo", "City" => "Chiredzi"),
    "292360" => array ( "Area" => "Bulawayo", "City" => "Bulawayo"),
    "292330" => array ( "Area" => "Bulawayo", "City" => "Bulawayo"),
    "292321" => array ( "Area" => "Bulawayo", "City" => "Bulawayo"),
    "292320" => array ( "Area" => "Bulawayo", "City" => "Bulawayo"),
    "292228" => array ( "Area" => "Bulawayo", "City" => "Queensdale"),
    "292227" => array ( "Area" => "Bulawayo", "City" => "Queensdale"),
    "292226" => array ( "Area" => "Bulawayo", "City" => "Queensdale"),
    "272053" => array ( "Area" => "Manicaland", "City" => "Chimanimani"),
    "272052" => array ( "Area" => "Manicaland", "City" => "Chimanimani"),
    "272042" => array ( "Area" => "Manicaland", "City" => "Chipinge"),
    "272032" => array ( "Area" => "Manicaland", "City" => "Birchenough Bridge"),
    "262092" => array ( "Area" => "Manicaland", "City" => "Hauna"),
    "262083" => array ( "Area" => "Manicaland", "City" => "Juliasdale"),
    "252072" => array ( "Area" => "Manicaland", "City" => "Headlands"),
    "252062" => array ( "Area" => "Manicaland", "City" => "Murambinda"),
    "252053" => array ( "Area" => "Manicaland", "City" => "Rusape MSAN"),
    "252052" => array ( "Area" => "Manicaland", "City" => "Rusape MSAN"),
    "252051" => array ( "Area" => "Manicaland", "City" => "Rusape MSAN"),
    "252050" => array ( "Area" => "Manicaland", "City" => "Rusape MSAN"),
    "242886" => array ( "Area" => "Harare", "City" => "Borrowdale Host"),
    "242885" => array ( "Area" => "Harare", "City" => "Borrowdale Host"),
    "242884" => array ( "Area" => "Harare", "City" => "Borrowdale Host"),
    "242883" => array ( "Area" => "Harare", "City" => "Borrowdale Host"),
    "242882" => array ( "Area" => "Harare", "City" => "Borrowdale Host"),
    "242881" => array ( "Area" => "Harare", "City" => "Borrowdale Host"),
    "242880" => array ( "Area" => "Harare", "City" => "Borrowdale Host"),
    "242870" => array ( "Area" => "Harare", "City" => "Borrowdale Host"),
    "242862" => array ( "Area" => "Harare", "City" => "Winchendon"),
    "242861" => array ( "Area" => "Harare", "City" => "Winchendon"),
    "242860" => array ( "Area" => "Harare", "City" => "Winchendon"),
    "242859" => array ( "Area" => "Harare", "City" => "Borrowdale Host"),
    "242858" => array ( "Area" => "Harare", "City" => "Borrowdale Host"),
    "242855" => array ( "Area" => "Harare", "City" => "Borrowdale Host"),
    "242854" => array ( "Area" => "Harare", "City" => "Borrowdale Host"),
    "242853" => array ( "Area" => "Harare", "City" => "Borrowdale Host"),
    "242852" => array ( "Area" => "Harare", "City" => "Borrowdale Host"),
    "242851" => array ( "Area" => "Harare", "City" => "Borrowdale Host"),
    "242850" => array ( "Area" => "Harare", "City" => "Borrowdale Host"),
    "242789" => array ( "Area" => "Harare", "City" => "Julius Nyerere Way Host"),
    "242788" => array ( "Area" => "Harare", "City" => "Julius Nyerere Way Host"),
    "242788" => array ( "Area" => "Harare", "City" => "Eastlea"),
    "242787" => array ( "Area" => "Harare", "City" => "Julius Nyerere Way Host"),
    "242786" => array ( "Area" => "Harare", "City" => "Julius Nyerere Way Host"),
    "242785" => array ( "Area" => "Harare", "City" => "Julius Nyerere Way Host"),
    "242783" => array ( "Area" => "Harare", "City" => "Gunhill"),
    "242782" => array ( "Area" => "Harare", "City" => "Braeside"),
    "242781" => array ( "Area" => "Harare", "City" => "Julius Nyerere Way Host"),
    "242780" => array ( "Area" => "Harare", "City" => "Julius Nyerere Way Host"),
    "242779" => array ( "Area" => "Harare", "City" => "Julius Nyerere Way Host"),
    "242778" => array ( "Area" => "Harare", "City" => "Hillside"),
    "242777" => array ( "Area" => "Harare", "City" => "Julius Nyerere Way Host"),
    "242776" => array ( "Area" => "Harare", "City" => "Eastlea"),
    "242775" => array ( "Area" => "Harare", "City" => "Julius Nyerere Way Host"),
    "242774" => array ( "Area" => "Harare", "City" => "Julius Nyerere Way Host"),
    "242773" => array ( "Area" => "Harare", "City" => "Julius Nyerere Way Host"),
    "242772" => array ( "Area" => "Harare", "City" => "Julius Nyerere Way Host"),
    "242771" => array ( "Area" => "Harare", "City" => "Julius Nyerere Way Host"),
    "242770" => array ( "Area" => "Harare", "City" => "Julius Nyerere Way Host"),
    "242749" => array ( "Area" => "Harare", "City" => "Julius Nyerere Way Host"),
    "242748" => array ( "Area" => "Harare", "City" => "Julius Nyerere Way Host"),
    "242747" => array ( "Area" => "Harare", "City" => "Hillside"),
    "242746" => array ( "Area" => "Harare", "City" => "Eastlea"),
    "242745" => array ( "Area" => "Harare", "City" => "Gunhill"),
    "242744" => array ( "Area" => "Harare", "City" => "Gunhill"),
    "242743" => array ( "Area" => "Harare", "City" => "Braeside"),
    "242742" => array ( "Area" => "Harare", "City" => "Braeside"),
    "242741" => array ( "Area" => "Harare", "City" => "Belvedere"),
    "242740" => array ( "Area" => "Harare", "City" => "Belvedere"),
    "242724" => array ( "Area" => "Harare", "City" => "Seke"),
    "242723" => array ( "Area" => "Harare", "City" => "Seke"),
    "242722" => array ( "Area" => "Harare", "City" => "Seke"),
    "242699" => array ( "Area" => "Harare", "City" => "Mufakose"),
    "242698" => array ( "Area" => "Harare", "City" => "Mufakose"),
    "242697" => array ( "Area" => "Harare", "City" => "Glen View Host"),
    "242696" => array ( "Area" => "Harare", "City" => "Glen View Host"),
    "242695" => array ( "Area" => "Harare", "City" => "Glen View Host"),
    "242694" => array ( "Area" => "Harare", "City" => "Glen View Host"),
    "242693" => array ( "Area" => "Harare", "City" => "Glen View Host"),
    "242692" => array ( "Area" => "Harare", "City" => "Glen View Host"),
    "242691" => array ( "Area" => "Harare", "City" => "Glen View Host"),
    "242690" => array ( "Area" => "Harare", "City" => "Glen View Host"),
    "242689" => array ( "Area" => "Harare", "City" => "Hatfield Host"),
    "242688" => array ( "Area" => "Harare", "City" => "Glen View Host"),
    "242687" => array ( "Area" => "Harare", "City" => "Glen View Host"),
    "242686" => array ( "Area" => "Harare", "City" => "Glen View Host"),
    "242685" => array ( "Area" => "Harare", "City" => "Glen View Host"),
    "242684" => array ( "Area" => "Harare", "City" => "Glen View Host"),
    "242683" => array ( "Area" => "Harare", "City" => "Glen View Host"),
    "242682" => array ( "Area" => "Harare", "City" => "Glen View Host"),
    "242681" => array ( "Area" => "Harare", "City" => "Mufakose"),
    "242680" => array ( "Area" => "Harare", "City" => "Glen Norah"),
    "242649" => array ( "Area" => "Harare", "City" => "Glen View Host"),
    "242648" => array ( "Area" => "Harare", "City" => "Glen View Host"),
    "242647" => array ( "Area" => "Harare", "City" => "Glen View Host"),
    "242646" => array ( "Area" => "Harare", "City" => "Glen View Host"),
    "242645" => array ( "Area" => "Harare", "City" => "Glen View Host"),
    "242621" => array ( "Area" => "Harare", "City" => "Southerton"),
    "242620" => array ( "Area" => "Harare", "City" => "Southerton"),
    "242617" => array ( "Area" => "Harare", "City" => "Waterfalls"),
    "242616" => array ( "Area" => "Harare", "City" => "Highfield"),
    "242615" => array ( "Area" => "Harare", "City" => "Waterfalls"),
    "242614" => array ( "Area" => "Harare", "City" => "Waterfalls"),
    "242613" => array ( "Area" => "Harare", "City" => "Glen Norah"),
    "242612" => array ( "Area" => "Harare", "City" => "Highfield"),
    "242611" => array ( "Area" => "Harare", "City" => "Highfield"),
    "242610" => array ( "Area" => "Harare", "City" => "Waterfalls"),
    "242589" => array ( "Area" => "Harare", "City" => "Sunningdale"),
    "242588" => array ( "Area" => "Harare", "City" => "Hatfield Host"),
    "242587" => array ( "Area" => "Harare", "City" => "Hatfield Host"),
    "242586" => array ( "Area" => "Harare", "City" => "Hatfield Host"),
    "242585" => array ( "Area" => "Harare", "City" => "Harare Airport"),
    "242584" => array ( "Area" => "Harare", "City" => "Hatfield Host"),
    "242583" => array ( "Area" => "Harare", "City" => "Hatfield Host"),
    "242582" => array ( "Area" => "Harare", "City" => "Hatfield Host"),
    "242581" => array ( "Area" => "Harare", "City" => "Hatfield Host"),
    "242580" => array ( "Area" => "Harare", "City" => "Hatfield Host"),
    "242579" => array ( "Area" => "Harare", "City" => "Hatfield Host"),
    "242578" => array ( "Area" => "Harare", "City" => "Hatfield Host"),
    "242577" => array ( "Area" => "Harare", "City" => "Epworth"),
    "242576" => array ( "Area" => "Harare", "City" => "Sunningdale"),
    "242575" => array ( "Area" => "Harare", "City" => "Harare Airport"),
    "242574" => array ( "Area" => "Harare", "City" => "Hatfield Host"),
    "242573" => array ( "Area" => "Harare", "City" => "Hatfield Host"),
    "242572" => array ( "Area" => "Harare", "City" => "Hatfield Host"),
    "242571" => array ( "Area" => "Harare", "City" => "Hatfield Host"),
    "242570" => array ( "Area" => "Harare", "City" => "Hatfield Host"),
    "242526" => array ( "Area" => "Harare", "City" => "Hillside"),
    "242499" => array ( "Area" => "Harare", "City" => "Kambanje"),
    "242498" => array ( "Area" => "Harare", "City" => "Highlands Host"),
    "242497" => array ( "Area" => "Harare", "City" => "Highlands Host"),
    "242496" => array ( "Area" => "Harare", "City" => "Highlands Host"),
    "242495" => array ( "Area" => "Harare", "City" => "Highlands Host"),
    "242493" => array ( "Area" => "Harare", "City" => "Mabvuku"),
    "242492" => array ( "Area" => "Harare", "City" => "Athlone"),
    "242491" => array ( "Area" => "Harare", "City" => "Mabvuku"),
    "242490" => array ( "Area" => "Harare", "City" => "Highlands Host"),
    "242489" => array ( "Area" => "Harare", "City" => "Mabvuku"),
    "242488" => array ( "Area" => "Harare", "City" => "Mabvuku"),
    "242487" => array ( "Area" => "Harare", "City" => "Msasa"),
    "242486" => array ( "Area" => "Harare", "City" => "Msasa"),
    "242485" => array ( "Area" => "Harare", "City" => "Msasa"),
    "242484" => array ( "Area" => "Harare", "City" => "Highlands Host"),
    "242483" => array ( "Area" => "Harare", "City" => "Highlands Host"),
    "242482" => array ( "Area" => "Harare", "City" => "Highlands Host"),
    "242481" => array ( "Area" => "Harare", "City" => "Highlands Host"),
    "242480" => array ( "Area" => "Harare", "City" => "Highlands Host"),
    "242461" => array ( "Area" => "Harare", "City" => "Mabvuku"),
    "242460" => array ( "Area" => "Harare", "City" => "Mabvuku"),
    "242459" => array ( "Area" => "Harare", "City" => "Mabvuku"),
    "242448" => array ( "Area" => "Harare", "City" => "Athlone"),
    "242447" => array ( "Area" => "Harare", "City" => "Msasa"),
    "242446" => array ( "Area" => "Harare", "City" => "Msasa"),
    "242445" => array ( "Area" => "Harare", "City" => "Highlands Host"),
    "242444" => array ( "Area" => "Harare", "City" => "Highlands Host"),
    "242443" => array ( "Area" => "Harare", "City" => "Highlands Host"),
    "242442" => array ( "Area" => "Harare", "City" => "Highlands Host"),
    "242439" => array ( "Area" => "Harare", "City" => "Highlands Host"),
    "242438" => array ( "Area" => "Harare", "City" => "Highlands Host"),
    "242437" => array ( "Area" => "Harare", "City" => "Highlands Host"),
    "242379" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242378" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242377" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242376" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242375" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242374" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242373" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242372" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242371" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242369" => array ( "Area" => "Harare", "City" => "Northwood"),
    "242339" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242338" => array ( "Area" => "Harare", "City" => "Northwood"),
    "242337" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242336" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242335" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242334" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242333" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242332" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242331" => array ( "Area" => "Harare", "City" => "Bluffhill"),
    "242329" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242328" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242327" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242326" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242316" => array ( "Area" => "Harare", "City" => "Meyrick Park"),
    "242315" => array ( "Area" => "Harare", "City" => "Meyrick Park"),
    "242313" => array ( "Area" => "Harare", "City" => "Marlborough"),
    "242311" => array ( "Area" => "Harare", "City" => "Meyrick Park"),
    "242310" => array ( "Area" => "Harare", "City" => "Bluffhill"),
    "242309" => array ( "Area" => "Harare", "City" => "Marlborough"),
    "242308" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242307" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242306" => array ( "Area" => "Harare", "City" => "Meyrick Park"),
    "242305" => array ( "Area" => "Harare", "City" => "Bluffhill"),
    "242304" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242303" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242302" => array ( "Area" => "Harare", "City" => "Avondale Host"),
    "242301" => array ( "Area" => "Harare", "City" => "Northwood"),
    "242300" => array ( "Area" => "Harare", "City" => "Marlborough"),
    "242257" => array ( "Area" => "Harare", "City" => "Unit 3"),
    "242256" => array ( "Area" => "Harare", "City" => "Unit 3"),
    "242255" => array ( "Area" => "Harare", "City" => "Unit 3"),
    "242254" => array ( "Area" => "Harare", "City" => "Unit 3"),
    "242253" => array ( "Area" => "Harare", "City" => "Unit 3"),
    "242252" => array ( "Area" => "Harare", "City" => "Unit 3"),
    "242251" => array ( "Area" => "Harare", "City" => "Unit 3"),
    "242250" => array ( "Area" => "Harare", "City" => "Unit 3"),
    "242217" => array ( "Area" => "Harare", "City" => "Dzivarasekwa"),
    "242216" => array ( "Area" => "Harare", "City" => "Dzivarasekwa"),
    "242209" => array ( "Area" => "Harare", "City" => "Kuwadzana Host"),
    "242208" => array ( "Area" => "Harare", "City" => "Kuwadzana Host"),
    "242207" => array ( "Area" => "Harare", "City" => "Kuwadzana Host"),
    "242154" => array ( "Area" => "Harare", "City" => "Norton, Knowe"),
    "242153" => array ( "Area" => "Harare", "City" => "Norton, Knowe"),
    "242152" => array ( "Area" => "Harare", "City" => "Norton, Knowe"),
    "242142" => array ( "Area" => "Harare", "City" => "Arcturus"),
    "242135" => array ( "Area" => "Harare", "City" => "Ruwa"),
    "242134" => array ( "Area" => "Harare", "City" => "Ruwa"),
    "242132" => array ( "Area" => "Harare", "City" => "Ruwa"),
    "242131" => array ( "Area" => "Harare", "City" => "Chitungwiza"),
    "242130" => array ( "Area" => "Harare", "City" => "Chitungwiza"),
    "242129" => array ( "Area" => "Harare", "City" => "Chitungwiza"),
    "242128" => array ( "Area" => "Harare", "City" => "Chitungwiza"),
    "242127" => array ( "Area" => "Harare", "City" => "Chitungwiza"),
    "242126" => array ( "Area" => "Harare", "City" => "Chitungwiza"),
    "242125" => array ( "Area" => "Harare", "City" => "Chitungwiza"),
    "242124" => array ( "Area" => "Harare", "City" => "Chitungwiza"),
    "242123" => array ( "Area" => "Harare", "City" => "Chitungwiza"),
    "242122" => array ( "Area" => "Harare", "City" => "Chitungwiza"),
    "242121" => array ( "Area" => "Harare", "City" => "Chitungwiza"),
    "242010" => array ( "Area" => "Harare", "City" => "Harare Soft Client"),
    "202131" => array ( "Area" => "Manicaland", "City" => "Dangamvura"),
    "202130" => array ( "Area" => "Manicaland", "City" => "Dangamvura"),
    "202031" => array ( "Area" => "Manicaland", "City" => "Dangamvura MSAN"),
    "202030" => array ( "Area" => "Manicaland", "City" => "Dangamvura MSAN"),
    "202025" => array ( "Area" => "Manicaland", "City" => "Mutare MSAN"),
    "202024" => array ( "Area" => "Manicaland", "City" => "Mutare MSAN"),
    "202023" => array ( "Area" => "Manicaland", "City" => "Mutare MSAN"),
    "202022" => array ( "Area" => "Manicaland", "City" => "Mutare MSAN"),
    "202021" => array ( "Area" => "Manicaland", "City" => "Mutare MSAN"),
    "202020" => array ( "Area" => "Manicaland", "City" => "Mutare MSAN"),
    "202010" => array ( "Area" => "Manicaland", "City" => "Chikanga MSAN"),
    "202002" => array ( "Area" => "Manicaland", "City" => "Odzi"),
    "83284" => array ( "Area" => "Matabeleland", "City" => "Victoria Falls (Airport)"),
    "54222" => array ( "Area" => "Midlands", "City" => "Gweru Host"),
    "29288" => array ( "Area" => "Bulawayo", "City" => "Bulawayo"),
    "29256" => array ( "Area" => "Bulawayo", "City" => "Cowdray Park"),
    "29252" => array ( "Area" => "Bulawayo", "City" => "Luveve"),
    "29249" => array ( "Area" => "Bulawayo", "City" => "Nkulumane"),
    "29248" => array ( "Area" => "Bulawayo", "City" => "Nkulumane"),
    "29247" => array ( "Area" => "Bulawayo", "City" => "Bellevue"),
    "29246" => array ( "Area" => "Bulawayo", "City" => "Bellevue"),
    "29243" => array ( "Area" => "Bulawayo", "City" => "Pumula"),
    "29242" => array ( "Area" => "Bulawayo", "City" => "Pumula"),
    "29241" => array ( "Area" => "Bulawayo", "City" => "Mabutweni"),
    "29240" => array ( "Area" => "Bulawayo", "City" => "Mabutweni"),
    "29229" => array ( "Area" => "Bulawayo", "City" => "Killarney"),
    "29228" => array ( "Area" => "Bulawayo", "City" => "Riverside"),
    "29227" => array ( "Area" => "Bulawayo", "City" => "Bulawayo"),
    "29226" => array ( "Area" => "Bulawayo", "City" => "Bulawayo"),
    "29225" => array ( "Area" => "Bulawayo", "City" => "Surburbs"),
    "29224" => array ( "Area" => "Bulawayo", "City" => "Hillside"),
    "29223" => array ( "Area" => "Bulawayo", "City" => "Surburbs"),
    "29221" => array ( "Area" => "Bulawayo", "City" => "Northend"),
    "29220" => array ( "Area" => "Bulawayo", "City" => "Northend"),
    "24293" => array ( "Area" => "Harare", "City" => "Unit 4 CDMA"),
    "24292" => array ( "Area" => "Harare", "City" => "Unit 4 CDMA"),
    "24291" => array ( "Area" => "Harare", "City" => "Unit 4 CDMA"),
    "24290" => array ( "Area" => "Harare", "City" => "Unit 4 CDMA"),
    "24279" => array ( "Area" => "Harare", "City" => "Unit 4 C&C08"),
    "24276" => array ( "Area" => "Harare", "City" => "Unit 4 C&C08"),
    "24275" => array ( "Area" => "Harare", "City" => "Julius Nyerere Way Host"),
    "24273" => array ( "Area" => "Harare", "City" => "Unit 6"),
    "24271" => array ( "Area" => "Harare", "City" => "Julius Nyerere Way Host"),
    "24270" => array ( "Area" => "Harare", "City" => "Unit 3"),
    "24266" => array ( "Area" => "Harare", "City" => "Southerton"),
    "24250" => array ( "Area" => "Harare", "City" => "Hatfield Host"),
    "24223" => array ( "Area" => "Harare", "City" => "Kuwadzana Host"),
    "24222" => array ( "Area" => "Harare", "City" => "Warren Park"),
    "24221" => array ( "Area" => "Harare", "City" => "Kuwadzana Host"),
    "24200" => array ( "Area" => "Harare", "City" => "Harare Soft Client"),
    "20206" => array ( "Area" => "Manicaland", "City" => "Mutare Fetex")
  );
  foreach ( $prefixes as $prefix => $data)
  {
    if ( strlen ( $parameters["Number"]) == 13 && (int) substr ( $parameters["Number"], 4, strlen ( $prefix)) == $prefix)
    {
      return array_merge_recursive ( ( is_array ( $buffer) ? $buffer : array ()), array ( "CC" => "263", "NDC" => substr ( $parameters["Number"], 4, 2), "Country" => "Zimbabwe", "Area" => $data["Area"], "City" => $data["City"], "Operator" => "", "SN" => substr ( $parameters["Number"], 6), "Type" => VD_PHONETYPE_LANDLINE, "CallFormats" => array ( "Local" => "0" . substr ( $parameters["Number"], 4, 2) . " " . substr ( $parameters["Number"], 6), "International" => "+263 " . substr ( $parameters["Number"], 4, 2) . " " . substr ( $parameters["Number"], 6))));
    }
  }

  /**
   * Check for VoIP network with 4 digits NDC and 6 digits SN
   */
  $prefixes = array (
    "8677665" => "Liquid Telecoms Zimbabwe",
    "8677664" => "Liquid Telecoms Zimbabwe",
    "8677663" => "Liquid Telecoms Zimbabwe",
    "8677662" => "Liquid Telecoms Zimbabwe",
    "8677661" => "Liquid Telecoms Zimbabwe",
    "8677660" => "Liquid Telecoms Zimbabwe",
    "8655025" => "Pecus Enterprises (Pvt) Ltd.",
    "8655024" => "Pecus Enterprises (Pvt) Ltd.",
    "8655023" => "Pecus Enterprises (Pvt) Ltd.",
    "8655022" => "Pecus Enterprises (Pvt) Ltd.",
    "8655021" => "Pecus Enterprises (Pvt) Ltd.",
    "8655020" => "Pecus Enterprises (Pvt) Ltd.",
    "8644280" => "Africom (Pvt) Ltd.",
    "8644155" => "Africom (Pvt) Ltd.",
    "8644154" => "Africom (Pvt) Ltd.",
    "8644153" => "Africom (Pvt) Ltd.",
    "8644152" => "Africom (Pvt) Ltd.",
    "8644151" => "Africom (Pvt) Ltd.",
    "8644150" => "Africom (Pvt) Ltd.",
    "8630004" => "Aquiva Wireless (Pvt) Ltd.",
    "8630003" => "Aquiva Wireless (Pvt) Ltd.",
    "8630002" => "Aquiva Wireless (Pvt) Ltd.",
    "8630001" => "Aquiva Wireless (Pvt) Ltd.",
    "8630000" => "Aquiva Wireless (Pvt) Ltd.",
    "868800" => "TelOne (Pvt) Ltd.",
    "868300" => "Telecontract (Pvt) Ltd.",
    "867765" => "Liquid Telecoms Zimbabwe",
    "867764" => "Liquid Telecoms Zimbabwe",
    "867763" => "Liquid Telecoms Zimbabwe",
    "867762" => "Liquid Telecoms Zimbabwe",
    "867761" => "Liquid Telecoms Zimbabwe",
    "867760" => "Liquid Telecoms Zimbabwe",
    "864499" => "Africom (Pvt) Ltd.",
    "864498" => "Africom (Pvt) Ltd.",
    "864497" => "Africom (Pvt) Ltd.",
    "864496" => "Africom (Pvt) Ltd.",
    "864495" => "Africom (Pvt) Ltd.",
    "864494" => "Africom (Pvt) Ltd.",
    "864493" => "Africom (Pvt) Ltd.",
    "864492" => "Africom (Pvt) Ltd.",
    "864491" => "Africom (Pvt) Ltd.",
    "864480" => "Africom (Pvt) Ltd.",
    "864427" => "Africom (Pvt) Ltd.",
    "864426" => "Africom (Pvt) Ltd.",
    "864425" => "Africom (Pvt) Ltd.",
    "864424" => "Africom (Pvt) Ltd.",
    "864423" => "Africom (Pvt) Ltd.",
    "864422" => "Africom (Pvt) Ltd.",
    "864421" => "Africom (Pvt) Ltd.",
    "864420" => "Africom (Pvt) Ltd.",
    "864414" => "Africom (Pvt) Ltd.",
    "864413" => "Africom (Pvt) Ltd.",
    "864412" => "Africom (Pvt) Ltd.",
    "864411" => "Africom (Pvt) Ltd.",
    "864410" => "Africom (Pvt) Ltd.",
    "865501" => "Pecus Enterprises (Pvt) Ltd.",
    "865500" => "Pecus Enterprises (Pvt) Ltd.",
    "862200" => "ZARNet",
    "861200" => "Dandemutande",
    "861141" => "PowerTel",
    "861140" => "PowerTel",
    "86775" => "Liquid Telecoms Zimbabwe",
    "86774" => "Liquid Telecoms Zimbabwe",
    "86773" => "Liquid Telecoms Zimbabwe",
    "86772" => "Liquid Telecoms Zimbabwe",
    "86771" => "Liquid Telecoms Zimbabwe",
    "86770" => "Liquid Telecoms Zimbabwe",
    "86440" => "Africom (Pvt) Ltd.",
    "86112" => "PowerTel",
    "86113" => "PowerTel"
  );
  foreach ( $prefixes as $prefix => $operator)
  {
    if ( strlen ( $parameters["Number"]) == 14 && (int) substr ( $parameters["Number"], 4, strlen ( $prefix)) == $prefix)
    {
      return array_merge_recursive ( ( is_array ( $buffer) ? $buffer : array ()), array ( "CC" => "263", "NDC" => substr ( $parameters["Number"], 4, 4), "Country" => "Zimbabwe", "Area" => "", "City" => "", "Operator" => $operator, "SN" => substr ( $parameters["Number"], 8), "Type" => VD_PHONETYPE_VOIP, "CallFormats" => array ( "Local" => "0" . substr ( $parameters["Number"], 4, 4) . " " . substr ( $parameters["Number"], 8), "International" => "+263 " . substr ( $parameters["Number"], 4, 4) . " " . substr ( $parameters["Number"], 8))));
    }
  }

  /**
   * Check for VoIP network with 3 digits NDC and 4 or 7 digits SN
   */
  $prefixes = array (
    "8002239" => array ( "Length" => 7, "Operator" => "TelOne (Pvt) Ltd."),
    "8002234" => array ( "Length" => 7, "Operator" => "TelOne (Pvt) Ltd."),
    "8002233" => array ( "Length" => 7, "Operator" => "TelOne (Pvt) Ltd."),
    "8002232" => array ( "Length" => 7, "Operator" => "TelOne (Pvt) Ltd."),
    "8002231" => array ( "Length" => 7, "Operator" => "TelOne (Pvt) Ltd."),
    "808" => array ( "Length" => 4, "Operator" => "Econet Wireless Zimbabwe"),
    "802" => array ( "Length" => 4, "Operator" => "PowerTel Communications"),
    "801" => array ( "Length" => 4, "Operator" => "NetOne (Pvt) Ltd."),
    "800" => array ( "Length" => 4, "Operator" => "TelOne (Pvt) Ltd.")
  );
  foreach ( $prefixes as $prefix => $data)
  {
    if ( strlen ( $parameters["Number"]) == 4 + $data["Length"] && (int) substr ( $parameters["Number"], 4, strlen ( $prefix)) == $prefix)
    {
      return array_merge_recursive ( ( is_array ( $buffer) ? $buffer : array ()), array ( "CC" => "263", "NDC" => substr ( $parameters["Number"], 4, 3), "Country" => "Zimbabwe", "Area" => "", "City" => "", "Operator" => $data["Operator"], "SN" => substr ( $parameters["Number"], 7), "Type" => VD_PHONETYPE_TOLLFREE, "CallFormats" => array ( "Local" => "0" . substr ( $parameters["Number"], 4, 3) . " " . substr ( $parameters["Number"], 7), "International" => "+263 " . substr ( $parameters["Number"], 4, 3) . " " . substr ( $parameters["Number"], 7))));
    }
  }

  /**
   * If reached here, number wasn't identified as a valid Zimbabwian phone number
   */
  return ( is_array ( $buffer) ? $buffer : false);
}
?>
