<?php
/**   ___ ___       ___ _______     ______                        __
 *   |   Y   .-----|   |   _   |   |   _  \ .-----.--------.---.-|__.-----.
 *   |.  |   |  _  |.  |.  1   |   |.  |   \|  _  |        |  _  |  |     |
 *   |.  |   |_____|.  |.  ____|   |.  |    |_____|__|__|__|___._|__|__|__|
 *   |:  1   |     |:  |:  |       |:  1    /
 *    \:.. ./      |::.|::.|       |::.. . /
 *     `---'       `---`---'       `------'
 *
 * Copyright (C) 2016-2025 Ernani José Camargo Azevedo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * VoIP Domain country database module filters. This module add the filter calls
 * related to country database of Panama.
 *
 * Reference: https://www.itu.int/oth/T02020000A3/en (2018-12-13)
 *            https://www.asep.gob.pa/?page_id=13113 (2022-12-26)
 *            https://www.asep.gob.pa/?page_id=13048 (2022-12-26)
 *
 * Glossary:
 *  CC - Country Code
 *  NDC - National Destination Code (also known as area code)
 *  N(S)N - National (Significant) Number
 *  SN - Subscriber Number
 *
 * @author     Ernani José Camargo Azevedo <azevedo@voipdomain.io>
 * @version    1.0
 * @package    VoIP Domain
 * @subpackage CountryDB
 * @copyright  2016-2025 Ernani José Camargo Azevedo. All rights reserved.
 * @license    https://www.gnu.org/licenses/gpl-3.0.en.html
 */

/**
 * E.164 Panama country hook
 */
framework_add_filter ( "e164_identify_country_PAN", "e164_identify_country_PAN");

/**
 * E.164 Pananemian area number identification hook. This hook is an
 * e164_identify sub hook, called when the ISO3166 Alpha3 are "PAN" (code for
 * Panama). This hook will verify if phone number is valid, returning the area
 * code, area name, phone number, others number related information and if
 * possible, the number type (mobile, landline, Premium Rate Number, etc).
 *
 * @param string $buffer Buffer from plugin system if processed by other function
 *                       before
 * @param array $parameters Parameters to the function. Number provided as
 *                          $parameters["Number"]
 * @return array Array contaning many information about the requested number
 */
function e164_identify_country_PAN ( $buffer, $parameters)
{
  /**
   * Check if number country code is from Panama
   */
  if ( substr ( $parameters["Number"], 0, 4) != "+507")
  {
    return ( is_array ( $buffer) ? $buffer : false);
  }

  /**
   * All numbers in Panama has 11 or 12 digits E.164 format
   */
  if ( strlen ( $parameters["Number"]) < 11 || strlen ( $parameters["Number"]) > 12)
  {
    return ( is_array ( $buffer) ? $buffer : false);
  }

  /**
   * Check for mobile network with 3 digits NDC and 4 or 5 digits SN
   */
  $prefixes = array (
    "811" => array ( "Length" => 7, "Area" => "", "Operator" => "Mobilphone de Panamá, S.A."),
    "810" => array ( "Length" => 7, "Area" => "", "Operator" => "Mobilphone de Panamá, S.A."),
    "699" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "698" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "697" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "696" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "695" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "694" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "693" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "692" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "691" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "690" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "689" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "688" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "687" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "686" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "685" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "684" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "683" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "682" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "681" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "680" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "669" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "668" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "667" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "666" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "665" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "664" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "663" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "662" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "661" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "660" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "659" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "658" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "657" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "656" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "655" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "654" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "653" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "652" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "651" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "650" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "639" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "638" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "637" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "636" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "635" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "634" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "633" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "632" => array ( "Length" => 8, "Area" => "", "Operator" => "Claro Panamá, S.A."),
    "631" => array ( "Length" => 8, "Area" => "", "Operator" => "Claro Panamá, S.A."),
    "630" => array ( "Length" => 8, "Area" => "", "Operator" => "Claro Panamá, S.A."),
    "619" => array ( "Length" => 8, "Area" => "", "Operator" => "Grupo de Comunicaciones Digitales, S.A."),
    "618" => array ( "Length" => 8, "Area" => "", "Operator" => "Claro Panamá, S.A."),
    "617" => array ( "Length" => 8, "Area" => "", "Operator" => "Claro Panamá, S.A."),
    "616" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "615" => array ( "Length" => 8, "Area" => "", "Operator" => "Digicel (Panamá), S.A."),
    "614" => array ( "Length" => 8, "Area" => "", "Operator" => "Digicel (Panamá), S.A."),
    "613" => array ( "Length" => 8, "Area" => "", "Operator" => "Digicel (Panamá), S.A."),
    "612" => array ( "Length" => 8, "Area" => "", "Operator" => "Digicel (Panamá), S.A."),
    "611" => array ( "Length" => 8, "Area" => "", "Operator" => "Digicel (Panamá), S.A."),
    "610" => array ( "Length" => 8, "Area" => "", "Operator" => "Digicel (Panamá), S.A."),
    "219" => array ( "Length" => 7, "Area" => "Panama", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "218" => array ( "Length" => 7, "Area" => "Panama", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "67" => array ( "Length" => 8, "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "64" => array ( "Length" => 8, "Area" => "", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "62" => array ( "Length" => 8, "Area" => "", "Operator" => "Claro Panamá, S.A."),
    "60" => array ( "Length" => 8, "Area" => "", "Operator" => "Digicel (Panamá), S.A.")
  );
  foreach ( $prefixes as $prefix => $data)
  {
    if ( strlen ( $parameters["Number"]) == $data["Length"] + 4 && (int) substr ( $parameters["Number"], 4, strlen ( $prefix)) == $prefix)
    {
      return array_merge_recursive ( ( is_array ( $buffer) ? $buffer : array ()), array ( "CC" => "507", "NDC" => substr ( $parameters["Number"], 4, 3), "Country" => "Panama", "Area" => $data["Area"], "City" => "", "Operator" => $data["Operator"], "SN" => substr ( $parameters["Number"], 7), "Type" => VD_PHONETYPE_MOBILE, "CallFormats" => array ( "Local" => substr ( $parameters["Number"], 4, 3) . " " . substr ( $parameters["Number"], 7), "International" => "+507 " . substr ( $parameters["Number"], 4, 3) . " " . substr ( $parameters["Number"], 7))));
    }
  }

  /**
   * Check for fixed line network with 3 digits NDC and 4 digits SN
   */
  $prefixes = array (
    "9699" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9698" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9697" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9696" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9695" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9694" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9693" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9692" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9691" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9690" => array ( "Area" => "Los Santos", "Operator" => "Cable Onda, S.A."),
    "9689" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9688" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9687" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9686" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9685" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9684" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9683" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9682" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9681" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9680" => array ( "Area" => "Los Santos", "Operator" => "Galaxy Communication, Corp."),
    "9379" => array ( "Area" => "Veraguas", "Operator" => ""),
    "9378" => array ( "Area" => "Veraguas", "Operator" => ""),
    "9377" => array ( "Area" => "Veraguas", "Operator" => ""),
    "9376" => array ( "Area" => "Veraguas", "Operator" => ""),
    "9375" => array ( "Area" => "Veraguas", "Operator" => ""),
    "9374" => array ( "Area" => "Veraguas", "Operator" => ""),
    "9373" => array ( "Area" => "Veraguas", "Operator" => ""),
    "9372" => array ( "Area" => "Veraguas", "Operator" => ""),
    "9371" => array ( "Area" => "Veraguas", "Operator" => ""),
    "9370" => array ( "Area" => "Veraguas", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "9359" => array ( "Area" => "Veraguas", "Operator" => ""),
    "9358" => array ( "Area" => "Veraguas", "Operator" => ""),
    "9357" => array ( "Area" => "Veraguas", "Operator" => ""),
    "9356" => array ( "Area" => "Veraguas", "Operator" => ""),
    "9355" => array ( "Area" => "Veraguas", "Operator" => ""),
    "9354" => array ( "Area" => "Veraguas", "Operator" => ""),
    "9353" => array ( "Area" => "Veraguas", "Operator" => ""),
    "9352" => array ( "Area" => "Veraguas", "Operator" => "Cable & Wireless Panama, S.A."),
    "9351" => array ( "Area" => "Veraguas", "Operator" => "Cable & Wireless Panama, S.A."),
    "9350" => array ( "Area" => "Veraguas", "Operator" => "Cable & Wireless Panama, S.A."),
    "9299" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9298" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9297" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9296" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9295" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9294" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9293" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9292" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9291" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9290" => array ( "Area" => "Los Santos", "Operator" => "Vozelia, S.A."),
    "9289" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9288" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9287" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9286" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9285" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9284" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9283" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9282" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9281" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9280" => array ( "Area" => "Los Santos", "Operator" => "Galaxy Communication, Corp."),
    "9279" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9278" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9277" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9276" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9275" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9274" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9273" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9272" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9271" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9270" => array ( "Area" => "Los Santos", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "9269" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9268" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9267" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9266" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9265" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9264" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9263" => array ( "Area" => "Los Santos", "Operator" => ""),
    "9262" => array ( "Area" => "Los Santos", "Operator" => "Cable & Wireless Panama, S.A."),
    "9261" => array ( "Area" => "Los Santos", "Operator" => "Cable & Wireless Panama, S.A."),
    "9260" => array ( "Area" => "Los Santos", "Operator" => "Cable & Wireless Panama, S.A."),
    "9209" => array ( "Area" => "Coclé", "Operator" => ""),
    "9208" => array ( "Area" => "Coclé", "Operator" => ""),
    "9207" => array ( "Area" => "Coclé", "Operator" => ""),
    "9206" => array ( "Area" => "Coclé", "Operator" => ""),
    "9205" => array ( "Area" => "Coclé", "Operator" => ""),
    "9204" => array ( "Area" => "Coclé", "Operator" => ""),
    "9203" => array ( "Area" => "Coclé", "Operator" => ""),
    "9202" => array ( "Area" => "Coclé", "Operator" => "Galaxy Communication, Corp."),
    "9201" => array ( "Area" => "Coclé", "Operator" => "Galaxy Communication, Corp."),
    "9200" => array ( "Area" => "Coclé", "Operator" => "Galaxy Communication, Corp."),
    "9189" => array ( "Area" => "Herrera", "Operator" => ""),
    "9188" => array ( "Area" => "Herrera", "Operator" => ""),
    "9187" => array ( "Area" => "Herrera", "Operator" => ""),
    "9186" => array ( "Area" => "Herrera", "Operator" => ""),
    "9185" => array ( "Area" => "Herrera", "Operator" => ""),
    "9184" => array ( "Area" => "Herrera", "Operator" => ""),
    "9183" => array ( "Area" => "Herrera", "Operator" => ""),
    "9182" => array ( "Area" => "Herrera", "Operator" => ""),
    "9181" => array ( "Area" => "Herrera", "Operator" => ""),
    "9180" => array ( "Area" => "Herrera", "Operator" => "Galaxy Communications Corp."),
    "9179" => array ( "Area" => "Herrera", "Operator" => ""),
    "9178" => array ( "Area" => "Herrera", "Operator" => ""),
    "9177" => array ( "Area" => "Herrera", "Operator" => ""),
    "9176" => array ( "Area" => "Herrera", "Operator" => ""),
    "9175" => array ( "Area" => "Herrera", "Operator" => ""),
    "9174" => array ( "Area" => "Herrera", "Operator" => ""),
    "9173" => array ( "Area" => "Herrera", "Operator" => ""),
    "9172" => array ( "Area" => "Herrera", "Operator" => ""),
    "9171" => array ( "Area" => "Herrera", "Operator" => ""),
    "9170" => array ( "Area" => "Herrera", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "9159" => array ( "Area" => "Herrera", "Operator" => ""),
    "9158" => array ( "Area" => "Herrera", "Operator" => ""),
    "9157" => array ( "Area" => "Herrera", "Operator" => ""),
    "9156" => array ( "Area" => "Herrera", "Operator" => ""),
    "9155" => array ( "Area" => "Herrera", "Operator" => ""),
    "9154" => array ( "Area" => "Herrera", "Operator" => ""),
    "9153" => array ( "Area" => "Herrera", "Operator" => ""),
    "9152" => array ( "Area" => "Herrera", "Operator" => ""),
    "9151" => array ( "Area" => "Herrera", "Operator" => ""),
    "9150" => array ( "Area" => "Herrera", "Operator" => "Vozelia, S.A."),
    "9139" => array ( "Area" => "Herrera", "Operator" => ""),
    "9138" => array ( "Area" => "Herrera", "Operator" => ""),
    "9137" => array ( "Area" => "Herrera", "Operator" => ""),
    "9136" => array ( "Area" => "Herrera", "Operator" => ""),
    "9135" => array ( "Area" => "Herrera", "Operator" => ""),
    "9134" => array ( "Area" => "Herrera", "Operator" => ""),
    "9133" => array ( "Area" => "Herrera", "Operator" => ""),
    "9132" => array ( "Area" => "Herrera", "Operator" => "Cable & Wireless Panama, S.A."),
    "9131" => array ( "Area" => "Herrera", "Operator" => "Cable & Wireless Panama, S.A."),
    "9130" => array ( "Area" => "Herrera", "Operator" => "Cable & Wireless Panama, S.A."),
    "9079" => array ( "Area" => "Coclé", "Operator" => ""),
    "9078" => array ( "Area" => "Coclé", "Operator" => ""),
    "9077" => array ( "Area" => "Coclé", "Operator" => ""),
    "9076" => array ( "Area" => "Coclé", "Operator" => ""),
    "9075" => array ( "Area" => "Coclé", "Operator" => ""),
    "9074" => array ( "Area" => "Coclé", "Operator" => ""),
    "9073" => array ( "Area" => "Coclé", "Operator" => ""),
    "9072" => array ( "Area" => "Coclé", "Operator" => ""),
    "9071" => array ( "Area" => "Coclé", "Operator" => ""),
    "9070" => array ( "Area" => "Coclé", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "9069" => array ( "Area" => "Coclé", "Operator" => ""),
    "9068" => array ( "Area" => "Coclé", "Operator" => ""),
    "9067" => array ( "Area" => "Coclé", "Operator" => ""),
    "9066" => array ( "Area" => "Coclé", "Operator" => ""),
    "9065" => array ( "Area" => "Coclé", "Operator" => ""),
    "9064" => array ( "Area" => "Coclé", "Operator" => ""),
    "9063" => array ( "Area" => "Coclé", "Operator" => ""),
    "9062" => array ( "Area" => "Coclé", "Operator" => "Cable & Wireless Panama, S.A."),
    "9061" => array ( "Area" => "Coclé", "Operator" => "Cable & Wireless Panama, S.A."),
    "9060" => array ( "Area" => "Coclé", "Operator" => "Cable & Wireless Panama, S.A."),
    "8549" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "8548" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "8547" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "8546" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "8545" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "8544" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "8543" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "8542" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "8541" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => "Cable Onda, S.A."),
    "8540" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => "Cable Onda, S.A."),
    "8519" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "8518" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "8517" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "8516" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "8515" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "8514" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "8513" => array ( "Area" => "Chiriquí", "Operator" => "Galaxy Communication, Corp."),
    "8512" => array ( "Area" => "Bocas del Toro", "Operator" => "Vozelia, S.A."),
    "8511" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "8510" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => "Galaxy Communication, Corp."),
    "8509" => array ( "Area" => "Bocas del Toro", "Operator" => "Cable & Wireless Panama, S.A."),
    "8508" => array ( "Area" => "Chiriquí", "Operator" => "Cable & Wireless Panama, S.A."),
    "8507" => array ( "Area" => "Bocas del Toro", "Operator" => "Cable & Wireless Panama, S.A."),
    "8506" => array ( "Area" => "Chiriquí", "Operator" => "Cable & Wireless Panama, S.A."),
    "8505" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "8504" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "8503" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "8502" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "8501" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "8500" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "8499" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "8498" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "8497" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "8496" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "8495" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "8494" => array ( "Area" => "Provincias Centrales", "Operator" => "Cable Onda, S.A."),
    "8493" => array ( "Area" => "Provincias Centrales", "Operator" => "Cable Onda, S.A."),
    "8492" => array ( "Area" => "Provincias Centrales", "Operator" => "Cable Onda, S.A."),
    "8491" => array ( "Area" => "Provincias Centrales", "Operator" => "Cable Onda, S.A."),
    "8490" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "8489" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "8488" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "8487" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "8486" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "8485" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "8484" => array ( "Area" => "Provincias Centrales", "Operator" => "Galaxy Communication, Corp."),
    "8483" => array ( "Area" => "Provincias Centrales", "Operator" => "Galaxy Communication, Corp."),
    "8482" => array ( "Area" => "Provincias Centrales", "Operator" => "Galaxy Communication, Corp."),
    "8481" => array ( "Area" => "Provincias Centrales", "Operator" => "Galaxy Communication, Corp."),
    "8480" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "8469" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "8468" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "8467" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "8466" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "8465" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "8464" => array ( "Area" => "Provincias Centrales", "Operator" => "Cable & Wireless Panama, S.A."),
    "8463" => array ( "Area" => "Provincias Centrales", "Operator" => "Cable & Wireless Panama, S.A."),
    "8462" => array ( "Area" => "Provincias Centrales", "Operator" => "Cable & Wireless Panama, S.A."),
    "8461" => array ( "Area" => "Provincias Centrales", "Operator" => "Cable & Wireless Panama, S.A."),
    "8460" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "8459" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "8458" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "8457" => array ( "Area" => "Provincias Centrales", "Operator" => "Vozelia, S.A."),
    "8456" => array ( "Area" => "Provincias Centrales", "Operator" => "Vozelia, S.A."),
    "8455" => array ( "Area" => "Provincias Centrales", "Operator" => "Vozelia, S.A."),
    "8454" => array ( "Area" => "Provincias Centrales", "Operator" => "Cable Onda, S.A."),
    "8453" => array ( "Area" => "Provincias Centrales", "Operator" => "Cable Onda, S.A."),
    "8452" => array ( "Area" => "Provincias Centrales", "Operator" => "Cable Onda, S.A."),
    "8451" => array ( "Area" => "Provincias Centrales", "Operator" => "Cable Onda, S.A."),
    "8450" => array ( "Area" => "Provincias Centrales", "Operator" => "Vozelia, S.A."),
    "8449" => array ( "Area" => "Cólon", "Operator" => ""),
    "8448" => array ( "Area" => "Cólon", "Operator" => ""),
    "8447" => array ( "Area" => "Cólon", "Operator" => ""),
    "8446" => array ( "Area" => "Cólon", "Operator" => ""),
    "8445" => array ( "Area" => "Cólon", "Operator" => ""),
    "8444" => array ( "Area" => "Cólon", "Operator" => ""),
    "8443" => array ( "Area" => "Cólon", "Operator" => ""),
    "8442" => array ( "Area" => "Cólon", "Operator" => ""),
    "8441" => array ( "Area" => "Cólon", "Operator" => "Vozelia, S.A."),
    "8440" => array ( "Area" => "Cólon", "Operator" => "Cable Onda, S.A."),
    "8429" => array ( "Area" => "Cólon", "Operator" => ""),
    "8428" => array ( "Area" => "Cólon", "Operator" => ""),
    "8427" => array ( "Area" => "Cólon", "Operator" => ""),
    "8426" => array ( "Area" => "Cólon", "Operator" => ""),
    "8425" => array ( "Area" => "Cólon", "Operator" => ""),
    "8424" => array ( "Area" => "Cólon", "Operator" => ""),
    "8423" => array ( "Area" => "Cólon", "Operator" => ""),
    "8422" => array ( "Area" => "Cólon", "Operator" => ""),
    "8421" => array ( "Area" => "Cólon", "Operator" => "Cable & Wireless Panamá, S.A."),
    "8420" => array ( "Area" => "Cólon", "Operator" => "Cable Onda, S.A."),
    "8419" => array ( "Area" => "Cólon", "Operator" => "Galaxy Communication, Corp."),
    "8418" => array ( "Area" => "Cólon", "Operator" => ""),
    "8417" => array ( "Area" => "Cólon", "Operator" => ""),
    "8416" => array ( "Area" => "Cólon", "Operator" => ""),
    "8415" => array ( "Area" => "Cólon", "Operator" => ""),
    "8414" => array ( "Area" => "Cólon", "Operator" => ""),
    "8413" => array ( "Area" => "Cólon", "Operator" => ""),
    "8412" => array ( "Area" => "Cólon", "Operator" => ""),
    "8411" => array ( "Area" => "Cólon", "Operator" => ""),
    "8410" => array ( "Area" => "Cólon", "Operator" => ""),
    "8409" => array ( "Area" => "Cólon", "Operator" => ""),
    "8408" => array ( "Area" => "Cólon", "Operator" => ""),
    "8407" => array ( "Area" => "Cólon", "Operator" => ""),
    "8406" => array ( "Area" => "Cólon", "Operator" => ""),
    "8405" => array ( "Area" => "Cólon", "Operator" => ""),
    "8404" => array ( "Area" => "Cólon", "Operator" => "Vozelia, S.A."),
    "8403" => array ( "Area" => "Cólon", "Operator" => "Cable & Wireless Panama, S.A."),
    "8402" => array ( "Area" => "Cólon", "Operator" => "Cable & Wireless Panama, S.A."),
    "8401" => array ( "Area" => "Cólon", "Operator" => "Cable & Wireless Panama, S.A."),
    "8400" => array ( "Area" => "Cólon", "Operator" => "Cable & Wireless Panama, S.A."),
    "8399" => array ( "Area" => "Panama", "Operator" => ""),
    "8398" => array ( "Area" => "Panama", "Operator" => ""),
    "8397" => array ( "Area" => "Panama", "Operator" => ""),
    "8396" => array ( "Area" => "Panama", "Operator" => ""),
    "8395" => array ( "Area" => "Panama", "Operator" => ""),
    "8394" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "8393" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "8392" => array ( "Area" => "Panama", "Operator" => "Vozelia, S.A."),
    "8391" => array ( "Area" => "Panama", "Operator" => "Vozelia, S.A."),
    "8390" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "8389" => array ( "Area" => "Panama", "Operator" => "Galaxy Communication, Corp."),
    "8388" => array ( "Area" => "Panama", "Operator" => "Galaxy Communication, Corp."),
    "8387" => array ( "Area" => "Panama", "Operator" => "Galaxy Communication, Corp."),
    "8386" => array ( "Area" => "Panama", "Operator" => "Galaxy Communication, Corp."),
    "8385" => array ( "Area" => "Panama", "Operator" => "Galaxy Communication, Corp."),
    "8384" => array ( "Area" => "Panama", "Operator" => ""),
    "8383" => array ( "Area" => "Panama", "Operator" => ""),
    "8382" => array ( "Area" => "Panama", "Operator" => ""),
    "8381" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panamá, S.A."),
    "8380" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panamá, S.A."),
    "8379" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "8378" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "8377" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "8376" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "8375" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "8374" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "8373" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "8372" => array ( "Area" => "Panama Oeste", "Operator" => "Galaxy Communication, Corp."),
    "8371" => array ( "Area" => "Panama Oeste", "Operator" => "Galaxy Communication, Corp."),
    "8370" => array ( "Area" => "Panama Oeste", "Operator" => "Galaxy Communication, Corp."),
    "8359" => array ( "Area" => "Panama", "Operator" => ""),
    "8358" => array ( "Area" => "Panama", "Operator" => ""),
    "8357" => array ( "Area" => "Panama", "Operator" => ""),
    "8356" => array ( "Area" => "Panama", "Operator" => ""),
    "8355" => array ( "Area" => "Panama", "Operator" => "Vozelia, S.A."),
    "8354" => array ( "Area" => "Panama", "Operator" => ""),
    "8353" => array ( "Area" => "Panama", "Operator" => ""),
    "8352" => array ( "Area" => "Panama", "Operator" => "Interfast Panamá, S.A."),
    "8351" => array ( "Area" => "Panama", "Operator" => "Mobil Red, Inc."),
    "8350" => array ( "Area" => "Panama", "Operator" => "Fortaleza Investment Group, Corp."),
    "8349" => array ( "Area" => "Panama", "Operator" => ""),
    "8348" => array ( "Area" => "Panama", "Operator" => "Galaxy Communication, Corp."),
    "8347" => array ( "Area" => "Panama", "Operator" => "Galaxy Communication, Corp."),
    "8346" => array ( "Area" => "Panama", "Operator" => ""),
    "8345" => array ( "Area" => "Panama", "Operator" => "Vozelia, S.A."),
    "8344" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "8343" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "8342" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "8341" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "8340" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "8339" => array ( "Area" => "Panama", "Operator" => "Galaxy Communication, Corp."),
    "8338" => array ( "Area" => "Panama", "Operator" => "Galaxy Communication, Corp."),
    "8337" => array ( "Area" => "Panama", "Operator" => "Galaxy Communication, Corp."),
    "8336" => array ( "Area" => "Panama", "Operator" => "Galaxy Communication, Corp."),
    "8335" => array ( "Area" => "Panama", "Operator" => "Galaxy Communication, Corp."),
    "8334" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "8333" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "8332" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "8331" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "8330" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "7909" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7908" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "8299" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "8298" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "8297" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "8296" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "8295" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "8294" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "8293" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "8292" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "8291" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "8290" => array ( "Area" => "Panama Oeste", "Operator" => "Vozelia, S.A."),
    "8289" => array ( "Area" => "Darién & Guna Yala", "Operator" => ""),
    "8288" => array ( "Area" => "Darién & Guna Yala", "Operator" => ""),
    "8287" => array ( "Area" => "Darién & Guna Yala", "Operator" => ""),
    "8286" => array ( "Area" => "Darién & Guna Yala", "Operator" => ""),
    "8285" => array ( "Area" => "Darién & Guna Yala", "Operator" => ""),
    "8284" => array ( "Area" => "Darién & Guna Yala", "Operator" => ""),
    "8283" => array ( "Area" => "Darién & Guna Yala", "Operator" => ""),
    "8282" => array ( "Area" => "Darién & Guna Yala", "Operator" => "Galaxy Communication, Corp."),
    "8281" => array ( "Area" => "Darién & Guna Yala", "Operator" => "Claro Panamá, S.A."),
    "8280" => array ( "Area" => "Darién & Guna Yala", "Operator" => "Vozelia, S.A."),
    "7907" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7906" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7905" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7904" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7903" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7902" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7901" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7900" => array ( "Area" => "Bocas del Toro", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "7669" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7668" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7667" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7666" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7665" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7664" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7663" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7662" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7661" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7660" => array ( "Area" => "Bocas del Toro", "Operator" => "Claro Panamá, S.A."),
    "7659" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7658" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7657" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7656" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7655" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7654" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7653" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7652" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7651" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7650" => array ( "Area" => "Bocas del Toro", "Operator" => "Vozelia, S.A."),
    "7509" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7508" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7507" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7506" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7505" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7504" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7503" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7502" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "7501" => array ( "Area" => "Bocas del Toro", "Operator" => "Cable & Wireless Panama, S.A."),
    "7500" => array ( "Area" => "Bocas del Toro", "Operator" => "Cable & Wireless Panama, S.A."),
    "7289" => array ( "Area" => "Chiriquí & Ngäbe Buglé", "Operator" => ""),
    "7288" => array ( "Area" => "Chiriquí & Ngäbe Buglé", "Operator" => ""),
    "7287" => array ( "Area" => "Chiriquí & Ngäbe Buglé", "Operator" => ""),
    "7286" => array ( "Area" => "Chiriquí & Ngäbe Buglé", "Operator" => ""),
    "7285" => array ( "Area" => "Chiriquí", "Operator" => "Cable & Wireless Panama, S.A."),
    "7284" => array ( "Area" => "Chiriquí", "Operator" => "Cable & Wireless Panama, S.A."),
    "7283" => array ( "Area" => "Chiriquí", "Operator" => "Cable & Wireless Panama, S.A."),
    "7282" => array ( "Area" => "Ngäbe Buglé", "Operator" => "Cable & Wireless Panama, S.A."),
    "7281" => array ( "Area" => "Chiriquí", "Operator" => "Cable & Wireless Panama, S.A."),
    "7280" => array ( "Area" => "Chiriquí", "Operator" => "Cable & Wireless Panama, S.A."),
    "7009" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "7008" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "7007" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "7006" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "7005" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "7004" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "7003" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "7002" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "7001" => array ( "Area" => "Chiriquí", "Operator" => "Galaxy Communication, Corp."),
    "7000" => array ( "Area" => "Chiriquí", "Operator" => "Galaxy Communication, Corp."),
    "2889" => array ( "Area" => "Panama", "Operator" => ""),
    "2888" => array ( "Area" => "Panama", "Operator" => ""),
    "2887" => array ( "Area" => "Panama", "Operator" => ""),
    "2886" => array ( "Area" => "Panama", "Operator" => ""),
    "2885" => array ( "Area" => "Panama", "Operator" => ""),
    "2884" => array ( "Area" => "Panama", "Operator" => ""),
    "2883" => array ( "Area" => "Panama", "Operator" => ""),
    "2882" => array ( "Area" => "Panama", "Operator" => ""),
    "2881" => array ( "Area" => "Panama", "Operator" => ""),
    "2880" => array ( "Area" => "Panama", "Operator" => "Fortaleza Investment Group, Corp."),
    "2879" => array ( "Area" => "Darién & Guna Yala", "Operator" => ""),
    "2878" => array ( "Area" => "Darién & Guna Yala", "Operator" => ""),
    "2877" => array ( "Area" => "Darién & Guna Yala", "Operator" => ""),
    "2876" => array ( "Area" => "Darién & Guna Yala", "Operator" => ""),
    "2875" => array ( "Area" => "Darién & Guna Yala", "Operator" => ""),
    "2874" => array ( "Area" => "Darién & Guna Yala", "Operator" => ""),
    "2873" => array ( "Area" => "Darién & Guna Yala", "Operator" => ""),
    "2872" => array ( "Area" => "Darién & Guna Yala", "Operator" => "Cable & Wireless Panama, S.A."),
    "2871" => array ( "Area" => "Darién & Guna Yala", "Operator" => ""),
    "2870" => array ( "Area" => "Darién & Guna Yala", "Operator" => "Cable & Wireless Panama, S.A."),
    "2499" => array ( "Area" => "Panama Oeste", "Operator" => "Cable Onda, S.A."),
    "2498" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2497" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2496" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2495" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2494" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2493" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2492" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2491" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2490" => array ( "Area" => "Panama Oeste", "Operator" => "Cable Onda, S.A."),
    "2469" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2468" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2467" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2466" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2465" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2464" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2463" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2462" => array ( "Area" => "Panama", "Operator" => "Galaxy Communication, Corp."),
    "2461" => array ( "Area" => "Panama Oeste", "Operator" => "Galaxy Communication, Corp."),
    "2460" => array ( "Area" => "Panama", "Operator" => "Galaxy Communication, Corp."),
    "2419" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2418" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2417" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2416" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2415" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2414" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2413" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2412" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2411" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "2410" => array ( "Area" => "Panama Oeste", "Operator" => "Vozelia, S.A."),
    "999" => array ( "Area" => "Veraguas", "Operator" => "Cable & Wireless Panama, S.A."),
    "998" => array ( "Area" => "Veraguas", "Operator" => "Cable & Wireless Panama, S.A."),
    "997" => array ( "Area" => "Coclé", "Operator" => "Cable & Wireless Panama, S.A."),
    "996" => array ( "Area" => "Herrera", "Operator" => "Cable & Wireless Panama, S.A."),
    "995" => array ( "Area" => "Los Santos", "Operator" => "Cable & Wireless Panama, S.A."),
    "994" => array ( "Area" => "Los Santos", "Operator" => "Cable & Wireless Panama, S.A."),
    "993" => array ( "Area" => "Coclé", "Operator" => "Cable & Wireless Panama, S.A."),
    "992" => array ( "Area" => "Herrera", "Operator" => "Cable & Wireless Panama, S.A."),
    "991" => array ( "Area" => "Provincias Centrales", "Operator" => "Cable & Wireless Panama, S.A."),
    "990" => array ( "Area" => "Provincias Centrales", "Operator" => "Claro Panamá, S.A."),
    "989" => array ( "Area" => "Coclé", "Operator" => ""),
    "988" => array ( "Area" => "Coclé", "Operator" => "Cable Onda, S.A."),
    "987" => array ( "Area" => "Coclé", "Operator" => "Cable & Wireless Panama, S.A."),
    "986" => array ( "Area" => "Coclé", "Operator" => "Cable & Wireless Panama, S.A."),
    "985" => array ( "Area" => "Coclé", "Operator" => ""),
    "984" => array ( "Area" => "Coclé", "Operator" => ""),
    "983" => array ( "Area" => "Coclé", "Operator" => "Cable & Wireless Panama, S.A."),
    "982" => array ( "Area" => "Coclé", "Operator" => ""),
    "980" => array ( "Area" => "Coclé", "Operator" => ""),
    "979" => array ( "Area" => "Herrera", "Operator" => "Cable Onda, S.A."),
    "978" => array ( "Area" => "Herrera", "Operator" => "Cable Onda, S.A."),
    "977" => array ( "Area" => "Herrera", "Operator" => "Cable & Wireless Panama, S.A."),
    "976" => array ( "Area" => "Herrera", "Operator" => "Cable & Wireless Panama, S.A."),
    "975" => array ( "Area" => "Herrera", "Operator" => ""),
    "974" => array ( "Area" => "Herrera", "Operator" => "Cable & Wireless Panama, S.A."),
    "973" => array ( "Area" => "Herrera", "Operator" => ""),
    "972" => array ( "Area" => "Herrera", "Operator" => ""),
    "971" => array ( "Area" => "Herrera", "Operator" => ""),
    "970" => array ( "Area" => "Herrera", "Operator" => "Cable & Wireless Panama, S.A."),
    "967" => array ( "Area" => "Los Santos", "Operator" => "Cable Onda, S.A."),
    "966" => array ( "Area" => "Los Santos", "Operator" => "Cable & Wireless Panama, S.A."),
    "965" => array ( "Area" => "Los Santos", "Operator" => ""),
    "964" => array ( "Area" => "Los Santos", "Operator" => ""),
    "963" => array ( "Area" => "Los Santos", "Operator" => ""),
    "962" => array ( "Area" => "Los Santos", "Operator" => ""),
    "961" => array ( "Area" => "Los Santos", "Operator" => ""),
    "960" => array ( "Area" => "Los Santos", "Operator" => "Cable & Wireless Panama, S.A."),
    "959" => array ( "Area" => "Veraguas", "Operator" => "Cable & Wireless Panama, S.A."),
    "958" => array ( "Area" => "Veraguas", "Operator" => "Cable & Wireless Panama, S.A."),
    "957" => array ( "Area" => "Veraguas", "Operator" => "Vozelia, S.A."),
    "956" => array ( "Area" => "Veraguas", "Operator" => ""),
    "955" => array ( "Area" => "Veraguas", "Operator" => ""),
    "954" => array ( "Area" => "Veraguas", "Operator" => "Cable & Wireless Panama, S.A."),
    "953" => array ( "Area" => "Veraguas", "Operator" => ""),
    "952" => array ( "Area" => "Veraguas", "Operator" => ""),
    "951" => array ( "Area" => "Veraguas", "Operator" => ""),
    "950" => array ( "Area" => "Veraguas", "Operator" => "Cable Onda, S.A."),
    "949" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "948" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "947" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "946" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "945" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "944" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "943" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "942" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "941" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "940" => array ( "Area" => "Provincias Centrales", "Operator" => "Cable & Wireless Panama, S.A."),
    "939" => array ( "Area" => "Veraguas", "Operator" => "Cable Onda, S.A."),
    "938" => array ( "Area" => "Veraguas", "Operator" => ""),
    "936" => array ( "Area" => "Veraguas", "Operator" => ""),
    "934" => array ( "Area" => "Veraguas", "Operator" => ""),
    "933" => array ( "Area" => "Veraguas", "Operator" => "Cable Onda, S.A."),
    "932" => array ( "Area" => "Veraguas", "Operator" => ""),
    "931" => array ( "Area" => "Veraguas", "Operator" => ""),
    "930" => array ( "Area" => "", "Operator" => ""),
    "925" => array ( "Area" => "Los Santos", "Operator" => ""),
    "924" => array ( "Area" => "Los Santos", "Operator" => ""),
    "923" => array ( "Area" => "Los Santos", "Operator" => "Cable Onda, S.A."),
    "922" => array ( "Area" => "Coclé", "Operator" => ""),
    "921" => array ( "Area" => "Coclé", "Operator" => ""),
    "919" => array ( "Area" => "Herrera", "Operator" => ""),
    "916" => array ( "Area" => "Herrera", "Operator" => ""),
    "914" => array ( "Area" => "Herrera", "Operator" => ""),
    "912" => array ( "Area" => "Herrera", "Operator" => ""),
    "911" => array ( "Area" => "", "Operator" => ""),
    "910" => array ( "Area" => "Herrera", "Operator" => "Cable Onda, S.A."),
    "899" => array ( "Area" => "", "Operator" => ""),
    "898" => array ( "Area" => "", "Operator" => ""),
    "897" => array ( "Area" => "", "Operator" => ""),
    "896" => array ( "Area" => "", "Operator" => ""),
    "894" => array ( "Area" => "", "Operator" => ""),
    "893" => array ( "Area" => "", "Operator" => ""),
    "892" => array ( "Area" => "", "Operator" => ""),
    "891" => array ( "Area" => "", "Operator" => ""),
    "890" => array ( "Area" => "", "Operator" => ""),
    "888" => array ( "Area" => "", "Operator" => ""),
    "885" => array ( "Area" => "", "Operator" => ""),
    "884" => array ( "Area" => "", "Operator" => ""),
    "883" => array ( "Area" => "", "Operator" => ""),
    "882" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "881" => array ( "Area" => "", "Operator" => ""),
    "880" => array ( "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "873" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "872" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "869" => array ( "Area" => "", "Operator" => ""),
    "868" => array ( "Area" => "", "Operator" => ""),
    "867" => array ( "Area" => "", "Operator" => ""),
    "866" => array ( "Area" => "", "Operator" => ""),
    "865" => array ( "Area" => "", "Operator" => ""),
    "864" => array ( "Area" => "", "Operator" => ""),
    "863" => array ( "Area" => "", "Operator" => ""),
    "862" => array ( "Area" => "", "Operator" => ""),
    "861" => array ( "Area" => "", "Operator" => ""),
    "859" => array ( "Area" => "", "Operator" => ""),
    "858" => array ( "Area" => "", "Operator" => ""),
    "857" => array ( "Area" => "", "Operator" => ""),
    "856" => array ( "Area" => "", "Operator" => ""),
    "853" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "852" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => ""),
    "847" => array ( "Area" => "Provincias Centrales", "Operator" => ""),
    "843" => array ( "Area" => "Cólon", "Operator" => ""),
    "836" => array ( "Area" => "Panama", "Operator" => "Galaxy Communication, Corp."),
    "832" => array ( "Area" => "Panama", "Operator" => "Galaxy Communication, Corp."),
    "831" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "830" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "909" => array ( "Area" => "Coclé", "Operator" => "Cable Onda, S.A."),
    "908" => array ( "Area" => "Coclé", "Operator" => "Cable Onda, S.A."),
    "905" => array ( "Area" => "Coclé", "Operator" => "Vozelia, S.A."),
    "827" => array ( "Area" => "Darién", "Operator" => ""),
    "819" => array ( "Area" => "", "Operator" => ""),
    "818" => array ( "Area" => "", "Operator" => ""),
    "817" => array ( "Area" => "", "Operator" => ""),
    "816" => array ( "Area" => "", "Operator" => ""),
    "815" => array ( "Area" => "", "Operator" => ""),
    "814" => array ( "Area" => "", "Operator" => ""),
    "813" => array ( "Area" => "", "Operator" => ""),
    "812" => array ( "Area" => "", "Operator" => ""),
    "809" => array ( "Area" => "", "Operator" => "Cable & Wireless Panama, S.A."),
    "808" => array ( "Area" => "", "Operator" => ""),
    "807" => array ( "Area" => "", "Operator" => ""),
    "806" => array ( "Area" => "", "Operator" => ""),
    "805" => array ( "Area" => "", "Operator" => ""),
    "804" => array ( "Area" => "", "Operator" => ""),
    "803" => array ( "Area" => "", "Operator" => ""),
    "802" => array ( "Area" => "", "Operator" => ""),
    "801" => array ( "Area" => "", "Operator" => ""),
    "800" => array ( "Area" => "", "Operator" => ""),
    "769" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "768" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "767" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "764" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "763" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "762" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "761" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "769" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "768" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "767" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "764" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "763" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "762" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "761" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "760" => array ( "Area" => "Bocas del Toro", "Operator" => "Cable Onda, S.A."),
    "759" => array ( "Area" => "Bocas del Toro", "Operator" => "Cable & Wireless Panama, S.A."),
    "758" => array ( "Area" => "Bocas del Toro", "Operator" => "Cable & Wireless Panama, S.A."),
    "757" => array ( "Area" => "Bocas del Toro", "Operator" => "Cable & Wireless Panama, S.A."),
    "756" => array ( "Area" => "Bocas del Toro", "Operator" => "Cable & Wireless Panama, S.A."),
    "755" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "754" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "753" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "752" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "751" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "799" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "798" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "797" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "796" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "795" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "794" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "793" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "792" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "791" => array ( "Area" => "Bocas del Toro", "Operator" => ""),
    "789" => array ( "Area" => "Chiriquí", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "788" => array ( "Area" => "Chiriquí", "Operator" => "Cable Onda, S.A."),
    "787" => array ( "Area" => "Chiriquí", "Operator" => "Cable Onda, S.A."),
    "786" => array ( "Area" => "Chiriquí", "Operator" => "Cable Onda, S.A."),
    "785" => array ( "Area" => "Chiriquí", "Operator" => "Cable Onda, S.A."),
    "784" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "783" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "782" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "781" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "780" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "779" => array ( "Area" => "Chiriquí & Bocas del Toro", "Operator" => "Cable & Wireless Panama, S.A."),
    "778" => array ( "Area" => "Chiriquí", "Operator" => "Vozelia, S.A."),
    "777" => array ( "Area" => "Chiriquí", "Operator" => "Cable & Wireless Panama, S.A."),
    "776" => array ( "Area" => "Chiriquí", "Operator" => "Cable & Wireless Panama, S.A."),
    "775" => array ( "Area" => "Chiriquí", "Operator" => "Cable & Wireless Panama, S.A."),
    "774" => array ( "Area" => "Chiriquí", "Operator" => "Cable & Wireless Panama, S.A."),
    "773" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "772" => array ( "Area" => "Chiriquí", "Operator" => "Cable & Wireless Panama, S.A."),
    "771" => array ( "Area" => "Chiriquí", "Operator" => "Cable & Wireless Panama, S.A."),
    "770" => array ( "Area" => "Chiriquí", "Operator" => "Cable & Wireless Panama, S.A."),
    "749" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "748" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "747" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "746" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "745" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "744" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "743" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "742" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "741" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "740" => array ( "Area" => "Chiriquí", "Operator" => "Cable & Wireless Panama, S.A."),
    "739" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "738" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "737" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "736" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "735" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "734" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "733" => array ( "Area" => "Chiriquí", "Operator" => "Cable Onda, S.A."),
    "732" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "731" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "730" => array ( "Area" => "Chiriquí", "Operator" => "Cable Onda, S.A."),
    "729" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "727" => array ( "Area" => "Chiriquí", "Operator" => "Cable & Wireless Panama, S.A."),
    "726" => array ( "Area" => "Chiriquí", "Operator" => "Cable & Wireless Panama, S.A."),
    "725" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "724" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "723" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "722" => array ( "Area" => "Chiriquí", "Operator" => "Cable & Wireless Panama, S.A."),
    "721" => array ( "Area" => "Chiriquí", "Operator" => "Cable & Wireless Panama, S.A."),
    "720" => array ( "Area" => "Chiriquí", "Operator" => "Cable & Wireless Panama, S.A."),
    "709" => array ( "Area" => "Chiriquí", "Operator" => "Cable Onda, S.A."),
    "708" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "707" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "706" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "705" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "704" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "703" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "702" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "701" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "579" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "578" => array ( "Area" => "Panama", "Operator" => ""),
    "577" => array ( "Area" => "Panama", "Operator" => ""),
    "576" => array ( "Area" => "Panama", "Operator" => ""),
    "575" => array ( "Area" => "Panama", "Operator" => ""),
    "574" => array ( "Area" => "Panama", "Operator" => ""),
    "573" => array ( "Area" => "Panama", "Operator" => ""),
    "572" => array ( "Area" => "Panama", "Operator" => ""),
    "571" => array ( "Area" => "Panama", "Operator" => ""),
    "570" => array ( "Area" => "Panama", "Operator" => ""),
    "569" => array ( "Area" => "Panama", "Operator" => ""),
    "568" => array ( "Area" => "Panama", "Operator" => ""),
    "567" => array ( "Area" => "Panama", "Operator" => ""),
    "566" => array ( "Area" => "Panama", "Operator" => ""),
    "565" => array ( "Area" => "Panama", "Operator" => ""),
    "564" => array ( "Area" => "Panama", "Operator" => ""),
    "563" => array ( "Area" => "Panama", "Operator" => ""),
    "562" => array ( "Area" => "Panama", "Operator" => ""),
    "561" => array ( "Area" => "Panama", "Operator" => ""),
    "560" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "559" => array ( "Area" => "Panama", "Operator" => ""),
    "558" => array ( "Area" => "Panama", "Operator" => ""),
    "557" => array ( "Area" => "Panama", "Operator" => ""),
    "556" => array ( "Area" => "Panama", "Operator" => ""),
    "555" => array ( "Area" => "Panama", "Operator" => ""),
    "554" => array ( "Area" => "Panama", "Operator" => ""),
    "553" => array ( "Area" => "Panama", "Operator" => ""),
    "552" => array ( "Area" => "Panama", "Operator" => ""),
    "551" => array ( "Area" => "Panama", "Operator" => ""),
    "550" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "539" => array ( "Area" => "Panama", "Operator" => ""),
    "538" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "537" => array ( "Area" => "Panama", "Operator" => ""),
    "536" => array ( "Area" => "Panama", "Operator" => ""),
    "535" => array ( "Area" => "Panama", "Operator" => ""),
    "534" => array ( "Area" => "Panama", "Operator" => ""),
    "533" => array ( "Area" => "Panama", "Operator" => ""),
    "532" => array ( "Area" => "Panama", "Operator" => ""),
    "531" => array ( "Area" => "Panama", "Operator" => ""),
    "530" => array ( "Area" => "Panama", "Operator" => ""),
    "529" => array ( "Area" => "Panama", "Operator" => ""),
    "528" => array ( "Area" => "Panama", "Operator" => ""),
    "527" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "526" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "525" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "524" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "523" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "522" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "521" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "520" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "479" => array ( "Area" => "Colón", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "478" => array ( "Area" => "Colón", "Operator" => "Cable & Wireless Panama, S.A."),
    "477" => array ( "Area" => "Colón", "Operator" => ""),
    "476" => array ( "Area" => "Colón", "Operator" => ""),
    "475" => array ( "Area" => "Colón", "Operator" => "Cable & Wireless Panama, S.A."),
    "474" => array ( "Area" => "Colón", "Operator" => "Cable Onda, S.A."),
    "473" => array ( "Area" => "Colón", "Operator" => "Cable & Wireless Panama, S.A."),
    "472" => array ( "Area" => "Colón", "Operator" => "Cable Onda, S.A."),
    "471" => array ( "Area" => "Colón", "Operator" => "Galaxy Communication, S.A."),
    "470" => array ( "Area" => "Colón", "Operator" => "Cable & Wireless Panama, S.A."),
    "469" => array ( "Area" => "Colón", "Operator" => ""),
    "468" => array ( "Area" => "Colón", "Operator" => ""),
    "467" => array ( "Area" => "Colón", "Operator" => ""),
    "466" => array ( "Area" => "Panama", "Operator" => ""),
    "465" => array ( "Area" => "Panama", "Operator" => ""),
    "464" => array ( "Area" => "Panama", "Operator" => ""),
    "463" => array ( "Area" => "Panama", "Operator" => ""),
    "462" => array ( "Area" => "Panama", "Operator" => ""),
    "461" => array ( "Area" => "Panama", "Operator" => ""),
    "460" => array ( "Area" => "Panama", "Operator" => ""),
    "449" => array ( "Area" => "Colón", "Operator" => "Cable & Wireless Panama, S.A."),
    "448" => array ( "Area" => "Colón", "Operator" => "Cable & Wireless Panama, S.A."),
    "447" => array ( "Area" => "Colón", "Operator" => "Cable & Wireless Panama, S.A."),
    "446" => array ( "Area" => "Colón", "Operator" => "Cable Onda, S.A."),
    "445" => array ( "Area" => "Colón", "Operator" => "Cable & Wireless Panama, S.A."),
    "444" => array ( "Area" => "Colón", "Operator" => "Cable & Wireless Panama, S.A."),
    "443" => array ( "Area" => "Colón", "Operator" => "ACP"),
    "442" => array ( "Area" => "Colón", "Operator" => "Cable & Wireless Panama, S.A."),
    "441" => array ( "Area" => "Colón", "Operator" => "Cable & Wireless Panama, S.A."),
    "440" => array ( "Area" => "Colón", "Operator" => "Cable Onda, S.A."),
    "439" => array ( "Area" => "Colón", "Operator" => "Cable Onda, S.A."),
    "438" => array ( "Area" => "Colón", "Operator" => ""),
    "437" => array ( "Area" => "Colón", "Operator" => "Claro Panamá, S.A."),
    "436" => array ( "Area" => "Colón", "Operator" => ""),
    "435" => array ( "Area" => "Colón", "Operator" => "Cable & Wireless Panama, S.A."),
    "434" => array ( "Area" => "Colón", "Operator" => "Cable & Wireless Panama, S.A."),
    "433" => array ( "Area" => "Colón", "Operator" => "Cable & Wireless Panama, S.A."),
    "432" => array ( "Area" => "Colón", "Operator" => "Vozelia, S.A."),
    "431" => array ( "Area" => "Colón", "Operator" => "Cable Onda, S.A."),
    "430" => array ( "Area" => "Colón", "Operator" => "Cable & Wireless Panama, S.A."),
    "409" => array ( "Area" => "Panama", "Operator" => ""),
    "408" => array ( "Area" => "Panama", "Operator" => ""),
    "407" => array ( "Area" => "Panama", "Operator" => ""),
    "406" => array ( "Area" => "Panama", "Operator" => ""),
    "405" => array ( "Area" => "Panama", "Operator" => ""),
    "404" => array ( "Area" => "Panama", "Operator" => ""),
    "403" => array ( "Area" => "Panama", "Operator" => ""),
    "402" => array ( "Area" => "Panama", "Operator" => ""),
    "401" => array ( "Area" => "Panama", "Operator" => ""),
    "400" => array ( "Area" => "Panama", "Operator" => "Claro Panamá, S.A."),
    "389" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "388" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "387" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "386" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "385" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "384" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "383" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "382" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "381" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "380" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "379" => array ( "Area" => "Panama", "Operator" => ""),
    "378" => array ( "Area" => "Panama", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "377" => array ( "Area" => "Panama", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "376" => array ( "Area" => "Panama", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "375" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "374" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "373" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "372" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "371" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "370" => array ( "Area" => "Panama", "Operator" => "Digicel (Panamá), S.A."),
    "369" => array ( "Area" => "Panama", "Operator" => ""),
    "368" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "367" => array ( "Area" => "Panama", "Operator" => ""),
    "366" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "365" => array ( "Area" => "Panama", "Operator" => ""),
    "364" => array ( "Area" => "Panama", "Operator" => ""),
    "363" => array ( "Area" => "Panama", "Operator" => ""),
    "362" => array ( "Area" => "Panama", "Operator" => ""),
    "361" => array ( "Area" => "Panama", "Operator" => ""),
    "360" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "359" => array ( "Area" => "Panama", "Operator" => ""),
    "358" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "357" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "356" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "355" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "354" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "353" => array ( "Area" => "Panama Oeste", "Operator" => "Cable & Wireless Panama, S.A."),
    "352" => array ( "Area" => "Panama Oeste", "Operator" => "Cable & Wireless Panama, S.A."),
    "351" => array ( "Area" => "Panama Oeste", "Operator" => "Cable & Wireless Panama, S.A."),
    "350" => array ( "Area" => "Panama Oeste", "Operator" => "Cable Onda, S.A."),
    "349" => array ( "Area" => "Panama Oeste", "Operator" => "Cable Onda, S.A."),
    "348" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "347" => array ( "Area" => "Panama Oeste", "Operator" => "Telefónica Móviles Panamá, S.A."),
    "346" => array ( "Area" => "Panama Oeste", "Operator" => "Cable & Wireless Panama, S.A."),
    "345" => array ( "Area" => "Panama Oeste", "Operator" => "Cable Onda, S.A."),
    "344" => array ( "Area" => "Panama Oeste", "Operator" => "Cable Onda, S.A."),
    "343" => array ( "Area" => "Panama Oeste", "Operator" => "Cable Onda, S.A."),
    "342" => array ( "Area" => "Panama Oeste", "Operator" => "Cable Onda, S.A."),
    "341" => array ( "Area" => "Panama Oeste", "Operator" => "Cable Onda, S.A."),
    "340" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "339" => array ( "Area" => "Panama", "Operator" => ""),
    "338" => array ( "Area" => "Panama", "Operator" => ""),
    "337" => array ( "Area" => "Panama", "Operator" => ""),
    "336" => array ( "Area" => "Panama", "Operator" => ""),
    "335" => array ( "Area" => "Panama", "Operator" => ""),
    "334" => array ( "Area" => "Panama", "Operator" => ""),
    "333" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "332" => array ( "Area" => "Panama", "Operator" => ""),
    "331" => array ( "Area" => "Panama", "Operator" => ""),
    "330" => array ( "Area" => "Panama", "Operator" => ""),
    "329" => array ( "Area" => "Panama", "Operator" => ""),
    "328" => array ( "Area" => "Panama", "Operator" => ""),
    "327" => array ( "Area" => "Panama", "Operator" => ""),
    "326" => array ( "Area" => "Panama", "Operator" => ""),
    "325" => array ( "Area" => "Panama", "Operator" => "Interfast Panamá, S.A."),
    "324" => array ( "Area" => "Panama", "Operator" => ""),
    "323" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "322" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "321" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "320" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "319" => array ( "Area" => "Panama", "Operator" => ""),
    "318" => array ( "Area" => "Panama", "Operator" => ""),
    "317" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "316" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "315" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "314" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "313" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "312" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "311" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "310" => array ( "Area" => "Panama", "Operator" => "Vozelia, S.A."),
    "299" => array ( "Area" => "Darién & Kuna Yala", "Operator" => "Cable & Wireless Panama, S.A."),
    "298" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "297" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "296" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "295" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "294" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "293" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "292" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "291" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "290" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "289" => array ( "Area" => "Darién & Guna Yala", "Operator" => ""),
    "286" => array ( "Area" => "Darién", "Operator" => "Cable & Wireless Panama, S.A."),
    "285" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "284" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "283" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "282" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "281" => array ( "Area" => "Panama", "Operator" => ""),
    "280" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "279" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "278" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "277" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "276" => array ( "Area" => "Panama", "Operator" => "ACP"),
    "275" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "274" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "273" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "272" => array ( "Area" => "Panama", "Operator" => "ACP"),
    "271" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "270" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "259" => array ( "Area" => "Panama Oeste", "Operator" => "Cable & Wireless Panama, S.A."),
    "258" => array ( "Area" => "Panama Oeste", "Operator" => "Cable Onda, S.A."),
    "257" => array ( "Area" => "Panama Oeste", "Operator" => "Cable & Wireless Panama, S.A."),
    "256" => array ( "Area" => "Panama Oeste", "Operator" => "Cable & Wireless Panama, S.A."),
    "255" => array ( "Area" => "Panama Oeste", "Operator" => "Cable & Wireless Panama, S.A."),
    "254" => array ( "Area" => "Panama Oeste", "Operator" => "Cable & Wireless Panama, S.A."),
    "253" => array ( "Area" => "Panama Oeste", "Operator" => "Cable & Wireless Panama, S.A."),
    "252" => array ( "Area" => "Panama Oeste", "Operator" => "Cable & Wireless Panama, S.A."),
    "251" => array ( "Area" => "Panama Oeste", "Operator" => "Cable & Wireless Panama, S.A."),
    "250" => array ( "Area" => "Panama Oeste", "Operator" => "Cable & Wireless Panama, S.A."),
    "248" => array ( "Area" => "Panama Oeste", "Operator" => "Cable & Wireless Panama, S.A."),
    "247" => array ( "Area" => "Panama Oeste", "Operator" => "Cable Onda, S.A."),
    "245" => array ( "Area" => "Panama Oeste", "Operator" => "Cable & Wireless Panama, S.A."),
    "244" => array ( "Area" => "Panama Oeste", "Operator" => "Cable & Wireless Panama, S.A."),
    "243" => array ( "Area" => "Panama Oeste", "Operator" => "Claro Panamá, S.A."),
    "242" => array ( "Area" => "Panama Oeste", "Operator" => ""),
    "240" => array ( "Area" => "Panama Oeste", "Operator" => "Cable & Wireless Panama, S.A."),
    "217" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "216" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "215" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "214" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "213" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "212" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "211" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "210" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "209" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "208" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "207" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "206" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "205" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "204" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "203" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "202" => array ( "Area" => "Panama", "Operator" => "Galaxy Communication, Corp."),
    "201" => array ( "Area" => "Panama", "Operator" => "Galaxy Communication, Corp."),
    "200" => array ( "Area" => "Panama", "Operator" => "Galaxy Communication, Corp."),
    "86" => array ( "Area" => "", "Operator" => ""),
    "71" => array ( "Area" => "Chiriquí", "Operator" => ""),
    "59" => array ( "Area" => "Panama", "Operator" => ""),
    "58" => array ( "Area" => "Panama", "Operator" => ""),
    "54" => array ( "Area" => "Panama", "Operator" => ""),
    "51" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "50" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "49" => array ( "Area" => "Panama", "Operator" => ""),
    "48" => array ( "Area" => "Panama", "Operator" => ""),
    "45" => array ( "Area" => "Panama", "Operator" => ""),
    "42" => array ( "Area" => "Panama", "Operator" => ""),
    "41" => array ( "Area" => "Panama", "Operator" => ""),
    "39" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "30" => array ( "Area" => "Panama", "Operator" => "Cable Onda, S.A."),
    "26" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "23" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
    "22" => array ( "Area" => "Panama", "Operator" => "Cable & Wireless Panama, S.A."),
  );
  foreach ( $prefixes as $prefix => $data)
  {
    if ( strlen ( $parameters["Number"]) == 11 && (int) substr ( $parameters["Number"], 4, strlen ( $prefix)) == $prefix)
    {
      return array_merge_recursive ( ( is_array ( $buffer) ? $buffer : array ()), array ( "CC" => "507", "NDC" => substr ( $parameters["Number"], 4, 3), "Country" => "Panama", "Area" => $data["Area"], "City" => "", "Operator" => $data["Operator"], "SN" => substr ( $parameters["Number"], 7), "Type" => VD_PHONETYPE_LANDLINE, "CallFormats" => array ( "Local" => substr ( $parameters["Number"], 4, 3) . " " . substr ( $parameters["Number"], 7), "International" => "+507 " . substr ( $parameters["Number"], 4, 3) . " " . substr ( $parameters["Number"], 7))));
    }
  }

  /**
   * Check for PRN network with 3 digits NDC and 4 digits SN
   */
  $prefixes = array (
    "8789" => "",
    "8788" => "",
    "8787" => "",
    "8786" => "",
    "8785" => "",
    "8784" => "",
    "8783" => "",
    "8782" => "",
    "8781" => "",
    "8780" => "Cable Onda, S.A.",
    "8779" => "",
    "8778" => "",
    "8777" => "",
    "8776" => "",
    "8775" => "",
    "8774" => "",
    "8773" => "",
    "8772" => "",
    "8771" => "",
    "8770" => "Cable Onda, S.A.",
    "8229" => "",
    "8228" => "",
    "8227" => "",
    "8226" => "",
    "8225" => "",
    "8224" => "",
    "8223" => "",
    "8222" => "",
    "8221" => "",
    "8220" => "Digicel (Panama), S.A.",
    "981" => "",
    "904" => "",
    "903" => "",
    "902" => "",
    "901" => "",
    "900" => "Cable & Wireless Panama, S.A.",
    "895" => "",
    "889" => "",
    "887" => "",
    "886" => "Mobil Red Inc.",
    "879" => "",
    "876" => "",
    "875" => "",
    "874" => "",
    "871" => "",
    "870" => "",
    "860" => "Cable & Wireless Panama, S.A.",
    "855" => "Cable & Wireless Panama, S.A.",
    "826" => "",
    "825" => "",
    "824" => "",
    "823" => "",
    "821" => "",
    "820" => "",
  );
  foreach ( $prefixes as $prefix => $operator)
  {
    if ( strlen ( $parameters["Number"]) == 11 && (int) substr ( $parameters["Number"], 4, strlen ( $prefix)) == $prefix)
    {
      return array_merge_recursive ( ( is_array ( $buffer) ? $buffer : array ()), array ( "CC" => "507", "NDC" => substr ( $parameters["Number"], 4, 3), "Country" => "Panama", "Area" => "", "City" => "", "Operator" => $operator, "SN" => substr ( $parameters["Number"], 7), "Type" => VD_PHONETYPE_PRN, "CallFormats" => array ( "Local" => substr ( $parameters["Number"], 4, 3) . " " . substr ( $parameters["Number"], 7), "International" => "+507 " . substr ( $parameters["Number"], 4, 3) . " " . substr ( $parameters["Number"], 7))));
    }
  }

  /**
   * If reached here, number wasn't identified as a valid Pananemian phone number
   */
  return ( is_array ( $buffer) ? $buffer : false);
}
?>
