<?php
/**   ___ ___       ___ _______     ______                        __
 *   |   Y   .-----|   |   _   |   |   _  \ .-----.--------.---.-|__.-----.
 *   |.  |   |  _  |.  |.  1   |   |.  |   \|  _  |        |  _  |  |     |
 *   |.  |   |_____|.  |.  ____|   |.  |    |_____|__|__|__|___._|__|__|__|
 *   |:  1   |     |:  |:  |       |:  1    /
 *    \:.. ./      |::.|::.|       |::.. . /
 *     `---'       `---`---'       `------'
 *
 * Copyright (C) 2016-2025 Ernani José Camargo Azevedo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * VoIP Domain country database module filters. This module add the filter calls
 * related to country database of Bangladesh.
 *
 * Reference: https://www.itu.int/oth/T0202000012/en (2007-04-29)
 *
 * Note: This country ITU-T paper has a lot of flaws. Probably will fail on a
 *       large number of valid numbers. If you've better information, please
 *       fix this file and submit to repository.
 *
 * Glossary:
 *  CC - Country Code
 *  NDC - National Destination Code (also known as area code)
 *  N(S)N - National (Significant) Number
 *  SN - Subscriber Number
 *
 * @author     Ernani José Camargo Azevedo <azevedo@voipdomain.io>
 * @version    1.0
 * @package    VoIP Domain
 * @subpackage CountryDB
 * @copyright  2016-2025 Ernani José Camargo Azevedo. All rights reserved.
 * @license    https://www.gnu.org/licenses/gpl-3.0.en.html
 */

/**
 * E.164 Bangladesh country hook
 */
framework_add_filter ( "e164_identify_country_BGD", "e164_identify_country_BGD");

/**
 * E.164 Bangladeshian area number identification hook. This hook is an
 * e164_identify sub hook, called when the ISO3166 Alpha3 are "BGD" (code for
 * Bangladesh). This hook will verify if phone number is valid, returning the area
 * code, area name, phone number, others number related information and if
 * possible, the number type (mobile, landline, Premium Rate Number, etc).
 *
 * @param string $buffer Buffer from plugin system if processed by other function
 *                       before
 * @param array $parameters Parameters to the function. Number provided as
 *                          $parameters["Number"]
 * @return array Array contaning many information about the requested number
 */
function e164_identify_country_BGD ( $buffer, $parameters)
{
  /**
   * Check if number country code is from Bangladesh
   */
  if ( substr ( $parameters["Number"], 0, 4) != "+880")
  {
    return ( is_array ( $buffer) ? $buffer : false);
  }

  /**
   * Check for mobile network with 2 digits NDC and 8 digits SN
   */
  $prefixes = array (
    "19" => "Sheba Mobile",
    "18" => "TMIB Mobile",
    "17" => "Grameen Phones Mobile",
    "16" => "Warid Telecom International LLC.",
    "15" => "TELETALK Mobile",
    "14" => "BBTT",
    "13" => "BTL",
    "11" => "PBTL Mobile"
  );
  foreach ( $prefixes as $prefix => $operator)
  {
    if ( (int) substr ( $parameters["Number"], 4, strlen ( $prefix)) == $prefix)
    {
      if ( strlen ( $parameters["Number"]) != 14)
      {
        return ( is_array ( $buffer) ? $buffer : false);
      }
      return array_merge_recursive ( ( is_array ( $buffer) ? $buffer : array ()), array ( "CC" => "880", "NDC" => substr ( $parameters["Number"], 4, 2), "Country" => "Bangladesh", "Area" => "", "City" => "", "Operator" => $operator, "SN" => substr ( $parameters["Number"], 6), "Type" => VD_PHONETYPE_MOBILE, "CallFormats" => array ( "Local" => substr ( $parameters["Number"], 4, 2) . " " . substr ( $parameters["Number"], 6, 4) . " " . substr ( $parameters["Number"], 10), "International" => "+880 " . substr ( $parameters["Number"], 4, 2) . " " . substr ( $parameters["Number"], 6, 4) . " " . substr ( $parameters["Number"], 10))));
    }
  }

  /**
   * Check for fixed line network
   */
  $prefixes = array (
    "46" => "Bashundhara Communication & Networks Ltd.",
    "45" => "Dominox Technologies Ltd.",
    "44" => "Ranks Telecom Ltd.",
    "43" => "Dhaka Telephone Company Ltd.",
    "42" => "Integrated Service Ltd.",
    "41" => "Nextel Telecom Ltd.",
    "40" => "Jalalabad Telecom Ltd.",
    "39" => "S.A. Telecom System Ltd.",
    "38" => "Peoples Telecommunication et Information Service Ltd.",
    "37" => "National Telecom Ltd.",
    "36" => "Tele Barta Ltd.",
    "35" => "Bangla Phone Ltd.",
    "34" => "GEP Telecom Ltd.",
    "33" => "One Tel Communication Ltd.",
    "32" => "Square Informatix Ltd.",
    "31" => "Westec Ltd.",
    "30" => "Worldtel",
    "2" => "Bangladesh Telegraph and Telephone Board"
  );
  foreach ( $prefixes as $prefix => $operator)
  {
    if ( (int) substr ( $parameters["Number"], 4, strlen ( $prefix)) == $prefix)
    {
      /**
       * Get area of line
       */
      $areas = array (
        "982756" => array ( "area" => "Jamalpur", "city" => "Sarishabari", "digits" => 5),
        "952956" => array ( "area" => "Netrokona", "city" => "Madan", "digits" => 5),
        "952856" => array ( "area" => "Netrokona", "city" => "Kendua", "digits" => 5),
        "952556" => array ( "area" => "Netrokona", "city" => "Durgapur", "digits" => 5),
        "952456" => array ( "area" => "Netrokona", "city" => "Mohanganj", "digits" => 5),
        "942656" => array ( "area" => "Kishoreganj", "city" => "Itna", "digits" => 5),
        "923373" => array ( "area" => "Tangail", "city" => "Nagarpur", "digits" => 5),
        "923256" => array ( "area" => "Tangail", "city" => "Shakhipur", "digits" => 5),
        "922856" => array ( "area" => "Tangail", "city" => "Modhupur", "digits" => 5),
        "922774" => array ( "area" => "Tangail", "city" => "Kalihati", "digits" => 5),
        "922556" => array ( "area" => "Tangail", "city" => "Ghatail", "digits" => 5),
        "922256" => array ( "area" => "Tangail", "city" => "Bashail", "digits" => 5),
        "903356" => array ( "area" => "Mymensingh", "city" => "Phulpur", "digits" => 5),
        "903256" => array ( "area" => "Mymensingh", "city" => "Trisal", "digits" => 5),
        "902756" => array ( "area" => "Mymensingh", "city" => "Iswarganj", "digits" => 5),
        "902556" => array ( "area" => "Mymensingh", "city" => "Gafargaon", "digits" => 5),
        "902256" => array ( "area" => "Mymensingh", "city" => "Bhaluka", "digits" => 5),
        "872756" => array ( "area" => "Sunamganj", "city" => "Jaganathpur", "digits" => 5),
        "872575" => array ( "area" => "Sunamganj", "city" => "Dharmapasha", "digits" => 5),
        "872356" => array ( "area" => "Sunamganj", "city" => "Chattak", "digits" => 5),
        "862456" => array ( "area" => "Maulavibazar", "city" => "Kulaura", "digits" => 5),
        "862256" => array ( "area" => "Maulavibazar", "city" => "Baralekha", "digits" => 5),
        "852473" => array ( "area" => "Brahmanbaria", "city" => "Kashba", "digits" => 5),
        "852356" => array ( "area" => "Brahmanbaria", "city" => "Bancharampur", "digits" => 5),
        "852256" => array ( "area" => "Brahmanbaria", "city" => "Akhaura", "digits" => 5),
        "842756" => array ( "area" => "Chandpur", "city" => "Shaharasti", "digits" => 5),
        "842656" => array ( "area" => "Chandpur", "city" => "Matlab", "digits" => 5),
        "842556" => array ( "area" => "Chandpur", "city" => "Kochua", "digits" => 5),
        "832856" => array ( "area" => "Habiganj", "city" => "Nabiganj", "digits" => 5),
        "823256" => array ( "area" => "Sylhet", "city" => "Jokiganj", "digits" => 5),
        "822956" => array ( "area" => "Sylhet", "city" => "Jaintapur", "digits" => 5),
        "822556" => array ( "area" => "Sylhet", "city" => "Companiganj", "digits" => 5),
        "802956" => array ( "area" => "Comilla", "city" => "Burichang", "digits" => 5),
        "802656" => array ( "area" => "Comilla", "city" => "Muradnagar", "digits" => 5),
        "802256" => array ( "area" => "Comilla", "city" => "Chandina", "digits" => 5),
        "802056" => array ( "area" => "Comilla", "city" => "Chauddagram", "digits" => 5),
        "792374" => array ( "area" => "Meherpur", "city" => "Mujibnagar", "digits" => 5),
        "772474" => array ( "area" => "Natore", "city" => "Gurudashpur", "digits" => 5),
        "752956" => array ( "area" => "Sirajganj", "city" => "Ullapara", "digits" => 5),
        "752856" => array ( "area" => "Sirajganj", "city" => "Tarash", "digits" => 5),
        "752656" => array ( "area" => "Sirajganj", "city" => "Raiganj", "digits" => 5),
        "752556" => array ( "area" => "Sirajganj", "city" => "Kazipur", "digits" => 5),
        "752256" => array ( "area" => "Sirajganj", "city" => "Belkuchi", "digits" => 5),
        "742675" => array ( "area" => "Nagoan", "city" => "Mohadevpur", "digits" => 5),
        "732956" => array ( "area" => "Pabna", "city" => "Sujanagar", "digits" => 5),
        "732756" => array ( "area" => "Pabna", "city" => "Shathiya", "digits" => 5),
        "732663" => array ( "area" => "Pabna", "city" => "Ishwardi", "digits" => 5),
        "732456" => array ( "area" => "Pabna", "city" => "Chatmohar", "digits" => 5),
        "722956" => array ( "area" => "Rajshahi", "city" => "Tanore", "digits" => 5),
        "722856" => array ( "area" => "Rajshahi", "city" => "Putia", "digits" => 5),
        "722556" => array ( "area" => "Rajshahi", "city" => "Godagari", "digits" => 5),
        "692356" => array ( "area" => "Munsigonj", "city" => "Lohajang", "digits" => 5),
        "682552" => array ( "area" => "Gazipur", "city" => "Sreepur", "digits" => 5),
        "682551" => array ( "area" => "Gazipur", "city" => "Sreepur", "digits" => 5),
        "682451" => array ( "area" => "Gazipur", "city" => "Kapashia", "digits" => 5),
        "682351" => array ( "area" => "Gazipur", "city" => "Kaliganj", "digits" => 5),
        "682251" => array ( "area" => "Gazipur", "city" => "Kaliakoir", "digits" => 5),
        "672556" => array ( "area" => "Narayanganj", "city" => "Rupganj", "digits" => 5),
        "672256" => array ( "area" => "Narayanganj", "city" => "Araihazar", "digits" => 5),
        "665559" => array ( "area" => "Gopalgonj", "city" => "Tungipara", "digits" => 5),
        "665556" => array ( "area" => "Gopalgonj", "city" => "Tungipara", "digits" => 5),
        "665456" => array ( "area" => "Gopalgonj", "city" => "Moksudpur", "digits" => 5),
        "665356" => array ( "area" => "Gopalgonj", "city" => "Kotalipara", "digits" => 5),
        "665256" => array ( "area" => "Gopalgonj", "city" => "Kashiani", "digits" => 5),
        "662456" => array ( "area" => "Madaripur", "city" => "Shibchar", "digits" => 5),
        "662356" => array ( "area" => "Madaripur", "city" => "Rajoir", "digits" => 5),
        "642475" => array ( "area" => "Rajbari", "city" => "Pangsha", "digits" => 5),
        "642356" => array ( "area" => "Rajbari", "city" => "Goalanda", "digits" => 5),
        "632875" => array ( "area" => "Faridpur", "city" => "Sadarpur (J.Monjil)", "digits" => 5),
        "632756" => array ( "area" => "Faridpur", "city" => "Nagarkanda", "digits" => 5),
        "632456" => array ( "area" => "Faridpur", "city" => "Boalmari", "digits" => 5),
        "632356" => array ( "area" => "Faridpur", "city" => "Bhanga", "digits" => 5),
        "625556" => array ( "area" => "Narsingdi", "city" => "Raipura", "digits" => 5),
        "625356" => array ( "area" => "Narsingdi", "city" => "Monahardi", "digits" => 5),
        "602475" => array ( "area" => "Shariatpur", "city" => "GoshairHat", "digits" => 5),
        "602356" => array ( "area" => "Shariatpur", "city" => "Damudda", "digits" => 5),
        "565356" => array ( "area" => "Panchagar", "city" => "Boda", "digits" => 5),
        "542656" => array ( "area" => "Gaibandha", "city" => "Saghata (Bonarpara)", "digits" => 5),
        "532656" => array ( "area" => "Dianjpur", "city" => "Chrirbandar", "digits" => 5),
        "522556" => array ( "area" => "Rangpur", "city" => "Mithapukur", "digits" => 5),
        "502856" => array ( "area" => "Bogra", "city" => "Shariakandi", "digits" => 5),
        "502356" => array ( "area" => "Bogra", "city" => "Dhunat", "digits" => 5),
        "495374" => array ( "area" => "Jhalakati", "city" => "Nalcity", "digits" => 5),
        "492575" => array ( "area" => "Bhola", "city" => "Lalmohan", "digits" => 5),
        "492456" => array ( "area" => "Bhola", "city" => "Daulatkhan", "digits" => 5),
        "492256" => array ( "area" => "Bhola", "city" => "Borhanuddin", "digits" => 5),
        "485456" => array ( "area" => "Magura", "city" => "Sreepur", "digits" => 5),
        "482356" => array ( "area" => "Narail", "city" => "Lohagara", "digits" => 5),
        "465756" => array ( "area" => "Bagerhat", "city" => "Rampal", "digits" => 5),
        "465656" => array ( "area" => "Bagerhat", "city" => "Morelganj", "digits" => 5),
        "465556" => array ( "area" => "Bagerhat", "city" => "Mollarhat", "digits" => 5),
        "462674" => array ( "area" => "Pirojpur", "city" => "Nazirpur", "digits" => 5),
        "462575" => array ( "area" => "Pirojpur", "city" => "Mothbaria", "digits" => 5),
        "462456" => array ( "area" => "Pirojpur", "city" => "Kaokhali", "digits" => 5),
        "445575" => array ( "area" => "Barguna", "city" => "Pathorghata", "digits" => 5),
        "442675" => array ( "area" => "Patuakhali", "city" => "Mirjagonj (RSU)", "digits" => 5),
        "442456" => array ( "area" => "Patuakhali", "city" => "Golachipa", "digits" => 5),
        "442356" => array ( "area" => "Patuakhali", "city" => "Dashmina", "digits" => 5),
        "442256" => array ( "area" => "Patuakhali", "city" => "Baufal", "digits" => 5),
        "433256" => array ( "area" => "Barisal", "city" => "Banaripara", "digits" => 5),
        "432874" => array ( "area" => "Barisal", "city" => "Bakergonj", "digits" => 5),
        "432773" => array ( "area" => "Barisal", "city" => "Babugonj", "digits" => 5),
        "432675" => array ( "area" => "Barisal", "city" => "Muladi", "digits" => 5),
        "432356" => array ( "area" => "Barisal", "city" => "Agailjhara", "digits" => 5),
        "432256" => array ( "area" => "Barisal", "city" => "Goarnadi", "digits" => 5),
        "422778" => array ( "area" => "Jessore", "city" => "Manirampur", "digits" => 5),
        "422656" => array ( "area" => "Jessore", "city" => "Keshobpur", "digits" => 5),
        "403356" => array ( "area" => "Khulna", "city" => "Dighalia RSU", "digits" => 5),
        "382256" => array ( "area" => "Laximpur", "city" => "Raipura", "digits" => 5),
        "342556" => array ( "area" => "Cox'sbazar", "city" => "Ramu", "digits" => 5),
        "342256" => array ( "area" => "Cox'sbazar", "city" => "Chokoria", "digits" => 5),
        "332456" => array ( "area" => "Feni", "city" => "Parshuram", "digits" => 5),
        "322556" => array ( "area" => "Noakhali", "city" => "Shenbag", "digits" => 5),
        "322356" => array ( "area" => "Noakhali", "city" => "Companiganj (B.Hat)", "digits" => 5),
        "302856" => array ( "area" => "Chittagong", "city" => "Barabkunda", "digits" => 5),
        "302456" => array ( "area" => "Chittagong", "city" => "Mirsharai", "digits" => 5),
        "302356" => array ( "area" => "Chittagong", "city" => "Hathazari", "digits" => 5),
        "98278" => array ( "area" => "Sarishabari", "city" => "Sarishabari", "digits" => 5),
        "98248" => array ( "area" => "Islampur", "city" => "Islampur", "digits" => 5),
        "98189" => array ( "area" => "Jamalpur", "city" => "Jamalpur", "digits" => 5),
        "98175" => array ( "area" => "Jamalpur", "city" => "Dewanganj", "digits" => 5),
        "98174" => array ( "area" => "Jamalpur", "city" => "Islampur", "digits" => 5),
        "98165" => array ( "area" => "Jamalpur", "city" => "Jamalpur", "digits" => 5),
        "98164" => array ( "area" => "Jamalpur", "city" => "Jamalpur", "digits" => 5),
        "98163" => array ( "area" => "Jamalpur", "city" => "Jamalpur", "digits" => 5),
        "98162" => array ( "area" => "Jamalpur", "city" => "Jamalpur", "digits" => 5),
        "95189" => array ( "area" => "Netrokona", "city" => "Netrokona", "digits" => 5),
        "95162" => array ( "area" => "Netrokona", "city" => "Netrokona", "digits" => 5),
        "95161" => array ( "area" => "Netrokona", "city" => "Netrokona", "digits" => 5),
        "94288" => array ( "area" => "Kotiadhi", "city" => "Kotiadhi", "digits" => 5),
        "94249" => array ( "area" => "Kishoreganj", "city" => "Bhairabbazar", "digits" => 3),
        "94248" => array ( "area" => "Bhairab bazar", "city" => "Bhairab bazar", "digits" => 5),
        "94247" => array ( "area" => "Kishoreganj", "city" => "Bhairabbazar", "digits" => 3),
        "94246" => array ( "area" => "Kishoreganj", "city" => "Bhairabbazar", "digits" => 3),
        "94245" => array ( "area" => "Kishoreganj", "city" => "Bhairabbazar", "digits" => 3),
        "94244" => array ( "area" => "Kishoreganj", "city" => "Bhairabbazar", "digits" => 3),
        "94243" => array ( "area" => "Kishoreganj", "city" => "Bhairabbazar", "digits" => 3),
        "94242" => array ( "area" => "Kishoreganj", "city" => "Bhairabbazar", "digits" => 3),
        "94233" => array ( "area" => "Kishoreganj", "city" => "Bajitpur", "digits" => 3),
        "94232" => array ( "area" => "Kishoreganj", "city" => "Bajitpur", "digits" => 3),
        "94175" => array ( "area" => "Kishoreganj", "city" => "Tarail", "digits" => 5),
        "94162" => array ( "area" => "Kishoreganj", "city" => "Kishoreganj", "digits" => 5),
        "94161" => array ( "area" => "Kishoreganj", "city" => "Kishoreganj", "digits" => 5),
        "94156" => array ( "area" => "Kishoreganj", "city" => "Kishoreganj", "digits" => 5),
        "94155" => array ( "area" => "Kishoreganj", "city" => "Kishoreganj", "digits" => 5),
        "93189" => array ( "area" => "Sherpur", "city" => "Sherpur", "digits" => 5),
        "93175" => array ( "area" => "Sherpur", "city" => "Nakla", "digits" => 5),
        "93173" => array ( "area" => "Sherpur", "city" => "Nalitabari", "digits" => 5),
        "93161" => array ( "area" => "Sherpur", "city" => "Sherpur", "digits" => 5),
        "92328" => array ( "area" => "Shakhipur", "city" => "Shakhipur", "digits" => 5),
        "92298" => array ( "area" => "Mirzapur", "city" => "Mirzapur", "digits" => 5),
        "92288" => array ( "area" => "Modhupur", "city" => "Modhupur", "digits" => 5),
        "92278" => array ( "area" => "Elenga/Kalihati", "city" => "Elenga/Kalihati", "digits" => 5),
        "92268" => array ( "area" => "Gopalpur", "city" => "Gopalpur", "digits" => 5),
        "92258" => array ( "area" => "Ghatail", "city" => "Ghatail", "digits" => 5),
        "92238" => array ( "area" => "Bhuapur", "city" => "Bhuapur", "digits" => 5),
        "92162" => array ( "area" => "Tangail", "city" => "Tangail", "digits" => 5),
        "92161" => array ( "area" => "Tangail", "city" => "Tangail", "digits" => 5),
        "92158" => array ( "area" => "Tangail", "city" => "Tangail", "digits" => 5),
        "92155" => array ( "area" => "Tangail", "city" => "Tangail", "digits" => 5),
        "92154" => array ( "area" => "Tangail", "city" => "Tangail", "digits" => 5),
        "92153" => array ( "area" => "Tangail", "city" => "Tangail", "digits" => 5),
        "90288" => array ( "area" => "Muktagacha", "city" => "Muktagacha", "digits" => 5),
        "90278" => array ( "area" => "Ishwargonj", "city" => "Ishwargonj", "digits" => 5),
        "90258" => array ( "area" => "Goforgaon", "city" => "Goforgaon", "digits" => 5),
        "90248" => array ( "area" => "Gouripur", "city" => "Gouripur", "digits" => 5),
        "90208" => array ( "area" => "Phulpur", "city" => "Phulpur", "digits" => 5),
        "87278" => array ( "area" => "Jagonnathpur", "city" => "Jagonnathpur", "digits" => 5),
        "87238" => array ( "area" => "Chatak", "city" => "Chatak", "digits" => 5),
        "87163" => array ( "area" => "Sunamganj", "city" => "Sunamganj", "digits" => 5),
        "87162" => array ( "area" => "Sunamganj", "city" => "Sunamganj", "digits" => 5),
        "87161" => array ( "area" => "Sunamganj", "city" => "Sunamganj", "digits" => 5),
        "87156" => array ( "area" => "Sunamganj", "city" => "Sunamganj", "digits" => 5),
        "87155" => array ( "area" => "Sunamganj", "city" => "Sunamganj", "digits" => 5),
        "86269" => array ( "area" => "Maulavibazar", "city" => "Sreemongal", "digits" => 3),
        "86268" => array ( "area" => "Srimongal", "city" => "Srimongal", "digits" => 5),
        "86267" => array ( "area" => "Maulavibazar", "city" => "Sreemongal", "digits" => 3),
        "86266" => array ( "area" => "Maulavibazar", "city" => "Sreemongal", "digits" => 3),
        "86265" => array ( "area" => "Maulavibazar", "city" => "Sreemongal", "digits" => 3),
        "86264" => array ( "area" => "Maulavibazar", "city" => "Sreemongal", "digits" => 3),
        "86263" => array ( "area" => "Maulavibazar", "city" => "Sreemongal", "digits" => 3),
        "86262" => array ( "area" => "Maulavibazar", "city" => "Sreemongal", "digits" => 3),
        "86258" => array ( "area" => "Rajnagar", "city" => "Rajnagar", "digits" => 5),
        "86248" => array ( "area" => "Kulaura", "city" => "Kulaura", "digits" => 5),
        "86238" => array ( "area" => "Komalgonj", "city" => "Komalgonj", "digits" => 5),
        "86228" => array ( "area" => "Baralekha", "city" => "Baralekha", "digits" => 5),
        "86189" => array ( "area" => "Maulavibazar", "city" => "Maulavibazar", "digits" => 5),
        "86175" => array ( "area" => "Maulavibazar", "city" => "Rajnagar", "digits" => 5),
        "86161" => array ( "area" => "Maulavibazar", "city" => "Maulavibazar", "digits" => 5),
        "86154" => array ( "area" => "Maulavibazar", "city" => "Maulavibazar", "digits" => 5),
        "86153" => array ( "area" => "Maulavibazar", "city" => "Maulavibazar", "digits" => 5),
        "86152" => array ( "area" => "Maulavibazar", "city" => "Maulavibazar", "digits" => 5),
        "85288" => array ( "area" => "Brahmanbaria", "city" => "Ashuganj", "digits" => 3),
        "85287" => array ( "area" => "Brahmanbaria", "city" => "Ashuganj", "digits" => 3),
        "85286" => array ( "area" => "Brahmanbaria", "city" => "Ashuganj", "digits" => 3),
        "85285" => array ( "area" => "Brahmanbaria", "city" => "Ashuganj", "digits" => 3),
        "85284" => array ( "area" => "Brahmanbaria", "city" => "Ashuganj", "digits" => 3),
        "85283" => array ( "area" => "Brahmanbaria", "city" => "Ashuganj", "digits" => 3),
        "85282" => array ( "area" => "Brahmanbaria", "city" => "Ashuganj", "digits" => 3),
        "85278" => array ( "area" => "Brahmanbaria", "city" => "Sarail", "digits" => 4),
        "85268" => array ( "area" => "Brahmanbaria", "city" => "Nasirnagar", "digits" => 4),
        "85258" => array ( "area" => "Brahmanbaria", "city" => "Nabinagar", "digits" => 4),
        "85248" => array ( "area" => "Brahmanbaria", "city" => "Quashba", "digits" => 4),
        "85238" => array ( "area" => "Brahmanbaria", "city" => "Bancharampur", "digits" => 4),
        "85228" => array ( "area" => "Brahmanbaria", "city" => "Akhaura", "digits" => 4),
        "85175" => array ( "area" => "Brahmanbaria", "city" => "Nabinagar", "digits" => 5),
        "85163" => array ( "area" => "Brahmanbaria", "city" => "Brahmanbaria", "digits" => 5),
        "85162" => array ( "area" => "Brahmanbaria", "city" => "Brahmanbaria", "digits" => 5),
        "85161" => array ( "area" => "Brahmanbaria", "city" => "Brahmanbaria", "digits" => 5),
        "85154" => array ( "area" => "Brahmanbaria", "city" => "Brahmanbaria", "digits" => 5),
        "85153" => array ( "area" => "Brahmanbaria", "city" => "Brahmanbaria", "digits" => 5),
        "85152" => array ( "area" => "Brahmanbaria", "city" => "Brahmanbaria", "digits" => 5),
        "84278" => array ( "area" => "Chandpur", "city" => "Shahrasti", "digits" => 4),
        "84268" => array ( "area" => "Chandpur", "city" => "Matlab", "digits" => 4),
        "84258" => array ( "area" => "Chandpur", "city" => "Kachua", "digits" => 4),
        "84248" => array ( "area" => "Chandpur", "city" => "Hajigonj", "digits" => 4),
        "84245" => array ( "area" => "Chandpur", "city" => "Hajiganj", "digits" => 3),
        "84244" => array ( "area" => "Chandpur", "city" => "Hajiganj", "digits" => 3),
        "84243" => array ( "area" => "Chandpur", "city" => "Hajiganj", "digits" => 3),
        "84242" => array ( "area" => "Chandpur", "city" => "Hajiganj", "digits" => 3),
        "84165" => array ( "area" => "Chandpur", "city" => "Chandpur", "digits" => 5),
        "84164" => array ( "area" => "Chandpur", "city" => "Chandpur", "digits" => 5),
        "84163" => array ( "area" => "Chandpur", "city" => "Chandpur", "digits" => 5),
        "83329" => array ( "area" => "Habiganj", "city" => "Sayestaganj", "digits" => 3),
        "83328" => array ( "area" => "Habiganj", "city" => "Sayestaganj", "digits" => 3),
        "83327" => array ( "area" => "Habiganj", "city" => "Sayestaganj", "digits" => 3),
        "83326" => array ( "area" => "Habiganj", "city" => "Sayestaganj", "digits" => 3),
        "83288" => array ( "area" => "Nabigonj", "city" => "Nabigonj", "digits" => 5),
        "83278" => array ( "area" => "Madabpur", "city" => "Madabpur", "digits" => 5),
        "83258" => array ( "area" => "Chunarughat", "city" => "Chunarughat", "digits" => 5),
        "83163" => array ( "area" => "Habiganj", "city" => "Habiganj", "digits" => 5),
        "83162" => array ( "area" => "Habiganj", "city" => "Habiganj", "digits" => 5),
        "83161" => array ( "area" => "Habiganj", "city" => "Habiganj", "digits" => 5),
        "83153" => array ( "area" => "Habiganj", "city" => "Habiganj", "digits" => 5),
        "83152" => array ( "area" => "Habiganj", "city" => "Habiganj", "digits" => 5),
        "82298" => array ( "area" => "Jaintapur", "city" => "Jaintapur", "digits" => 5),
        "82278" => array ( "area" => "Golapgonj", "city" => "Golapgonj", "digits" => 5),
        "82268" => array ( "area" => "Fenchugonj", "city" => "Fenchugonj", "digits" => 5),
        "82248" => array ( "area" => "Biswanath", "city" => "Biswanath", "digits" => 5),
        "82238" => array ( "area" => "Bianibazar", "city" => "Bianibazar", "digits" => 5),
        "82228" => array ( "area" => "Balagonj", "city" => "Balagonj", "digits" => 5),
        "82208" => array ( "area" => "Kanaighat", "city" => "Kanaighat", "digits" => 5),
        "82181" => array ( "area" => "Sylhet", "city" => "Sylhet MEA", "digits" => 6),
        "82176" => array ( "area" => "Sylhet", "city" => "Sylhet MEA", "digits" => 6),
        "82172" => array ( "area" => "Sylhet", "city" => "Sylhet MEA", "digits" => 6),
        "82171" => array ( "area" => "Sylhet", "city" => "Sylhet MEA", "digits" => 6),
        "80338" => array ( "area" => "Comilla", "city" => "Nangalcoat", "digits" => 4),
        "80328" => array ( "area" => "Comilla", "city" => "Laksham", "digits" => 4),
        "80325" => array ( "area" => "Comilla", "city" => "Laksham", "digits" => 3),
        "80324" => array ( "area" => "Comilla", "city" => "Laksham", "digits" => 3),
        "80323" => array ( "area" => "Comilla", "city" => "Laksham", "digits" => 3),
        "80322" => array ( "area" => "Comilla", "city" => "Laksham", "digits" => 3),
        "80298" => array ( "area" => "Comilla", "city" => "Burichang", "digits" => 4),
        "80288" => array ( "area" => "Comilla", "city" => "Brahmanpara", "digits" => 4),
        "80278" => array ( "area" => "Comilla", "city" => "Barura", "digits" => 4),
        "80268" => array ( "area" => "Comilla", "city" => "Muradnagar", "digits" => 4),
        "80258" => array ( "area" => "Comilla", "city" => "Homna", "digits" => 4),
        "80248" => array ( "area" => "Comilla", "city" => "Debidwar", "digits" => 4),
        "80238" => array ( "area" => "Comilla", "city" => "Daudkandi", "digits" => 4),
        "80234" => array ( "area" => "Comilla", "city" => "Daudkandi", "digits" => 3),
        "80233" => array ( "area" => "Comilla", "city" => "Daudkandi", "digits" => 3),
        "80228" => array ( "area" => "Comilla", "city" => "Chandiana", "digits" => 4),
        "80208" => array ( "area" => "Comilla", "city" => "Chauddagram", "digits" => 4),
        "79163" => array ( "area" => "Meherpur", "city" => "Meherpur", "digits" => 5),
        "79162" => array ( "area" => "Meherpur", "city" => "Meherpur", "digits" => 5),
        "78258" => array ( "area" => "Shibgonj", "city" => "Shibgonj", "digits" => 5),
        "78238" => array ( "area" => "Rohanpur", "city" => "Rohanpur", "digits" => 5),
        "78189" => array ( "area" => "Chapai Nobabganj", "city" => "Chapai Nobabganj", "digits" => 5),
        "78175" => array ( "area" => "Chapai Nobabganj", "city" => "Shibganj", "digits" => 5),
        "78174" => array ( "area" => "Chapai Nobabganj", "city" => "Rahanpur", "digits" => 5),
        "78162" => array ( "area" => "Chapai Nobabganj", "city" => "Chapai Nobabganj", "digits" => 5),
        "78161" => array ( "area" => "Chapai Nobabganj", "city" => "Chapai Nobabganj", "digits" => 5),
        "78160" => array ( "area" => "Chapai Nobabganj", "city" => "Chapai Nobabganj", "digits" => 5),
        "78156" => array ( "area" => "Chapai Nobabganj", "city" => "Chapai Nobabganj", "digits" => 5),
        "78155" => array ( "area" => "Chapai Nobabganj", "city" => "Chapai Nobabganj", "digits" => 5),
        "77189" => array ( "area" => "Natore", "city" => "Natore", "digits" => 5),
        "77175" => array ( "area" => "Natore", "city" => "Lalpur", "digits" => 5),
        "77167" => array ( "area" => "Natore", "city" => "Natore", "digits" => 5),
        "77166" => array ( "area" => "Natore", "city" => "Natore", "digits" => 5),
        "77162" => array ( "area" => "Natore", "city" => "Natore", "digits" => 5),
        "77161" => array ( "area" => "Natore", "city" => "Natore", "digits" => 5),
        "76223" => array ( "area" => "Chuadanga", "city" => "Alamdanga", "digits" => 3),
        "76222" => array ( "area" => "Chuadanga", "city" => "Alamdanga", "digits" => 3),
        "76189" => array ( "area" => "Chuadanga", "city" => "Chuadanga", "digits" => 5),
        "76164" => array ( "area" => "Chuadanga", "city" => "Chuadanga", "digits" => 5),
        "76163" => array ( "area" => "Chuadanga", "city" => "Chuadanga", "digits" => 5),
        "76162" => array ( "area" => "Chuadanga", "city" => "Chuadanga", "digits" => 5),
        "75298" => array ( "area" => "Sirajgonj", "city" => "Ullapara", "digits" => 4),
        "75288" => array ( "area" => "Sirajgonj", "city" => "Tarash", "digits" => 4),
        "75278" => array ( "area" => "Sirajgonj", "city" => "Shajatpur", "digits" => 4),
        "75268" => array ( "area" => "Sirajgonj", "city" => "Raigonj", "digits" => 4),
        "75258" => array ( "area" => "Sirajgonj", "city" => "Kazipur", "digits" => 4),
        "75248" => array ( "area" => "Sirajgonj", "city" => "Kamarkhand", "digits" => 4),
        "75238" => array ( "area" => "Sirajgonj", "city" => "Chouhali", "digits" => 4),
        "75228" => array ( "area" => "Sirajgonj", "city" => "Belkuchi", "digits" => 4),
        "75189" => array ( "area" => "Sirajganj", "city" => "Sirajganj", "digits" => 5),
        "75173" => array ( "area" => "Sirajganj", "city" => "Sirajganj", "digits" => 5),
        "75172" => array ( "area" => "Sirajganj", "city" => "Sirajganj", "digits" => 5),
        "75163" => array ( "area" => "Sirajganj", "city" => "Sirajganj", "digits" => 5),
        "75162" => array ( "area" => "Sirajganj", "city" => "Sirajganj", "digits" => 5),
        "74268" => array ( "area" => "Mahadevpur", "city" => "Mahadevpur", "digits" => 5),
        "74258" => array ( "area" => "Manda", "city" => "Manda", "digits" => 5),
        "74189" => array ( "area" => "Nagoan", "city" => "Nagoan", "digits" => 5),
        "74169" => array ( "area" => "Nagoan", "city" => "Santahar", "digits" => 5),
        "74163" => array ( "area" => "Nagoan", "city" => "Nagoan", "digits" => 5),
        "74162" => array ( "area" => "Nagoan", "city" => "Nagoan", "digits" => 5),
        "74161" => array ( "area" => "Nagoan", "city" => "Nagoan", "digits" => 5),
        "74155" => array ( "area" => "Nagoan", "city" => "Santahar", "digits" => 5),
        "74153" => array ( "area" => "Nagoan", "city" => "Nagoan", "digits" => 5),
        "74152" => array ( "area" => "Nagoan", "city" => "Nagoan", "digits" => 5),
        "73288" => array ( "area" => "Pabna", "city" => "Bhangura", "digits" => 4),
        "73278" => array ( "area" => "Pabna", "city" => "Sathia", "digits" => 4),
        "73258" => array ( "area" => "Pabna", "city" => "Faridpur", "digits" => 4),
        "73248" => array ( "area" => "Pabna", "city" => "Chatmohar", "digits" => 4),
        "73238" => array ( "area" => "Pabna", "city" => "Bera", "digits" => 4),
        "73189" => array ( "area" => "Pabna", "city" => "Pabna", "digits" => 5),
        "73175" => array ( "area" => "Pabna", "city" => "Bera", "digits" => 5),
        "73166" => array ( "area" => "Pabna", "city" => "Pabna", "digits" => 5),
        "73165" => array ( "area" => "Pabna", "city" => "Pabna", "digits" => 5),
        "73164" => array ( "area" => "Pabna", "city" => "Pabna", "digits" => 5),
        "73163" => array ( "area" => "Pabna", "city" => "Pabna", "digits" => 5),
        "73162" => array ( "area" => "Pabna", "city" => "Pabna", "digits" => 5),
        "72298" => array ( "area" => "Tanore", "city" => "Tanore", "digits" => 5),
        "72288" => array ( "area" => "Baneswar", "city" => "Baneswar", "digits" => 5),
        "72278" => array ( "area" => "Paba", "city" => "Paba", "digits" => 5),
        "72258" => array ( "area" => "Godagari", "city" => "Godagari", "digits" => 5),
        "72186" => array ( "area" => "Rajshahi", "city" => "Rajshahi MEA", "digits" => 6),
        "72181" => array ( "area" => "Rajshahi", "city" => "Rajshahi MEA", "digits" => 6),
        "72180" => array ( "area" => "Rajshahi", "city" => "Rajshahi MEA", "digits" => 6),
        "72177" => array ( "area" => "Rajshahi", "city" => "Rajshahi MEA", "digits" => 6),
        "72176" => array ( "area" => "Rajshahi", "city" => "Rajshahi MEA", "digits" => 6),
        "72175" => array ( "area" => "Rajshahi", "city" => "Rajshahi MEA", "digits" => 6),
        "70223" => array ( "area" => "Kushtia", "city" => "Bheramara", "digits" => 3),
        "70222" => array ( "area" => "Kushtia", "city" => "Bheramara", "digits" => 3),
        "69268" => array ( "area" => "Tongibari", "city" => "Tongibari", "digits" => 5),
        "69258" => array ( "area" => "Sreenagar", "city" => "Sreenagar", "digits" => 5),
        "69248" => array ( "area" => "Sirajdikhan", "city" => "Sirajdikhan", "digits" => 5),
        "69228" => array ( "area" => "Gazaria", "city" => "Gazaria", "digits" => 5),
        "69189" => array ( "area" => "Munsigonj", "city" => "Munsigonj", "digits" => 5),
        "69174" => array ( "area" => "Munsigonj", "city" => "Tongibari", "digits" => 5),
        "69163" => array ( "area" => "Munsigonj", "city" => "Munsigonj", "digits" => 5),
        "69162" => array ( "area" => "Munsigonj", "city" => "Munsigonj", "digits" => 5),
        "69161" => array ( "area" => "Munsigonj", "city" => "Munsigonj", "digits" => 5),
        "67258" => array ( "area" => "Rupgonj", "city" => "Rupgonj", "digits" => 5),
        "67248" => array ( "area" => "Bandar", "city" => "Bandar", "digits" => 5),
        "67238" => array ( "area" => "Sonargaon", "city" => "Sonargaon", "digits" => 5),
        "67228" => array ( "area" => "Arihazar", "city" => "Arihazar", "digits" => 5),
        "66861" => array ( "area" => "Gopalgonj", "city" => "Gopalgonj", "digits" => 5),
        "66858" => array ( "area" => "Gopalgonj", "city" => "Gopalgonj", "digits" => 5),
        "66857" => array ( "area" => "Gopalgonj", "city" => "Gopalgonj", "digits" => 5),
        "66855" => array ( "area" => "Gopalgonj", "city" => "Gopalgonj", "digits" => 5),
        "66558" => array ( "area" => "Gopalgonj", "city" => "Tongipara", "digits" => 4),
        "66538" => array ( "area" => "Gopalgonj", "city" => "Kotalipara", "digits" => 4),
        "66228" => array ( "area" => "Madaripur", "city" => "Kalkini", "digits" => 4),
        "66162" => array ( "area" => "Madaripur", "city" => "Madaripur", "digits" => 5),
        "66161" => array ( "area" => "Madaripur", "city" => "Madaripur", "digits" => 5),
        "66156" => array ( "area" => "Madaripur", "city" => "Madaripur", "digits" => 5),
        "66155" => array ( "area" => "Madaripur", "city" => "Madaripur", "digits" => 5),
        "65278" => array ( "area" => "Singair", "city" => "Singair", "digits" => 5),
        "65248" => array ( "area" => "Zitka", "city" => "Zitka", "digits" => 5),
        "65189" => array ( "area" => "Maninganj", "city" => "Maninganj", "digits" => 5),
        "65175" => array ( "area" => "Maninganj", "city" => "Shibalaya", "digits" => 5),
        "65174" => array ( "area" => "Maninganj", "city" => "Daulatpur", "digits" => 5),
        "65171" => array ( "area" => "Maninganj", "city" => "Singair", "digits" => 5),
        "65163" => array ( "area" => "Maninganj", "city" => "Maninganj", "digits" => 5),
        "65161" => array ( "area" => "Maninganj", "city" => "Maninganj", "digits" => 5),
        "64189" => array ( "area" => "Rajbari", "city" => "Rajbari", "digits" => 5),
        "64165" => array ( "area" => "Rajbari", "city" => "Rajbari", "digits" => 5),
        "63189" => array ( "area" => "Faridpur", "city" => "Faridpur", "digits" => 5),
        "63167" => array ( "area" => "Faridpur", "city" => "Faridpur", "digits" => 5),
        "63166" => array ( "area" => "Faridpur", "city" => "Faridpur", "digits" => 5),
        "63165" => array ( "area" => "Faridpur", "city" => "Faridpur", "digits" => 5),
        "63164" => array ( "area" => "Faridpur", "city" => "Faridpur", "digits" => 5),
        "63163" => array ( "area" => "Faridpur", "city" => "Faridpur", "digits" => 5),
        "63162" => array ( "area" => "Faridpur", "city" => "Faridpur", "digits" => 5),
        "63161" => array ( "area" => "Faridpur", "city" => "Faridpur", "digits" => 5),
        "62875" => array ( "area" => "Narsingdi", "city" => "Shibpur", "digits" => 5),
        "62874" => array ( "area" => "Narsingdi", "city" => "Palash (Ghorasal)", "digits" => 5),
        "62864" => array ( "area" => "Narsingdi", "city" => "Narsingdi", "digits" => 5),
        "62863" => array ( "area" => "Narsingdi", "city" => "Narsingdi", "digits" => 5),
        "62862" => array ( "area" => "Narsingdi", "city" => "Narsingdi", "digits" => 5),
        "62579" => array ( "area" => "Narsingdi", "city" => "Madhabdi", "digits" => 3),
        "62577" => array ( "area" => "Narsingdi", "city" => "Madhabdi", "digits" => 3),
        "62576" => array ( "area" => "Narsingdi", "city" => "Madhabdi", "digits" => 3),
        "62575" => array ( "area" => "Narsingdi", "city" => "Madhabdi", "digits" => 3),
        "62574" => array ( "area" => "Narsingdi", "city" => "Madhabdi", "digits" => 3),
        "62573" => array ( "area" => "Narsingdi", "city" => "Madhabdi", "digits" => 3),
        "62572" => array ( "area" => "Narsingdi", "city" => "Madhabdi", "digits" => 3),
        "62548" => array ( "area" => "Palash", "city" => "Palash", "digits" => 5),
        "62538" => array ( "area" => "Monohordi", "city" => "Monohordi", "digits" => 5),
        "62258" => array ( "area" => "Nowabgonj", "city" => "Nowabgonj", "digits" => 5),
        "62248" => array ( "area" => "Keranigonj", "city" => "Keranigonj", "digits" => 5),
        "62238" => array ( "area" => "Dohar", "city" => "Dohar", "digits" => 5),
        "62228" => array ( "area" => "Dhamrai", "city" => "Dhamrai", "digits" => 5),
        "60248" => array ( "area" => "Sariatpur", "city" => "Goshairhat", "digits" => 4),
        "60161" => array ( "area" => "Shariatpur", "city" => "Shariatpur", "digits" => 5),
        "60159" => array ( "area" => "Shariatpur", "city" => "Naria", "digits" => 5),
        "60155" => array ( "area" => "Shariatpur", "city" => "Shariatpur", "digits" => 5),
        "59189" => array ( "area" => "Lalmonirhat", "city" => "Lalmonirhat", "digits" => 5),
        "59162" => array ( "area" => "Lalmonirhat", "city" => "Lalmonirhat", "digits" => 5),
        "59161" => array ( "area" => "Lalmonirhat", "city" => "Lalmonirhat", "digits" => 5),
        "58268" => array ( "area" => "Nageswari", "city" => "Nageswari", "digits" => 5),
        "58189" => array ( "area" => "Kurigram", "city" => "Kurigram", "digits" => 5),
        "58162" => array ( "area" => "Kurigram", "city" => "Kurigram", "digits" => 5),
        "58161" => array ( "area" => "Kurigram", "city" => "Kurigram", "digits" => 5),
        "57248" => array ( "area" => "Panchbibi", "city" => "Panchbibi", "digits" => 5),
        "57189" => array ( "area" => "Joypurhat", "city" => "Jhinaidah", "digits" => 5),
        "57175" => array ( "area" => "Joypurhat", "city" => "Panchbibi", "digits" => 5),
        "57163" => array ( "area" => "Joypurhat", "city" => "Jhinaidah", "digits" => 5),
        "57162" => array ( "area" => "Joypurhat", "city" => "Jhinaidah", "digits" => 5),
        "56889" => array ( "area" => "Panchagar", "city" => "Panchagar", "digits" => 5),
        "56875" => array ( "area" => "Panchagar", "city" => "Tetulia", "digits" => 5),
        "56862" => array ( "area" => "Panchagar", "city" => "Panchagar", "digits" => 5),
        "56861" => array ( "area" => "Panchagar", "city" => "Panchagar", "digits" => 5),
        "56189" => array ( "area" => "Thakurgoan", "city" => "Thakurgoan", "digits" => 5),
        "56161" => array ( "area" => "Thakurgoan", "city" => "Thakurgoan", "digits" => 5),
        "56152" => array ( "area" => "Thakurgoan", "city" => "Thakurgoan", "digits" => 5),
        "55268" => array ( "area" => "Syedpur", "city" => "Syedpur", "digits" => 5),
        "55262" => array ( "area" => "Nilphamari", "city" => "Saidpur", "digits" => 4),
        "55189" => array ( "area" => "Nilphamari", "city" => "Nilphamari", "digits" => 5),
        "55175" => array ( "area" => "Nilphamari", "city" => "Domar", "digits" => 5),
        "55162" => array ( "area" => "Nilphamari", "city" => "Nilphamari", "digits" => 5),
        "55161" => array ( "area" => "Nilphamari", "city" => "Nilphamari", "digits" => 5),
        "54248" => array ( "area" => "Palashbari", "city" => "Palashbari", "digits" => 5),
        "54189" => array ( "area" => "Gaibandha", "city" => "Gaibandha", "digits" => 5),
        "54175" => array ( "area" => "Gaibandha", "city" => "Gabindaganj", "digits" => 5),
        "54162" => array ( "area" => "Gaibandha", "city" => "Gaibandha", "digits" => 5),
        "54161" => array ( "area" => "Gaibandha", "city" => "Gaibandha", "digits" => 5),
        "53298" => array ( "area" => "Bangla Hili", "city" => "Bangla Hili", "digits" => 5),
        "53273" => array ( "area" => "Dianjpur", "city" => "Fulbari", "digits" => 3),
        "53272" => array ( "area" => "Dianjpur", "city" => "Fulbari", "digits" => 3),
        "53258" => array ( "area" => "Shetabgonj", "city" => "Shetabgonj", "digits" => 5),
        "53238" => array ( "area" => "Gobindagonj", "city" => "Gobindagonj", "digits" => 5),
        "53236" => array ( "area" => "Dianjpur", "city" => "Birganj", "digits" => 3),
        "53235" => array ( "area" => "Dianjpur", "city" => "Birganj", "digits" => 3),
        "53234" => array ( "area" => "Dianjpur", "city" => "Birganj", "digits" => 3),
        "53233" => array ( "area" => "Dianjpur", "city" => "Birganj", "digits" => 3),
        "53232" => array ( "area" => "Dianjpur", "city" => "Birganj", "digits" => 3),
        "53189" => array ( "area" => "Dianjpur", "city" => "Dianjpur", "digits" => 5),
        "53175" => array ( "area" => "Dianjpur", "city" => "Hakimpur (Hili)", "digits" => 5),
        "53174" => array ( "area" => "Dianjpur", "city" => "Parbitipur", "digits" => 5),
        "53166" => array ( "area" => "Dianjpur", "city" => "Dianjpur", "digits" => 5),
        "53165" => array ( "area" => "Dianjpur", "city" => "Dianjpur", "digits" => 5),
        "53164" => array ( "area" => "Dianjpur", "city" => "Dianjpur", "digits" => 5),
        "53163" => array ( "area" => "Dianjpur", "city" => "Dianjpur", "digits" => 5),
        "53162" => array ( "area" => "Dianjpur", "city" => "Dianjpur", "digits" => 5),
        "53161" => array ( "area" => "Dianjpur", "city" => "Dianjpur", "digits" => 5),
        "52278" => array ( "area" => "Pirgonj", "city" => "Pirgonj", "digits" => 5),
        "52258" => array ( "area" => "Mithapukur", "city" => "Mithapukur", "digits" => 5),
        "52248" => array ( "area" => "Haragacha", "city" => "Haragacha", "digits" => 5),
        "52223" => array ( "area" => "Rangpur", "city" => "Badarganj", "digits" => 3),
        "52222" => array ( "area" => "Rangpur", "city" => "Badarganj", "digits" => 3),
        "52169" => array ( "area" => "Rangpur", "city" => "Rangpur", "digits" => 5),
        "52168" => array ( "area" => "Rangpur", "city" => "Rangpur", "digits" => 5),
        "52167" => array ( "area" => "Rangpur", "city" => "Rangpur", "digits" => 5),
        "52161" => array ( "area" => "Rangpur", "city" => "Rangpur", "digits" => 5),
        "50298" => array ( "area" => "Sherpur", "city" => "Sherpur", "digits" => 5),
        "50248" => array ( "area" => "Dhupchachia", "city" => "Dhupchachia", "digits" => 5),
        "50208" => array ( "area" => "Sibgonj", "city" => "Sibgonj (Mokamtala)", "digits" => 5),
        "49889" => array ( "area" => "Jhalakati", "city" => "Jhalakati", "digits" => 5),
        "49863" => array ( "area" => "Jhalakati", "city" => "Jhalakati", "digits" => 5),
        "49862" => array ( "area" => "Jhalakati", "city" => "Jhalakati", "digits" => 5),
        "49538" => array ( "area" => "Jhalokhati", "city" => "Nalcity", "digits" => 4),
        "49162" => array ( "area" => "Bhola", "city" => "Bhola", "digits" => 5),
        "49161" => array ( "area" => "Bhola", "city" => "Bhola", "digits" => 5),
        "49158" => array ( "area" => "Bhola", "city" => "Bhola", "digits" => 5),
        "49155" => array ( "area" => "Bhola", "city" => "Bhola", "digits" => 5),
        "48889" => array ( "area" => "Magura", "city" => "Magura", "digits" => 5),
        "48875" => array ( "area" => "Magura", "city" => "Mohammadpur", "digits" => 5),
        "48863" => array ( "area" => "Magura", "city" => "Magura", "digits" => 5),
        "48862" => array ( "area" => "Magura", "city" => "Magura", "digits" => 5),
        "48189" => array ( "area" => "Narail", "city" => "Narail", "digits" => 5),
        "48163" => array ( "area" => "Narail", "city" => "Narail", "digits" => 5),
        "48162" => array ( "area" => "Narail", "city" => "Narail", "digits" => 5),
        "47166" => array ( "area" => "Satkhira", "city" => "Satkhira", "digits" => 5),
        "47165" => array ( "area" => "Satkhira", "city" => "Satkhira", "digits" => 5),
        "47164" => array ( "area" => "Satkhira", "city" => "Satkhira", "digits" => 5),
        "47163" => array ( "area" => "Satkhira", "city" => "Satkhira", "digits" => 5),
        "47162" => array ( "area" => "Satkhira", "city" => "Satkhira", "digits" => 5),
        "46875" => array ( "area" => "Bagerhat", "city" => "Mongla Port", "digits" => 5),
        "46863" => array ( "area" => "Bagerhat", "city" => "Bagerhat", "digits" => 5),
        "46862" => array ( "area" => "Bagerhat", "city" => "Bagerhat", "digits" => 5),
        "46861" => array ( "area" => "Bagerhat", "city" => "Bagerhat", "digits" => 5),
        "46585" => array ( "area" => "Bagerhat", "city" => "Mongla", "digits" => 3),
        "46584" => array ( "area" => "Bagerhat", "city" => "Mongla", "digits" => 3),
        "46583" => array ( "area" => "Bagerhat", "city" => "Mongla", "digits" => 3),
        "46582" => array ( "area" => "Bagerhat", "city" => "Mongla", "digits" => 3),
        "46578" => array ( "area" => "Bagerhat", "city" => "Rampal", "digits" => 4),
        "46558" => array ( "area" => "Bagerhat", "city" => "Mollarhat", "digits" => 4),
        "46548" => array ( "area" => "Bagerhat", "city" => "Kachua", "digits" => 4),
        "46538" => array ( "area" => "Bagerhat", "city" => "Fakirhat", "digits" => 4),
        "46535" => array ( "area" => "Bagerhat", "city" => "Fakirhat", "digits" => 3),
        "46534" => array ( "area" => "Bagerhat", "city" => "Fakirhat", "digits" => 3),
        "46533" => array ( "area" => "Bagerhat", "city" => "Fakirhat", "digits" => 3),
        "46532" => array ( "area" => "Bagerhat", "city" => "Fakirhat", "digits" => 3),
        "46528" => array ( "area" => "Bagerhat", "city" => "Chitalmari", "digits" => 4),
        "46278" => array ( "area" => "Bagerhat", "city" => "Swarupkhati", "digits" => 4),
        "46268" => array ( "area" => "Bagerhat", "city" => "Nazirpur", "digits" => 4),
        "46248" => array ( "area" => "Bagerhat", "city" => "Kawkhali", "digits" => 4),
        "46233" => array ( "area" => "Pirojpur", "city" => "Bhandaria", "digits" => 3),
        "46232" => array ( "area" => "Pirojpur", "city" => "Bhandaria", "digits" => 3),
        "46163" => array ( "area" => "Pirojpur", "city" => "Pirojpur", "digits" => 5),
        "46162" => array ( "area" => "Pirojpur", "city" => "Pirojpur", "digits" => 5),
        "45253" => array ( "area" => "Jhinaidah", "city" => "Moheshpur", "digits" => 3),
        "45252" => array ( "area" => "Jhinaidah", "city" => "Moheshpur", "digits" => 3),
        "45238" => array ( "area" => "Jenidah", "city" => "Kaligonj", "digits" => 4),
        "45189" => array ( "area" => "Jhinaidah", "city" => "Jhinaidah", "digits" => 5),
        "45174" => array ( "area" => "Jhinaidah", "city" => "Horinakunda", "digits" => 5),
        "45164" => array ( "area" => "Jhinaidah", "city" => "Jhinaidah", "digits" => 5),
        "45163" => array ( "area" => "Jhinaidah", "city" => "Jhinaidah", "digits" => 5),
        "45162" => array ( "area" => "Jhinaidah", "city" => "Jhinaidah", "digits" => 5),
        "45161" => array ( "area" => "Jhinaidah", "city" => "Jhinaidah", "digits" => 5),
        "44863" => array ( "area" => "Barguna", "city" => "Barguna", "digits" => 5),
        "44862" => array ( "area" => "Barguna", "city" => "Barguna", "digits" => 5),
        "44253" => array ( "area" => "Patuakhali", "city" => "Khepupara", "digits" => 3),
        "44252" => array ( "area" => "Patuakhali", "city" => "Khepupara", "digits" => 3),
        "44164" => array ( "area" => "Patuakhali", "city" => "Patuakhali", "digits" => 5),
        "44163" => array ( "area" => "Patuakhali", "city" => "Patuakhali", "digits" => 5),
        "44162" => array ( "area" => "Patuakhali", "city" => "Patuakhali", "digits" => 5),
        "43298" => array ( "area" => "Barisal", "city" => "Uzirpur", "digits" => 4),
        "43288" => array ( "area" => "Barisal", "city" => "Bakergonj", "digits" => 4),
        "43278" => array ( "area" => "Barisal", "city" => "Babugonj", "digits" => 4),
        "43268" => array ( "area" => "Barisal", "city" => "Muladi", "digits" => 4),
        "43258" => array ( "area" => "Barisal", "city" => "Mehendigonj", "digits" => 4),
        "43248" => array ( "area" => "Barisal", "city" => "Hizla", "digits" => 4),
        "43238" => array ( "area" => "Barisal", "city" => "Agailjhara", "digits" => 4),
        "43228" => array ( "area" => "Barisal", "city" => "Gournadi", "digits" => 4),
        "43208" => array ( "area" => "Barisal", "city" => "Banaripara", "digits" => 4),
        "43121" => array ( "area" => "Barisal", "city" => "Barisal", "digits" => 7),
        "42288" => array ( "area" => "Jessore", "city" => "Sharsa", "digits" => 4),
        "42278" => array ( "area" => "Jessore", "city" => "Monirampur", "digits" => 4),
        "42268" => array ( "area" => "Jessore", "city" => "Keshobpur", "digits" => 4),
        "42258" => array ( "area" => "Jessore", "city" => "Jhikargacha", "digits" => 4),
        "42255" => array ( "area" => "Jessore", "city" => "Jhikargacha", "digits" => 3),
        "42254" => array ( "area" => "Jessore", "city" => "Jhikargacha", "digits" => 3),
        "42253" => array ( "area" => "Jessore", "city" => "Jhikargacha", "digits" => 3),
        "42252" => array ( "area" => "Jessore", "city" => "Jhikargacha", "digits" => 3),
        "42248" => array ( "area" => "Jessore", "city" => "Chaugacha", "digits" => 4),
        "42238" => array ( "area" => "Jessore", "city" => "Bagerphara", "digits" => 4),
        "42228" => array ( "area" => "Jessore", "city" => "Abhynagar", "digits" => 4),
        "42223" => array ( "area" => "Jessore", "city" => "Abhaynagar (Noapara)", "digits" => 3),
        "42222" => array ( "area" => "Jessore", "city" => "Abhaynagar (Noapara)", "digits" => 3),
        "42175" => array ( "area" => "Jessore", "city" => "Sharsa (Benapol)", "digits" => 5),
        "40298" => array ( "area" => "Khulna", "city" => "Terokhada", "digits" => 4),
        "40274" => array ( "area" => "Khulna", "city" => "Paikgacha", "digits" => 3),
        "40273" => array ( "area" => "Khulna", "city" => "Paikgacha", "digits" => 3),
        "40272" => array ( "area" => "Khulna", "city" => "Paikgacha", "digits" => 3),
        "40208" => array ( "area" => "Khulna", "city" => "Rupsha", "digits" => 4),
        "38248" => array ( "area" => "Laximpur", "city" => "Ramgonj", "digits" => 4),
        "38233" => array ( "area" => "Laximpur", "city" => "Ramgati (Alexender)", "digits" => 3),
        "38232" => array ( "area" => "Laximpur", "city" => "Ramgati (Alexender)", "digits" => 3),
        "38175" => array ( "area" => "Laximpur", "city" => "Ramganj", "digits" => 5),
        "38162" => array ( "area" => "Laximpur", "city" => "Laximpur", "digits" => 5),
        "38161" => array ( "area" => "Laximpur", "city" => "Laximpur", "digits" => 5),
        "38158" => array ( "area" => "Laximpur", "city" => "Laximpur", "digits" => 5),
        "38155" => array ( "area" => "Laximpur", "city" => "Laximpur", "digits" => 5),
        "37162" => array ( "area" => "Khagrachari", "city" => "Khagrachari", "digits" => 5),
        "37161" => array ( "area" => "Khagrachari", "city" => "Khagrachari", "digits" => 5),
        "36189" => array ( "area" => "Bandarban", "city" => "Bandarban", "digits" => 5),
        "36163" => array ( "area" => "Bandarban", "city" => "Bandarban", "digits" => 5),
        "36162" => array ( "area" => "Bandarban", "city" => "Bandarban", "digits" => 5),
        "35294" => array ( "area" => "Rangamati", "city" => "Kaptai", "digits" => 3),
        "35293" => array ( "area" => "Rangamati", "city" => "Kaptai", "digits" => 3),
        "35292" => array ( "area" => "Rangamati", "city" => "Kaptai", "digits" => 3),
        "35163" => array ( "area" => "Rangamati", "city" => "Rangamati", "digits" => 5),
        "35162" => array ( "area" => "Rangamati", "city" => "Rangamati", "digits" => 5),
        "35161" => array ( "area" => "Rangamati", "city" => "Rangamati", "digits" => 5),
        "34273" => array ( "area" => "Cox'sbazar", "city" => "Ukhiya", "digits" => 3),
        "34272" => array ( "area" => "Cox'sbazar", "city" => "Ukhiya", "digits" => 3),
        "34243" => array ( "area" => "Cox'sbazar", "city" => "Moheshkhali", "digits" => 3),
        "34242" => array ( "area" => "Cox'sbazar", "city" => "Moheshkhali", "digits" => 3),
        "34228" => array ( "area" => "Cox's Bazar", "city" => "Chakaria", "digits" => 4),
        "34164" => array ( "area" => "Cox'sbazar", "city" => "Cox'sbazar", "digits" => 5),
        "34163" => array ( "area" => "Cox'sbazar", "city" => "Cox'sbazar", "digits" => 5),
        "34162" => array ( "area" => "Cox'sbazar", "city" => "Cox'sbazar", "digits" => 5),
        "34158" => array ( "area" => "Cox'sbazar", "city" => "Eidgaon", "digits" => 5),
        "33268" => array ( "area" => "Feni", "city" => "Fulgazi", "digits" => 4),
        "33258" => array ( "area" => "Feni", "city" => "Sonagazi", "digits" => 4),
        "33248" => array ( "area" => "Feni", "city" => "Parsuram", "digits" => 4),
        "33238" => array ( "area" => "Feni", "city" => "Dagonbhuya", "digits" => 4),
        "33228" => array ( "area" => "Feni", "city" => "Chhagalnaiya", "digits" => 4),
        "33179" => array ( "area" => "Feni", "city" => "Daganbhuyan", "digits" => 5),
        "33178" => array ( "area" => "Feni", "city" => "Chagalnaiya", "digits" => 5),
        "33176" => array ( "area" => "Feni", "city" => "Sonagazi", "digits" => 5),
        "33174" => array ( "area" => "Feni", "city" => "Feni", "digits" => 5),
        "33173" => array ( "area" => "Feni", "city" => "Feni", "digits" => 5),
        "33163" => array ( "area" => "Feni", "city" => "Feni", "digits" => 5),
        "33162" => array ( "area" => "Feni", "city" => "Feni", "digits" => 5),
        "33161" => array ( "area" => "Feni", "city" => "Feni", "digits" => 5),
        "33160" => array ( "area" => "Feni", "city" => "Feni", "digits" => 5),
        "32258" => array ( "area" => "Noakhali", "city" => "Senbag", "digits" => 4),
        "32243" => array ( "area" => "Noakhali", "city" => "Hatiya (Oshkhali)", "digits" => 3),
        "32242" => array ( "area" => "Noakhali", "city" => "Hatiya (Oshkhali)", "digits" => 3),
        "32238" => array ( "area" => "Noakhali", "city" => "Companigonj", "digits" => 4),
        "32228" => array ( "area" => "Noakhali", "city" => "Chatkhil", "digits" => 4),
        "32218" => array ( "area" => "Noakhali", "city" => "Begamgonj", "digits" => 4),
        "32175" => array ( "area" => "Noakhali", "city" => "Chatkhil", "digits" => 5),
        "32163" => array ( "area" => "Noakhali", "city" => "Noakhali", "digits" => 5),
        "32162" => array ( "area" => "Noakhali", "city" => "Noakhali", "digits" => 5),
        "32161" => array ( "area" => "Noakhali", "city" => "Noakhali", "digits" => 5),
        "32153" => array ( "area" => "Noakhali", "city" => "Noakhali", "digits" => 5),
        "32152" => array ( "area" => "Noakhali", "city" => "Noakhali", "digits" => 5),
        "32151" => array ( "area" => "Noakhali", "city" => "Noakhali", "digits" => 5),
        "30368" => array ( "area" => "Chittagong", "city" => "Satkhania", "digits" => 4),
        "30363" => array ( "area" => "Chittagong", "city" => "Satkania", "digits" => 3),
        "30362" => array ( "area" => "Chittagong", "city" => "Satkania", "digits" => 3),
        "30358" => array ( "area" => "Chittagong", "city" => "Potiya", "digits" => 4),
        "30355" => array ( "area" => "Chittagong", "city" => "Potia", "digits" => 3),
        "30354" => array ( "area" => "Chittagong", "city" => "Potia", "digits" => 3),
        "30353" => array ( "area" => "Chittagong", "city" => "Potia", "digits" => 3),
        "30352" => array ( "area" => "Chittagong", "city" => "Potia", "digits" => 3),
        "30348" => array ( "area" => "Chittagong", "city" => "Lohagara", "digits" => 4),
        "30338" => array ( "area" => "Chittagong", "city" => "Chandanaish", "digits" => 4),
        "30328" => array ( "area" => "Chittagong", "city" => "Boalkhali", "digits" => 4),
        "30298" => array ( "area" => "Chittagong", "city" => "Anwara", "digits" => 4),
        "30288" => array ( "area" => "Chittagong", "city" => "Sitakunda", "digits" => 4),
        "30278" => array ( "area" => "Chittagong", "city" => "Snadwip", "digits" => 4),
        "30268" => array ( "area" => "Chittagong", "city" => "Rauzan", "digits" => 4),
        "30258" => array ( "area" => "Chittagong", "city" => "Rangunia", "digits" => 4),
        "30248" => array ( "area" => "Chittagong", "city" => "Mirsari", "digits" => 4),
        "30238" => array ( "area" => "Chittagong", "city" => "Hathazari", "digits" => 4),
        "30228" => array ( "area" => "Chittagong", "city" => "Fatikchari", "digits" => 4),
        "30208" => array ( "area" => "Chittagong", "city" => "Banskhali", "digits" => 4),
        "9189" => array ( "area" => "Mymensingh", "city" => "Mymensingh", "digits" => 5),
        "9175" => array ( "area" => "Mymensingh", "city" => "Muktagacha", "digits" => 5),
        "9164" => array ( "area" => "Mymensingh", "city" => "Mymensingh", "digits" => 5),
        "9163" => array ( "area" => "Mymensingh", "city" => "Mymensingh", "digits" => 5),
        "9162" => array ( "area" => "Mymensingh", "city" => "Mymensingh", "digits" => 5),
        "9161" => array ( "area" => "Mymensingh", "city" => "Mymensingh", "digits" => 5),
        "9156" => array ( "area" => "Mymensingh", "city" => "Mymensingh", "digits" => 5),
        "9155" => array ( "area" => "Mymensingh", "city" => "Mymensingh", "digits" => 5),
        "9154" => array ( "area" => "Mymensingh", "city" => "Mymensingh", "digits" => 5),
        "9153" => array ( "area" => "Mymensingh", "city" => "Mymensingh", "digits" => 5),
        "9152" => array ( "area" => "Mymensingh", "city" => "Mymensingh", "digits" => 5),
        "9151" => array ( "area" => "Mymensingh", "city" => "Mymensingh", "digits" => 5),
        "8177" => array ( "area" => "Comilla", "city" => "Comilla", "digits" => 5),
        "8176" => array ( "area" => "Comilla", "city" => "Comilla", "digits" => 5),
        "8175" => array ( "area" => "Comilla", "city" => "Comilla", "digits" => 5),
        "8174" => array ( "area" => "Comilla", "city" => "Comilla", "digits" => 5),
        "8173" => array ( "area" => "Comilla", "city" => "Comilla", "digits" => 5),
        "8172" => array ( "area" => "Comilla", "city" => "Comilla", "digits" => 5),
        "8171" => array ( "area" => "Comilla", "city" => "Comilla", "digits" => 5),
        "8154" => array ( "area" => "Comilla", "city" => "Homna", "digits" => 5),
        "7189" => array ( "area" => "Kushtia", "city" => "Kushtia", "digits" => 5),
        "7176" => array ( "area" => "Kushtia", "city" => "Kumarkhali", "digits" => 5),
        "7175" => array ( "area" => "Kushtia", "city" => "Daulatpur", "digits" => 5),
        "7171" => array ( "area" => "Kushtia", "city" => "Kushtia", "digits" => 5),
        "7162" => array ( "area" => "Kushtia", "city" => "Kushtia", "digits" => 5),
        "7161" => array ( "area" => "Kushtia", "city" => "Kushtia", "digits" => 5),
        "7155" => array ( "area" => "Kushtia", "city" => "Kushtia", "digits" => 5),
        "7154" => array ( "area" => "Kushtia", "city" => "Kushtia", "digits" => 5),
        "7153" => array ( "area" => "Kushtia", "city" => "Kushtia", "digits" => 5),
        "5189" => array ( "area" => "Bogra", "city" => "Bogra", "digits" => 5),
        "5177" => array ( "area" => "Bogra", "city" => "Sherpur", "digits" => 5),
        "5176" => array ( "area" => "Bogra", "city" => "Nandigram", "digits" => 5),
        "5175" => array ( "area" => "Bogra", "city" => "Gabtali", "digits" => 5),
        "5173" => array ( "area" => "Bogra", "city" => "Bogra", "digits" => 5),
        "5172" => array ( "area" => "Bogra", "city" => "Bogra", "digits" => 5),
        "5171" => array ( "area" => "Bogra", "city" => "Bogra", "digits" => 5),
        "5168" => array ( "area" => "Bogra", "city" => "Bogra", "digits" => 5),
        "5167" => array ( "area" => "Bogra", "city" => "Bogra", "digits" => 5),
        "5166" => array ( "area" => "Bogra", "city" => "Bogra", "digits" => 5),
        "5165" => array ( "area" => "Bogra", "city" => "Bogra", "digits" => 5),
        "5164" => array ( "area" => "Bogra", "city" => "Bogra", "digits" => 5),
        "5163" => array ( "area" => "Bogra", "city" => "Bogra", "digits" => 5),
        "5162" => array ( "area" => "Bogra", "city" => "Bogra", "digits" => 5),
        "5161" => array ( "area" => "Bogra", "city" => "Bogra", "digits" => 5),
        "4186" => array ( "area" => "Khulna", "city" => "Khulna MEA", "digits" => 6),
        "4181" => array ( "area" => "Khulna", "city" => "Khulna MEA", "digits" => 6),
        "4180" => array ( "area" => "Khulna", "city" => "Khulna MEA", "digits" => 6),
        "4178" => array ( "area" => "Khulna", "city" => "Khulna MEA", "digits" => 6),
        "4177" => array ( "area" => "Khulna", "city" => "Khulna MEA", "digits" => 6),
        "4176" => array ( "area" => "Khulna", "city" => "Khulna MEA", "digits" => 6),
        "4173" => array ( "area" => "Khulna", "city" => "Khulna MEA", "digits" => 6),
        "4172" => array ( "area" => "Khulna", "city" => "Khulna MEA", "digits" => 6),
        "3181" => array ( "area" => "Chittagong", "city" => "Chittagong MEA", "digits" => 6),
        "3175" => array ( "area" => "Chittagong", "city" => "Chittagong MEA", "digits" => 6),
        "3174" => array ( "area" => "Chittagong", "city" => "Chittagong MEA", "digits" => 6),
        "3172" => array ( "area" => "Chittagong", "city" => "Chittagong MEA", "digits" => 6),
        "3171" => array ( "area" => "Chittagong", "city" => "Chittagong MEA", "digits" => 6),
        "3168" => array ( "area" => "Chittagong", "city" => "Chittagong MEA", "digits" => 6),
        "3167" => array ( "area" => "Chittagong", "city" => "Chittagong MEA", "digits" => 6),
        "3165" => array ( "area" => "Chittagong", "city" => "Chittagong MEA", "digits" => 6),
        "3163" => array ( "area" => "Chittagong", "city" => "Chittagong MEA", "digits" => 6),
        "3162" => array ( "area" => "Chittagong", "city" => "Chittagong MEA", "digits" => 6),
        "3161" => array ( "area" => "Chittagong", "city" => "Chittagong MEA", "digits" => 6),
        "2987" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2986" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2981" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2980" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2975" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2971" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2967" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2966" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2961" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2960" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2957" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2956" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2955" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2936" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2935" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2934" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2933" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2928" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2926" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2925" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2914" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2913" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2912" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2911" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2901" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2900" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2896" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2895" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2892" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2891" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2886" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2885" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2882" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2881" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2875" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2865" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2863" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2862" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2861" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2836" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2835" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2834" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2833" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2832" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2831" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2829" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2828" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2827" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2825" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2820" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2816" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2815" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2813" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2812" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2811" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2805" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2802" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2801" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2777" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2771" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2770" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2761" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2760" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2752" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2751" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2741" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2740" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2739" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2732" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2731" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2730" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2729" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2728" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2722" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2721" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2720" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2717" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2716" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2712" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2711" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "2710" => array ( "area" => "Dhaka", "city" => "Dhaka MEA", "digits" => 7),
        "816" => array ( "area" => "Comilla", "city" => "Comilla", "digits" => 5)
      );
      foreach ( $areas as $area => $data)
      {
        if ( (int) substr ( $parameters["Number"], 4, strlen ( $area)) == $area)
        {
          if ( strlen ( $parameters["Number"]) - 4 - strlen ( $prefix) > $data["digits"])
          {
            return ( is_array ( $buffer) ? $buffer : false);
          }
          if ( $prefix == "2")
          {
            $callformats = array ( "Local" => substr ( $parameters["Number"], 4, 1) . " " . substr ( $parameters["Number"], 5, 3) . " " . substr ( $parameters["Number"], 8), "International" => "+880 " . substr ( $parameters["Number"], 4, 1) . " " . substr ( $parameters["Number"], 5, 3) . " " . substr ( $parameters["Number"], 8));
          } else {
            $callformats = array ( "Local" => substr ( $parameters["Number"], 4, 2) . " " . substr ( $parameters["Number"], 6, 3) . " " . substr ( $parameters["Number"], 9), "International" => "+880 " . substr ( $parameters["Number"], 4, 3) . " " . substr ( $parameters["Number"], 7, 3) . " " . substr ( $parameters["Number"], 10));
          }
          return array_merge_recursive ( ( is_array ( $buffer) ? $buffer : array ()), array ( "CC" => "880", "NDC" => ( $prefix == "2" ? substr ( $parameters["Number"], 4, 2) : substr ( $parameters["Number"], 4, 3)), "Country" => "Bangladesh", "Area" => $data["area"], "City" => $data["city"], "Operator" => $operator, "SN" => ( $prefix == "2" ? substr ( $parameters["Number"], 6) : substr ( $parameters["Number"], 7)), "Type" => VD_PHONETYPE_LANDLINE, "CallFormats" => $callformats));
        }
      }
    }
  }

  /**
   * Check for VoIP network
   */
  $prefixes = array (
    "9678" => "Link3 Technologies LTD.",
    "9677" => "BRACNet Limited",
    "9669" => "ConnectTel",
    "9666" => "BDCom",
    "9639" => "ICC Communication",
    "9638" => "Intercloud Limited",
    "9633" => "IDEA Networks and Communications Limited",
    "9614" => "NextFone",
    "9613" => "GETCO Online",
    "9612" => "MetroNet",
    "9610" => "ADN Telecom",
    "9609" => "BEXIMCO",
    "9606" => "Agni Systems Ltd",
    "9604" => "FUSION NET"
  );
  foreach ( $prefixes as $prefix => $operator)
  {
    if ( (int) substr ( $parameters["Number"], 4, strlen ( $prefix)) == $prefix)
    {
      return array_merge_recursive ( ( is_array ( $buffer) ? $buffer : array ()), array ( "CC" => "880", "NDC" => substr ( $parameters["Number"], 4, 4), "Country" => "Bangladesh", "Area" => "", "City" => "", "Operator" => $operator, "SN" => substr ( $parameters["Number"], 8), "Type" => VD_PHONETYPE_VOIP, "CallFormats" => array ( "Local" => substr ( $parameters["Number"], 4, 4) . " " . substr ( $parameters["Number"], 8), "International" => "+880 " . substr ( $parameters["Number"], 4, 4) . " " . substr ( $parameters["Number"], 8))));
    }
  }

  /**
   * If reached here, number wasn't identified as a valid Bangladeshian phone
   * number
   */
  return ( is_array ( $buffer) ? $buffer : false);
}
?>
