<?php
/**   ___ ___       ___ _______     ______                        __
 *   |   Y   .-----|   |   _   |   |   _  \ .-----.--------.---.-|__.-----.
 *   |.  |   |  _  |.  |.  1   |   |.  |   \|  _  |        |  _  |  |     |
 *   |.  |   |_____|.  |.  ____|   |.  |    |_____|__|__|__|___._|__|__|__|
 *   |:  1   |     |:  |:  |       |:  1    /
 *    \:.. ./      |::.|::.|       |::.. . /
 *     `---'       `---`---'       `------'
 *
 * Copyright (C) 2016-2025 Ernani José Camargo Azevedo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * VoIP Domain country database module filters. This module add the filter calls
 * related to country database of Nepal.
 *
 * Reference: https://www.itu.int/oth/T0202000095/en (2006-07-20)
 *
 * Glossary:
 *  CC - Country Code
 *  NDC - National Destination Code (also known as area code)
 *  N(S)N - National (Significant) Number
 *  SN - Subscriber Number
 *
 * @author     Ernani José Camargo Azevedo <azevedo@voipdomain.io>
 * @version    1.0
 * @package    VoIP Domain
 * @subpackage CountryDB
 * @copyright  2016-2025 Ernani José Camargo Azevedo. All rights reserved.
 * @license    https://www.gnu.org/licenses/gpl-3.0.en.html
 */

/**
 * E.164 Nepal country hook
 */
framework_add_filter ( "e164_identify_country_NPL", "e164_identify_country_NPL");

/**
 * E.164 Nepalian area number identification hook. This hook is an e164_identify
 * sub hook, called when the ISO3166 Alpha3 are "NPL" (code for Nepal). This
 * hook will verify if phone number is valid, returning the area code, area name,
 * phone number, others number related information and if possible, the number
 * type (mobile, landline, Premium Rate Number, etc).
 *
 * @param string $buffer Buffer from plugin system if processed by other function
 *                       before
 * @param array $parameters Parameters to the function. Number provided as
 *                          $parameters["Number"]
 * @return array Array contaning many information about the requested number
 */
function e164_identify_country_NPL ( $buffer, $parameters)
{
  /**
   * Check if number country code is from Nepal
   */
  if ( substr ( $parameters["Number"], 0, 4) != "+977")
  {
    return ( is_array ( $buffer) ? $buffer : false);
  }

  /**
   * All numbers in Nepal has 12 digits E.164 format
   */
  if ( strlen ( $parameters["Number"]) != 12)
  {
    return ( is_array ( $buffer) ? $buffer : false);
  }

  /**
   * Check for mobile network with 2 digits NDC and 6 digits SN
   */
  $prefixes = array (
    "98590" => array ( "Area" => "Kalikot", "City" => "Dhangadhi", "Operator" => "Nepal Telecom"),
    "98587" => array ( "Area" => "Mahakali", "City" => "", "Operator" => "Nepal Telecom"),
    "98584" => array ( "Area" => "Seti", "City" => "", "Operator" => "Nepal Telecom"),
    "98580" => array ( "Area" => "Nepalgunj", "City" => "", "Operator" => "Nepal Telecom"),
    "98570" => array ( "Area" => "Myagdi", "City" => "Bhairahawa", "Operator" => "Nepal Telecom"),
    "98560" => array ( "Area" => "Makwanpur", "City" => "Pokhara", "Operator" => "Nepal Telecom"),
    "98550" => array ( "Area" => "Dolkha", "City" => "Birgunj", "Operator" => "Nepal Telecom"),
    "98540" => array ( "Area" => "Solukhumbu", "City" => "Janakpur", "Operator" => "Nepal Telecom"),
    "98528" => array ( "Area" => "S. Sabha", "City" => "", "Operator" => "Nepal Telecom"),
    "98526" => array ( "Area" => "Mechi", "City" => "", "Operator" => "Nepal Telecom"),
    "98520" => array ( "Area" => "Ilam", "City" => "Biratnagar", "Operator" => "Nepal Telecom"),
    "98510" => array ( "Area" => "Kathmandu", "City" => "", "Operator" => "Nepal Telecom"),
    "98460" => array ( "Area" => "Makwanpur", "City" => "Pokhara", "Operator" => "Nepal Telecom"),
    "98450" => array ( "Area" => "Dolkha", "City" => "Birgunj", "Operator" => "Nepal Telecom"),
    "98420" => array ( "Area" => "Ilam", "City" => "Biratnagar", "Operator" => "Nepal Telecom"),
    "98412" => array ( "Area" => "Kathmandu", "City" => "", "Operator" => "Nepal Telecom"),
    "981" => array ( "Area" => "", "City" => "", "Operator" => "nCell"),
    "980" => array ( "Area" => "", "City" => "", "Operator" => "nCell")
  );
  foreach ( $prefixes as $prefix => $data)
  {
    if ( (int) substr ( $parameters["Number"], 4, strlen ( $prefix)) == $prefix)
    {
      return array_merge_recursive ( ( is_array ( $buffer) ? $buffer : array ()), array ( "CC" => "977", "NDC" => $prefix, "Country" => "Nepal", "Area" => $data["Area"], "City" => $data["City"], "Operator" => $data["Operator"], "SN" => substr ( $parameters["Number"], 4 + strlen ( $prefix)), "Type" => VD_PHONETYPE_LANDLINE, "CallFormats" => array ( "Local" => substr ( $parameters["Number"], 4, 2) . " " . substr ( $parameters["Number"], 6, 3) . " " . substr ( $parameters["Number"], 9), "International" => "+977 " . substr ( $parameters["Number"], 4, 2) . " " . substr ( $parameters["Number"], 6, 3) . " " . substr ( $parameters["Number"], 9))));
    }
  }

  /**
   * Check for landline network with 1 or 2 digits NDC and 6 or 7 digits SN
   */
  $prefixes = array (
    "995404" => array ( "Area" => "Kanchanpur", "City" => "Jhallari"),
    "995403" => array ( "Area" => "Kanchanpur", "City" => "Jhallari"),
    "995402" => array ( "Area" => "Kanchanpur", "City" => "Jhallari"),
    "995401" => array ( "Area" => "Kanchanpur", "City" => "Jhallari"),
    "995400" => array ( "Area" => "Kanchanpur", "City" => "Jhallari"),
    "995804" => array ( "Area" => "Kanchanpur", "City" => "Bellauri"),
    "995803" => array ( "Area" => "Kanchanpur", "City" => "Bellauri"),
    "995802" => array ( "Area" => "Kanchanpur", "City" => "Bellauri"),
    "995801" => array ( "Area" => "Kanchanpur", "City" => "Bellauri"),
    "995800" => array ( "Area" => "Kanchanpur", "City" => "Bellauri"),
    "976204" => array ( "Area" => "Achham", "City" => "Mangalsen"),
    "976203" => array ( "Area" => "Achham", "City" => "Mangalsen"),
    "976202" => array ( "Area" => "Achham", "City" => "Mangalsen"),
    "976201" => array ( "Area" => "Achham", "City" => "Mangalsen"),
    "976200" => array ( "Area" => "Achham", "City" => "Mangalsen"),
    "975404" => array ( "Area" => "Bajura", "City" => "Martadi"),
    "975403" => array ( "Area" => "Bajura", "City" => "Martadi"),
    "975402" => array ( "Area" => "Bajura", "City" => "Martadi"),
    "975401" => array ( "Area" => "Bajura", "City" => "Martadi"),
    "975400" => array ( "Area" => "Bajura", "City" => "Martadi"),
    "964204" => array ( "Area" => "Dadeldhura", "City" => "Dadeldhura"),
    "964203" => array ( "Area" => "Dadeldhura", "City" => "Dadeldhura"),
    "964202" => array ( "Area" => "Dadeldhura", "City" => "Dadeldhura"),
    "964201" => array ( "Area" => "Dadeldhura", "City" => "Dadeldhura"),
    "964200" => array ( "Area" => "Dadeldhura", "City" => "Dadeldhura"),
    "955204" => array ( "Area" => "Baitadi", "City" => "Baitadi"),
    "955203" => array ( "Area" => "Baitadi", "City" => "Baitadi"),
    "955202" => array ( "Area" => "Baitadi", "City" => "Baitadi"),
    "955201" => array ( "Area" => "Baitadi", "City" => "Baitadi"),
    "955200" => array ( "Area" => "Baitadi", "City" => "Baitadi"),
    "934204" => array ( "Area" => "Darchula", "City" => "Darchula"),
    "934203" => array ( "Area" => "Darchula", "City" => "Darchula"),
    "934202" => array ( "Area" => "Darchula", "City" => "Darchula"),
    "934201" => array ( "Area" => "Darchula", "City" => "Darchula"),
    "934200" => array ( "Area" => "Darchula", "City" => "Darchula"),
    "924204" => array ( "Area" => "Bajhang", "City" => "Chainpur"),
    "924203" => array ( "Area" => "Bajhang", "City" => "Chainpur"),
    "924202" => array ( "Area" => "Bajhang", "City" => "Chainpur"),
    "924201" => array ( "Area" => "Bajhang", "City" => "Chainpur"),
    "924200" => array ( "Area" => "Bajhang", "City" => "Chainpur"),
    "915804" => array ( "Area" => "Kailali", "City" => "Bhajani"),
    "915803" => array ( "Area" => "Kailali", "City" => "Bhajani"),
    "915802" => array ( "Area" => "Kailali", "City" => "Bhajani"),
    "915801" => array ( "Area" => "Kailali", "City" => "Bhajani"),
    "915800" => array ( "Area" => "Kailali", "City" => "Bhajani"),
    "915404" => array ( "Area" => "Kalikot", "City" => "Lamki"),
    "915403" => array ( "Area" => "Kalikot", "City" => "Lamki"),
    "915402" => array ( "Area" => "Kalikot", "City" => "Lamki"),
    "915401" => array ( "Area" => "Kalikot", "City" => "Lamki"),
    "915400" => array ( "Area" => "Kalikot", "City" => "Lamki"),
    "894204" => array ( "Area" => "Dailekh", "City" => "Dailekh"),
    "894203" => array ( "Area" => "Dailekh", "City" => "Dailekh"),
    "894202" => array ( "Area" => "Dailekh", "City" => "Dailekh"),
    "894201" => array ( "Area" => "Dailekh", "City" => "Dailekh"),
    "894200" => array ( "Area" => "Dailekh", "City" => "Dailekh"),
    "875204" => array ( "Area" => "Jumla", "City" => "Jumla"),
    "875203" => array ( "Area" => "Jumla", "City" => "Jumla"),
    "875202" => array ( "Area" => "Jumla", "City" => "Jumla"),
    "875201" => array ( "Area" => "Jumla", "City" => "Jumla"),
    "875200" => array ( "Area" => "Jumla", "City" => "Jumla"),
    "874404" => array ( "Area" => "Kalikot", "City" => "Manma"),
    "874403" => array ( "Area" => "Kalikot", "City" => "Manma"),
    "874402" => array ( "Area" => "Kalikot", "City" => "Manma"),
    "874401" => array ( "Area" => "Kalikot", "City" => "Manma"),
    "874400" => array ( "Area" => "Kalikot", "City" => "Manma"),
    "864404" => array ( "Area" => "Pyuthan", "City" => "Bijuwar"),
    "864403" => array ( "Area" => "Pyuthan", "City" => "Bijuwar"),
    "864402" => array ( "Area" => "Pyuthan", "City" => "Bijuwar"),
    "864401" => array ( "Area" => "Pyuthan", "City" => "Bijuwar"),
    "864400" => array ( "Area" => "Pyuthan", "City" => "Bijuwar"),
    "864204" => array ( "Area" => "Pyuthan", "City" => "Pyuthankh"),
    "864203" => array ( "Area" => "Pyuthan", "City" => "Pyuthankh"),
    "864202" => array ( "Area" => "Pyuthan", "City" => "Pyuthankh"),
    "864201" => array ( "Area" => "Pyuthan", "City" => "Pyuthankh"),
    "864200" => array ( "Area" => "Pyuthan", "City" => "Pyuthankh"),
    "844604" => array ( "Area" => "Bardia", "City" => "Rajapur"),
    "844603" => array ( "Area" => "Bardia", "City" => "Rajapur"),
    "844602" => array ( "Area" => "Bardia", "City" => "Rajapur"),
    "844601" => array ( "Area" => "Bardia", "City" => "Rajapur"),
    "844600" => array ( "Area" => "Bardia", "City" => "Rajapur"),
    "844304" => array ( "Area" => "Bardia", "City" => "Taratal"),
    "844303" => array ( "Area" => "Bardia", "City" => "Taratal"),
    "844302" => array ( "Area" => "Bardia", "City" => "Taratal"),
    "844301" => array ( "Area" => "Bardia", "City" => "Taratal"),
    "844300" => array ( "Area" => "Bardia", "City" => "Taratal"),
    "835404" => array ( "Area" => "Surkhet", "City" => "Chhinchu"),
    "835403" => array ( "Area" => "Surkhet", "City" => "Chhinchu"),
    "835402" => array ( "Area" => "Surkhet", "City" => "Chhinchu"),
    "835401" => array ( "Area" => "Surkhet", "City" => "Chhinchu"),
    "835400" => array ( "Area" => "Surkhet", "City" => "Chhinchu"),
    "825804" => array ( "Area" => "Dang", "City" => "Lalmattya"),
    "825803" => array ( "Area" => "Dang", "City" => "Lalmattya"),
    "825802" => array ( "Area" => "Dang", "City" => "Lalmattya"),
    "825801" => array ( "Area" => "Dang", "City" => "Lalmattya"),
    "825800" => array ( "Area" => "Dang", "City" => "Lalmattya"),
    "825404" => array ( "Area" => "Dang", "City" => "Lamahi"),
    "825403" => array ( "Area" => "Dang", "City" => "Lamahi"),
    "825402" => array ( "Area" => "Dang", "City" => "Lamahi"),
    "825401" => array ( "Area" => "Dang", "City" => "Lamahi"),
    "825400" => array ( "Area" => "Dang", "City" => "Lamahi"),
    "815404" => array ( "Area" => "Banke", "City" => "Kohalpur"),
    "815403" => array ( "Area" => "Banke", "City" => "Kohalpur"),
    "815402" => array ( "Area" => "Banke", "City" => "Kohalpur"),
    "815401" => array ( "Area" => "Banke", "City" => "Kohalpur"),
    "815400" => array ( "Area" => "Banke", "City" => "Kohalpur"),
    "795204" => array ( "Area" => "Gulmi", "City" => "Tamghas"),
    "795203" => array ( "Area" => "Gulmi", "City" => "Tamghas"),
    "795202" => array ( "Area" => "Gulmi", "City" => "Tamghas"),
    "795201" => array ( "Area" => "Gulmi", "City" => "Tamghas"),
    "795200" => array ( "Area" => "Gulmi", "City" => "Tamghas"),
    "785804" => array ( "Area" => "N. Parasi", "City" => "Bargadhat"),
    "785803" => array ( "Area" => "N. Parasi", "City" => "Bargadhat"),
    "785802" => array ( "Area" => "N. Parasi", "City" => "Bargadhat"),
    "785801" => array ( "Area" => "N. Parasi", "City" => "Bargadhat"),
    "785800" => array ( "Area" => "N. Parasi", "City" => "Bargadhat"),
    "785704" => array ( "Area" => "N. Parasi", "City" => "Sunwol"),
    "785703" => array ( "Area" => "N. Parasi", "City" => "Sunwol"),
    "785702" => array ( "Area" => "N. Parasi", "City" => "Sunwol"),
    "785701" => array ( "Area" => "N. Parasi", "City" => "Sunwol"),
    "785700" => array ( "Area" => "N. Parasi", "City" => "Sunwol"),
    "785404" => array ( "Area" => "A. Khachi", "City" => "Kowasiti"),
    "785403" => array ( "Area" => "A. Khachi", "City" => "Kowasiti"),
    "785402" => array ( "Area" => "A. Khachi", "City" => "Kowasiti"),
    "785401" => array ( "Area" => "A. Khachi", "City" => "Kowasiti"),
    "785400" => array ( "Area" => "A. Khachi", "City" => "Kowasiti"),
    "774204" => array ( "Area" => "A. Khachi", "City" => "Sandhikharka"),
    "774203" => array ( "Area" => "A. Khachi", "City" => "Sandhikharka"),
    "774202" => array ( "Area" => "A. Khachi", "City" => "Sandhikharka"),
    "774201" => array ( "Area" => "A. Khachi", "City" => "Sandhikharka"),
    "774200" => array ( "Area" => "A. Khachi", "City" => "Sandhikharka"),
    "715804" => array ( "Area" => "Rupandehi", "City" => "Lumbini"),
    "715803" => array ( "Area" => "Rupandehi", "City" => "Lumbini"),
    "715802" => array ( "Area" => "Rupandehi", "City" => "Lumbini"),
    "715801" => array ( "Area" => "Rupandehi", "City" => "Lumbini"),
    "715800" => array ( "Area" => "Rupandehi", "City" => "Lumbini"),
    "695204" => array ( "Area" => "Myagdi", "City" => "Beni"),
    "695203" => array ( "Area" => "Myagdi", "City" => "Beni"),
    "695202" => array ( "Area" => "Myagdi", "City" => "Beni"),
    "695201" => array ( "Area" => "Myagdi", "City" => "Beni"),
    "695200" => array ( "Area" => "Myagdi", "City" => "Beni"),
    "675204" => array ( "Area" => "Parbat", "City" => "Kusma"),
    "675203" => array ( "Area" => "Parbat", "City" => "Kusma"),
    "675202" => array ( "Area" => "Parbat", "City" => "Kusma"),
    "675201" => array ( "Area" => "Parbat", "City" => "Kusma"),
    "675200" => array ( "Area" => "Parbat", "City" => "Kusma"),
    "665204" => array ( "Area" => "Lamjung", "City" => "Besisahar"),
    "665203" => array ( "Area" => "Lamjung", "City" => "Besisahar"),
    "665202" => array ( "Area" => "Lamjung", "City" => "Besisahar"),
    "665201" => array ( "Area" => "Lamjung", "City" => "Besisahar"),
    "665200" => array ( "Area" => "Lamjung", "City" => "Besisahar"),
    "655804" => array ( "Area" => "Gorkha", "City" => "Dumre"),
    "655803" => array ( "Area" => "Gorkha", "City" => "Dumre"),
    "655802" => array ( "Area" => "Gorkha", "City" => "Dumre"),
    "655801" => array ( "Area" => "Gorkha", "City" => "Dumre"),
    "655800" => array ( "Area" => "Gorkha", "City" => "Dumre"),
    "655404" => array ( "Area" => "Gorkha", "City" => "Ambukhairani"),
    "655403" => array ( "Area" => "Gorkha", "City" => "Ambukhairani"),
    "655402" => array ( "Area" => "Gorkha", "City" => "Ambukhairani"),
    "655401" => array ( "Area" => "Gorkha", "City" => "Ambukhairani"),
    "655400" => array ( "Area" => "Gorkha", "City" => "Ambukhairani"),
    "634604" => array ( "Area" => "Syangia", "City" => "Galvang Bazar"),
    "634603" => array ( "Area" => "Syangia", "City" => "Galvang Bazar"),
    "634602" => array ( "Area" => "Syangia", "City" => "Galvang Bazar"),
    "634601" => array ( "Area" => "Syangia", "City" => "Galvang Bazar"),
    "634600" => array ( "Area" => "Syangia", "City" => "Galvang Bazar"),
    "634404" => array ( "Area" => "Syangia", "City" => "Walling"),
    "634403" => array ( "Area" => "Syangia", "City" => "Walling"),
    "634402" => array ( "Area" => "Syangia", "City" => "Walling"),
    "634401" => array ( "Area" => "Syangia", "City" => "Walling"),
    "634400" => array ( "Area" => "Syangia", "City" => "Walling"),
    "634204" => array ( "Area" => "Kaski", "City" => "Syangja"),
    "634203" => array ( "Area" => "Kaski", "City" => "Syangja"),
    "634202" => array ( "Area" => "Kaski", "City" => "Syangja"),
    "634201" => array ( "Area" => "Kaski", "City" => "Syangja"),
    "634200" => array ( "Area" => "Kaski", "City" => "Syangja"),
    "575404" => array ( "Area" => "Makwanpur", "City" => "Bhimphedi"),
    "575403" => array ( "Area" => "Makwanpur", "City" => "Bhimphedi"),
    "575402" => array ( "Area" => "Makwanpur", "City" => "Bhimphedi"),
    "575401" => array ( "Area" => "Makwanpur", "City" => "Bhimphedi"),
    "575400" => array ( "Area" => "Makwanpur", "City" => "Bhimphedi"),
    "565804" => array ( "Area" => "Chitwan", "City" => "Sauraha"),
    "565803" => array ( "Area" => "Chitwan", "City" => "Sauraha"),
    "565802" => array ( "Area" => "Chitwan", "City" => "Sauraha"),
    "565801" => array ( "Area" => "Chitwan", "City" => "Sauraha"),
    "565800" => array ( "Area" => "Chitwan", "City" => "Sauraha"),
    "565404" => array ( "Area" => "Rautahat", "City" => "Mugling"),
    "565403" => array ( "Area" => "Rautahat", "City" => "Mugling"),
    "565402" => array ( "Area" => "Rautahat", "City" => "Mugling"),
    "565401" => array ( "Area" => "Rautahat", "City" => "Mugling"),
    "565400" => array ( "Area" => "Rautahat", "City" => "Mugling"),
    "555404" => array ( "Area" => "Rautahat", "City" => "Chandranigahpur"),
    "555403" => array ( "Area" => "Rautahat", "City" => "Chandranigahpur"),
    "555402" => array ( "Area" => "Rautahat", "City" => "Chandranigahpur"),
    "555401" => array ( "Area" => "Rautahat", "City" => "Chandranigahpur"),
    "555400" => array ( "Area" => "Rautahat", "City" => "Chandranigahpur"),
    "535404" => array ( "Area" => "Bara", "City" => "Nijgadh"),
    "535403" => array ( "Area" => "Bara", "City" => "Nijgadh"),
    "535402" => array ( "Area" => "Bara", "City" => "Nijgadh"),
    "535401" => array ( "Area" => "Bara", "City" => "Nijgadh"),
    "535400" => array ( "Area" => "Bara", "City" => "Nijgadh"),
    "515604" => array ( "Area" => "Parsa", "City" => "Pokharia"),
    "515603" => array ( "Area" => "Parsa", "City" => "Pokharia"),
    "515602" => array ( "Area" => "Parsa", "City" => "Pokharia"),
    "515601" => array ( "Area" => "Parsa", "City" => "Pokharia"),
    "515600" => array ( "Area" => "Parsa", "City" => "Pokharia"),
    "494204" => array ( "Area" => "Dolkha", "City" => "Charikot"),
    "494203" => array ( "Area" => "Dolkha", "City" => "Charikot"),
    "494202" => array ( "Area" => "Dolkha", "City" => "Charikot"),
    "494201" => array ( "Area" => "Dolkha", "City" => "Charikot"),
    "494200" => array ( "Area" => "Dolkha", "City" => "Charikot"),
    "485404" => array ( "Area" => "Sindhuli", "City" => "Manthali"),
    "485403" => array ( "Area" => "Sindhuli", "City" => "Manthali"),
    "485402" => array ( "Area" => "Sindhuli", "City" => "Manthali"),
    "485401" => array ( "Area" => "Sindhuli", "City" => "Manthali"),
    "485400" => array ( "Area" => "Sindhuli", "City" => "Manthali"),
    "475204" => array ( "Area" => "Sindhuli", "City" => "Sindhuli Madi"),
    "475203" => array ( "Area" => "Sindhuli", "City" => "Sindhuli Madi"),
    "475202" => array ( "Area" => "Sindhuli", "City" => "Sindhuli Madi"),
    "475201" => array ( "Area" => "Sindhuli", "City" => "Sindhuli Madi"),
    "475200" => array ( "Area" => "Sindhuli", "City" => "Sindhuli Madi"),
    "465404" => array ( "Area" => "Sarlahi", "City" => "Barathhawa"),
    "465403" => array ( "Area" => "Sarlahi", "City" => "Barathhawa"),
    "465402" => array ( "Area" => "Sarlahi", "City" => "Barathhawa"),
    "465401" => array ( "Area" => "Sarlahi", "City" => "Barathhawa"),
    "465400" => array ( "Area" => "Sarlahi", "City" => "Barathhawa"),
    "445404" => array ( "Area" => "Mahottari", "City" => "Matihani"),
    "445403" => array ( "Area" => "Mahottari", "City" => "Matihani"),
    "445402" => array ( "Area" => "Mahottari", "City" => "Matihani"),
    "445401" => array ( "Area" => "Mahottari", "City" => "Matihani"),
    "445400" => array ( "Area" => "Mahottari", "City" => "Matihani"),
    "415404" => array ( "Area" => "Dhanusha", "City" => "Mahendranagar"),
    "415403" => array ( "Area" => "Dhanusha", "City" => "Mahendranagar"),
    "415402" => array ( "Area" => "Dhanusha", "City" => "Mahendranagar"),
    "415401" => array ( "Area" => "Dhanusha", "City" => "Mahendranagar"),
    "415400" => array ( "Area" => "Dhanusha", "City" => "Mahendranagar"),
    "386404" => array ( "Area" => "Solukhumbu", "City" => "Namche"),
    "386403" => array ( "Area" => "Solukhumbu", "City" => "Namche"),
    "386402" => array ( "Area" => "Solukhumbu", "City" => "Namche"),
    "386401" => array ( "Area" => "Solukhumbu", "City" => "Namche"),
    "386400" => array ( "Area" => "Solukhumbu", "City" => "Namche"),
    "386204" => array ( "Area" => "Solukhumbu", "City" => "Salleri"),
    "386203" => array ( "Area" => "Solukhumbu", "City" => "Salleri"),
    "386202" => array ( "Area" => "Solukhumbu", "City" => "Salleri"),
    "386201" => array ( "Area" => "Solukhumbu", "City" => "Salleri"),
    "386200" => array ( "Area" => "Solukhumbu", "City" => "Salleri"),
    "375404" => array ( "Area" => "Okhaldhunga", "City" => "Rumjatar"),
    "375403" => array ( "Area" => "Okhaldhunga", "City" => "Rumjatar"),
    "375402" => array ( "Area" => "Okhaldhunga", "City" => "Rumjatar"),
    "375401" => array ( "Area" => "Okhaldhunga", "City" => "Rumjatar"),
    "375400" => array ( "Area" => "Okhaldhunga", "City" => "Rumjatar"),
    "375204" => array ( "Area" => "Okhaldhunga", "City" => "Okhaldhunga"),
    "375203" => array ( "Area" => "Okhaldhunga", "City" => "Okhaldhunga"),
    "375202" => array ( "Area" => "Okhaldhunga", "City" => "Okhaldhunga"),
    "375201" => array ( "Area" => "Okhaldhunga", "City" => "Okhaldhunga"),
    "375200" => array ( "Area" => "Okhaldhunga", "City" => "Okhaldhunga"),
    "364204" => array ( "Area" => "Khotang", "City" => "Diktel"),
    "364203" => array ( "Area" => "Khotang", "City" => "Diktel"),
    "364202" => array ( "Area" => "Khotang", "City" => "Diktel"),
    "364201" => array ( "Area" => "Khotang", "City" => "Diktel"),
    "364200" => array ( "Area" => "Khotang", "City" => "Diktel"),
    "354204" => array ( "Area" => "Udaypur", "City" => "Gaighat"),
    "354203" => array ( "Area" => "Udaypur", "City" => "Gaighat"),
    "354202" => array ( "Area" => "Udaypur", "City" => "Gaighat"),
    "354201" => array ( "Area" => "Udaypur", "City" => "Gaighat"),
    "354200" => array ( "Area" => "Udaypur", "City" => "Gaighat"),
    "335804" => array ( "Area" => "Sagarmatha", "City" => "Mirchaiya"),
    "335803" => array ( "Area" => "Sagarmatha", "City" => "Mirchaiya"),
    "335802" => array ( "Area" => "Sagarmatha", "City" => "Mirchaiya"),
    "335801" => array ( "Area" => "Sagarmatha", "City" => "Mirchaiya"),
    "335800" => array ( "Area" => "Sagarmatha", "City" => "Mirchaiya"),
    "315404" => array ( "Area" => "S. Sabha", "City" => "Kalyanpur"),
    "315403" => array ( "Area" => "S. Sabha", "City" => "Kalyanpur"),
    "315402" => array ( "Area" => "S. Sabha", "City" => "Kalyanpur"),
    "315401" => array ( "Area" => "S. Sabha", "City" => "Kalyanpur"),
    "315400" => array ( "Area" => "S. Sabha", "City" => "Kalyanpur"),
    "295704" => array ( "Area" => "S. Sabha", "City" => "Chainpur"),
    "295703" => array ( "Area" => "S. Sabha", "City" => "Chainpur"),
    "295702" => array ( "Area" => "S. Sabha", "City" => "Chainpur"),
    "295701" => array ( "Area" => "S. Sabha", "City" => "Chainpur"),
    "295700" => array ( "Area" => "S. Sabha", "City" => "Chainpur"),
    "294204" => array ( "Area" => "Bhojpur", "City" => "Bhojpur"),
    "294203" => array ( "Area" => "Bhojpur", "City" => "Bhojpur"),
    "294202" => array ( "Area" => "Bhojpur", "City" => "Bhojpur"),
    "294201" => array ( "Area" => "Bhojpur", "City" => "Bhojpur"),
    "294200" => array ( "Area" => "Bhojpur", "City" => "Bhojpur"),
    "275404" => array ( "Area" => "Ilam", "City" => "Fikkal"),
    "275403" => array ( "Area" => "Ilam", "City" => "Fikkal"),
    "275402" => array ( "Area" => "Ilam", "City" => "Fikkal"),
    "275401" => array ( "Area" => "Ilam", "City" => "Fikkal"),
    "275400" => array ( "Area" => "Ilam", "City" => "Fikkal"),
    "265404" => array ( "Area" => "Dhankuta", "City" => "Hile"),
    "265403" => array ( "Area" => "Dhankuta", "City" => "Hile"),
    "265402" => array ( "Area" => "Dhankuta", "City" => "Hile"),
    "265401" => array ( "Area" => "Dhankuta", "City" => "Hile"),
    "265400" => array ( "Area" => "Dhankuta", "City" => "Hile"),
    "255624" => array ( "Area" => "Sunsari", "City" => "Jhumka"),
    "255623" => array ( "Area" => "Sunsari", "City" => "Jhumka"),
    "255622" => array ( "Area" => "Sunsari", "City" => "Jhumka"),
    "255621" => array ( "Area" => "Sunsari", "City" => "Jhumka"),
    "255620" => array ( "Area" => "Sunsari", "City" => "Jhumka"),
    "245204" => array ( "Area" => "Panchthar", "City" => "Phidim"),
    "245203" => array ( "Area" => "Panchthar", "City" => "Phidim"),
    "245202" => array ( "Area" => "Panchthar", "City" => "Phidim"),
    "245201" => array ( "Area" => "Panchthar", "City" => "Phidim"),
    "245200" => array ( "Area" => "Panchthar", "City" => "Phidim"),
    "235554" => array ( "Area" => "S. Palchok", "City" => "Buddhabare"),
    "235553" => array ( "Area" => "S. Palchok", "City" => "Buddhabare"),
    "235552" => array ( "Area" => "S. Palchok", "City" => "Buddhabare"),
    "235551" => array ( "Area" => "S. Palchok", "City" => "Buddhabare"),
    "235550" => array ( "Area" => "S. Palchok", "City" => "Buddhabare"),
    "235504" => array ( "Area" => "S. Palchok", "City" => "Surungga"),
    "235503" => array ( "Area" => "S. Palchok", "City" => "Surungga"),
    "235502" => array ( "Area" => "S. Palchok", "City" => "Surungga"),
    "235501" => array ( "Area" => "S. Palchok", "City" => "Surungga"),
    "235500" => array ( "Area" => "S. Palchok", "City" => "Surungga"),
    "235394" => array ( "Area" => "Mechi", "City" => "Damak pmp"),
    "235393" => array ( "Area" => "Mechi", "City" => "Damak pmp"),
    "235392" => array ( "Area" => "Mechi", "City" => "Damak pmp"),
    "235391" => array ( "Area" => "Mechi", "City" => "Damak pmp"),
    "235390" => array ( "Area" => "Mechi", "City" => "Damak pmp"),
    "215804" => array ( "Area" => "Morang", "City" => "Rangeli"),
    "215803" => array ( "Area" => "Morang", "City" => "Rangeli"),
    "215802" => array ( "Area" => "Morang", "City" => "Rangeli"),
    "215801" => array ( "Area" => "Morang", "City" => "Rangeli"),
    "215800" => array ( "Area" => "Morang", "City" => "Rangeli"),
    "215554" => array ( "Area" => "Ilam", "City" => "Pathari"),
    "215553" => array ( "Area" => "Ilam", "City" => "Pathari"),
    "215552" => array ( "Area" => "Ilam", "City" => "Pathari"),
    "215551" => array ( "Area" => "Ilam", "City" => "Pathari"),
    "215550" => array ( "Area" => "Ilam", "City" => "Pathari"),
    "115204" => array ( "Area" => "S. Palchok", "City" => "Chautara"),
    "115203" => array ( "Area" => "S. Palchok", "City" => "Chautara"),
    "115202" => array ( "Area" => "S. Palchok", "City" => "Chautara"),
    "115201" => array ( "Area" => "S. Palchok", "City" => "Chautara"),
    "115200" => array ( "Area" => "S. Palchok", "City" => "Chautara"),
    "105404" => array ( "Area" => "Rasuwa", "City" => "Dhunche"),
    "105403" => array ( "Area" => "Rasuwa", "City" => "Dhunche"),
    "105402" => array ( "Area" => "Rasuwa", "City" => "Dhunche"),
    "105401" => array ( "Area" => "Rasuwa", "City" => "Dhunche"),
    "105400" => array ( "Area" => "Rasuwa", "City" => "Dhunche"),
    "99524" => array ( "Area" => "Mahakali", "City" => "Mahendranagar"),
    "99523" => array ( "Area" => "Mahakali", "City" => "Mahendranagar"),
    "99522" => array ( "Area" => "Mahakali", "City" => "Mahendranagar"),
    "99521" => array ( "Area" => "Mahakali", "City" => "Mahendranagar"),
    "99520" => array ( "Area" => "Mahakali", "City" => "Mahendranagar"),
    "94440" => array ( "Area" => "Doti", "City" => "Dipayal"),
    "94420" => array ( "Area" => "Doti", "City" => "S. Doti"),
    "91551" => array ( "Area" => "Kailali", "City" => "Attaria"),
    "91550" => array ( "Area" => "Kailali", "City" => "Attaria"),
    "91560" => array ( "Area" => "Kailali", "City" => "Tikapur"),
    "91524" => array ( "Area" => "Kalikot", "City" => "Dhangadhi"),
    "91523" => array ( "Area" => "Kalikot", "City" => "Dhangadhi"),
    "91522" => array ( "Area" => "Kalikot", "City" => "Dhangadhi"),
    "91521" => array ( "Area" => "Kalikot", "City" => "Dhangadhi"),
    "91520" => array ( "Area" => "Kalikot", "City" => "Dhangadhi"),
    "84420" => array ( "Area" => "Surkhet", "City" => "Guleria"),
    "83521" => array ( "Area" => "Surkhet", "City" => "Surkhet"),
    "83520" => array ( "Area" => "Surkhet", "City" => "Surkhet"),
    "82561" => array ( "Area" => "Dang", "City" => "Ghorai"),
    "82560" => array ( "Area" => "Dang", "City" => "Ghorai"),
    "82521" => array ( "Area" => "Dailekh", "City" => "Tulsipur"),
    "82520" => array ( "Area" => "Dailekh", "City" => "Tulsipur"),
    "81560" => array ( "Area" => "Banke", "City" => "Khajura"),
    "81525" => array ( "Area" => "Gulmi", "City" => "Nepaljunj"),
    "81524" => array ( "Area" => "Gulmi", "City" => "Nepaljunj"),
    "81523" => array ( "Area" => "Gulmi", "City" => "Nepaljunj"),
    "81522" => array ( "Area" => "Gulmi", "City" => "Nepaljunj"),
    "81521" => array ( "Area" => "Gulmi", "City" => "Nepaljunj"),
    "81520" => array ( "Area" => "Gulmi", "City" => "Nepaljunj"),
    "78520" => array ( "Area" => "A. Khachi", "City" => "Parasi"),
    "78560" => array ( "Area" => "N. Parasi", "City" => "Tribeni"),
    "76560" => array ( "Area" => "Kapilvastu", "City" => "Taulihawa"),
    "76521" => array ( "Area" => "Kapilvastu", "City" => "Krishnanagar"),
    "76520" => array ( "Area" => "Kapilvastu", "City" => "Krishnanagar"),
    "75521" => array ( "Area" => "Palpa", "City" => "Tansen"),
    "75520" => array ( "Area" => "Palpa", "City" => "Tansen"),
    "71562" => array ( "Area" => "Rupandehi", "City" => "Manglapur"),
    "71561" => array ( "Area" => "Rupandehi", "City" => "Manglapur"),
    "71560" => array ( "Area" => "Rupandehi", "City" => "Manglapur"),
    "68521" => array ( "Area" => "Baglung", "City" => "Baglung"),
    "68520" => array ( "Area" => "Baglung", "City" => "Baglung"),
    "65561" => array ( "Area" => "Gorkha", "City" => "Damauli"),
    "65560" => array ( "Area" => "Gorkha", "City" => "Damauli"),
    "64460" => array ( "Area" => "Gorkha", "City" => "Manakamna"),
    "64420" => array ( "Area" => "Gorkha", "City" => "Gorkha"),
    "61560" => array ( "Area" => "Kaski", "City" => "Sisuwa"),
    "57524" => array ( "Area" => "Chitwan", "City" => "Hetauda"),
    "57523" => array ( "Area" => "Chitwan", "City" => "Hetauda"),
    "57522" => array ( "Area" => "Chitwan", "City" => "Hetauda"),
    "57521" => array ( "Area" => "Chitwan", "City" => "Hetauda"),
    "57520" => array ( "Area" => "Chitwan", "City" => "Hetauda"),
    "56583" => array ( "Area" => "Chitwan", "City" => "Parsa Khairani"),
    "56582" => array ( "Area" => "Chitwan", "City" => "Parsa Khairani"),
    "56581" => array ( "Area" => "Chitwan", "City" => "Rampur"),
    "56562" => array ( "Area" => "Rautahat", "City" => "Tandi"),
    "56561" => array ( "Area" => "Rautahat", "City" => "Tandi"),
    "56560" => array ( "Area" => "Rautahat", "City" => "Tandi"),
    "55520" => array ( "Area" => "Rautahat", "City" => "Gaur"),
    "53550" => array ( "Area" => "Bara", "City" => "Kalaiya"),
    "53520" => array ( "Area" => "Parsa", "City" => "Simara"),
    "51570" => array ( "Area" => "Parsa", "City" => "Parwanipur"),
    "46520" => array ( "Area" => "Mahottari", "City" => "Malangwa"),
    "44520" => array ( "Area" => "Dhanusha", "City" => "Jaleswar"),
    "41528" => array ( "Area" => "Solukhumbu", "City" => "Janakpur"),
    "41527" => array ( "Area" => "Solukhumbu", "City" => "Janakpur"),
    "41526" => array ( "Area" => "Solukhumbu", "City" => "Janakpur"),
    "41525" => array ( "Area" => "Solukhumbu", "City" => "Janakpur"),
    "41524" => array ( "Area" => "Solukhumbu", "City" => "Janakpur"),
    "41523" => array ( "Area" => "Solukhumbu", "City" => "Janakpur"),
    "41522" => array ( "Area" => "Solukhumbu", "City" => "Janakpur"),
    "41521" => array ( "Area" => "Solukhumbu", "City" => "Janakpur"),
    "41520" => array ( "Area" => "Solukhumbu", "City" => "Janakpur"),
    "33561" => array ( "Area" => "Siraha", "City" => "Lahan"),
    "33560" => array ( "Area" => "Siraha", "City" => "Lahan"),
    "33520" => array ( "Area" => "Siraha", "City" => "Siraha"),
    "31580" => array ( "Area" => "Saptari", "City" => "Hanumannagar"),
    "31560" => array ( "Area" => "Saptari", "City" => "Kanchanpur"),
    "31521" => array ( "Area" => "S. Sabha", "City" => "Rajbiraj"),
    "31520" => array ( "Area" => "S. Sabha", "City" => "Rajbiraj"),
    "29560" => array ( "Area" => "Bhojpur", "City" => "Khandbari"),
    "27560" => array ( "Area" => "Ilam", "City" => "Pashupatinagar"),
    "27521" => array ( "Area" => "Taplejung", "City" => "Ilam"),
    "27520" => array ( "Area" => "Taplejung", "City" => "Ilam"),
    "26460" => array ( "Area" => "Terhathum", "City" => "Terhathum"),
    "26521" => array ( "Area" => "Dhankuta", "City" => "Dhankuta"),
    "26520" => array ( "Area" => "Dhankuta", "City" => "Dhankuta"),
    "25561" => array ( "Area" => "Sunsari", "City" => "Inerwa"),
    "25560" => array ( "Area" => "Sunsari", "City" => "Inerwa"),
    "25541" => array ( "Area" => "Morang", "City" => "Duhabi"),
    "25540" => array ( "Area" => "Morang", "City" => "Duhabi"),
    "24560" => array ( "Area" => "Taplejung", "City" => "Taplejung"),
    "23581" => array ( "Area" => "Mechi", "City" => "Damak"),
    "23580" => array ( "Area" => "Mechi", "City" => "Damak"),
    "23570" => array ( "Area" => "Jhapa", "City" => "Kakadvitta"),
    "23544" => array ( "Area" => "S. Palchok", "City" => "Birtamod"),
    "23543" => array ( "Area" => "S. Palchok", "City" => "Birtamod"),
    "23542" => array ( "Area" => "S. Palchok", "City" => "Birtamod"),
    "23541" => array ( "Area" => "S. Palchok", "City" => "Birtamod"),
    "23540" => array ( "Area" => "S. Palchok", "City" => "Birtamod"),
    "23523" => array ( "Area" => "S. Palchok", "City" => "Bhadrapur"),
    "23522" => array ( "Area" => "S. Palchok", "City" => "Bhadrapur"),
    "23521" => array ( "Area" => "S. Palchok", "City" => "Bhadrapur"),
    "23520" => array ( "Area" => "S. Palchok", "City" => "Bhadrapur"),
    "23461" => array ( "Area" => "Jhapa", "City" => "Dhulabarj"),
    "23460" => array ( "Area" => "Jhapa", "City" => "Dhulabarj"),
    "21549" => array ( "Area" => "Morang", "City" => "Birathagar pmp"),
    "21560" => array ( "Area" => "Morang", "City" => "Letang"),
    "21540" => array ( "Area" => "Ilam", "City" => "Urlabari"),
    "16680" => array ( "Area" => "Bhaktapur", "City" => "Nagarkot"),
    "15584" => array ( "Area" => "Bhaktapur", "City" => "Lubhu"),
    "15583" => array ( "Area" => "Bhaktapur", "City" => "Lubhu"),
    "15582" => array ( "Area" => "Bhaktapur", "City" => "Lubhu"),
    "15581" => array ( "Area" => "Bhaktapur", "City" => "Sanagaun"),
    "15580" => array ( "Area" => "Bhaktapur", "City" => "Lubhu"),
    "15572" => array ( "Area" => "Bhaktapur", "City" => "Thecho"),
    "15571" => array ( "Area" => "Bhaktapur", "City" => "Thecho"),
    "15570" => array ( "Area" => "Bhaktapur", "City" => "Thecho"),
    "15563" => array ( "Area" => "Bhaktapur", "City" => "Thaiba"),
    "15562" => array ( "Area" => "Bhaktapur", "City" => "Thaiba"),
    "15561" => array ( "Area" => "Bhaktapur", "City" => "Thaiba"),
    "15560" => array ( "Area" => "Bhaktapur", "City" => "Thaiba"),
    "14459" => array ( "Area" => "Kathmandu", "City" => "Chabahil"),
    "14458" => array ( "Area" => "Kathmandu", "City" => "Chabahil"),
    "14457" => array ( "Area" => "Kathmandu", "City" => "Chabahil"),
    "14456" => array ( "Area" => "Kathmandu", "City" => "Chabahil"),
    "14455" => array ( "Area" => "Kathmandu", "City" => "Indrayani"),
    "11565" => array ( "Area" => "S. Palchok", "City" => "Banepa"),
    "11564" => array ( "Area" => "S. Palchok", "City" => "Banepa"),
    "11563" => array ( "Area" => "S. Palchok", "City" => "Banepa"),
    "11562" => array ( "Area" => "S. Palchok", "City" => "Banepa"),
    "11561" => array ( "Area" => "S. Palchok", "City" => "Banepa"),
    "11560" => array ( "Area" => "S. Palchok", "City" => "Banepa"),
    "10560" => array ( "Area" => "Nuwakot", "City" => "Trishuli"),
    "10520" => array ( "Area" => "Dhading", "City" => "Dhading"),
    "7154" => array ( "Area" => "Myagdi", "City" => "Butwal"),
    "7152" => array ( "Area" => "Myagdi", "City" => "Bhairahawa"),
    "6153" => array ( "Area" => "Makwanpur", "City" => "Pokhara"),
    "6152" => array ( "Area" => "Makwanpur", "City" => "Pokhara"),
    "5652" => array ( "Area" => "Rautahat", "City" => "Bharatpur"),
    "5153" => array ( "Area" => "Dolkha", "City" => "Birgunj"),
    "5152" => array ( "Area" => "Dolkha", "City" => "Birgunj"),
    "2558" => array ( "Area" => "Sunsari", "City" => "Itahari"),
    "2553" => array ( "Area" => "Morang", "City" => "Dharan"),
    "2552" => array ( "Area" => "Morang", "City" => "Dharan"),
    "2153" => array ( "Area" => "Ilam", "City" => "Biratnagar"),
    "2152" => array ( "Area" => "Ilam", "City" => "Biratnagar"),
    "1664" => array ( "Area" => "Bhaktapur", "City" => "Thimi"),
    "1663" => array ( "Area" => "Bhaktapur", "City" => "Thimi"),
    "1662" => array ( "Area" => "Bhaktapur", "City" => "Bhaktapur"),
    "1661" => array ( "Area" => "Bhaktapur", "City" => "Bhaktapur"),
    "1555" => array ( "Area" => "Bhaktapur", "City" => "Patan"),
    "1554" => array ( "Area" => "Bhaktapur", "City" => "Patan"),
    "1553" => array ( "Area" => "Bhaktapur", "City" => "Patan"),
    "1552" => array ( "Area" => "Bhaktapur", "City" => "Patan"),
    "1478" => array ( "Area" => "Kathmandu", "City" => "Babarmahal (TTC)"),
    "1477" => array ( "Area" => "Kathmandu", "City" => "Ghattekulo"),
    "1471" => array ( "Area" => "Kathmandu", "City" => "Dakchhinkali"),
    "1449" => array ( "Area" => "Kathmandu", "City" => "Chabahil"),
    "1448" => array ( "Area" => "Kathmandu", "City" => "Chabahil"),
    "1447" => array ( "Area" => "Kathmandu", "City" => "Chabahil"),
    "1446" => array ( "Area" => "Kathmandu", "City" => "Chabahil"),
    "1444" => array ( "Area" => "Kathmandu", "City" => "Naxal"),
    "1443" => array ( "Area" => "Kathmandu", "City" => "Naxal"),
    "1442" => array ( "Area" => "Kathmandu", "City" => "Naxal"),
    "1441" => array ( "Area" => "Kathmandu", "City" => "Naxal"),
    "1440" => array ( "Area" => "Kathmandu", "City" => "Naxal"),
    "1437" => array ( "Area" => "Kathmandu", "City" => "Bhadrakali"),
    "1436" => array ( "Area" => "Kathmandu", "City" => "Gongabu"),
    "1435" => array ( "Area" => "Kathmandu", "City" => "Gongabu"),
    "1433" => array ( "Area" => "Kathmandu", "City" => "Kirtipur"),
    "1432" => array ( "Area" => "Kathmandu", "City" => "Balambu"),
    "1431" => array ( "Area" => "Kathmandu", "City" => "Balambu"),
    "1428" => array ( "Area" => "Kathmandu", "City" => "Chhauni"),
    "1427" => array ( "Area" => "Kathmandu", "City" => "Chhauni"),
    "1426" => array ( "Area" => "Kathmandu", "City" => "Central"),
    "1425" => array ( "Area" => "Kathmandu", "City" => "Central"),
    "1424" => array ( "Area" => "Kathmandu", "City" => "Central"),
    "1423" => array ( "Area" => "Kathmandu", "City" => "Central"),
    "1422" => array ( "Area" => "Kathmandu", "City" => "Central"),
    "1421" => array ( "Area" => "Kathmandu", "City" => "Central")
  );
  foreach ( $prefixes as $prefix => $data)
  {
    if ( (int) substr ( $parameters["Number"], 4, strlen ( $prefix)) == $prefix)
    {
      if ( substr ( $parameters["Number"], 4, 1) == "1" && substr ( $parameters["Number"], 5, 1) != "0" && substr ( $parameters["Number"], 5, 1) != "1")
      {
        $prefix = "1";
        $local = substr ( $parameters["Number"], 4, 1) . " " . substr ( $parameters["Number"], 5, 4) . " " . substr ( $parameters["Number"], 9);
      } else {
        $prefix = substr ( $parameters["Number"], 4, 2);
        $local = substr ( $parameters["Number"], 4, 2) . " " . substr ( $parameters["Number"], 6, 3) . " " . substr ( $parameters["Number"], 9);
      }
      return array_merge_recursive ( ( is_array ( $buffer) ? $buffer : array ()), array ( "CC" => "977", "NDC" => $prefix, "Country" => "Nepal", "Area" => $data["Area"], "City" => $data["City"], "Operator" => "", "SN" => substr ( $parameters["Number"], 4 + strlen ( $prefix)), "Type" => VD_PHONETYPE_LANDLINE, "CallFormats" => array ( "Local" => $local, "International" => "+977 " . $local)));
    }
  }

  /**
   * If reached here, number wasn't identified as a valid Nepalian phone number
   */
  return ( is_array ( $buffer) ? $buffer : false);
}
?>
