<?php
/**   ___ ___       ___ _______     ______                        __
 *   |   Y   .-----|   |   _   |   |   _  \ .-----.--------.---.-|__.-----.
 *   |.  |   |  _  |.  |.  1   |   |.  |   \|  _  |        |  _  |  |     |
 *   |.  |   |_____|.  |.  ____|   |.  |    |_____|__|__|__|___._|__|__|__|
 *   |:  1   |     |:  |:  |       |:  1    /
 *    \:.. ./      |::.|::.|       |::.. . /
 *     `---'       `---`---'       `------'
 *
 * Copyright (C) 2016-2025 Ernani José Camargo Azevedo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * VoIP Domain country database module filters. This module add the filter calls
 * related to country database of United States of America.
 *
 * Reference: https://www.itu.int/oth/T02020000DE/en (2006-11-22)
 *            https://www.nationalpooling.com/reports/region/AllBlocksAugmentedReport.zip (2023-02-13)
 *
 * Glossary:
 *  CC - Country Code
 *  NDC - National Destination Code (also known as area code)
 *  N(S)N - National (Significant) Number
 *  SN - Subscriber Number
 *
 * @author     Ernani José Camargo Azevedo <azevedo@voipdomain.io>
 * @version    1.0
 * @package    VoIP Domain
 * @subpackage CountryDB
 * @copyright  2016-2025 Ernani José Camargo Azevedo. All rights reserved.
 * @license    https://www.gnu.org/licenses/gpl-3.0.en.html
 */

/**
 * E.164 United States of America NDC 938 country hook
 */
framework_add_filter ( "e164_identify_NANPA_938", "e164_identify_NANPA_938");

/**
 * E.164 North American area number identification hook. This hook is an
 * e164_identify sub hook, called when the ISO3166 Alpha3 are "USA" (code for
 * United States of America). This hook will verify if phone number is valid,
 * returning the area code, area name, phone number, others number related
 * information and if possible, the number type (mobile, landline, Premium Rate
 * Number, etc).
 *
 * @param string $buffer Buffer from plugin system if processed by other function
 *                       before
 * @param array $parameters Parameters to the function. Number provided as
 *                          $parameters["Number"]
 * @return array Array contaning many information about the requested number
 */
function e164_identify_NANPA_938 ( $buffer, $parameters)
{
  /**
   * Check if number country code is from United States of America at NDC 938 area
   */
  if ( substr ( $parameters["Number"], 0, 5) != "+1938")
  {
    return ( is_array ( $buffer) ? $buffer : false);
  }

  $prefixes = array (
    "9999" => array ( "Area" => "Alabama", "City" => "Attalla", "Operator" => "ONVOY, LLC - AL"),
    "9998" => array ( "Area" => "Alabama", "City" => "Attalla", "Operator" => "METROPCS, INC."),
    "9997" => array ( "Area" => "Alabama", "City" => "Attalla", "Operator" => "CORETEL ALABAMA, INC. - AL"),
    "9996" => array ( "Area" => "Alabama", "City" => "Attalla", "Operator" => "CORETEL ALABAMA, INC. - AL"),
    "9995" => array ( "Area" => "Alabama", "City" => "Attalla", "Operator" => "CORETEL ALABAMA, INC. - AL"),
    "9994" => array ( "Area" => "Alabama", "City" => "Attalla", "Operator" => "CORETEL ALABAMA, INC. - AL"),
    "9993" => array ( "Area" => "Alabama", "City" => "Attalla", "Operator" => "CORETEL ALABAMA, INC. - AL"),
    "9992" => array ( "Area" => "Alabama", "City" => "Attalla", "Operator" => "CORETEL ALABAMA, INC. - AL"),
    "9991" => array ( "Area" => "Alabama", "City" => "Attalla", "Operator" => "ONVOY, LLC - AL"),
    "9990" => array ( "Area" => "Alabama", "City" => "Attalla", "Operator" => "ONVOY, LLC - AL"),
    "9468" => array ( "Area" => "Alabama", "City" => "Chulafinnee", "Operator" => "ONVOY, LLC - AL"),
    "9467" => array ( "Area" => "Alabama", "City" => "Chulafinnee", "Operator" => "ONVOY, LLC - AL"),
    "9466" => array ( "Area" => "Alabama", "City" => "Chulafinnee", "Operator" => "ONVOY, LLC - AL"),
    "9465" => array ( "Area" => "Alabama", "City" => "Chulafinnee", "Operator" => "ONVOY, LLC - AL"),
    "9464" => array ( "Area" => "Alabama", "City" => "Chulafinnee", "Operator" => "ONVOY, LLC - AL"),
    "9463" => array ( "Area" => "Alabama", "City" => "Chulafinnee", "Operator" => "FRACTEL, LLC"),
    "9462" => array ( "Area" => "Alabama", "City" => "Chulafinnee", "Operator" => "TWILIO INTERNATIONAL, INC."),
    "9460" => array ( "Area" => "Alabama", "City" => "Chulafinnee", "Operator" => "TELNYX LLC"),
    "9305" => array ( "Area" => "Alabama", "City" => "Stevenson", "Operator" => "ONVOY, LLC - AL"),
    "9304" => array ( "Area" => "Alabama", "City" => "Stevenson", "Operator" => "ONVOY, LLC - AL"),
    "9303" => array ( "Area" => "Alabama", "City" => "Stevenson", "Operator" => "ONVOY, LLC - AL"),
    "9302" => array ( "Area" => "Alabama", "City" => "Stevenson", "Operator" => "TWILIO INTERNATIONAL, INC."),
    "9301" => array ( "Area" => "Alabama", "City" => "Stevenson", "Operator" => "BANDWIDTH.COM CLEC, LLC - AL"),
    "9029" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "ONVOY SPECTRUM, LLC"),
    "9028" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "9027" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "9026" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "9025" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "9024" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "ONVOY, LLC - AL"),
    "9023" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "ONVOY, LLC - AL"),
    "9022" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "ONVOY, LLC - AL"),
    "9021" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "9020" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "9009" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "ONVOY, LLC - AL"),
    "9008" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "TELEPORT COMMUNICATIONS AMERICA, LLC - AL"),
    "9007" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "9006" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "9005" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "9004" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "9003" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "CELLCO PARTNERSHIP DBA VERIZON WIRELESS - AL"),
    "9002" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "9001" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "9000" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "TERRA NOVA TELECOM INC."),
    "8999" => array ( "Area" => "Alabama", "City" => "Anniston", "Operator" => "FRACTEL, LLC"),
    "8998" => array ( "Area" => "Alabama", "City" => "Anniston", "Operator" => "COMMIO, LLC"),
    "8997" => array ( "Area" => "Alabama", "City" => "Anniston", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "8996" => array ( "Area" => "Alabama", "City" => "Anniston", "Operator" => "AIRUS, INC. - AL"),
    "8995" => array ( "Area" => "Alabama", "City" => "Anniston", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "8994" => array ( "Area" => "Alabama", "City" => "Anniston", "Operator" => "CELLCO PARTNERSHIP DBA VERIZON WIRELESS - AL"),
    "8993" => array ( "Area" => "Alabama", "City" => "Anniston", "Operator" => "ONVOY, LLC - AL"),
    "8992" => array ( "Area" => "Alabama", "City" => "Anniston", "Operator" => "ONVOY, LLC - AL"),
    "8991" => array ( "Area" => "Alabama", "City" => "Anniston", "Operator" => "COMMIO, LLC"),
    "8990" => array ( "Area" => "Alabama", "City" => "Anniston", "Operator" => "COMMIO, LLC"),
    "8889" => array ( "Area" => "Alabama", "City" => "Killen", "Operator" => "ONVOY, LLC - AL"),
    "8888" => array ( "Area" => "Alabama", "City" => "Killen", "Operator" => "ONVOY, LLC - AL"),
    "8887" => array ( "Area" => "Alabama", "City" => "Killen", "Operator" => "ONVOY, LLC - AL"),
    "8886" => array ( "Area" => "Alabama", "City" => "Killen", "Operator" => "ONVOY, LLC - AL"),
    "8884" => array ( "Area" => "Alabama", "City" => "Killen", "Operator" => "ONVOY, LLC - AL"),
    "8883" => array ( "Area" => "Alabama", "City" => "Killen", "Operator" => "ONVOY, LLC - AL"),
    "8882" => array ( "Area" => "Alabama", "City" => "Killen", "Operator" => "ONVOY, LLC - AL"),
    "8881" => array ( "Area" => "Alabama", "City" => "Killen", "Operator" => "ONVOY, LLC - AL"),
    "8880" => array ( "Area" => "Alabama", "City" => "Killen", "Operator" => "ONVOY, LLC - AL"),
    "8679" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "8678" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "ONVOY, LLC - AL"),
    "8677" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "ONVOY, LLC - AL"),
    "8676" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "ONVOY, LLC - AL"),
    "8675" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "COMMIO, LLC"),
    "8674" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "ONVOY, LLC - AL"),
    "8673" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "8672" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "8671" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "8670" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "8426" => array ( "Area" => "Alabama", "City" => "Whorton", "Operator" => "TON80 COMMUNICATIONS, LLC"),
    "8425" => array ( "Area" => "Alabama", "City" => "Whorton", "Operator" => "FRACTEL, LLC"),
    "8424" => array ( "Area" => "Alabama", "City" => "Whorton", "Operator" => "ONVOY, LLC - AL"),
    "8423" => array ( "Area" => "Alabama", "City" => "Whorton", "Operator" => "ONVOY, LLC - AL"),
    "8399" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "ONVOY, LLC - AL"),
    "8398" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "ONVOY, LLC - AL"),
    "8397" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "ONVOY, LLC - AL"),
    "8396" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "ONVOY, LLC - AL"),
    "8395" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "ONVOY, LLC - AL"),
    "8394" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "ONVOY, LLC - AL"),
    "8393" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "ONVOY, LLC - AL"),
    "8392" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "ONVOY, LLC - AL"),
    "8391" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "ONVOY, LLC - AL"),
    "8390" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "TELNYX LLC"),
    "8374" => array ( "Area" => "Alabama", "City" => "Boaz", "Operator" => "CORETEL ALABAMA, INC. - AL"),
    "8373" => array ( "Area" => "Alabama", "City" => "Boaz", "Operator" => "TWILIO INTERNATIONAL, INC."),
    "8372" => array ( "Area" => "Alabama", "City" => "Boaz", "Operator" => "TON80 COMMUNICATIONS, LLC"),
    "8371" => array ( "Area" => "Alabama", "City" => "Boaz", "Operator" => "COMMIO, LLC"),
    "8370" => array ( "Area" => "Alabama", "City" => "Boaz", "Operator" => "AIRUS, INC. - AL"),
    "8329" => array ( "Area" => "Alabama", "City" => "Rogersville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "8328" => array ( "Area" => "Alabama", "City" => "Rogersville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "8327" => array ( "Area" => "Alabama", "City" => "Rogersville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "8326" => array ( "Area" => "Alabama", "City" => "Rogersville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "8325" => array ( "Area" => "Alabama", "City" => "Rogersville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "8324" => array ( "Area" => "Alabama", "City" => "Rogersville", "Operator" => "TON80 COMMUNICATIONS, LLC"),
    "8323" => array ( "Area" => "Alabama", "City" => "Rogersville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "8322" => array ( "Area" => "Alabama", "City" => "Rogersville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "8321" => array ( "Area" => "Alabama", "City" => "Rogersville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "8320" => array ( "Area" => "Alabama", "City" => "Rogersville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "8298" => array ( "Area" => "Alabama", "City" => "Piedmont", "Operator" => "TWILIO INTERNATIONAL, INC."),
    "8295" => array ( "Area" => "Alabama", "City" => "Piedmont", "Operator" => "ONVOY, LLC - AL"),
    "8294" => array ( "Area" => "Alabama", "City" => "Piedmont", "Operator" => "CORETEL ALABAMA, INC. - AL"),
    "8293" => array ( "Area" => "Alabama", "City" => "Piedmont", "Operator" => "ONVOY, LLC - AL"),
    "8292" => array ( "Area" => "Alabama", "City" => "Piedmont", "Operator" => "BANDWIDTH.COM CLEC, LLC - AL"),
    "8291" => array ( "Area" => "Alabama", "City" => "Piedmont", "Operator" => "BANDWIDTH.COM CLEC, LLC - AL"),
    "8290" => array ( "Area" => "Alabama", "City" => "Piedmont", "Operator" => "BANDWIDTH.COM CLEC, LLC - AL"),
    "8009" => array ( "Area" => "Alabama", "City" => "Cullman", "Operator" => "ONVOY, LLC - AL"),
    "8008" => array ( "Area" => "Alabama", "City" => "Cullman", "Operator" => "ONVOY, LLC - AL"),
    "8007" => array ( "Area" => "Alabama", "City" => "Cullman", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "8006" => array ( "Area" => "Alabama", "City" => "Cullman", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "8005" => array ( "Area" => "Alabama", "City" => "Cullman", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "8004" => array ( "Area" => "Alabama", "City" => "Cullman", "Operator" => "ONVOY, LLC - AL"),
    "8003" => array ( "Area" => "Alabama", "City" => "Cullman", "Operator" => "ONVOY, LLC - AL"),
    "8002" => array ( "Area" => "Alabama", "City" => "Cullman", "Operator" => "ONVOY, LLC - AL"),
    "8001" => array ( "Area" => "Alabama", "City" => "Cullman", "Operator" => "ONVOY, LLC - AL"),
    "8000" => array ( "Area" => "Alabama", "City" => "Cullman", "Operator" => "ONVOY, LLC - AL"),
    "7878" => array ( "Area" => "Alabama", "City" => "Veto", "Operator" => "TON80 COMMUNICATIONS, LLC"),
    "7877" => array ( "Area" => "Alabama", "City" => "Veto", "Operator" => "ONVOY, LLC - AL"),
    "7867" => array ( "Area" => "Alabama", "City" => "Aroney", "Operator" => "FRACTEL, LLC"),
    "7866" => array ( "Area" => "Alabama", "City" => "Aroney", "Operator" => "ONVOY, LLC - AL"),
    "7864" => array ( "Area" => "Alabama", "City" => "Aroney", "Operator" => "ONVOY, LLC - AL"),
    "7863" => array ( "Area" => "Alabama", "City" => "Aroney", "Operator" => "ONVOY, LLC - AL"),
    "7779" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "TELNYX LLC"),
    "7778" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "AIRUS, INC. - AL"),
    "7777" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "ONVOY, LLC - AL"),
    "7776" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "CORETEL ALABAMA, INC. - AL"),
    "7775" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "ONVOY, LLC - AL"),
    "7774" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "ONVOY, LLC - AL"),
    "7773" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "ONVOY, LLC - AL"),
    "7772" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "ONVOY, LLC - AL"),
    "7771" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "AIRUS, INC. - AL"),
    "7770" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "AIRUS, INC. - AL"),
    "7669" => array ( "Area" => "Alabama", "City" => "Sylacauga", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "7668" => array ( "Area" => "Alabama", "City" => "Sylacauga", "Operator" => "CORETEL ALABAMA, INC. - AL"),
    "7667" => array ( "Area" => "Alabama", "City" => "Sylacauga", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "7666" => array ( "Area" => "Alabama", "City" => "Sylacauga", "Operator" => "CORETEL ALABAMA, INC. - AL"),
    "7665" => array ( "Area" => "Alabama", "City" => "Sylacauga", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "7664" => array ( "Area" => "Alabama", "City" => "Sylacauga", "Operator" => "METROPCS, INC."),
    "7662" => array ( "Area" => "Alabama", "City" => "Sylacauga", "Operator" => "TELNYX LLC"),
    "7661" => array ( "Area" => "Alabama", "City" => "Sylacauga", "Operator" => "AIRUS, INC. - AL"),
    "7587" => array ( "Area" => "Alabama", "City" => "Cedar Bluff", "Operator" => "ONVOY, LLC - AL"),
    "7586" => array ( "Area" => "Alabama", "City" => "Cedar Bluff", "Operator" => "FRACTEL, LLC"),
    "7585" => array ( "Area" => "Alabama", "City" => "Cedar Bluff", "Operator" => "ONVOY, LLC - AL"),
    "7469" => array ( "Area" => "Alabama", "City" => "Hazel Green", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "7467" => array ( "Area" => "Alabama", "City" => "Hazel Green", "Operator" => "TON80 COMMUNICATIONS, LLC"),
    "7462" => array ( "Area" => "Alabama", "City" => "Hazel Green", "Operator" => "ONVOY, LLC - AL"),
    "7460" => array ( "Area" => "Alabama", "City" => "Hazel Green", "Operator" => "COMMIO, LLC"),
    "7329" => array ( "Area" => "Alabama", "City" => "Ranburne", "Operator" => "ONVOY SPECTRUM, LLC"),
    "7328" => array ( "Area" => "Alabama", "City" => "Ranburne", "Operator" => "ONVOY SPECTRUM, LLC"),
    "7327" => array ( "Area" => "Alabama", "City" => "Ranburne", "Operator" => "ONVOY SPECTRUM, LLC"),
    "7326" => array ( "Area" => "Alabama", "City" => "Ranburne", "Operator" => "ONVOY SPECTRUM, LLC"),
    "7325" => array ( "Area" => "Alabama", "City" => "Ranburne", "Operator" => "FRACTEL, LLC"),
    "7324" => array ( "Area" => "Alabama", "City" => "Ranburne", "Operator" => "CHARTER FIBERLINK - ALABAMA, LLC - AL"),
    "7323" => array ( "Area" => "Alabama", "City" => "Ranburne", "Operator" => "TWILIO INTERNATIONAL, INC."),
    "7322" => array ( "Area" => "Alabama", "City" => "Ranburne", "Operator" => "ONVOY SPECTRUM, LLC"),
    "7321" => array ( "Area" => "Alabama", "City" => "Ranburne", "Operator" => "ONVOY SPECTRUM, LLC"),
    "7320" => array ( "Area" => "Alabama", "City" => "Ranburne", "Operator" => "WHITESKY COMMUNICATIONS, LLC"),
    "7246" => array ( "Area" => "Alabama", "City" => "Rinehart", "Operator" => "TON80 COMMUNICATIONS, LLC"),
    "7245" => array ( "Area" => "Alabama", "City" => "Rinehart", "Operator" => "ONVOY, LLC - AL"),
    "7239" => array ( "Area" => "Alabama", "City" => "Moulton", "Operator" => "POWERTEL BIRMINGHAM LICENSES, INC."),
    "7233" => array ( "Area" => "Alabama", "City" => "Moulton", "Operator" => "TON80 COMMUNICATIONS, LLC"),
    "7230" => array ( "Area" => "Alabama", "City" => "Moulton", "Operator" => "COMMIO, LLC"),
    "7225" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "TON80 COMMUNICATIONS, LLC"),
    "7222" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "ONVOY, LLC - AL"),
    "7220" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "BANDWIDTH.COM CLEC, LLC - AL"),
    "6669" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "ONVOY, LLC - AL"),
    "6668" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "ONVOY, LLC - AL"),
    "6667" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "TELEPORT COMMUNICATIONS AMERICA, LLC - AL"),
    "6666" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "ONVOY, LLC - AL"),
    "6665" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "ONVOY, LLC - AL"),
    "6664" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "LEVEL 3 COMMUNICATIONS, LLC - AL"),
    "6663" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "ONVOY, LLC - AL"),
    "6662" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "METROPCS, INC."),
    "6661" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "ONVOY, LLC - AL"),
    "6660" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "CELLCO PARTNERSHIP DBA VERIZON WIRELESS - AL"),
    "6659" => array ( "Area" => "Alabama", "City" => "Talladega", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "6658" => array ( "Area" => "Alabama", "City" => "Talladega", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "6657" => array ( "Area" => "Alabama", "City" => "Talladega", "Operator" => "TON80 COMMUNICATIONS, LLC"),
    "6655" => array ( "Area" => "Alabama", "City" => "Talladega", "Operator" => "DISH WIRELESS, LLC"),
    "6650" => array ( "Area" => "Alabama", "City" => "Talladega", "Operator" => "COMMIO, LLC"),
    "6539" => array ( "Area" => "Alabama", "City" => "Arab", "Operator" => "POWERTEL BIRMINGHAM LICENSES, INC."),
    "6536" => array ( "Area" => "Alabama", "City" => "Arab", "Operator" => "TON80 COMMUNICATIONS, LLC"),
    "6532" => array ( "Area" => "Alabama", "City" => "Arab", "Operator" => "POWERTEL BIRMINGHAM LICENSES, INC."),
    "6531" => array ( "Area" => "Alabama", "City" => "Arab", "Operator" => "POWERTEL BIRMINGHAM LICENSES, INC."),
    "6530" => array ( "Area" => "Alabama", "City" => "Arab", "Operator" => "POWERTEL BIRMINGHAM LICENSES, INC."),
    "6469" => array ( "Area" => "Alabama", "City" => "Russellville", "Operator" => "POWERTEL BIRMINGHAM LICENSES, INC."),
    "6468" => array ( "Area" => "Alabama", "City" => "Russellville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "6466" => array ( "Area" => "Alabama", "City" => "Russellville", "Operator" => "TON80 COMMUNICATIONS, LLC"),
    "6460" => array ( "Area" => "Alabama", "City" => "Russellville", "Operator" => "POWERTEL BIRMINGHAM LICENSES, INC."),
    "6006" => array ( "Area" => "Alabama", "City" => "Lecta", "Operator" => "FRACTEL, LLC"),
    "6003" => array ( "Area" => "Alabama", "City" => "Lecta", "Operator" => "ONVOY, LLC - AL"),
    "6002" => array ( "Area" => "Alabama", "City" => "Lecta", "Operator" => "ONVOY, LLC - AL"),
    "6000" => array ( "Area" => "Alabama", "City" => "Lecta", "Operator" => "FRACTEL, LLC"),
    "5299" => array ( "Area" => "Alabama", "City" => "Collinsville", "Operator" => "FRACTEL, LLC"),
    "5298" => array ( "Area" => "Alabama", "City" => "Collinsville", "Operator" => "ONVOY, LLC - AL"),
    "5297" => array ( "Area" => "Alabama", "City" => "Collinsville", "Operator" => "ONVOY, LLC - AL"),
    "5296" => array ( "Area" => "Alabama", "City" => "Collinsville", "Operator" => "ONVOY, LLC - AL"),
    "5294" => array ( "Area" => "Alabama", "City" => "Collinsville", "Operator" => "ONVOY, LLC - AL"),
    "5293" => array ( "Area" => "Alabama", "City" => "Collinsville", "Operator" => "FRACTEL, LLC"),
    "5292" => array ( "Area" => "Alabama", "City" => "Collinsville", "Operator" => "ONVOY, LLC - AL"),
    "5290" => array ( "Area" => "Alabama", "City" => "Collinsville", "Operator" => "ONVOY, LLC - AL"),
    "5263" => array ( "Area" => "Alabama", "City" => "Ranburne", "Operator" => "TON80 COMMUNICATIONS, LLC"),
    "5109" => array ( "Area" => "Alabama", "City" => "Russellville", "Operator" => "TELNYX LLC"),
    "5108" => array ( "Area" => "Alabama", "City" => "Russellville", "Operator" => "COMMIO, LLC"),
    "5106" => array ( "Area" => "Alabama", "City" => "Russellville", "Operator" => "BANDWIDTH.COM CLEC, LLC - AL"),
    "5105" => array ( "Area" => "Alabama", "City" => "Russellville", "Operator" => "ONVOY SPECTRUM, LLC"),
    "5104" => array ( "Area" => "Alabama", "City" => "Russellville", "Operator" => "ONVOY SPECTRUM, LLC"),
    "5103" => array ( "Area" => "Alabama", "City" => "Russellville", "Operator" => "MCIMETRO ACCESS TRANSMISSION SERVICES LLC - AL"),
    "5102" => array ( "Area" => "Alabama", "City" => "Russellville", "Operator" => "BANDWIDTH.COM CLEC, LLC - AL"),
    "5101" => array ( "Area" => "Alabama", "City" => "Russellville", "Operator" => "CELLCO PARTNERSHIP DBA VERIZON WIRELESS - AL"),
    "5100" => array ( "Area" => "Alabama", "City" => "Russellville", "Operator" => "ONVOY SPECTRUM, LLC"),
    "5005" => array ( "Area" => "Alabama", "City" => "Flat Rock", "Operator" => "FRACTEL, LLC"),
    "5000" => array ( "Area" => "Alabama", "City" => "Flat Rock", "Operator" => "FRACTEL, LLC"),
    "4659" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "TWILIO INTERNATIONAL, INC."),
    "4658" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "FRACTEL, LLC"),
    "4657" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "BANDWIDTH.COM CLEC, LLC - AL"),
    "4656" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "ONVOY, LLC - AL"),
    "4655" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "ONVOY, LLC - AL"),
    "4654" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "ONVOY, LLC - AL"),
    "4653" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "ONVOY, LLC - AL"),
    "4651" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "BANDWIDTH.COM CLEC, LLC - AL"),
    "4650" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "ONVOY, LLC - AL"),
    "4637" => array ( "Area" => "Alabama", "City" => "Athens", "Operator" => "TON80 COMMUNICATIONS, LLC"),
    "4636" => array ( "Area" => "Alabama", "City" => "Athens", "Operator" => "POWERTEL BIRMINGHAM LICENSES, INC."),
    "4635" => array ( "Area" => "Alabama", "City" => "Athens", "Operator" => "POWERTEL BIRMINGHAM LICENSES, INC."),
    "4634" => array ( "Area" => "Alabama", "City" => "Athens", "Operator" => "DISH WIRELESS, LLC"),
    "4633" => array ( "Area" => "Alabama", "City" => "Athens", "Operator" => "CELLCO PARTNERSHIP DBA VERIZON WIRELESS - AL"),
    "4632" => array ( "Area" => "Alabama", "City" => "Athens", "Operator" => "CELLCO PARTNERSHIP DBA VERIZON WIRELESS - AL"),
    "4631" => array ( "Area" => "Alabama", "City" => "Athens", "Operator" => "CELLCO PARTNERSHIP DBA VERIZON WIRELESS - AL"),
    "4630" => array ( "Area" => "Alabama", "City" => "Athens", "Operator" => "COMMIO, LLC"),
    "4465" => array ( "Area" => "Alabama", "City" => "Lexington", "Operator" => "TON80 COMMUNICATIONS, LLC"),
    "4462" => array ( "Area" => "Alabama", "City" => "Lexington", "Operator" => "ONVOY, LLC - AL"),
    "4449" => array ( "Area" => "Alabama", "City" => "Decatur", "Operator" => "TELNYX LLC"),
    "4448" => array ( "Area" => "Alabama", "City" => "Decatur", "Operator" => "ONVOY, LLC - AL"),
    "4447" => array ( "Area" => "Alabama", "City" => "Decatur", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "4446" => array ( "Area" => "Alabama", "City" => "Decatur", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "4445" => array ( "Area" => "Alabama", "City" => "Decatur", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "4444" => array ( "Area" => "Alabama", "City" => "Decatur", "Operator" => "ONVOY, LLC - AL"),
    "4443" => array ( "Area" => "Alabama", "City" => "Decatur", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "4442" => array ( "Area" => "Alabama", "City" => "Decatur", "Operator" => "CHARTER FIBERLINK - ALABAMA, LLC - AL"),
    "4441" => array ( "Area" => "Alabama", "City" => "Decatur", "Operator" => "ONVOY, LLC - AL"),
    "4440" => array ( "Area" => "Alabama", "City" => "Decatur", "Operator" => "ONVOY, LLC - AL"),
    "4336" => array ( "Area" => "Alabama", "City" => "Fruithurst", "Operator" => "TON80 COMMUNICATIONS, LLC"),
    "4268" => array ( "Area" => "Alabama", "City" => "Leighton", "Operator" => "ONVOY SPECTRUM, LLC"),
    "4267" => array ( "Area" => "Alabama", "City" => "Leighton", "Operator" => "ONVOY SPECTRUM, LLC"),
    "4266" => array ( "Area" => "Alabama", "City" => "Leighton", "Operator" => "TON80 COMMUNICATIONS, LLC"),
    "4265" => array ( "Area" => "Alabama", "City" => "Leighton", "Operator" => "ONVOY, LLC - AL"),
    "4264" => array ( "Area" => "Alabama", "City" => "Leighton", "Operator" => "TWILIO INTERNATIONAL, INC."),
    "4263" => array ( "Area" => "Alabama", "City" => "Leighton", "Operator" => "ONVOY, LLC - AL"),
    "4262" => array ( "Area" => "Alabama", "City" => "Leighton", "Operator" => "ONVOY, LLC - AL"),
    "4261" => array ( "Area" => "Alabama", "City" => "Leighton", "Operator" => "CHARTER FIBERLINK - ALABAMA, LLC - AL"),
    "4213" => array ( "Area" => "Alabama", "City" => "Oden Ridge", "Operator" => "ONVOY, LLC - AL"),
    "4212" => array ( "Area" => "Alabama", "City" => "Oden Ridge", "Operator" => "ONVOY, LLC - AL"),
    "4211" => array ( "Area" => "Alabama", "City" => "Oden Ridge", "Operator" => "CHARTER FIBERLINK - ALABAMA, LLC - AL"),
    "4210" => array ( "Area" => "Alabama", "City" => "Oden Ridge", "Operator" => "TELNYX LLC"),
    "4106" => array ( "Area" => "Alabama", "City" => "Red Bay", "Operator" => "ONVOY, LLC - AL"),
    "4105" => array ( "Area" => "Alabama", "City" => "Red Bay", "Operator" => "ONVOY, LLC - AL"),
    "4104" => array ( "Area" => "Alabama", "City" => "Red Bay", "Operator" => "ONVOY SPECTRUM, LLC"),
    "4103" => array ( "Area" => "Alabama", "City" => "Red Bay", "Operator" => "ONVOY SPECTRUM, LLC"),
    "4100" => array ( "Area" => "Alabama", "City" => "Red Bay", "Operator" => "ONVOY SPECTRUM, LLC"),
    "4009" => array ( "Area" => "Alabama", "City" => "Massey", "Operator" => "TWILIO INTERNATIONAL, INC."),
    "4008" => array ( "Area" => "Alabama", "City" => "Massey", "Operator" => "ONVOY, LLC - AL"),
    "4007" => array ( "Area" => "Alabama", "City" => "Massey", "Operator" => "ONVOY, LLC - AL"),
    "4006" => array ( "Area" => "Alabama", "City" => "Massey", "Operator" => "ONVOY, LLC - AL"),
    "4005" => array ( "Area" => "Alabama", "City" => "Massey", "Operator" => "ONVOY, LLC - AL"),
    "4004" => array ( "Area" => "Alabama", "City" => "Massey", "Operator" => "FRACTEL, LLC"),
    "4003" => array ( "Area" => "Alabama", "City" => "Massey", "Operator" => "ONVOY, LLC - AL"),
    "4001" => array ( "Area" => "Alabama", "City" => "Massey", "Operator" => "TELNYX LLC"),
    "4000" => array ( "Area" => "Alabama", "City" => "Massey", "Operator" => "FRACTEL, LLC"),
    "3893" => array ( "Area" => "Alabama", "City" => "Wedowee", "Operator" => "ONVOY, LLC - AL"),
    "3889" => array ( "Area" => "Alabama", "City" => "Delta", "Operator" => "ONVOY, LLC - AL"),
    "3888" => array ( "Area" => "Alabama", "City" => "Delta", "Operator" => "FRACTEL, LLC"),
    "3887" => array ( "Area" => "Alabama", "City" => "Delta", "Operator" => "ONVOY, LLC - AL"),
    "3886" => array ( "Area" => "Alabama", "City" => "Delta", "Operator" => "ONVOY, LLC - AL"),
    "3885" => array ( "Area" => "Alabama", "City" => "Delta", "Operator" => "ONVOY, LLC - AL"),
    "3884" => array ( "Area" => "Alabama", "City" => "Delta", "Operator" => "ONVOY, LLC - AL"),
    "3883" => array ( "Area" => "Alabama", "City" => "Delta", "Operator" => "TWILIO INTERNATIONAL, INC."),
    "3882" => array ( "Area" => "Alabama", "City" => "Delta", "Operator" => "ONVOY, LLC - AL"),
    "3688" => array ( "Area" => "Alabama", "City" => "Florence", "Operator" => "CELLCO PARTNERSHIP DBA VERIZON WIRELESS - AL"),
    "3687" => array ( "Area" => "Alabama", "City" => "Florence", "Operator" => "TON80 COMMUNICATIONS, LLC"),
    "3684" => array ( "Area" => "Alabama", "City" => "Florence", "Operator" => "POWERTEL BIRMINGHAM LICENSES, INC."),
    "3683" => array ( "Area" => "Alabama", "City" => "Florence", "Operator" => "METROPCS, INC."),
    "3682" => array ( "Area" => "Alabama", "City" => "Florence", "Operator" => "CELLCO PARTNERSHIP DBA VERIZON WIRELESS - AL"),
    "3681" => array ( "Area" => "Alabama", "City" => "Florence", "Operator" => "CELLCO PARTNERSHIP DBA VERIZON WIRELESS - AL"),
    "3680" => array ( "Area" => "Alabama", "City" => "Florence", "Operator" => "CELLCO PARTNERSHIP DBA VERIZON WIRELESS - AL"),
    "3569" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "FRACTEL, LLC"),
    "3568" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "ONVOY, LLC - AL"),
    "3567" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "FRACTEL, LLC"),
    "3566" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "ONVOY, LLC - AL"),
    "3565" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "ONVOY, LLC - AL"),
    "3564" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "ONVOY, LLC - AL"),
    "3563" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "ONVOY, LLC - AL"),
    "3562" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "ONVOY, LLC - AL"),
    "3561" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "TWILIO INTERNATIONAL, INC."),
    "3560" => array ( "Area" => "Alabama", "City" => "Section", "Operator" => "ONVOY, LLC - AL"),
    "3489" => array ( "Area" => "Alabama", "City" => "Skyline", "Operator" => "DISH WIRELESS, LLC"),
    "3488" => array ( "Area" => "Alabama", "City" => "Skyline", "Operator" => "ONVOY, LLC - AL"),
    "3487" => array ( "Area" => "Alabama", "City" => "Skyline", "Operator" => "ONVOY, LLC - AL"),
    "3486" => array ( "Area" => "Alabama", "City" => "Skyline", "Operator" => "FRACTEL, LLC"),
    "3485" => array ( "Area" => "Alabama", "City" => "Skyline", "Operator" => "ONVOY, LLC - AL"),
    "3484" => array ( "Area" => "Alabama", "City" => "Skyline", "Operator" => "ONVOY, LLC - AL"),
    "3483" => array ( "Area" => "Alabama", "City" => "Skyline", "Operator" => "ONVOY, LLC - AL"),
    "3482" => array ( "Area" => "Alabama", "City" => "Skyline", "Operator" => "TWILIO INTERNATIONAL, INC."),
    "3481" => array ( "Area" => "Alabama", "City" => "Skyline", "Operator" => "ONVOY, LLC - AL"),
    "3480" => array ( "Area" => "Alabama", "City" => "Skyline", "Operator" => "ONVOY, LLC - AL"),
    "3456" => array ( "Area" => "Alabama", "City" => "Owens Cross Roads", "Operator" => "FRACTEL, LLC"),
    "3369" => array ( "Area" => "Alabama", "City" => "Oden Ridge", "Operator" => "ONVOY, LLC - AL"),
    "3368" => array ( "Area" => "Alabama", "City" => "Oden Ridge", "Operator" => "FRACTEL, LLC"),
    "3367" => array ( "Area" => "Alabama", "City" => "Oden Ridge", "Operator" => "TWILIO INTERNATIONAL, INC."),
    "3366" => array ( "Area" => "Alabama", "City" => "Oden Ridge", "Operator" => "TELNYX LLC"),
    "3365" => array ( "Area" => "Alabama", "City" => "Oden Ridge", "Operator" => "ONVOY, LLC - AL"),
    "3364" => array ( "Area" => "Alabama", "City" => "Oden Ridge", "Operator" => "ONVOY, LLC - AL"),
    "3363" => array ( "Area" => "Alabama", "City" => "Oden Ridge", "Operator" => "ONVOY, LLC - AL"),
    "3362" => array ( "Area" => "Alabama", "City" => "Oden Ridge", "Operator" => "ONVOY, LLC - AL"),
    "3361" => array ( "Area" => "Alabama", "City" => "Oden Ridge", "Operator" => "BANDWIDTH.COM CLEC, LLC - AL"),
    "3360" => array ( "Area" => "Alabama", "City" => "Oden Ridge", "Operator" => "TELNYX LLC"),
    "3339" => array ( "Area" => "Alabama", "City" => "Gurley", "Operator" => "COMMIO, LLC"),
    "3338" => array ( "Area" => "Alabama", "City" => "Gurley", "Operator" => "ONVOY, LLC - AL"),
    "3337" => array ( "Area" => "Alabama", "City" => "Gurley", "Operator" => "ONVOY, LLC - AL"),
    "3336" => array ( "Area" => "Alabama", "City" => "Gurley", "Operator" => "ONVOY SPECTRUM, LLC"),
    "3335" => array ( "Area" => "Alabama", "City" => "Gurley", "Operator" => "ONVOY SPECTRUM, LLC"),
    "3333" => array ( "Area" => "Alabama", "City" => "Gurley", "Operator" => "ONVOY, LLC - AL"),
    "3332" => array ( "Area" => "Alabama", "City" => "Gurley", "Operator" => "TWILIO INTERNATIONAL, INC."),
    "3330" => array ( "Area" => "Alabama", "City" => "Gurley", "Operator" => "BANDWIDTH.COM CLEC, LLC - AL"),
    "3229" => array ( "Area" => "Alabama", "City" => "Decatur", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "3228" => array ( "Area" => "Alabama", "City" => "Decatur", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "3227" => array ( "Area" => "Alabama", "City" => "Decatur", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "3226" => array ( "Area" => "Alabama", "City" => "Decatur", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "3225" => array ( "Area" => "Alabama", "City" => "Decatur", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "3224" => array ( "Area" => "Alabama", "City" => "Decatur", "Operator" => "TON80 COMMUNICATIONS, LLC"),
    "3223" => array ( "Area" => "Alabama", "City" => "Decatur", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "3222" => array ( "Area" => "Alabama", "City" => "Decatur", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "3221" => array ( "Area" => "Alabama", "City" => "Decatur", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "3220" => array ( "Area" => "Alabama", "City" => "Decatur", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "3109" => array ( "Area" => "Alabama", "City" => "Madison", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "3108" => array ( "Area" => "Alabama", "City" => "Madison", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "3104" => array ( "Area" => "Alabama", "City" => "Madison", "Operator" => "ONVOY SPECTRUM, LLC"),
    "3103" => array ( "Area" => "Alabama", "City" => "Madison", "Operator" => "ONVOY SPECTRUM, LLC"),
    "3101" => array ( "Area" => "Alabama", "City" => "Madison", "Operator" => "COMMIO, LLC"),
    "3100" => array ( "Area" => "Alabama", "City" => "Madison", "Operator" => "ONVOY SPECTRUM, LLC"),
    "3009" => array ( "Area" => "Alabama", "City" => "Attalla", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "3008" => array ( "Area" => "Alabama", "City" => "Attalla", "Operator" => "ONVOY, LLC - AL"),
    "3007" => array ( "Area" => "Alabama", "City" => "Attalla", "Operator" => "ONVOY, LLC - AL"),
    "3006" => array ( "Area" => "Alabama", "City" => "Attalla", "Operator" => "ONVOY, LLC - AL"),
    "3005" => array ( "Area" => "Alabama", "City" => "Attalla", "Operator" => "ONVOY, LLC - AL"),
    "3004" => array ( "Area" => "Alabama", "City" => "Attalla", "Operator" => "ONVOY, LLC - AL"),
    "3003" => array ( "Area" => "Alabama", "City" => "Attalla", "Operator" => "ONVOY, LLC - AL"),
    "3002" => array ( "Area" => "Alabama", "City" => "Attalla", "Operator" => "ONVOY, LLC - AL"),
    "3001" => array ( "Area" => "Alabama", "City" => "Attalla", "Operator" => "ONVOY, LLC - AL"),
    "3000" => array ( "Area" => "Alabama", "City" => "Attalla", "Operator" => "FRACTEL, LLC"),
    "2588" => array ( "Area" => "Alabama", "City" => "Guntersville", "Operator" => "METROPCS, INC."),
    "2587" => array ( "Area" => "Alabama", "City" => "Guntersville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2586" => array ( "Area" => "Alabama", "City" => "Guntersville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2583" => array ( "Area" => "Alabama", "City" => "Guntersville", "Operator" => "TON80 COMMUNICATIONS, LLC"),
    "2580" => array ( "Area" => "Alabama", "City" => "Guntersville", "Operator" => "CELLCO PARTNERSHIP DBA VERIZON WIRELESS - AL"),
    "2539" => array ( "Area" => "Alabama", "City" => "Chulafinnee", "Operator" => "ONVOY, LLC - AL"),
    "2538" => array ( "Area" => "Alabama", "City" => "Chulafinnee", "Operator" => "ONVOY, LLC - AL"),
    "2537" => array ( "Area" => "Alabama", "City" => "Chulafinnee", "Operator" => "ONVOY, LLC - AL"),
    "2536" => array ( "Area" => "Alabama", "City" => "Chulafinnee", "Operator" => "ONVOY, LLC - AL"),
    "2535" => array ( "Area" => "Alabama", "City" => "Chulafinnee", "Operator" => "ONVOY, LLC - AL"),
    "2534" => array ( "Area" => "Alabama", "City" => "Chulafinnee", "Operator" => "ONVOY, LLC - AL"),
    "2533" => array ( "Area" => "Alabama", "City" => "Chulafinnee", "Operator" => "ONVOY, LLC - AL"),
    "2532" => array ( "Area" => "Alabama", "City" => "Chulafinnee", "Operator" => "ONVOY, LLC - AL"),
    "2531" => array ( "Area" => "Alabama", "City" => "Chulafinnee", "Operator" => "ONVOY, LLC - AL"),
    "2530" => array ( "Area" => "Alabama", "City" => "Chulafinnee", "Operator" => "TELNYX LLC"),
    "2387" => array ( "Area" => "Alabama", "City" => "Goodwater", "Operator" => "AT&T CORP."),
    "2385" => array ( "Area" => "Alabama", "City" => "Goodwater", "Operator" => "ONVOY, LLC - AL"),
    "2384" => array ( "Area" => "Alabama", "City" => "Goodwater", "Operator" => "ONVOY, LLC - AL"),
    "2383" => array ( "Area" => "Alabama", "City" => "Goodwater", "Operator" => "ONVOY, LLC - AL"),
    "2382" => array ( "Area" => "Alabama", "City" => "Goodwater", "Operator" => "ONVOY, LLC - AL"),
    "2381" => array ( "Area" => "Alabama", "City" => "Goodwater", "Operator" => "ONVOY, LLC - AL"),
    "2380" => array ( "Area" => "Alabama", "City" => "Goodwater", "Operator" => "COMMIO, LLC"),
    "2349" => array ( "Area" => "Alabama", "City" => "Hazel Green", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2348" => array ( "Area" => "Alabama", "City" => "Hazel Green", "Operator" => "DISH WIRELESS, LLC"),
    "2347" => array ( "Area" => "Alabama", "City" => "Hazel Green", "Operator" => "ONVOY SPECTRUM, LLC"),
    "2346" => array ( "Area" => "Alabama", "City" => "Hazel Green", "Operator" => "ONVOY SPECTRUM, LLC"),
    "2345" => array ( "Area" => "Alabama", "City" => "Hazel Green", "Operator" => "FRACTEL, LLC"),
    "2344" => array ( "Area" => "Alabama", "City" => "Hazel Green", "Operator" => "ONVOY, LLC - AL"),
    "2343" => array ( "Area" => "Alabama", "City" => "Hazel Green", "Operator" => "ONVOY, LLC - AL"),
    "2342" => array ( "Area" => "Alabama", "City" => "Hazel Green", "Operator" => "TWILIO INTERNATIONAL, INC."),
    "2341" => array ( "Area" => "Alabama", "City" => "Hazel Green", "Operator" => "ONVOY SPECTRUM, LLC"),
    "2340" => array ( "Area" => "Alabama", "City" => "Hazel Green", "Operator" => "WHITESKY COMMUNICATIONS, LLC"),
    "2279" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2278" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2277" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "TON80 COMMUNICATIONS, LLC"),
    "2276" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "TELEPORT COMMUNICATIONS AMERICA, LLC - AL"),
    "2275" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2274" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2273" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2272" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "LEVEL 3 COMMUNICATIONS, LLC - AL"),
    "2271" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2270" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2268" => array ( "Area" => "Alabama", "City" => "Falkville", "Operator" => "DISH WIRELESS, LLC"),
    "2267" => array ( "Area" => "Alabama", "City" => "Falkville", "Operator" => "DISH WIRELESS, LLC"),
    "2266" => array ( "Area" => "Alabama", "City" => "Falkville", "Operator" => "TON80 COMMUNICATIONS, LLC"),
    "2239" => array ( "Area" => "Alabama", "City" => "Red Bay", "Operator" => "ONVOY, LLC - AL"),
    "2238" => array ( "Area" => "Alabama", "City" => "Red Bay", "Operator" => "ONVOY, LLC - AL"),
    "2237" => array ( "Area" => "Alabama", "City" => "Red Bay", "Operator" => "AT&T CORP."),
    "2236" => array ( "Area" => "Alabama", "City" => "Red Bay", "Operator" => "ONVOY, LLC - AL"),
    "2235" => array ( "Area" => "Alabama", "City" => "Red Bay", "Operator" => "BANDWIDTH.COM CLEC, LLC - AL"),
    "2234" => array ( "Area" => "Alabama", "City" => "Red Bay", "Operator" => "TWILIO INTERNATIONAL, INC."),
    "2233" => array ( "Area" => "Alabama", "City" => "Red Bay", "Operator" => "BANDWIDTH.COM CLEC, LLC - AL"),
    "2232" => array ( "Area" => "Alabama", "City" => "Red Bay", "Operator" => "ONVOY, LLC - AL"),
    "2231" => array ( "Area" => "Alabama", "City" => "Red Bay", "Operator" => "BANDWIDTH.COM CLEC, LLC - AL"),
    "2230" => array ( "Area" => "Alabama", "City" => "Red Bay", "Operator" => "BANDWIDTH.COM CLEC, LLC - AL"),
    "2229" => array ( "Area" => "Alabama", "City" => "Florence", "Operator" => "ONVOY, LLC - AL"),
    "2228" => array ( "Area" => "Alabama", "City" => "Florence", "Operator" => "ONVOY, LLC - AL"),
    "2227" => array ( "Area" => "Alabama", "City" => "Florence", "Operator" => "WHITESKY COMMUNICATIONS, LLC"),
    "2226" => array ( "Area" => "Alabama", "City" => "Florence", "Operator" => "ONVOY, LLC - AL"),
    "2225" => array ( "Area" => "Alabama", "City" => "Florence", "Operator" => "ONVOY, LLC - AL"),
    "2224" => array ( "Area" => "Alabama", "City" => "Florence", "Operator" => "ONVOY, LLC - AL"),
    "2223" => array ( "Area" => "Alabama", "City" => "Florence", "Operator" => "ONVOY, LLC - AL"),
    "2222" => array ( "Area" => "Alabama", "City" => "Florence", "Operator" => "ONVOY, LLC - AL"),
    "2221" => array ( "Area" => "Alabama", "City" => "Florence", "Operator" => "CELLCO PARTNERSHIP DBA VERIZON WIRELESS - AL"),
    "2220" => array ( "Area" => "Alabama", "City" => "Florence", "Operator" => "ONVOY, LLC - AL"),
    "2079" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2078" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2077" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2076" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2075" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2074" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2073" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2072" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2071" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "US LEC OF ALABAMA, INC."),
    "2070" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "ONVOY SPECTRUM, LLC"),
    "2068" => array ( "Area" => "Alabama", "City" => "Anniston", "Operator" => "DISH WIRELESS, LLC"),
    "2066" => array ( "Area" => "Alabama", "City" => "Anniston", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2065" => array ( "Area" => "Alabama", "City" => "Anniston", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2064" => array ( "Area" => "Alabama", "City" => "Anniston", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2063" => array ( "Area" => "Alabama", "City" => "Anniston", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2062" => array ( "Area" => "Alabama", "City" => "Anniston", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2061" => array ( "Area" => "Alabama", "City" => "Anniston", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2060" => array ( "Area" => "Alabama", "City" => "Anniston", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2049" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "BANDWIDTH.COM CLEC, LLC - AL"),
    "2048" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "ONVOY, LLC - AL"),
    "2047" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "ONVOY, LLC - AL"),
    "2046" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "ONVOY, LLC - AL"),
    "2045" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "ONVOY, LLC - AL"),
    "2044" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "ONVOY, LLC - AL"),
    "2043" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "ONVOY, LLC - AL"),
    "2041" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "AIRUS, INC. - AL"),
    "2040" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "BANDWIDTH.COM CLEC, LLC - AL"),
    "2019" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "AIRUS, INC. - AL"),
    "2018" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "ONVOY, LLC - AL"),
    "2017" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "ONVOY, LLC - AL"),
    "2016" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "ONVOY, LLC - AL"),
    "2015" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "ONVOY, LLC - AL"),
    "2014" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "ONVOY, LLC - AL"),
    "2013" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2012" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2011" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "AIRUS, INC. - AL"),
    "2010" => array ( "Area" => "Alabama", "City" => "Childersburg", "Operator" => "AIRUS, INC. - AL"),
    "2009" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "ONVOY, LLC - AL"),
    "2008" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "ONVOY, LLC - AL"),
    "2007" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2006" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2005" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2004" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2003" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2002" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "TELEPORT COMMUNICATIONS AMERICA, LLC - AL"),
    "2001" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "NEW CINGULAR WIRELESS PCS, LLC - GA"),
    "2000" => array ( "Area" => "Alabama", "City" => "Huntsville", "Operator" => "VONAGE AMERICA LLC")
  );
  foreach ( $prefixes as $prefix => $data)
  {
    if ( (int) substr ( $parameters["Number"], 5, strlen ( $prefix)) == $prefix)
    {
      return array_merge_recursive ( is_array ( $buffer) ? $buffer : array (), $data);
    }
  }
  return array_merge_recursive ( is_array ( $buffer) ? $buffer : array (), array ( "Area" => $data["Area"]));
}
