<?php
/**   ___ ___       ___ _______     ______                        __
 *   |   Y   .-----|   |   _   |   |   _  \ .-----.--------.---.-|__.-----.
 *   |.  |   |  _  |.  |.  1   |   |.  |   \|  _  |        |  _  |  |     |
 *   |.  |   |_____|.  |.  ____|   |.  |    |_____|__|__|__|___._|__|__|__|
 *   |:  1   |     |:  |:  |       |:  1    /
 *    \:.. ./      |::.|::.|       |::.. . /
 *     `---'       `---`---'       `------'
 *
 * Copyright (C) 2016-2025 Ernani José Camargo Azevedo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * VoIP Domain country database module filters. This module add the filter calls
 * related to country database of Austria.
 *
 * Reference: https://www.itu.int/oth/T020200000E/en (2011-06-08)
 * Reference: https://www.rtr.at/en/tk/E129 (2011-03-30)
 *
 * Glossary:
 *  CC - Country Code
 *  NDC - National Destination Code (also known as area code)
 *  N(S)N - National (Significant) Number
 *  SN - Subscriber Number
 *
 * @author     Ernani José Camargo Azevedo <azevedo@voipdomain.io>
 * @version    1.0
 * @package    VoIP Domain
 * @subpackage CountryDB
 * @copyright  2016-2025 Ernani José Camargo Azevedo. All rights reserved.
 * @license    https://www.gnu.org/licenses/gpl-3.0.en.html
 */

/**
 * E.164 Austria country hook
 */
framework_add_filter ( "e164_identify_country_AUT", "e164_identify_country_AUT");

/**
 * E.164 Austrian area number identification hook. This hook is an e164_identify
 * sub hook, called when the ISO3166 Alpha3 are "AUT" (code for Austria). This
 * hook will verify if phone number is valid, returning the area code, area name,
 * phone number, others number related information and if possible, the number
 * type (mobile, landline, Premium Rate Number, etc).
 *
 * @param string $buffer Buffer from plugin system if processed by other function
 *                       before
 * @param array $parameters Parameters to the function. Number provided as
 *                          $parameters["Number"]
 * @return array Array contaning many information about the requested number
 */
function e164_identify_country_AUT ( $buffer, $parameters)
{
  /**
   * Check if number country code is from Austria
   */
  if ( substr ( $parameters["Number"], 0, 3) != "+43")
  {
    return ( is_array ( $buffer) ? $buffer : false);
  }

  /**
   * Numbers in Austria has no fixed length, but at least 7 and max 16 digits
   * E.164 format
   */
  if ( strlen ( $parameters["Number"]) < 7 || strlen ( $parameters["Number"]) > 16)
  {
    return ( is_array ( $buffer) ? $buffer : false);
  }

  /**
   * Check for mobile network (It's not possible to confirm the operator due to
   * portability)
   */
  $prefixes = array (
    "669",
    "668",
    "667",
    "666",
    "665",
    "664",
    "663",
    "661",
    "660",
    "659",
    "657",
    "655",
    "653",
    "652",
    "651",
    "650",
    "69",
    "68",
    "67"
  );
  foreach ( $prefixes as $prefix)
  {
    if ( (int) substr ( $parameters["Number"], 3, strlen ( $prefix)) == $prefix)
    {
      if ( strlen ( $parameters["Number"]) < 10)
      {
        return ( is_array ( $buffer) ? $buffer : false);
      }
      return array_merge_recursive ( ( is_array ( $buffer) ? $buffer : array ()), array ( "CC" => "43", "NDC" => $prefix, "Country" => "Austria", "Area" => "", "City" => "", "Operator" => "", "SN" => substr ( $parameters["Number"], 3 + strlen ( $prefix)), "Type" => VD_PHONETYPE_MOBILE, "CallFormats" => array ( "Local" => "0" . $prefix . " " . substr ( $parameters["Number"], 3 + strlen ( $prefix)), "International" => "+43 " . $prefix . " " . substr ( $parameters["Number"], 3 + strlen ( $prefix)))));
    }
  }

  /**
   * Check for fixed line network
   */
  $prefixes = array (
    "1" => array ( "minimum" => 10, "area" => "Wien"),
    "2142" => array ( "minimum" => 10, "area" => "Gattendorf"),
    "2143" => array ( "minimum" => 10, "area" => "Kittsee"),
    "2144" => array ( "minimum" => 10, "area" => "Deutsch Jahrndorf"),
    "2145" => array ( "minimum" => 10, "area" => "Prellenkirchen"),
    "2146" => array ( "minimum" => 10, "area" => "Nickelsdorf"),
    "2147" => array ( "minimum" => 10, "area" => "Zurndorf"),
    "2160" => array ( "minimum" => 10, "area" => "Jois"),
    "2162" => array ( "minimum" => 10, "area" => "Bruck an der Leitha"),
    "2163" => array ( "minimum" => 10, "area" => "Petronell-Carnuntum"),
    "2164" => array ( "minimum" => 10, "area" => "Rohrau"),
    "2165" => array ( "minimum" => 10, "area" => "Hainburg a.d. Donau"),
    "2166" => array ( "minimum" => 10, "area" => "Parndorf"),
    "2167" => array ( "minimum" => 10, "area" => "Neusiedl am See"),
    "2168" => array ( "minimum" => 10, "area" => "Mannersdorf am Leithagebirge"),
    "2169" => array ( "minimum" => 10, "area" => "Trautmannsdorf an der Leitha"),
    "2172" => array ( "minimum" => 10, "area" => "Frauenkirchen"),
    "2173" => array ( "minimum" => 10, "area" => "Gols"),
    "2174" => array ( "minimum" => 10, "area" => "Wallern im Burgenland"),
    "2175" => array ( "minimum" => 10, "area" => "Apetlon"),
    "2176" => array ( "minimum" => 10, "area" => "Tadten"),
    "2177" => array ( "minimum" => 10, "area" => "Podersdorf am See"),
    "2212" => array ( "minimum" => 10, "area" => "Orth an der Donau"),
    "2213" => array ( "minimum" => 10, "area" => "Lassee"),
    "2214" => array ( "minimum" => 10, "area" => "Kopfstetten"),
    "2215" => array ( "minimum" => 10, "area" => "Probstdorf"),
    "2216" => array ( "minimum" => 10, "area" => "Leopoldsdorf im Marchfelde"),
    "2230" => array ( "minimum" => 10, "area" => "Schwadorf"),
    "2231" => array ( "minimum" => 10, "area" => "Purkersdorf"),
    "2232" => array ( "minimum" => 10, "area" => "Fischamend"),
    "2233" => array ( "minimum" => 10, "area" => "Preßbaum"),
    "2234" => array ( "minimum" => 10, "area" => "Gramatneusiedl"),
    "2235" => array ( "minimum" => 10, "area" => "Maria-Lanzendorf"),
    "2236" => array ( "minimum" => 10, "area" => "Mödling"),
    "2237" => array ( "minimum" => 10, "area" => "Gaaden"),
    "2238" => array ( "minimum" => 10, "area" => "Kaltenleutgeben"),
    "2239" => array ( "minimum" => 10, "area" => "Breitenfurt bei Wien"),
    "2242" => array ( "minimum" => 10, "area" => "Sankt Andrä-Wördern"),
    "2243" => array ( "minimum" => 10, "area" => "Klosterneuburg"),
    "2244" => array ( "minimum" => 10, "area" => "Langenzersdorf"),
    "2245" => array ( "minimum" => 10, "area" => "Wolkersdorf im Weinviertel"),
    "2246" => array ( "minimum" => 10, "area" => "Gerasdorf bei Wien"),
    "2247" => array ( "minimum" => 10, "area" => "Deutsch-Wagram"),
    "2248" => array ( "minimum" => 10, "area" => "Markgrafneusiedl"),
    "2249" => array ( "minimum" => 10, "area" => "Groß-Enzersdorf"),
    "2252" => array ( "minimum" => 10, "area" => "Baden"),
    "2253" => array ( "minimum" => 10, "area" => "Oberwaltersdorf"),
    "2254" => array ( "minimum" => 10, "area" => "Ebreichsdorf"),
    "2255" => array ( "minimum" => 10, "area" => "Deutsch Brodersdorf"),
    "2256" => array ( "minimum" => 10, "area" => "Leobersdorf"),
    "2257" => array ( "minimum" => 10, "area" => "Klausen-Leopoldsdorf"),
    "2258" => array ( "minimum" => 10, "area" => "Alland"),
    "2259" => array ( "minimum" => 10, "area" => "Münchendorf"),
    "2262" => array ( "minimum" => 10, "area" => "Korneuburg"),
    "2263" => array ( "minimum" => 10, "area" => "Großrußbach"),
    "2264" => array ( "minimum" => 10, "area" => "Rückersdorf (Harmannsdorf)"),
    "2265" => array ( "minimum" => 10, "area" => "Hausleiten"),
    "2266" => array ( "minimum" => 10, "area" => "Stockerau"),
    "2267" => array ( "minimum" => 10, "area" => "Sierndorf"),
    "2268" => array ( "minimum" => 10, "area" => "Großmugl"),
    "2269" => array ( "minimum" => 10, "area" => "Niederfellabrunn"),
    "2271" => array ( "minimum" => 10, "area" => "Ried am Riederberg"),
    "2272" => array ( "minimum" => 10, "area" => "Tulln an der Donau"),
    "2273" => array ( "minimum" => 10, "area" => "Tulbing"),
    "2274" => array ( "minimum" => 10, "area" => "Sieghartskirchen"),
    "2275" => array ( "minimum" => 10, "area" => "Atzenbrugg"),
    "2276" => array ( "minimum" => 10, "area" => "Reidling"),
    "2277" => array ( "minimum" => 10, "area" => "Zwentendorf"),
    "2278" => array ( "minimum" => 10, "area" => "Absdorf"),
    "2279" => array ( "minimum" => 10, "area" => "Kirchberg am Wagram"),
    "2282" => array ( "minimum" => 10, "area" => "Gänserndorf"),
    "2283" => array ( "minimum" => 10, "area" => "Angern an der March"),
    "2284" => array ( "minimum" => 10, "area" => "Oberweiden"),
    "2285" => array ( "minimum" => 10, "area" => "Marchegg"),
    "2286" => array ( "minimum" => 10, "area" => "Obersiebenbrunn"),
    "2287" => array ( "minimum" => 10, "area" => "Strasshof an der Nordbahn"),
    "2288" => array ( "minimum" => 10, "area" => "Auersthal"),
    "2289" => array ( "minimum" => 10, "area" => "Matzen"),
    "2522" => array ( "minimum" => 10, "area" => "Laa an der Thaya"),
    "2523" => array ( "minimum" => 10, "area" => "Kirchstetten (Neudorf bei Staatz)"),
    "2524" => array ( "minimum" => 10, "area" => "Kautendorf"),
    "2525" => array ( "minimum" => 10, "area" => "Gnadendorf"),
    "2526" => array ( "minimum" => 10, "area" => "Stronsdorf"),
    "2527" => array ( "minimum" => 10, "area" => "Wulzeshofen"),
    "2532" => array ( "minimum" => 10, "area" => "Zistersdorf"),
    "2533" => array ( "minimum" => 10, "area" => "Neusiedl an der Zaya"),
    "2534" => array ( "minimum" => 10, "area" => "Niedersulz"),
    "2535" => array ( "minimum" => 10, "area" => "Hohenau an der March"),
    "2536" => array ( "minimum" => 10, "area" => "Drösing"),
    "2538" => array ( "minimum" => 10, "area" => "Velm-Götzendorf"),
    "2552" => array ( "minimum" => 10, "area" => "Poysdorf"),
    "2554" => array ( "minimum" => 10, "area" => "Stützenhofen"),
    "2555" => array ( "minimum" => 10, "area" => "Herrnbaumgarten"),
    "2556" => array ( "minimum" => 10, "area" => "Großkrut"),
    "2557" => array ( "minimum" => 10, "area" => "Bernhardsthal"),
    "2572" => array ( "minimum" => 10, "area" => "Mistelbach"),
    "2573" => array ( "minimum" => 10, "area" => "Wilfersdorf"),
    "2574" => array ( "minimum" => 10, "area" => "Gaweinstal"),
    "2575" => array ( "minimum" => 10, "area" => "Ladendorf"),
    "2576" => array ( "minimum" => 10, "area" => "Ernstbrunn"),
    "2577" => array ( "minimum" => 10, "area" => "Asparn an der Zaya"),
    "2610" => array ( "minimum" => 10, "area" => "Horitschon"),
    "2611" => array ( "minimum" => 10, "area" => "Mannersdorf an der Rabnitz"),
    "2612" => array ( "minimum" => 10, "area" => "Oberpullendorf"),
    "2613" => array ( "minimum" => 10, "area" => "Deutschkreutz"),
    "2614" => array ( "minimum" => 10, "area" => "Kleinwarasdorf"),
    "2615" => array ( "minimum" => 10, "area" => "Lutzmannsburg"),
    "2616" => array ( "minimum" => 10, "area" => "Lockenhaus"),
    "2617" => array ( "minimum" => 10, "area" => "Draßmarkt"),
    "2618" => array ( "minimum" => 10, "area" => "Markt Sankt Martin"),
    "2619" => array ( "minimum" => 10, "area" => "Lackendorf"),
    "2620" => array ( "minimum" => 10, "area" => "Willendorf"),
    "2621" => array ( "minimum" => 10, "area" => "Sieggraben"),
    "2622" => array ( "minimum" => 10, "area" => "Wiener Neustadt"),
    "2623" => array ( "minimum" => 10, "area" => "Pottendorf"),
    "2624" => array ( "minimum" => 10, "area" => "Ebenfurth"),
    "2625" => array ( "minimum" => 10, "area" => "Bad Sauerbrunn"),
    "2626" => array ( "minimum" => 10, "area" => "Mattersburg"),
    "2627" => array ( "minimum" => 10, "area" => "Pitten"),
    "2628" => array ( "minimum" => 10, "area" => "Felixdorf"),
    "2629" => array ( "minimum" => 10, "area" => "Warth (Niederösterreich)"),
    "2630" => array ( "minimum" => 10, "area" => "Ternitz"),
    "2631" => array ( "minimum" => 10, "area" => "Pöttsching"),
    "2632" => array ( "minimum" => 10, "area" => "Pernitz"),
    "2633" => array ( "minimum" => 10, "area" => "Markt Piesting"),
    "2634" => array ( "minimum" => 10, "area" => "Gutenstein"),
    "2635" => array ( "minimum" => 10, "area" => "Neunkirchen"),
    "2636" => array ( "minimum" => 10, "area" => "Puchberg am Schneeberg"),
    "2637" => array ( "minimum" => 10, "area" => "Grünbach am Schneeberg"),
    "2638" => array ( "minimum" => 10, "area" => "Winzendorf-Muthmannsdorf"),
    "2639" => array ( "minimum" => 10, "area" => "Bad Fischau"),
    "2641" => array ( "minimum" => 10, "area" => "Kirchberg am Wechsel"),
    "2642" => array ( "minimum" => 10, "area" => "Aspangberg-Sankt Peter"),
    "2643" => array ( "minimum" => 10, "area" => "Lichtenegg"),
    "2644" => array ( "minimum" => 10, "area" => "Grimmenstein"),
    "2645" => array ( "minimum" => 10, "area" => "Wiesmath"),
    "2646" => array ( "minimum" => 10, "area" => "Kirchschlag in der Buckligen Welt"),
    "2647" => array ( "minimum" => 10, "area" => "Krumbach (Niederösterreich)"),
    "2648" => array ( "minimum" => 10, "area" => "Hochneukirchen"),
    "2649" => array ( "minimum" => 10, "area" => "Mönichkirchen"),
    "2662" => array ( "minimum" => 10, "area" => "Gloggnitz"),
    "2663" => array ( "minimum" => 10, "area" => "Schottwien"),
    "2664" => array ( "minimum" => 10, "area" => "Semmering"),
    "2665" => array ( "minimum" => 10, "area" => "Prein an der Rax"),
    "2666" => array ( "minimum" => 10, "area" => "Reichenau"),
    "2667" => array ( "minimum" => 10, "area" => "Schwarzau im Gebirge"),
    "2672" => array ( "minimum" => 10, "area" => "Berndorf"),
    "2673" => array ( "minimum" => 10, "area" => "Altenmarkt an der Triesting"),
    "2674" => array ( "minimum" => 10, "area" => "Weißenbach an der Triesting"),
    "2680" => array ( "minimum" => 10, "area" => "Sankt Margarethen im Burgenland"),
    "2682" => array ( "minimum" => 10, "area" => "Eisenstadt"),
    "2683" => array ( "minimum" => 10, "area" => "Purbach am Neusiedler See"),
    "2684" => array ( "minimum" => 10, "area" => "Schützen am Gebirge"),
    "2685" => array ( "minimum" => 10, "area" => "Rust"),
    "2686" => array ( "minimum" => 10, "area" => "Draßburg"),
    "2687" => array ( "minimum" => 10, "area" => "Siegendorf"),
    "2688" => array ( "minimum" => 10, "area" => "Steinbrunn"),
    "2689" => array ( "minimum" => 10, "area" => "Hornstein"),
    "2711" => array ( "minimum" => 10, "area" => "Dürnstein"),
    "2712" => array ( "minimum" => 10, "area" => "Aggsbach"),
    "2713" => array ( "minimum" => 10, "area" => "Spitz"),
    "2714" => array ( "minimum" => 10, "area" => "Rossatz"),
    "2715" => array ( "minimum" => 10, "area" => "Weißenkirchen in der Wachau"),
    "2716" => array ( "minimum" => 10, "area" => "Gföhl"),
    "2717" => array ( "minimum" => 10, "area" => "Unter-Meisling"),
    "2718" => array ( "minimum" => 10, "area" => "Lichtenau im Waldviertel"),
    "2719" => array ( "minimum" => 10, "area" => "Droß"),
    "2722" => array ( "minimum" => 10, "area" => "Kirchberg an der Pielach"),
    "2723" => array ( "minimum" => 10, "area" => "Rabenstein an der Pielach"),
    "2724" => array ( "minimum" => 10, "area" => "Schwarzenbach an der Pielach"),
    "2725" => array ( "minimum" => 10, "area" => "Frankenfels"),
    "2726" => array ( "minimum" => 10, "area" => "Puchenstuben"),
    "2728" => array ( "minimum" => 10, "area" => "Wienerbruck"),
    "2731" => array ( "minimum" => 10, "area" => "Idolsberg"),
    "2732" => array ( "minimum" => 10, "area" => "Krems an der Donau"),
    "2733" => array ( "minimum" => 10, "area" => "Schönberg am Kamp"),
    "2734" => array ( "minimum" => 10, "area" => "Langenlois"),
    "2735" => array ( "minimum" => 10, "area" => "Hadersdorf am Kamp"),
    "2736" => array ( "minimum" => 10, "area" => "Paudorf"),
    "2738" => array ( "minimum" => 10, "area" => "Fels am Wagram"),
    "2739" => array ( "minimum" => 10, "area" => "Tiefenfucha"),
    "2741" => array ( "minimum" => 10, "area" => "Flinsbach"),
    "2742" => array ( "minimum" => 10, "area" => "Sankt Pölten"),
    "2743" => array ( "minimum" => 10, "area" => "Böheimkirchen"),
    "2744" => array ( "minimum" => 10, "area" => "Kasten bei Böheimkirchen"),
    "2745" => array ( "minimum" => 10, "area" => "Pyhra"),
    "2746" => array ( "minimum" => 10, "area" => "Wilhelmsburg"),
    "2747" => array ( "minimum" => 10, "area" => "Ober-Grafendorf"),
    "2748" => array ( "minimum" => 10, "area" => "Kilb"),
    "2749" => array ( "minimum" => 10, "area" => "Prinzersdorf"),
    "2752" => array ( "minimum" => 10, "area" => "Melk"),
    "2753" => array ( "minimum" => 10, "area" => "Gansbach"),
    "2754" => array ( "minimum" => 10, "area" => "Loosdorf"),
    "2755" => array ( "minimum" => 10, "area" => "Mank"),
    "2756" => array ( "minimum" => 10, "area" => "Sankt Leonhard am Forst"),
    "2757" => array ( "minimum" => 10, "area" => "Pöchlarn"),
    "2758" => array ( "minimum" => 10, "area" => "Pöggstall"),
    "2762" => array ( "minimum" => 10, "area" => "Lilienfeld"),
    "2763" => array ( "minimum" => 10, "area" => "Sankt Veit an der Gölsen"),
    "2764" => array ( "minimum" => 10, "area" => "Hainfeld"),
    "2765" => array ( "minimum" => 10, "area" => "Kaumberg"),
    "2766" => array ( "minimum" => 10, "area" => "Kleinzell"),
    "2767" => array ( "minimum" => 10, "area" => "Hohenberg"),
    "2768" => array ( "minimum" => 10, "area" => "Sankt Aegyd am Neuwalde"),
    "2769" => array ( "minimum" => 10, "area" => "Türnitz"),
    "2772" => array ( "minimum" => 10, "area" => "Neulengbach"),
    "2773" => array ( "minimum" => 10, "area" => "Eichgraben"),
    "2774" => array ( "minimum" => 10, "area" => "Innermanzing"),
    "2782" => array ( "minimum" => 10, "area" => "Herzogenburg"),
    "2783" => array ( "minimum" => 10, "area" => "Traismauer"),
    "2784" => array ( "minimum" => 10, "area" => "Perschling"),
    "2786" => array ( "minimum" => 10, "area" => "Oberwölbling"),
    "2812" => array ( "minimum" => 10, "area" => "Groß Gerungs"),
    "2813" => array ( "minimum" => 10, "area" => "Arbesbach"),
    "2814" => array ( "minimum" => 10, "area" => "Langschlag"),
    "2815" => array ( "minimum" => 10, "area" => "Großschönau"),
    "2816" => array ( "minimum" => 10, "area" => "Karlstift"),
    "2822" => array ( "minimum" => 10, "area" => "Zwettl-Niederösterreich"),
    "2823" => array ( "minimum" => 10, "area" => "Großglobnitz"),
    "2824" => array ( "minimum" => 10, "area" => "Allentsteig"),
    "2825" => array ( "minimum" => 10, "area" => "Göpfritz an der Wild"),
    "2826" => array ( "minimum" => 10, "area" => "Rastenfeld"),
    "2827" => array ( "minimum" => 10, "area" => "Schönbach"),
    "2828" => array ( "minimum" => 10, "area" => "Rappottenstein"),
    "2829" => array ( "minimum" => 10, "area" => "Schweiggers"),
    "2841" => array ( "minimum" => 10, "area" => "Vitis"),
    "2842" => array ( "minimum" => 10, "area" => "Waidhofen an der Thaya"),
    "2843" => array ( "minimum" => 10, "area" => "Dobersberg"),
    "2844" => array ( "minimum" => 10, "area" => "Karlstein an der Thaya"),
    "2845" => array ( "minimum" => 10, "area" => "Weikertschlag an der Thaya (Raabs an der Thaya)"),
    "2846" => array ( "minimum" => 10, "area" => "Raabs an der Thaya"),
    "2847" => array ( "minimum" => 10, "area" => "Groß-Siegharts"),
    "2848" => array ( "minimum" => 10, "area" => "Pfaffenschlag bei Waidhofen a.d.Thaya"),
    "2849" => array ( "minimum" => 10, "area" => "Schwarzenau"),
    "2852" => array ( "minimum" => 10, "area" => "Gmünd"),
    "2853" => array ( "minimum" => 10, "area" => "Schrems"),
    "2854" => array ( "minimum" => 10, "area" => "Kirchberg am Walde"),
    "2855" => array ( "minimum" => 10, "area" => "Waldenstein"),
    "2856" => array ( "minimum" => 10, "area" => "Weitra"),
    "2857" => array ( "minimum" => 10, "area" => "Bad Großpertholz"),
    "2858" => array ( "minimum" => 10, "area" => "Moorbad Harbach"),
    "2859" => array ( "minimum" => 10, "area" => "Brand-Nagelberg"),
    "2862" => array ( "minimum" => 10, "area" => "Heidenreichstein"),
    "2863" => array ( "minimum" => 10, "area" => "Eggern"),
    "2864" => array ( "minimum" => 10, "area" => "Kautzen"),
    "2865" => array ( "minimum" => 10, "area" => "Litschau"),
    "2872" => array ( "minimum" => 10, "area" => "Ottenschlag"),
    "2873" => array ( "minimum" => 10, "area" => "Kottes"),
    "2874" => array ( "minimum" => 10, "area" => "Martinsberg"),
    "2875" => array ( "minimum" => 10, "area" => "Grafenschlag"),
    "2876" => array ( "minimum" => 10, "area" => "Els"),
    "2877" => array ( "minimum" => 10, "area" => "Grainbrunn"),
    "2878" => array ( "minimum" => 10, "area" => "Traunstein"),
    "2912" => array ( "minimum" => 10, "area" => "Geras"),
    "2913" => array ( "minimum" => 10, "area" => "Hötzelsdorf"),
    "2914" => array ( "minimum" => 10, "area" => "Japons"),
    "2915" => array ( "minimum" => 10, "area" => "Drosendorf-Zissersdorf"),
    "2916" => array ( "minimum" => 10, "area" => "Riegersburg (Hardegg)"),
    "2942" => array ( "minimum" => 10, "area" => "Retz"),
    "2943" => array ( "minimum" => 10, "area" => "Obritz"),
    "2944" => array ( "minimum" => 10, "area" => "Haugsdorf"),
    "2945" => array ( "minimum" => 10, "area" => "Zellerndorf"),
    "2946" => array ( "minimum" => 10, "area" => "Pulkau"),
    "2947" => array ( "minimum" => 10, "area" => "Theras"),
    "2948" => array ( "minimum" => 10, "area" => "Weitersfeld"),
    "2949" => array ( "minimum" => 10, "area" => "Niederfladnitz"),
    "2951" => array ( "minimum" => 10, "area" => "Guntersdorf"),
    "2952" => array ( "minimum" => 10, "area" => "Hollabrunn"),
    "2953" => array ( "minimum" => 10, "area" => "Nappersdorf"),
    "2954" => array ( "minimum" => 10, "area" => "Göllersdorf"),
    "2955" => array ( "minimum" => 10, "area" => "Großweikersdorf"),
    "2956" => array ( "minimum" => 10, "area" => "Ziersdorf"),
    "2957" => array ( "minimum" => 10, "area" => "Hohenwarth"),
    "2958" => array ( "minimum" => 10, "area" => "Maissau"),
    "2959" => array ( "minimum" => 10, "area" => "Sitzendorf an der Schmida"),
    "2982" => array ( "minimum" => 10, "area" => "Horn"),
    "2983" => array ( "minimum" => 10, "area" => "Sigmundsherberg"),
    "2984" => array ( "minimum" => 10, "area" => "Eggenburg"),
    "2985" => array ( "minimum" => 10, "area" => "Gars am Kamp"),
    "2986" => array ( "minimum" => 10, "area" => "Irnfritz"),
    "2987" => array ( "minimum" => 10, "area" => "Sankt Leonhard am Hornerwald"),
    "2988" => array ( "minimum" => 10, "area" => "Neupölla"),
    "2989" => array ( "minimum" => 10, "area" => "Brunn an der Wild"),
    "3112" => array ( "minimum" => 10, "area" => "Gleisdorf"),
    "3113" => array ( "minimum" => 10, "area" => "Pischelsdorf in der Steiermark"),
    "3114" => array ( "minimum" => 10, "area" => "Markt Hartmannsdorf"),
    "3115" => array ( "minimum" => 10, "area" => "Studenzen"),
    "3116" => array ( "minimum" => 10, "area" => "Kirchbach in Steiermark"),
    "3117" => array ( "minimum" => 10, "area" => "Eggersdorf bei Graz"),
    "3118" => array ( "minimum" => 10, "area" => "Sinabelkirchen"),
    "3119" => array ( "minimum" => 10, "area" => "Sankt Marein bei Graz"),
    "3123" => array ( "minimum" => 10, "area" => "Sankt Oswald bei Plankenwarth"),
    "3124" => array ( "minimum" => 10, "area" => "Gratkorn"),
    "3125" => array ( "minimum" => 10, "area" => "Übelbach"),
    "3126" => array ( "minimum" => 10, "area" => "Frohnleiten"),
    "3127" => array ( "minimum" => 10, "area" => "Peggau"),
    "3132" => array ( "minimum" => 10, "area" => "Kumberg"),
    "3133" => array ( "minimum" => 10, "area" => "Nestelbach"),
    "3134" => array ( "minimum" => 10, "area" => "Heiligenkreuz am Waasen"),
    "3135" => array ( "minimum" => 10, "area" => "Kalsdorf bei Graz"),
    "3136" => array ( "minimum" => 10, "area" => "Dobl"),
    "3137" => array ( "minimum" => 10, "area" => "Söding"),
    "3140" => array ( "minimum" => 10, "area" => "Sankt Martin am Wöllmißberg"),
    "3141" => array ( "minimum" => 10, "area" => "Hirschegg"),
    "3142" => array ( "minimum" => 10, "area" => "Voitsberg"),
    "3143" => array ( "minimum" => 10, "area" => "Krottendorf"),
    "3144" => array ( "minimum" => 10, "area" => "Köflach"),
    "3145" => array ( "minimum" => 10, "area" => "Edelschrott"),
    "3146" => array ( "minimum" => 10, "area" => "Modriach"),
    "3147" => array ( "minimum" => 10, "area" => "Salla"),
    "3148" => array ( "minimum" => 10, "area" => "Kainach bei Voitsberg"),
    "3149" => array ( "minimum" => 10, "area" => "Geistthal"),
    "3150" => array ( "minimum" => 10, "area" => "Paldau"),
    "3151" => array ( "minimum" => 10, "area" => "Gnas"),
    "3152" => array ( "minimum" => 10, "area" => "Feldbach"),
    "3153" => array ( "minimum" => 10, "area" => "Riegersburg"),
    "3155" => array ( "minimum" => 10, "area" => "Fehring"),
    "3157" => array ( "minimum" => 10, "area" => "Kapfenstein"),
    "3158" => array ( "minimum" => 10, "area" => "Sankt Anna am Aigen"),
    "3159" => array ( "minimum" => 10, "area" => "Bad Gleichenberg"),
    "316" => array ( "minimum" => 9, "area" => "Graz"),
    "3170" => array ( "minimum" => 10, "area" => "Fischbach"),
    "3171" => array ( "minimum" => 10, "area" => "Gasen"),
    "3172" => array ( "minimum" => 10, "area" => "Weiz"),
    "3173" => array ( "minimum" => 10, "area" => "Ratten"),
    "3174" => array ( "minimum" => 10, "area" => "Birkfeld"),
    "3175" => array ( "minimum" => 10, "area" => "Anger"),
    "3176" => array ( "minimum" => 10, "area" => "Stubenberg"),
    "3177" => array ( "minimum" => 10, "area" => "Puch bei Weiz"),
    "3178" => array ( "minimum" => 10, "area" => "Sankt Ruprecht an der Raab"),
    "3179" => array ( "minimum" => 10, "area" => "Passail"),
    "3182" => array ( "minimum" => 10, "area" => "Wildon"),
    "3183" => array ( "minimum" => 10, "area" => "Sankt Georgen an der Stiefing"),
    "3184" => array ( "minimum" => 10, "area" => "Wolfsberg im Schwarzautal"),
    "3185" => array ( "minimum" => 10, "area" => "Preding"),
    "3322" => array ( "minimum" => 10, "area" => "Güssing"),
    "3323" => array ( "minimum" => 10, "area" => "Eberau"),
    "3324" => array ( "minimum" => 10, "area" => "Strem"),
    "3325" => array ( "minimum" => 10, "area" => "Heiligenkreuz im Lafnitztal"),
    "3326" => array ( "minimum" => 10, "area" => "Stegersbach"),
    "3327" => array ( "minimum" => 10, "area" => "Sankt Michael im Burgenland"),
    "3328" => array ( "minimum" => 10, "area" => "Kukmirn"),
    "3329" => array ( "minimum" => 10, "area" => "Jennersdorf"),
    "3331" => array ( "minimum" => 10, "area" => "Sankt Lorenzen am Wechsel"),
    "3332" => array ( "minimum" => 10, "area" => "Hartberg"),
    "3333" => array ( "minimum" => 10, "area" => "Sebersdorf"),
    "3334" => array ( "minimum" => 10, "area" => "Kaindorf"),
    "3335" => array ( "minimum" => 10, "area" => "Pöllau"),
    "3336" => array ( "minimum" => 10, "area" => "Waldbach"),
    "3337" => array ( "minimum" => 10, "area" => "Vorau"),
    "3338" => array ( "minimum" => 10, "area" => "Lafnitz"),
    "3339" => array ( "minimum" => 10, "area" => "Friedberg"),
    "3352" => array ( "minimum" => 10, "area" => "Oberwart"),
    "3353" => array ( "minimum" => 10, "area" => "Oberschützen"),
    "3354" => array ( "minimum" => 10, "area" => "Bernstein"),
    "3355" => array ( "minimum" => 10, "area" => "Stadtschlaining"),
    "3356" => array ( "minimum" => 10, "area" => "Markt Allhau"),
    "3357" => array ( "minimum" => 10, "area" => "Pinkafeld"),
    "3358" => array ( "minimum" => 10, "area" => "Litzelsdorf"),
    "3359" => array ( "minimum" => 10, "area" => "Loipersdorf-Kitzladen"),
    "3362" => array ( "minimum" => 10, "area" => "Großpetersdorf"),
    "3363" => array ( "minimum" => 10, "area" => "Rechnitz"),
    "3364" => array ( "minimum" => 10, "area" => "Hannersdorf"),
    "3365" => array ( "minimum" => 10, "area" => "Deutsch Schützen-Eisenberg"),
    "3366" => array ( "minimum" => 10, "area" => "Kohfidisch"),
    "3382" => array ( "minimum" => 10, "area" => "Fürstenfeld"),
    "3383" => array ( "minimum" => 10, "area" => "Burgau"),
    "3385" => array ( "minimum" => 10, "area" => "Ilz"),
    "3386" => array ( "minimum" => 10, "area" => "Großsteinbach"),
    "3387" => array ( "minimum" => 10, "area" => "Söchau"),
    "3452" => array ( "minimum" => 10, "area" => "Leibnitz"),
    "3453" => array ( "minimum" => 10, "area" => "Ehrenhausen"),
    "3454" => array ( "minimum" => 10, "area" => "Leutschach"),
    "3455" => array ( "minimum" => 10, "area" => "Arnfels"),
    "3456" => array ( "minimum" => 10, "area" => "Fresing"),
    "3457" => array ( "minimum" => 10, "area" => "Gleinstätten"),
    "3460" => array ( "minimum" => 10, "area" => "Soboth"),
    "3461" => array ( "minimum" => 10, "area" => "Trahütten"),
    "3462" => array ( "minimum" => 10, "area" => "Deutschlandsberg"),
    "3463" => array ( "minimum" => 10, "area" => "Stainz"),
    "3464" => array ( "minimum" => 10, "area" => "Groß Sankt Florian"),
    "3465" => array ( "minimum" => 10, "area" => "Pölfing-Brunn"),
    "3466" => array ( "minimum" => 10, "area" => "Eibiswald"),
    "3467" => array ( "minimum" => 10, "area" => "Schwanberg"),
    "3468" => array ( "minimum" => 10, "area" => "Sankt Oswald ob Eibiswald"),
    "3469" => array ( "minimum" => 10, "area" => "Sankt Oswald im Freiland"),
    "3472" => array ( "minimum" => 10, "area" => "Mureck"),
    "3473" => array ( "minimum" => 10, "area" => "Straden"),
    "3474" => array ( "minimum" => 10, "area" => "Deutsch Goritz"),
    "3475" => array ( "minimum" => 10, "area" => "Hürth"),
    "3476" => array ( "minimum" => 10, "area" => "Bad Radkersburg"),
    "3477" => array ( "minimum" => 10, "area" => "Sankt Peter am Ottersbach"),
    "3512" => array ( "minimum" => 10, "area" => "Knittelfeld"),
    "3513" => array ( "minimum" => 10, "area" => "Bischoffeld"),
    "3514" => array ( "minimum" => 10, "area" => "Seckau"),
    "3515" => array ( "minimum" => 10, "area" => "Sankt Lorenzen bei Knittelfeld"),
    "3516" => array ( "minimum" => 10, "area" => "Kleinlobming"),
    "3532" => array ( "minimum" => 10, "area" => "Murau"),
    "3533" => array ( "minimum" => 10, "area" => "Turrach"),
    "3534" => array ( "minimum" => 10, "area" => "Stadl an der Mur"),
    "3535" => array ( "minimum" => 10, "area" => "Krakaudorf"),
    "3536" => array ( "minimum" => 10, "area" => "Sankt Peter am Kammersberg"),
    "3537" => array ( "minimum" => 10, "area" => "Sankt Georgen ob Murau"),
    "3571" => array ( "minimum" => 10, "area" => "Möderbrugg"),
    "3572" => array ( "minimum" => 10, "area" => "Judenburg"),
    "3573" => array ( "minimum" => 10, "area" => "Fohnsdorf"),
    "3574" => array ( "minimum" => 10, "area" => "Pusterwald"),
    "3575" => array ( "minimum" => 10, "area" => "Sankt Johann am Tauern"),
    "3576" => array ( "minimum" => 10, "area" => "Bretstein"),
    "3577" => array ( "minimum" => 10, "area" => "Zeltweg"),
    "3578" => array ( "minimum" => 10, "area" => "Obdach"),
    "3579" => array ( "minimum" => 10, "area" => "Pöls"),
    "3581" => array ( "minimum" => 10, "area" => "Oberwölz"),
    "3582" => array ( "minimum" => 10, "area" => "Scheifling"),
    "3583" => array ( "minimum" => 10, "area" => "Unzmarkt"),
    "3584" => array ( "minimum" => 10, "area" => "Neumarkt in Steiermark"),
    "3585" => array ( "minimum" => 10, "area" => "Sankt Lambrecht"),
    "3586" => array ( "minimum" => 10, "area" => "Mühlen"),
    "3587" => array ( "minimum" => 10, "area" => "Schönberg-Lachtal"),
    "3588" => array ( "minimum" => 10, "area" => "Katsch an der Mur"),
    "3611" => array ( "minimum" => 10, "area" => "Johnsbach"),
    "3612" => array ( "minimum" => 10, "area" => "Liezen"),
    "3613" => array ( "minimum" => 10, "area" => "Admont"),
    "3614" => array ( "minimum" => 10, "area" => "Rottenmann"),
    "3615" => array ( "minimum" => 10, "area" => "Trieben"),
    "3616" => array ( "minimum" => 10, "area" => "Selzthal"),
    "3617" => array ( "minimum" => 10, "area" => "Gaishorn am See"),
    "3618" => array ( "minimum" => 10, "area" => "Hohentauern"),
    "3619" => array ( "minimum" => 10, "area" => "Oppenberg"),
    "3622" => array ( "minimum" => 10, "area" => "Bad Aussee"),
    "3623" => array ( "minimum" => 10, "area" => "Bad Mitterndorf"),
    "3624" => array ( "minimum" => 10, "area" => "Pichl-Kainisch"),
    "3631" => array ( "minimum" => 10, "area" => "Unterlaussa"),
    "3632" => array ( "minimum" => 10, "area" => "Sankt Gallen"),
    "3633" => array ( "minimum" => 10, "area" => "Landl"),
    "3634" => array ( "minimum" => 10, "area" => "Hieflau"),
    "3635" => array ( "minimum" => 10, "area" => "Radmer"),
    "3636" => array ( "minimum" => 10, "area" => "Wildalpen"),
    "3637" => array ( "minimum" => 10, "area" => "Gams bei Hieflau"),
    "3638" => array ( "minimum" => 10, "area" => "Palfau"),
    "3680" => array ( "minimum" => 10, "area" => "Donnersbachwald"),
    "3682" => array ( "minimum" => 10, "area" => "Stainach"),
    "3683" => array ( "minimum" => 10, "area" => "Donnersbach"),
    "3684" => array ( "minimum" => 10, "area" => "Sankt Martin am Grimming"),
    "3685" => array ( "minimum" => 10, "area" => "Gröbming"),
    "3686" => array ( "minimum" => 10, "area" => "Haus"),
    "3687" => array ( "minimum" => 10, "area" => "Schladming"),
    "3688" => array ( "minimum" => 10, "area" => "Tauplitz"),
    "3689" => array ( "minimum" => 10, "area" => "Sankt Nikolai im Sölktal"),
    "3832" => array ( "minimum" => 10, "area" => "Kraubath an der Mur"),
    "3833" => array ( "minimum" => 10, "area" => "Traboch"),
    "3834" => array ( "minimum" => 10, "area" => "Wald am Schoberpaß"),
    "3842" => array ( "minimum" => 10, "area" => "Leoben"),
    "3843" => array ( "minimum" => 10, "area" => "Sankt Michael in Obersteiermark"),
    "3844" => array ( "minimum" => 10, "area" => "Kammern im Liesingtal"),
    "3845" => array ( "minimum" => 10, "area" => "Mautern in Steiermark"),
    "3846" => array ( "minimum" => 10, "area" => "Kalwang"),
    "3847" => array ( "minimum" => 10, "area" => "Trofaiach"),
    "3848" => array ( "minimum" => 10, "area" => "Eisenerz"),
    "3849" => array ( "minimum" => 10, "area" => "Vordernberg"),
    "3852" => array ( "minimum" => 10, "area" => "Mürzzuschlag"),
    "3853" => array ( "minimum" => 10, "area" => "Spital am Semmering"),
    "3854" => array ( "minimum" => 10, "area" => "Langenwang"),
    "3855" => array ( "minimum" => 10, "area" => "Krieglach"),
    "3856" => array ( "minimum" => 10, "area" => "Veitsch"),
    "3857" => array ( "minimum" => 10, "area" => "Neuberg an der Mürz"),
    "3858" => array ( "minimum" => 10, "area" => "Mitterdorf im Mürztal"),
    "3859" => array ( "minimum" => 10, "area" => "Mürzsteg"),
    "3861" => array ( "minimum" => 10, "area" => "Aflenz"),
    "3862" => array ( "minimum" => 10, "area" => "Bruck an der Mur"),
    "3863" => array ( "minimum" => 10, "area" => "Turnau"),
    "3864" => array ( "minimum" => 10, "area" => "Sankt Marein im Mürztal"),
    "3865" => array ( "minimum" => 10, "area" => "Kindberg"),
    "3866" => array ( "minimum" => 10, "area" => "Breitenau am Hochlantsch"),
    "3867" => array ( "minimum" => 10, "area" => "Pernegg an der Mur"),
    "3868" => array ( "minimum" => 10, "area" => "Tragöß"),
    "3869" => array ( "minimum" => 10, "area" => "Sankt Katharein an der Laming"),
    "3882" => array ( "minimum" => 10, "area" => "Mariazell"),
    "3883" => array ( "minimum" => 10, "area" => "Terz"),
    "3884" => array ( "minimum" => 10, "area" => "Wegscheid"),
    "3885" => array ( "minimum" => 10, "area" => "Greith"),
    "3886" => array ( "minimum" => 10, "area" => "Weichselboden"),
    "4212" => array ( "minimum" => 10, "area" => "Sankt Veit an der Glan"),
    "4213" => array ( "minimum" => 10, "area" => "Launsdorf"),
    "4214" => array ( "minimum" => 10, "area" => "Brückl"),
    "4215" => array ( "minimum" => 10, "area" => "Liebenfels"),
    "4220" => array ( "minimum" => 10, "area" => "Köttmannsdorf"),
    "4221" => array ( "minimum" => 10, "area" => "Gallizien"),
    "4223" => array ( "minimum" => 10, "area" => "Maria Saal"),
    "4224" => array ( "minimum" => 10, "area" => "Pischeldorf"),
    "4225" => array ( "minimum" => 10, "area" => "Grafenstein"),
    "4226" => array ( "minimum" => 10, "area" => "Sankt Margareten im Rosental"),
    "4227" => array ( "minimum" => 10, "area" => "Ferlach"),
    "4228" => array ( "minimum" => 10, "area" => "Feistritz im Rosental"),
    "4229" => array ( "minimum" => 10, "area" => "Krumpendorf am Wörther See"),
    "4230" => array ( "minimum" => 10, "area" => "Globasnitz"),
    "4231" => array ( "minimum" => 10, "area" => "Mittertrixen"),
    "4232" => array ( "minimum" => 10, "area" => "Völkermarkt"),
    "4233" => array ( "minimum" => 10, "area" => "Griffen"),
    "4234" => array ( "minimum" => 10, "area" => "Ruden"),
    "4235" => array ( "minimum" => 10, "area" => "Bleiburg"),
    "4236" => array ( "minimum" => 10, "area" => "Eberndorf"),
    "4237" => array ( "minimum" => 10, "area" => "Miklauzhof"),
    "4238" => array ( "minimum" => 10, "area" => "Eisenkappel-Vellach"),
    "4239" => array ( "minimum" => 10, "area" => "Sankt Kanzian am Klopeiner See"),
    "4240" => array ( "minimum" => 10, "area" => "Bad Kleinkirchheim"),
    "4242" => array ( "minimum" => 10, "area" => "Villach"),
    "4243" => array ( "minimum" => 10, "area" => "Bodensdorf"),
    "4244" => array ( "minimum" => 10, "area" => "Bad Bleiberg"),
    "4245" => array ( "minimum" => 10, "area" => "Feistritz an der Drau"),
    "4246" => array ( "minimum" => 10, "area" => "Radenthein"),
    "4247" => array ( "minimum" => 10, "area" => "Afritz"),
    "4248" => array ( "minimum" => 10, "area" => "Treffen"),
    "4252" => array ( "minimum" => 10, "area" => "Wernberg"),
    "4253" => array ( "minimum" => 10, "area" => "Sankt Jakob im Rosental"),
    "4254" => array ( "minimum" => 10, "area" => "Faak am See"),
    "4255" => array ( "minimum" => 10, "area" => "Arnoldstein"),
    "4256" => array ( "minimum" => 10, "area" => "Nötsch im Gailtal"),
    "4257" => array ( "minimum" => 10, "area" => "Fürnitz"),
    "4258" => array ( "minimum" => 10, "area" => "Gummern"),
    "4262" => array ( "minimum" => 10, "area" => "Treibach"),
    "4263" => array ( "minimum" => 10, "area" => "Hüttenberg"),
    "4264" => array ( "minimum" => 10, "area" => "Klein Sankt Paul"),
    "4265" => array ( "minimum" => 10, "area" => "Weitensfeld im Gurktal"),
    "4266" => array ( "minimum" => 10, "area" => "Straßburg"),
    "4267" => array ( "minimum" => 10, "area" => "Metnitz"),
    "4268" => array ( "minimum" => 10, "area" => "Friesach"),
    "4269" => array ( "minimum" => 10, "area" => "Flattnitz"),
    "4271" => array ( "minimum" => 10, "area" => "Steuerberg"),
    "4272" => array ( "minimum" => 10, "area" => "Pörtschach am Wörther See"),
    "4273" => array ( "minimum" => 10, "area" => "Reifnitz"),
    "4274" => array ( "minimum" => 10, "area" => "Velden am Wörther See"),
    "4275" => array ( "minimum" => 10, "area" => "Ebene Reichenau"),
    "4276" => array ( "minimum" => 10, "area" => "Feldkirchen in Kärnten"),
    "4277" => array ( "minimum" => 10, "area" => "Glanegg"),
    "4278" => array ( "minimum" => 10, "area" => "Gnesau"),
    "4279" => array ( "minimum" => 10, "area" => "Sirnitz"),
    "4282" => array ( "minimum" => 10, "area" => "Hermagor"),
    "4283" => array ( "minimum" => 10, "area" => "Sankt Stefan im Gailtal"),
    "4284" => array ( "minimum" => 10, "area" => "Kirchbach"),
    "4285" => array ( "minimum" => 10, "area" => "Tröpolach"),
    "4286" => array ( "minimum" => 10, "area" => "Weißbriach"),
    "4350" => array ( "minimum" => 10, "area" => "Bad Sankt Leonhard im Lavanttal"),
    "4352" => array ( "minimum" => 10, "area" => "Wolfsberg"),
    "4353" => array ( "minimum" => 10, "area" => "Prebl"),
    "4354" => array ( "minimum" => 10, "area" => "Preitenegg"),
    "4355" => array ( "minimum" => 10, "area" => "Gemmersdorf"),
    "4356" => array ( "minimum" => 10, "area" => "Lavamünd"),
    "4357" => array ( "minimum" => 10, "area" => "Sankt Paul im Lavanttal"),
    "4358" => array ( "minimum" => 10, "area" => "Sankt Andrä"),
    "4359" => array ( "minimum" => 10, "area" => "Reichenfels"),
    "463" => array ( "minimum" => 9, "area" => "Klagenfurt"),
    "4710" => array ( "minimum" => 10, "area" => "Oberdrauburg"),
    "4712" => array ( "minimum" => 10, "area" => "Greifenburg"),
    "4713" => array ( "minimum" => 10, "area" => "Techendorf"),
    "4714" => array ( "minimum" => 10, "area" => "Dellach im Drautal"),
    "4715" => array ( "minimum" => 10, "area" => "Kötschach-Mauthen"),
    "4716" => array ( "minimum" => 10, "area" => "Lesachtal"),
    "4717" => array ( "minimum" => 10, "area" => "Steinfeld"),
    "4718" => array ( "minimum" => 10, "area" => "Dellach"),
    "4732" => array ( "minimum" => 10, "area" => "Gmünd in Kärnten"),
    "4733" => array ( "minimum" => 10, "area" => "Malta"),
    "4734" => array ( "minimum" => 10, "area" => "Rennweg"),
    "4735" => array ( "minimum" => 10, "area" => "Kremsbrücke"),
    "4736" => array ( "minimum" => 10, "area" => "Innerkrems"),
    "4761" => array ( "minimum" => 10, "area" => "Stockenboi"),
    "4762" => array ( "minimum" => 10, "area" => "Spittal an der Drau"),
    "4766" => array ( "minimum" => 10, "area" => "Millstatt"),
    "4767" => array ( "minimum" => 10, "area" => "Rothenthurn"),
    "4768" => array ( "minimum" => 10, "area" => "Kleblach-Lind"),
    "4769" => array ( "minimum" => 10, "area" => "Möllbrücke"),
    "4782" => array ( "minimum" => 10, "area" => "Obervellach"),
    "4783" => array ( "minimum" => 10, "area" => "Reißeck"),
    "4784" => array ( "minimum" => 10, "area" => "Mallnitz"),
    "4785" => array ( "minimum" => 10, "area" => "Außerfragant"),
    "4822" => array ( "minimum" => 10, "area" => "Winklern"),
    "4823" => array ( "minimum" => 10, "area" => "Tresdorf (Rangersdorf)"),
    "4824" => array ( "minimum" => 10, "area" => "Heiligenblut"),
    "4825" => array ( "minimum" => 10, "area" => "Großkirchheim"),
    "4826" => array ( "minimum" => 10, "area" => "Mörtschach"),
    "4842" => array ( "minimum" => 10, "area" => "Sillian"),
    "4843" => array ( "minimum" => 10, "area" => "Außervillgraten"),
    "4846" => array ( "minimum" => 10, "area" => "Abfaltersbach"),
    "4847" => array ( "minimum" => 10, "area" => "Obertilliach"),
    "4848" => array ( "minimum" => 10, "area" => "Kartitsch"),
    "4852" => array ( "minimum" => 10, "area" => "Lienz"),
    "4853" => array ( "minimum" => 10, "area" => "Ainet"),
    "4855" => array ( "minimum" => 10, "area" => "Assling"),
    "4858" => array ( "minimum" => 10, "area" => "Nikolsdorf"),
    "4872" => array ( "minimum" => 10, "area" => "Huben"),
    "4873" => array ( "minimum" => 10, "area" => "Sankt Jakob in Defereggen"),
    "4874" => array ( "minimum" => 10, "area" => "Virgen"),
    "4875" => array ( "minimum" => 10, "area" => "Matrei in Osttirol"),
    "4876" => array ( "minimum" => 10, "area" => "Kals am Großglockner"),
    "4877" => array ( "minimum" => 10, "area" => "Prägraten am Großvenediger"),
    "4879" => array ( "minimum" => 10, "area" => "Sankt Veit in Defereggen"),
    "501" => array ( "minimum" => 8, "area" => ""),
    "502" => array ( "minimum" => 8, "area" => ""),
    "503" => array ( "minimum" => 8, "area" => ""),
    "504" => array ( "minimum" => 8, "area" => ""),
    "505" => array ( "minimum" => 8, "area" => ""),
    "506" => array ( "minimum" => 8, "area" => ""),
    "507" => array ( "minimum" => 8, "area" => ""),
    "508" => array ( "minimum" => 8, "area" => ""),
    "509" => array ( "minimum" => 8, "area" => ""),
    "512" => array ( "minimum" => 9, "area" => "Innsbruck"),
    "517" => array ( "minimum" => 8, "area" => ""),
    "5212" => array ( "minimum" => 10, "area" => "Seefeld in Tirol"),
    "5213" => array ( "minimum" => 10, "area" => "Scharnitz"),
    "5214" => array ( "minimum" => 10, "area" => "Leutasch"),
    "5223" => array ( "minimum" => 10, "area" => "Hall in Tirol"),
    "5224" => array ( "minimum" => 10, "area" => "Wattens"),
    "5225" => array ( "minimum" => 10, "area" => "Fulpmes"),
    "5226" => array ( "minimum" => 10, "area" => "Neustift im Stubaital"),
    "5230" => array ( "minimum" => 10, "area" => "Sellrain"),
    "5232" => array ( "minimum" => 10, "area" => "Kematen in Tirol"),
    "5234" => array ( "minimum" => 10, "area" => "Axams"),
    "5236" => array ( "minimum" => 10, "area" => "Gries im Sellrain"),
    "5238" => array ( "minimum" => 10, "area" => "Zirl"),
    "5239" => array ( "minimum" => 10, "area" => "Kühtai"),
    "5242" => array ( "minimum" => 10, "area" => "Schwaz"),
    "5243" => array ( "minimum" => 10, "area" => "Maurach"),
    "5244" => array ( "minimum" => 10, "area" => "Jenbach"),
    "5245" => array ( "minimum" => 10, "area" => "Hinterriß"),
    "5246" => array ( "minimum" => 10, "area" => "Achenkirch"),
    "5248" => array ( "minimum" => 10, "area" => "Steinberg am Rofan"),
    "5252" => array ( "minimum" => 10, "area" => "Oetz"),
    "5253" => array ( "minimum" => 10, "area" => "Längenfeld"),
    "5254" => array ( "minimum" => 10, "area" => "Sölden"),
    "5255" => array ( "minimum" => 10, "area" => "Umhausen"),
    "5256" => array ( "minimum" => 10, "area" => "Untergurgl"),
    "5262" => array ( "minimum" => 10, "area" => "Telfs"),
    "5263" => array ( "minimum" => 10, "area" => "Silz"),
    "5264" => array ( "minimum" => 10, "area" => "Mieming"),
    "5265" => array ( "minimum" => 10, "area" => "Nassereith"),
    "5266" => array ( "minimum" => 10, "area" => "Ötztal-Bahnhof"),
    "5272" => array ( "minimum" => 10, "area" => "Steinach am Brenner"),
    "5273" => array ( "minimum" => 10, "area" => "Matrei am Brenner"),
    "5274" => array ( "minimum" => 10, "area" => "Gries am Brenner"),
    "5275" => array ( "minimum" => 10, "area" => "Trins"),
    "5276" => array ( "minimum" => 10, "area" => "Gschnitz"),
    "5278" => array ( "minimum" => 10, "area" => "Navis"),
    "5279" => array ( "minimum" => 10, "area" => "Sankt Jodok am Brenner"),
    "5280" => array ( "minimum" => 10, "area" => "Hochfügen"),
    "5282" => array ( "minimum" => 10, "area" => "Zell am Ziller"),
    "5283" => array ( "minimum" => 10, "area" => "Kaltenbach"),
    "5284" => array ( "minimum" => 10, "area" => "Gerlos"),
    "5285" => array ( "minimum" => 10, "area" => "Mayrhofen"),
    "5286" => array ( "minimum" => 10, "area" => "Ginzling"),
    "5287" => array ( "minimum" => 10, "area" => "Tux"),
    "5288" => array ( "minimum" => 10, "area" => "Fügen"),
    "5289" => array ( "minimum" => 10, "area" => "Häusling"),
    "5331" => array ( "minimum" => 10, "area" => "Brandenberg"),
    "5332" => array ( "minimum" => 10, "area" => "Wörgl"),
    "5333" => array ( "minimum" => 10, "area" => "Söll"),
    "5334" => array ( "minimum" => 10, "area" => "Westendorf"),
    "5335" => array ( "minimum" => 10, "area" => "Hopfgarten im Brixental"),
    "5336" => array ( "minimum" => 10, "area" => "Alpbach"),
    "5337" => array ( "minimum" => 10, "area" => "Brixlegg"),
    "5338" => array ( "minimum" => 10, "area" => "Kundl"),
    "5339" => array ( "minimum" => 10, "area" => "Wildschönau"),
    "5352" => array ( "minimum" => 10, "area" => "Sankt Johann in Tirol"),
    "5353" => array ( "minimum" => 10, "area" => "Waidring"),
    "5354" => array ( "minimum" => 10, "area" => "Fieberbrunn"),
    "5355" => array ( "minimum" => 10, "area" => "Jochberg"),
    "5356" => array ( "minimum" => 10, "area" => "Kitzbühel"),
    "5357" => array ( "minimum" => 10, "area" => "Kirchberg in Tirol"),
    "5358" => array ( "minimum" => 10, "area" => "Ellmau"),
    "5359" => array ( "minimum" => 10, "area" => "Hochfilzen"),
    "5372" => array ( "minimum" => 10, "area" => "Kufstein"),
    "5373" => array ( "minimum" => 10, "area" => "Ebbs"),
    "5374" => array ( "minimum" => 10, "area" => "Walchsee"),
    "5375" => array ( "minimum" => 10, "area" => "Kössen"),
    "5376" => array ( "minimum" => 10, "area" => "Thiersee"),
    "5412" => array ( "minimum" => 10, "area" => "Imst"),
    "5413" => array ( "minimum" => 10, "area" => "Sankt Leonhard im Pitztal"),
    "5414" => array ( "minimum" => 10, "area" => "Wenns"),
    "5417" => array ( "minimum" => 10, "area" => "Roppen"),
    "5418" => array ( "minimum" => 10, "area" => "Schönwies"),
    "5441" => array ( "minimum" => 10, "area" => "See"),
    "5442" => array ( "minimum" => 10, "area" => "Landeck"),
    "5443" => array ( "minimum" => 10, "area" => "Galtür"),
    "5444" => array ( "minimum" => 10, "area" => "Ischgl"),
    "5445" => array ( "minimum" => 10, "area" => "Kappl"),
    "5446" => array ( "minimum" => 10, "area" => "Sankt Anton am Arlberg"),
    "5447" => array ( "minimum" => 10, "area" => "Flirsch"),
    "5448" => array ( "minimum" => 10, "area" => "Pettneu am Arlberg"),
    "5449" => array ( "minimum" => 10, "area" => "Fließ"),
    "5472" => array ( "minimum" => 10, "area" => "Prutz"),
    "5473" => array ( "minimum" => 10, "area" => "Nauders"),
    "5474" => array ( "minimum" => 10, "area" => "Pfunds"),
    "5475" => array ( "minimum" => 10, "area" => "Feichten"),
    "5476" => array ( "minimum" => 10, "area" => "Serfaus"),
    "5477" => array ( "minimum" => 10, "area" => "Tösens"),
    "5510" => array ( "minimum" => 10, "area" => "Damüls"),
    "5512" => array ( "minimum" => 10, "area" => "Egg"),
    "5513" => array ( "minimum" => 10, "area" => "Hittisau"),
    "5514" => array ( "minimum" => 10, "area" => "Bezau"),
    "5515" => array ( "minimum" => 10, "area" => "Au"),
    "5516" => array ( "minimum" => 10, "area" => "Doren"),
    "5517" => array ( "minimum" => 10, "area" => "Riezlern"),
    "5518" => array ( "minimum" => 10, "area" => "Mellau"),
    "5519" => array ( "minimum" => 10, "area" => "Schröcken"),
    "5522" => array ( "minimum" => 10, "area" => "Feldkirch"),
    "5523" => array ( "minimum" => 10, "area" => "Götzis"),
    "5524" => array ( "minimum" => 10, "area" => "Satteins"),
    "5525" => array ( "minimum" => 10, "area" => "Nenzing"),
    "5526" => array ( "minimum" => 10, "area" => "Laterns"),
    "5550" => array ( "minimum" => 10, "area" => "Thüringen"),
    "5552" => array ( "minimum" => 10, "area" => "Bludenz"),
    "5553" => array ( "minimum" => 10, "area" => "Raggal"),
    "5554" => array ( "minimum" => 10, "area" => "Sonntag"),
    "5556" => array ( "minimum" => 10, "area" => "Schruns"),
    "5557" => array ( "minimum" => 10, "area" => "Sankt Gallenkirch"),
    "5558" => array ( "minimum" => 10, "area" => "Gaschurn"),
    "5559" => array ( "minimum" => 10, "area" => "Brand"),
    "5572" => array ( "minimum" => 10, "area" => "Dornbirn"),
    "5573" => array ( "minimum" => 10, "area" => "Hörbranz"),
    "5574" => array ( "minimum" => 10, "area" => "Bregenz"),
    "5575" => array ( "minimum" => 10, "area" => "Langen bei Bregenz"),
    "5576" => array ( "minimum" => 10, "area" => "Hohenems"),
    "5577" => array ( "minimum" => 10, "area" => "Lustenau"),
    "5578" => array ( "minimum" => 10, "area" => "Höchst"),
    "5579" => array ( "minimum" => 10, "area" => "Alberschwende"),
    "5582" => array ( "minimum" => 10, "area" => "Klösterle"),
    "5583" => array ( "minimum" => 10, "area" => "Lech"),
    "5585" => array ( "minimum" => 10, "area" => "Dalaas"),
    "5632" => array ( "minimum" => 10, "area" => "Stanzach"),
    "5633" => array ( "minimum" => 10, "area" => "Hägerau"),
    "5634" => array ( "minimum" => 10, "area" => "Elbigenalp"),
    "5635" => array ( "minimum" => 10, "area" => "Elmen"),
    "5672" => array ( "minimum" => 10, "area" => "Reutte"),
    "5673" => array ( "minimum" => 10, "area" => "Ehrwald"),
    "5674" => array ( "minimum" => 10, "area" => "Bichlbach"),
    "5675" => array ( "minimum" => 10, "area" => "Tannheim"),
    "5676" => array ( "minimum" => 10, "area" => "Jungholz"),
    "5677" => array ( "minimum" => 10, "area" => "Vils"),
    "5678" => array ( "minimum" => 10, "area" => "Weißenbach am Lech"),
    "57" => array ( "minimum" => 8, "area" => ""),
    "59" => array ( "minimum" => 8, "area" => ""),
    "6131" => array ( "minimum" => 10, "area" => "Obertraun"),
    "6132" => array ( "minimum" => 10, "area" => "Bad Ischl"),
    "6133" => array ( "minimum" => 10, "area" => "Ebensee"),
    "6134" => array ( "minimum" => 10, "area" => "Hallstatt"),
    "6135" => array ( "minimum" => 10, "area" => "Bad Goisern"),
    "6136" => array ( "minimum" => 10, "area" => "Gosau"),
    "6137" => array ( "minimum" => 10, "area" => "Strobl"),
    "6138" => array ( "minimum" => 10, "area" => "Sankt Wolfgang im Salzkammergut"),
    "6212" => array ( "minimum" => 10, "area" => "Seekirchen am Wallersee"),
    "6213" => array ( "minimum" => 10, "area" => "Oberhofen am Irrsee"),
    "6214" => array ( "minimum" => 10, "area" => "Henndorf am Wallersee"),
    "6215" => array ( "minimum" => 10, "area" => "Straßwalchen"),
    "6216" => array ( "minimum" => 10, "area" => "Neumarkt am Wallersee"),
    "6217" => array ( "minimum" => 10, "area" => "Mattsee"),
    "6219" => array ( "minimum" => 10, "area" => "Obertrum am See"),
    "6221" => array ( "minimum" => 10, "area" => "Koppl"),
    "6223" => array ( "minimum" => 10, "area" => "Anthering"),
    "6224" => array ( "minimum" => 10, "area" => "Hintersee"),
    "6225" => array ( "minimum" => 10, "area" => "Eugendorf"),
    "6226" => array ( "minimum" => 10, "area" => "Fuschl am See"),
    "6227" => array ( "minimum" => 10, "area" => "Sankt Gilgen"),
    "6228" => array ( "minimum" => 10, "area" => "Faistenau"),
    "6229" => array ( "minimum" => 10, "area" => "Hof bei Salzburg"),
    "6232" => array ( "minimum" => 10, "area" => "Mondsee"),
    "6233" => array ( "minimum" => 10, "area" => "Oberwang"),
    "6234" => array ( "minimum" => 10, "area" => "Zell am Moos"),
    "6235" => array ( "minimum" => 10, "area" => "Thalgau"),
    "6240" => array ( "minimum" => 10, "area" => "Krispl"),
    "6241" => array ( "minimum" => 10, "area" => "Sankt Koloman"),
    "6242" => array ( "minimum" => 10, "area" => "Rußbach am Paß Gschütt"),
    "6243" => array ( "minimum" => 10, "area" => "Abtenau"),
    "6244" => array ( "minimum" => 10, "area" => "Golling an der Salzach"),
    "6245" => array ( "minimum" => 10, "area" => "Hallein"),
    "6246" => array ( "minimum" => 10, "area" => "Grödig"),
    "6247" => array ( "minimum" => 10, "area" => "Großgmain"),
    "6272" => array ( "minimum" => 10, "area" => "Oberndorf bei Salzburg"),
    "6274" => array ( "minimum" => 10, "area" => "Lamprechtshausen"),
    "6276" => array ( "minimum" => 10, "area" => "Nußdorf am Haunsberg"),
    "6277" => array ( "minimum" => 10, "area" => "Sankt Pantaleon"),
    "6278" => array ( "minimum" => 10, "area" => "Ostermiething"),
    "6412" => array ( "minimum" => 10, "area" => "Sankt Johann im Pongau"),
    "6413" => array ( "minimum" => 10, "area" => "Wagrain"),
    "6414" => array ( "minimum" => 10, "area" => "Großarl"),
    "6415" => array ( "minimum" => 10, "area" => "Schwarzach im Pongau"),
    "6416" => array ( "minimum" => 10, "area" => "Lend"),
    "6417" => array ( "minimum" => 10, "area" => "Hüttschlag"),
    "6418" => array ( "minimum" => 10, "area" => "Kleinarl"),
    "6432" => array ( "minimum" => 10, "area" => "Bad Hofgastein"),
    "6433" => array ( "minimum" => 10, "area" => "Dorfgastein"),
    "6434" => array ( "minimum" => 10, "area" => "Bad Gastein"),
    "6452" => array ( "minimum" => 10, "area" => "Radstadt"),
    "6453" => array ( "minimum" => 10, "area" => "Filzmoos"),
    "6454" => array ( "minimum" => 10, "area" => "Mandling"),
    "6455" => array ( "minimum" => 10, "area" => "Untertauern"),
    "6456" => array ( "minimum" => 10, "area" => "Obertauern"),
    "6457" => array ( "minimum" => 10, "area" => "Flachau"),
    "6458" => array ( "minimum" => 10, "area" => "Hüttau"),
    "6461" => array ( "minimum" => 10, "area" => "Dienten am Hochkönig"),
    "6462" => array ( "minimum" => 10, "area" => "Bischofshofen"),
    "6463" => array ( "minimum" => 10, "area" => "Annaberg-Lungötz"),
    "6466" => array ( "minimum" => 10, "area" => "Werfenweng"),
    "6467" => array ( "minimum" => 10, "area" => "Mühlbach am Hochkönig"),
    "6468" => array ( "minimum" => 10, "area" => "Werfen"),
    "6470" => array ( "minimum" => 10, "area" => "Atzmannsdorf"),
    "6471" => array ( "minimum" => 10, "area" => "Tweng"),
    "6472" => array ( "minimum" => 10, "area" => "Mauterndorf"),
    "6473" => array ( "minimum" => 10, "area" => "Mariapfarr"),
    "6474" => array ( "minimum" => 10, "area" => "Tamsweg"),
    "6475" => array ( "minimum" => 10, "area" => "Ramingstein"),
    "6476" => array ( "minimum" => 10, "area" => "Sankt Margarethen im Lungau"),
    "6477" => array ( "minimum" => 10, "area" => "Sankt Michael im Lungau"),
    "6478" => array ( "minimum" => 10, "area" => "Zederhaus"),
    "6479" => array ( "minimum" => 10, "area" => "Muhr"),
    "6483" => array ( "minimum" => 10, "area" => "Göriach"),
    "6484" => array ( "minimum" => 10, "area" => "Lessach"),
    "6541" => array ( "minimum" => 10, "area" => "Saalbach"),
    "6542" => array ( "minimum" => 10, "area" => "Zell am See"),
    "6543" => array ( "minimum" => 10, "area" => "Taxenbach"),
    "6544" => array ( "minimum" => 10, "area" => "Rauris"),
    "6545" => array ( "minimum" => 10, "area" => "Bruck an der Großglocknerstraße"),
    "6546" => array ( "minimum" => 10, "area" => "Fusch an der Großglocknerstraße"),
    "6547" => array ( "minimum" => 10, "area" => "Kaprun"),
    "6548" => array ( "minimum" => 10, "area" => "Niedernsill"),
    "6549" => array ( "minimum" => 10, "area" => "Piesendorf"),
    "6562" => array ( "minimum" => 10, "area" => "Mittersill"),
    "6563" => array ( "minimum" => 10, "area" => "Uttendorf"),
    "6564" => array ( "minimum" => 10, "area" => "Krimml"),
    "6565" => array ( "minimum" => 10, "area" => "Neukirchen am Großvenediger"),
    "6566" => array ( "minimum" => 10, "area" => "Bramberg am Wildkogel"),
    "6582" => array ( "minimum" => 10, "area" => "Saalfelden am Steinernen Meer"),
    "6583" => array ( "minimum" => 10, "area" => "Leogang"),
    "6584" => array ( "minimum" => 10, "area" => "Maria Alm am Steinernen Meer"),
    "6588" => array ( "minimum" => 10, "area" => "Lofer"),
    "6589" => array ( "minimum" => 10, "area" => "Unken"),
    "662" => array ( "minimum" => 9, "area" => "Salzburg"),
    "720" => array ( "minimum" => 12, "area" => ""),
    "7211" => array ( "minimum" => 10, "area" => "Reichenau im Mühlkreis"),
    "7212" => array ( "minimum" => 10, "area" => "Zwettl an der Rodl"),
    "7213" => array ( "minimum" => 10, "area" => "Bad Leonfelden"),
    "7214" => array ( "minimum" => 10, "area" => "Reichenthal"),
    "7215" => array ( "minimum" => 10, "area" => "Hellmonsödt"),
    "7216" => array ( "minimum" => 10, "area" => "Helfenberg"),
    "7217" => array ( "minimum" => 10, "area" => "Sankt Veit im Mühlkreis"),
    "7218" => array ( "minimum" => 10, "area" => "Großtraberg"),
    "7219" => array ( "minimum" => 10, "area" => "Vorderweißenbach"),
    "7221" => array ( "minimum" => 10, "area" => "Hörsching"),
    "7223" => array ( "minimum" => 10, "area" => "Enns"),
    "7224" => array ( "minimum" => 10, "area" => "Sankt Florian"),
    "7225" => array ( "minimum" => 10, "area" => "Hargelsberg"),
    "7226" => array ( "minimum" => 10, "area" => "Wilhering"),
    "7227" => array ( "minimum" => 10, "area" => "Neuhofen an der Krems"),
    "7228" => array ( "minimum" => 10, "area" => "Kematen an der Krems"),
    "7229" => array ( "minimum" => 10, "area" => "Traun"),
    "7230" => array ( "minimum" => 10, "area" => "Altenberg bei Linz"),
    "7231" => array ( "minimum" => 10, "area" => "Herzogsdorf"),
    "7232" => array ( "minimum" => 10, "area" => "Sankt Martin im Mühlkreis"),
    "7233" => array ( "minimum" => 10, "area" => "Feldkirchen an der Donau"),
    "7234" => array ( "minimum" => 10, "area" => "Ottensheim"),
    "7235" => array ( "minimum" => 10, "area" => "Gallneukirchen"),
    "7236" => array ( "minimum" => 10, "area" => "Pregarten"),
    "7237" => array ( "minimum" => 10, "area" => "Sankt Georgen an der Gusen"),
    "7238" => array ( "minimum" => 10, "area" => "Mauthausen"),
    "7239" => array ( "minimum" => 10, "area" => "Lichtenberg"),
    "7240" => array ( "minimum" => 10, "area" => "Sipbachzell"),
    "7241" => array ( "minimum" => 10, "area" => "Steinerkirchen an der Traun"),
    "7242" => array ( "minimum" => 10, "area" => "Wels"),
    "7243" => array ( "minimum" => 10, "area" => "Marchtrenk"),
    "7244" => array ( "minimum" => 10, "area" => "Sattledt"),
    "7245" => array ( "minimum" => 10, "area" => "Lambach"),
    "7246" => array ( "minimum" => 10, "area" => "Gunskirchen"),
    "7247" => array ( "minimum" => 10, "area" => "Kematen am Innbach"),
    "7248" => array ( "minimum" => 10, "area" => "Grieskirchen"),
    "7249" => array ( "minimum" => 10, "area" => "Bad Schallerbach"),
    "7250" => array ( "minimum" => 10, "area" => "Maria Neustift"),
    "7251" => array ( "minimum" => 10, "area" => "Schiedlberg"),
    "7252" => array ( "minimum" => 10, "area" => "Steyr"),
    "7253" => array ( "minimum" => 10, "area" => "Wolfern"),
    "7254" => array ( "minimum" => 10, "area" => "Großraming"),
    "7255" => array ( "minimum" => 10, "area" => "Losenstein"),
    "7256" => array ( "minimum" => 10, "area" => "Ternberg"),
    "7257" => array ( "minimum" => 10, "area" => "Grünburg"),
    "7258" => array ( "minimum" => 10, "area" => "Bad Hall"),
    "7259" => array ( "minimum" => 10, "area" => "Sierning"),
    "7260" => array ( "minimum" => 10, "area" => "Waldhausen"),
    "7261" => array ( "minimum" => 10, "area" => "Schönau im Mühlkreis"),
    "7262" => array ( "minimum" => 10, "area" => "Perg"),
    "7263" => array ( "minimum" => 10, "area" => "Bad Zell"),
    "7264" => array ( "minimum" => 10, "area" => "Windhaag bei Perg"),
    "7265" => array ( "minimum" => 10, "area" => "Pabneukirchen"),
    "7266" => array ( "minimum" => 10, "area" => "Bad Kreuzen"),
    "7267" => array ( "minimum" => 10, "area" => "Mönchdorf"),
    "7268" => array ( "minimum" => 10, "area" => "Grein"),
    "7269" => array ( "minimum" => 10, "area" => "Baumgartenberg"),
    "7272" => array ( "minimum" => 10, "area" => "Eferding"),
    "7273" => array ( "minimum" => 10, "area" => "Aschach an der Donau"),
    "7274" => array ( "minimum" => 10, "area" => "Alkoven"),
    "7276" => array ( "minimum" => 10, "area" => "Peuerbach"),
    "7277" => array ( "minimum" => 10, "area" => "Waizenkirchen"),
    "7278" => array ( "minimum" => 10, "area" => "Neukirchen am Walde"),
    "7279" => array ( "minimum" => 10, "area" => "Haibach ob der Donau"),
    "7280" => array ( "minimum" => 10, "area" => "Schwarzenberg am Böhmerwald"),
    "7281" => array ( "minimum" => 10, "area" => "Aigen im Mühlkreis"),
    "7282" => array ( "minimum" => 10, "area" => "Neufelden"),
    "7283" => array ( "minimum" => 10, "area" => "Sarleinsbach"),
    "7284" => array ( "minimum" => 10, "area" => "Oberkappel"),
    "7285" => array ( "minimum" => 10, "area" => "Hofkirchen im Mühlkreis"),
    "7286" => array ( "minimum" => 10, "area" => "Lembach im Mühlkreis"),
    "7287" => array ( "minimum" => 10, "area" => "Peilstein im Mühlviertel"),
    "7288" => array ( "minimum" => 10, "area" => "Ulrichsberg"),
    "7289" => array ( "minimum" => 10, "area" => "Rohrbach in Oberösterreich"),
    "732" => array ( "minimum" => 9, "area" => "Linz"),
    "7353" => array ( "minimum" => 10, "area" => "Gaflenz"),
    "7355" => array ( "minimum" => 10, "area" => "Weyer"),
    "7357" => array ( "minimum" => 10, "area" => "Kleinreifling"),
    "7412" => array ( "minimum" => 10, "area" => "Ybbs an der Donau"),
    "7413" => array ( "minimum" => 10, "area" => "Marbach an der Donau"),
    "7414" => array ( "minimum" => 10, "area" => "Weins-Isperdorf"),
    "7415" => array ( "minimum" => 10, "area" => "Altenmarkt (Yspertal)"),
    "7416" => array ( "minimum" => 10, "area" => "Wieselburg"),
    "7432" => array ( "minimum" => 10, "area" => "Strengberg"),
    "7433" => array ( "minimum" => 10, "area" => "Wallsee"),
    "7434" => array ( "minimum" => 10, "area" => "Haag"),
    "7435" => array ( "minimum" => 10, "area" => "Sankt Valentin"),
    "7442" => array ( "minimum" => 10, "area" => "Waidhofen an der Ybbs"),
    "7443" => array ( "minimum" => 10, "area" => "Ybbsitz"),
    "7444" => array ( "minimum" => 10, "area" => "Opponitz"),
    "7445" => array ( "minimum" => 10, "area" => "Hollenstein an der Ybbs"),
    "7448" => array ( "minimum" => 10, "area" => "Kematen an der Ybbs"),
    "7471" => array ( "minimum" => 10, "area" => "Neustadtl an der Donau"),
    "7472" => array ( "minimum" => 10, "area" => "Amstetten"),
    "7473" => array ( "minimum" => 10, "area" => "Blindenmarkt"),
    "7474" => array ( "minimum" => 10, "area" => "Euratsfeld"),
    "7475" => array ( "minimum" => 10, "area" => "Hausmening (Neuhofen an der Ybbs)"),
    "7476" => array ( "minimum" => 10, "area" => "Aschbach-Markt"),
    "7477" => array ( "minimum" => 10, "area" => "Sankt Peter in der Au"),
    "7478" => array ( "minimum" => 10, "area" => "Oed-Oehling"),
    "7479" => array ( "minimum" => 10, "area" => "Ardagger"),
    "7480" => array ( "minimum" => 10, "area" => "Langau (Gaming)"),
    "7482" => array ( "minimum" => 10, "area" => "Scheibbs"),
    "7483" => array ( "minimum" => 10, "area" => "Oberndorf an der Melk"),
    "7484" => array ( "minimum" => 10, "area" => "Göstling an der Ybbs"),
    "7485" => array ( "minimum" => 10, "area" => "Gaming"),
    "7486" => array ( "minimum" => 10, "area" => "Lunz am See"),
    "7487" => array ( "minimum" => 10, "area" => "Gresten"),
    "7488" => array ( "minimum" => 10, "area" => "Steinakirchen am Forst"),
    "7489" => array ( "minimum" => 10, "area" => "Purgstall an der Erlauf"),
    "7562" => array ( "minimum" => 10, "area" => "Windischgarsten"),
    "7563" => array ( "minimum" => 10, "area" => "Spital am Pyhrn"),
    "7564" => array ( "minimum" => 10, "area" => "Hinterstoder"),
    "7565" => array ( "minimum" => 10, "area" => "Sankt Pankraz"),
    "7566" => array ( "minimum" => 10, "area" => "Rosenau am Hengstpaß"),
    "7582" => array ( "minimum" => 10, "area" => "Kirchdorf an der Krems"),
    "7583" => array ( "minimum" => 10, "area" => "Kremsmünster"),
    "7584" => array ( "minimum" => 10, "area" => "Molln"),
    "7585" => array ( "minimum" => 10, "area" => "Klaus an der Pyhrnbahn"),
    "7586" => array ( "minimum" => 10, "area" => "Pettenbach"),
    "7587" => array ( "minimum" => 10, "area" => "Wartberg an der Krems"),
    "7588" => array ( "minimum" => 10, "area" => "Ried im Traunkreis"),
    "7612" => array ( "minimum" => 10, "area" => "Gmunden"),
    "7613" => array ( "minimum" => 10, "area" => "Laakirchen"),
    "7614" => array ( "minimum" => 10, "area" => "Vorchdorf"),
    "7615" => array ( "minimum" => 10, "area" => "Scharnstein"),
    "7616" => array ( "minimum" => 10, "area" => "Grünau im Almtal"),
    "7617" => array ( "minimum" => 10, "area" => "Traunkirchen"),
    "7618" => array ( "minimum" => 10, "area" => "Neukirchen (Altmünster)"),
    "7619" => array ( "minimum" => 10, "area" => "Kirchham"),
    "7662" => array ( "minimum" => 10, "area" => "Seewalchen am Attersee"),
    "7663" => array ( "minimum" => 10, "area" => "Steinbach am Attersee"),
    "7664" => array ( "minimum" => 10, "area" => "Weyregg am Attersee"),
    "7665" => array ( "minimum" => 10, "area" => "Unterach am Attersee"),
    "7666" => array ( "minimum" => 10, "area" => "Attersee"),
    "7667" => array ( "minimum" => 10, "area" => "Sankt Georgen im Attergau"),
    "7672" => array ( "minimum" => 10, "area" => "Vöcklabruck"),
    "7673" => array ( "minimum" => 10, "area" => "Schwanenstadt"),
    "7674" => array ( "minimum" => 10, "area" => "Attnang-Puchheim"),
    "7675" => array ( "minimum" => 10, "area" => "Ampflwang im Hausruckwald"),
    "7676" => array ( "minimum" => 10, "area" => "Ottnang am Hausruck"),
    "7682" => array ( "minimum" => 10, "area" => "Vöcklamarkt"),
    "7683" => array ( "minimum" => 10, "area" => "Frankenburg am Hausruck"),
    "7684" => array ( "minimum" => 10, "area" => "Frankenmarkt"),
    "7711" => array ( "minimum" => 10, "area" => "Suben"),
    "7712" => array ( "minimum" => 10, "area" => "Schärding"),
    "7713" => array ( "minimum" => 10, "area" => "Schardenberg"),
    "7714" => array ( "minimum" => 10, "area" => "Esternberg"),
    "7716" => array ( "minimum" => 10, "area" => "Münzkirchen"),
    "7717" => array ( "minimum" => 10, "area" => "Sankt Aegidi"),
    "7718" => array ( "minimum" => 10, "area" => "Waldkirchen am Wesen"),
    "7719" => array ( "minimum" => 10, "area" => "Taufkirchen an der Pram"),
    "7722" => array ( "minimum" => 10, "area" => "Braunau am Inn"),
    "7723" => array ( "minimum" => 10, "area" => "Altheim"),
    "7724" => array ( "minimum" => 10, "area" => "Mauerkirchen"),
    "7727" => array ( "minimum" => 10, "area" => "Ach"),
    "7728" => array ( "minimum" => 10, "area" => "Schwand im Innkreis"),
    "7729" => array ( "minimum" => 10, "area" => "Neukirchen an der Enknach"),
    "7732" => array ( "minimum" => 10, "area" => "Haag am Hausruck"),
    "7733" => array ( "minimum" => 10, "area" => "Neumarkt im Hausruckkreis"),
    "7734" => array ( "minimum" => 10, "area" => "Hofkirchen an der Trattnach"),
    "7735" => array ( "minimum" => 10, "area" => "Gaspoltshofen"),
    "7736" => array ( "minimum" => 10, "area" => "Pram"),
    "7742" => array ( "minimum" => 10, "area" => "Mattighofen"),
    "7743" => array ( "minimum" => 10, "area" => "Maria Schmolln"),
    "7744" => array ( "minimum" => 10, "area" => "Munderfing"),
    "7745" => array ( "minimum" => 10, "area" => "Lochen"),
    "7746" => array ( "minimum" => 10, "area" => "Friedburg"),
    "7747" => array ( "minimum" => 10, "area" => "Kirchberg bei Mattighofen"),
    "7748" => array ( "minimum" => 10, "area" => "Eggelsberg"),
    "7750" => array ( "minimum" => 10, "area" => "Andrichsfurt"),
    "7751" => array ( "minimum" => 10, "area" => "Sankt Martin im Innkreis"),
    "7752" => array ( "minimum" => 10, "area" => "Ried im Innkreis"),
    "7753" => array ( "minimum" => 10, "area" => "Eberschwang"),
    "7754" => array ( "minimum" => 10, "area" => "Waldzell"),
    "7755" => array ( "minimum" => 10, "area" => "Mettmach"),
    "7757" => array ( "minimum" => 10, "area" => "Gurten"),
    "7758" => array ( "minimum" => 10, "area" => "Obernberg am Inn"),
    "7759" => array ( "minimum" => 10, "area" => "Antiesenhofen"),
    "7762" => array ( "minimum" => 10, "area" => "Raab"),
    "7763" => array ( "minimum" => 10, "area" => "Kopfing im Innkreis"),
    "7764" => array ( "minimum" => 10, "area" => "Riedau"),
    "7765" => array ( "minimum" => 10, "area" => "Lambrechten"),
    "7766" => array ( "minimum" => 10, "area" => "Andorf"),
    "7767" => array ( "minimum" => 10, "area" => "Eggerding"),
    "7941" => array ( "minimum" => 10, "area" => "Neumarkt im Mühlkreis"),
    "7942" => array ( "minimum" => 10, "area" => "Freistadt"),
    "7943" => array ( "minimum" => 10, "area" => "Windhaag bei Freistadt"),
    "7944" => array ( "minimum" => 10, "area" => "Sandl"),
    "7945" => array ( "minimum" => 10, "area" => "Sankt Oswald bei Freistadt"),
    "7946" => array ( "minimum" => 10, "area" => "Gutau"),
    "7947" => array ( "minimum" => 10, "area" => "Kefermarkt"),
    "7948" => array ( "minimum" => 10, "area" => "Hirschbach im Mühlkreis"),
    "7949" => array ( "minimum" => 10, "area" => "Rainbach im Mühlkreis"),
    "7952" => array ( "minimum" => 10, "area" => "Weitersfelden"),
    "7953" => array ( "minimum" => 10, "area" => "Liebenau"),
    "7954" => array ( "minimum" => 10, "area" => "Sankt Georgen am Walde"),
    "7955" => array ( "minimum" => 10, "area" => "Königswiesen"),
    "7956" => array ( "minimum" => 10, "area" => "Unterweißenbach")
  );
  foreach ( $prefixes as $prefix => $data)
  {
    if ( (int) substr ( $parameters["Number"], 3, strlen ( $prefix)) == $prefix && strlen ( $parameters["Number"]) >= $data["minimum"])
    {
      return array_merge_recursive ( ( is_array ( $buffer) ? $buffer : array ()), array ( "CC" => "43", "NDC" => $prefix, "Country" => "Austria", "Area" => $data["area"], "City" => "", "Operator" => "", "SN" => substr ( $parameters["Number"], 3 + strlen ( $prefix)), "Type" => VD_PHONETYPE_LANDLINE, "CallFormats" => array ( "Local" => "0" . $prefix . " " . substr ( $parameters["Number"], 3 + strlen ( $prefix)), "International" => "+43 " . $prefix . " " . substr ( $parameters["Number"], 3 + strlen ( $prefix)))));
    }
  }

  /**
   * If reached here, number wasn't identified as a valid Austrian phone
   * number
   */
  return ( is_array ( $buffer) ? $buffer : false);
}
?>
