<?php
/**   ___ ___       ___ _______     ______                        __
 *   |   Y   .-----|   |   _   |   |   _  \ .-----.--------.---.-|__.-----.
 *   |.  |   |  _  |.  |.  1   |   |.  |   \|  _  |        |  _  |  |     |
 *   |.  |   |_____|.  |.  ____|   |.  |    |_____|__|__|__|___._|__|__|__|
 *   |:  1   |     |:  |:  |       |:  1    /
 *    \:.. ./      |::.|::.|       |::.. . /
 *     `---'       `---`---'       `------'
 *
 * Copyright (C) 2016-2025 Ernani José Camargo Azevedo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * VoIP Domain country database module install script.
 *
 * @author     Ernani José Camargo Azevedo <azevedo@voipdomain.io>
 * @version    1.0
 * @package    VoIP Domain
 * @subpackage CountryDB
 * @copyright  2016-2025 Ernani José Camargo Azevedo. All rights reserved.
 * @license    https://www.gnu.org/licenses/gpl-3.0.en.html
 */

/**
 * Hook to create Countries database
 */
framework_add_hook ( "install_db", "countries_install_db");

/**
 * Function to create countries database structure.
 *
 * @param string $buffer Buffer from plugin system if processed by other function
 *                       before
 * @param array $parameters Optional parameters to the function
 * @return string Output of the generated page
 */
function countries_install_db ( $buffer, $parameters)
{
  /**
   * Add basic system tables
   */
  install_add_db_table ( "Countries", "CREATE TABLE `Countries` (\n" .
                                      "  `Code` int(2) unsigned NOT NULL,\n" .
                                      "  `Name` varchar(255) NOT NULL,\n" .
                                      "  `Alpha2` char(2) NOT NULL,\n" .
                                      "  `Alpha3` char(3) NOT NULL,\n" .
                                      "  `Region` varchar(255) NOT NULL,\n" .
                                      "  `RegionCode` smallint(2) unsigned NOT NULL,\n" .
                                      "  `SubRegion` varchar(255) NOT NULL,\n" .
                                      "  `SubRegionCode` smallint(2) unsigned NOT NULL,\n" .
                                      "  `ISO3166-2` char(2) NOT NULL,\n" .
                                      "  `Currency` int(2) unsigned NOT NULL,\n" .
                                      "  PRIMARY KEY (`Code`),\n" .
                                      "  KEY `Name` (`Name`,`ISO3166-2`),\n" .
                                      "  KEY `Region` (`Region`,`SubRegion`),\n" .
                                      "  KEY `RegionCode` (`RegionCode`,`SubRegionCode`)\n" .
                                      ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Countries database';\n");
  install_add_db_table ( "CountryCodes", "CREATE TABLE `CountryCodes` (\n" .
                                         "  `Country` int(2) unsigned NOT NULL,\n" .
                                         "  `Prefix` varchar(255) NOT NULL,\n" .
                                         "  `Code` varchar(6) NOT NULL,\n" .
                                         "  KEY `Prefix` (`Prefix`),\n" .
                                         "  KEY `Code` (`Code`),\n" .
                                         "  KEY `CountryCodes_ibfk_1` (`Country`),\n" .
                                         "  CONSTRAINT `CountryCodes_ibfk_1` FOREIGN KEY (`Country`) REFERENCES `Countries` (`Code`) ON DELETE CASCADE ON UPDATE CASCADE\n" .
                                         ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Countries E.164 phone prefixes';\n", array ( "Countries"));

  /**
   * Add basic system triggers
   */
  install_add_db_trigger ( "CountriesInsert", "CREATE TRIGGER `CountriesInsert` AFTER INSERT ON `Countries` FOR EACH ROW CALL UpdateCache('Countries')");
  install_add_db_trigger ( "CountriesUpdate", "CREATE TRIGGER `CountriesUpdate` AFTER UPDATE ON `Countries` FOR EACH ROW CALL UpdateCache('Countries')");
  install_add_db_trigger ( "CountriesDelete", "CREATE TRIGGER `CountriesDelete` AFTER DELETE ON `Countries` FOR EACH ROW CALL UpdateCache('Countries')");
  install_add_db_trigger ( "CountryCodesInsert", "CREATE TRIGGER `CountryCodesInsert` AFTER INSERT ON `CountryCodes` FOR EACH ROW CALL UpdateCache('CountryCodes')");
  install_add_db_trigger ( "CountryCodesUpdate", "CREATE TRIGGER `CountryCodesUpdate` AFTER UPDATE ON `CountryCodes` FOR EACH ROW CALL UpdateCache('CountryCodes')");
  install_add_db_trigger ( "CountryCodesDelete", "CREATE TRIGGER `CountryCodesDelete` AFTER DELETE ON `CountryCodes` FOR EACH ROW CALL UpdateCache('CountryCodes')");

  /**
   * Add basic system tables data
   */
  install_add_db_data ( "Countries", array (
    array ( "Code" => 4, "Name" => "Afghanistan", "Alpha2" => "AF", "Alpha3" => "AFG", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Southern Asia", "SubRegionCode" => 34, "ISO3166-2" => "AF", "Currency" => 971),
    array ( "Code" => 8, "Name" => "Albania", "Alpha2" => "AL", "Alpha3" => "ALB", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Southern Europe", "SubRegionCode" => 39, "ISO3166-2" => "AL", "Currency" => 8),
    array ( "Code" => 10, "Name" => "Antarctica", "Alpha2" => "AQ", "Alpha3" => "ATA", "Region" => "", "RegionCode" => 0, "SubRegion" => "", "SubRegionCode" => 0, "ISO3166-2" => "AQ", "Currency" => 0),
    array ( "Code" => 12, "Name" => "Algeria", "Alpha2" => "DZ", "Alpha3" => "DZA", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Northern Africa", "SubRegionCode" => 15, "ISO3166-2" => "DZ", "Currency" => 12),
    array ( "Code" => 16, "Name" => "American Samoa", "Alpha2" => "AS", "Alpha3" => "ASM", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Polynesia", "SubRegionCode" => 61, "ISO3166-2" => "AS", "Currency" => 840),
    array ( "Code" => 20, "Name" => "Andorra", "Alpha2" => "AD", "Alpha3" => "AND", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Southern Europe", "SubRegionCode" => 39, "ISO3166-2" => "AD", "Currency" => 978),
    array ( "Code" => 24, "Name" => "Angola", "Alpha2" => "AO", "Alpha3" => "AGO", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Middle Africa", "SubRegionCode" => 17, "ISO3166-2" => "AO", "Currency" => 973),
    array ( "Code" => 28, "Name" => "Antigua and Barbuda", "Alpha2" => "AG", "Alpha3" => "ATG", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "AG", "Currency" => 951),
    array ( "Code" => 31, "Name" => "Azerbaijan", "Alpha2" => "AZ", "Alpha3" => "AZE", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Western Asia", "SubRegionCode" => 145, "ISO3166-2" => "AZ", "Currency" => 944),
    array ( "Code" => 32, "Name" => "Argentina", "Alpha2" => "AR", "Alpha3" => "ARG", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "South America", "SubRegionCode" => 5, "ISO3166-2" => "AR", "Currency" => 32),
    array ( "Code" => 36, "Name" => "Australia", "Alpha2" => "AU", "Alpha3" => "AUS", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Australia and New Zealand", "SubRegionCode" => 53, "ISO3166-2" => "AU", "Currency" => 36),
    array ( "Code" => 40, "Name" => "Austria", "Alpha2" => "AT", "Alpha3" => "AUT", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Western Europe", "SubRegionCode" => 155, "ISO3166-2" => "AT", "Currency" => 978),
    array ( "Code" => 44, "Name" => "Bahamas", "Alpha2" => "BS", "Alpha3" => "BHS", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "BS", "Currency" => 44),
    array ( "Code" => 48, "Name" => "Bahrain", "Alpha2" => "BH", "Alpha3" => "BHR", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Western Asia", "SubRegionCode" => 145, "ISO3166-2" => "BH", "Currency" => 48),
    array ( "Code" => 50, "Name" => "Bangladesh", "Alpha2" => "BD", "Alpha3" => "BGD", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Southern Asia", "SubRegionCode" => 34, "ISO3166-2" => "BD", "Currency" => 50),
    array ( "Code" => 51, "Name" => "Armenia", "Alpha2" => "AM", "Alpha3" => "ARM", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Western Asia", "SubRegionCode" => 145, "ISO3166-2" => "AM", "Currency" => 51),
    array ( "Code" => 52, "Name" => "Barbados", "Alpha2" => "BB", "Alpha3" => "BRB", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "BB", "Currency" => 52),
    array ( "Code" => 56, "Name" => "Belgium", "Alpha2" => "BE", "Alpha3" => "BEL", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Western Europe", "SubRegionCode" => 155, "ISO3166-2" => "BE", "Currency" => 978),
    array ( "Code" => 60, "Name" => "Bermuda", "Alpha2" => "BM", "Alpha3" => "BMU", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Northern America", "SubRegionCode" => 21, "ISO3166-2" => "BM", "Currency" => 60),
    array ( "Code" => 64, "Name" => "Bhutan", "Alpha2" => "BT", "Alpha3" => "BTN", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Southern Asia", "SubRegionCode" => 34, "ISO3166-2" => "BT", "Currency" => 64),
    array ( "Code" => 68, "Name" => "Bolivia (Plurinational State of)", "Alpha2" => "BO", "Alpha3" => "BOL", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "South America", "SubRegionCode" => 5, "ISO3166-2" => "BO", "Currency" => 68),
    array ( "Code" => 70, "Name" => "Bosnia and Herzegovina", "Alpha2" => "BA", "Alpha3" => "BIH", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Southern Europe", "SubRegionCode" => 39, "ISO3166-2" => "BA", "Currency" => 977),
    array ( "Code" => 72, "Name" => "Botswana", "Alpha2" => "BW", "Alpha3" => "BWA", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Southern Africa", "SubRegionCode" => 18, "ISO3166-2" => "BW", "Currency" => 72),
    array ( "Code" => 74, "Name" => "Bouvet Island", "Alpha2" => "BV", "Alpha3" => "BVT", "Region" => "", "RegionCode" => 0, "SubRegion" => "", "SubRegionCode" => 0, "ISO3166-2" => "BV", "Currency" => 578),
    array ( "Code" => 76, "Name" => "Brazil", "Alpha2" => "BR", "Alpha3" => "BRA", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "South America", "SubRegionCode" => 5, "ISO3166-2" => "BR", "Currency" => 986),
    array ( "Code" => 84, "Name" => "Belize", "Alpha2" => "BZ", "Alpha3" => "BLZ", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Central America", "SubRegionCode" => 13, "ISO3166-2" => "BZ", "Currency" => 84),
    array ( "Code" => 86, "Name" => "British Indian Ocean Territory", "Alpha2" => "IO", "Alpha3" => "IOT", "Region" => "", "RegionCode" => 0, "SubRegion" => "", "SubRegionCode" => 0, "ISO3166-2" => "IO", "Currency" => 840),
    array ( "Code" => 90, "Name" => "Solomon Islands", "Alpha2" => "SB", "Alpha3" => "SLB", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Melanesia", "SubRegionCode" => 54, "ISO3166-2" => "SB", "Currency" => 90),
    array ( "Code" => 92, "Name" => "Virgin Islands (British)", "Alpha2" => "VG", "Alpha3" => "VGB", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "VG", "Currency" => 840),
    array ( "Code" => 96, "Name" => "Brunei Darussalam", "Alpha2" => "BN", "Alpha3" => "BRN", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "South-Eastern Asia", "SubRegionCode" => 35, "ISO3166-2" => "BN", "Currency" => 96),
    array ( "Code" => 100, "Name" => "Bulgaria", "Alpha2" => "BG", "Alpha3" => "BGR", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Eastern Europe", "SubRegionCode" => 151, "ISO3166-2" => "BG", "Currency" => 975),
    array ( "Code" => 104, "Name" => "Myanmar", "Alpha2" => "MM", "Alpha3" => "MMR", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "South-Eastern Asia", "SubRegionCode" => 35, "ISO3166-2" => "MM", "Currency" => 104),
    array ( "Code" => 108, "Name" => "Burundi", "Alpha2" => "BI", "Alpha3" => "BDI", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Eastern Africa", "SubRegionCode" => 14, "ISO3166-2" => "BI", "Currency" => 108),
    array ( "Code" => 112, "Name" => "Belarus", "Alpha2" => "BY", "Alpha3" => "BLR", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Eastern Europe", "SubRegionCode" => 151, "ISO3166-2" => "BY", "Currency" => 933),
    array ( "Code" => 116, "Name" => "Cambodia", "Alpha2" => "KH", "Alpha3" => "KHM", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "South-Eastern Asia", "SubRegionCode" => 35, "ISO3166-2" => "KH", "Currency" => 116),
    array ( "Code" => 120, "Name" => "Cameroon", "Alpha2" => "CM", "Alpha3" => "CMR", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Middle Africa", "SubRegionCode" => 17, "ISO3166-2" => "CM", "Currency" => 950),
    array ( "Code" => 124, "Name" => "Canada", "Alpha2" => "CA", "Alpha3" => "CAN", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Northern America", "SubRegionCode" => 21, "ISO3166-2" => "CA", "Currency" => 124),
    array ( "Code" => 132, "Name" => "Cabo Verde", "Alpha2" => "CV", "Alpha3" => "CPV", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Western Africa", "SubRegionCode" => 11, "ISO3166-2" => "CV", "Currency" => 132),
    array ( "Code" => 136, "Name" => "Cayman Islands", "Alpha2" => "KY", "Alpha3" => "CYM", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "KY", "Currency" => 136),
    array ( "Code" => 140, "Name" => "Central African Republic", "Alpha2" => "CF", "Alpha3" => "CAF", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Middle Africa", "SubRegionCode" => 17, "ISO3166-2" => "CF", "Currency" => 950),
    array ( "Code" => 144, "Name" => "Sri Lanka", "Alpha2" => "LK", "Alpha3" => "LKA", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Southern Asia", "SubRegionCode" => 34, "ISO3166-2" => "LK", "Currency" => 144),
    array ( "Code" => 148, "Name" => "Chad", "Alpha2" => "TD", "Alpha3" => "TCD", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Middle Africa", "SubRegionCode" => 17, "ISO3166-2" => "TD", "Currency" => 950),
    array ( "Code" => 152, "Name" => "Chile", "Alpha2" => "CL", "Alpha3" => "CHL", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "South America", "SubRegionCode" => 5, "ISO3166-2" => "CL", "Currency" => 152),
    array ( "Code" => 156, "Name" => "China", "Alpha2" => "CN", "Alpha3" => "CHN", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Eastern Asia", "SubRegionCode" => 30, "ISO3166-2" => "CN", "Currency" => 156),
    array ( "Code" => 158, "Name" => "Taiwan, Province of China", "Alpha2" => "TW", "Alpha3" => "TWN", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Eastern Asia", "SubRegionCode" => 30, "ISO3166-2" => "TW", "Currency" => 901),
    array ( "Code" => 162, "Name" => "Christmas Island", "Alpha2" => "CX", "Alpha3" => "CXR", "Region" => "", "RegionCode" => 0, "SubRegion" => "", "SubRegionCode" => 0, "ISO3166-2" => "CX", "Currency" => 36),
    array ( "Code" => 166, "Name" => "Cocos (Keeling) Islands", "Alpha2" => "CC", "Alpha3" => "CCK", "Region" => "", "RegionCode" => 0, "SubRegion" => "", "SubRegionCode" => 0, "ISO3166-2" => "CC", "Currency" => 36),
    array ( "Code" => 170, "Name" => "Colombia", "Alpha2" => "CO", "Alpha3" => "COL", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "South America", "SubRegionCode" => 5, "ISO3166-2" => "CO", "Currency" => 170),
    array ( "Code" => 174, "Name" => "Comoros", "Alpha2" => "KM", "Alpha3" => "COM", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Eastern Africa", "SubRegionCode" => 14, "ISO3166-2" => "KM", "Currency" => 174),
    array ( "Code" => 175, "Name" => "Mayotte", "Alpha2" => "YT", "Alpha3" => "MYT", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Eastern Africa", "SubRegionCode" => 14, "ISO3166-2" => "YT", "Currency" => 978),
    array ( "Code" => 178, "Name" => "Congo", "Alpha2" => "CG", "Alpha3" => "COG", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Middle Africa", "SubRegionCode" => 17, "ISO3166-2" => "CG", "Currency" => 950),
    array ( "Code" => 180, "Name" => "Congo (Democratic Republic of the)", "Alpha2" => "CD", "Alpha3" => "COD", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Middle Africa", "SubRegionCode" => 17, "ISO3166-2" => "CD", "Currency" => 976),
    array ( "Code" => 184, "Name" => "Cook Islands", "Alpha2" => "CK", "Alpha3" => "COK", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Polynesia", "SubRegionCode" => 61, "ISO3166-2" => "CK", "Currency" => 554),
    array ( "Code" => 188, "Name" => "Costa Rica", "Alpha2" => "CR", "Alpha3" => "CRI", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Central America", "SubRegionCode" => 13, "ISO3166-2" => "CR", "Currency" => 188),
    array ( "Code" => 191, "Name" => "Croatia", "Alpha2" => "HR", "Alpha3" => "HRV", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Southern Europe", "SubRegionCode" => 39, "ISO3166-2" => "HR", "Currency" => 978),
    array ( "Code" => 192, "Name" => "Cuba", "Alpha2" => "CU", "Alpha3" => "CUB", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "CU", "Currency" => 931),
    array ( "Code" => 196, "Name" => "Cyprus", "Alpha2" => "CY", "Alpha3" => "CYP", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Western Asia", "SubRegionCode" => 145, "ISO3166-2" => "CY", "Currency" => 978),
    array ( "Code" => 203, "Name" => "Czech Republic", "Alpha2" => "CZ", "Alpha3" => "CZE", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Eastern Europe", "SubRegionCode" => 151, "ISO3166-2" => "CZ", "Currency" => 203),
    array ( "Code" => 204, "Name" => "Benin", "Alpha2" => "BJ", "Alpha3" => "BEN", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Western Africa", "SubRegionCode" => 11, "ISO3166-2" => "BJ", "Currency" => 952),
    array ( "Code" => 208, "Name" => "Denmark", "Alpha2" => "DK", "Alpha3" => "DNK", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Northern Europe", "SubRegionCode" => 154, "ISO3166-2" => "DK", "Currency" => 208),
    array ( "Code" => 212, "Name" => "Dominica", "Alpha2" => "DM", "Alpha3" => "DMA", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "DM", "Currency" => 951),
    array ( "Code" => 214, "Name" => "Dominican Republic", "Alpha2" => "DO", "Alpha3" => "DOM", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "DO", "Currency" => 214),
    array ( "Code" => 218, "Name" => "Ecuador", "Alpha2" => "EC", "Alpha3" => "ECU", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "South America", "SubRegionCode" => 5, "ISO3166-2" => "EC", "Currency" => 840),
    array ( "Code" => 222, "Name" => "El Salvador", "Alpha2" => "SV", "Alpha3" => "SLV", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Central America", "SubRegionCode" => 13, "ISO3166-2" => "SV", "Currency" => 840),
    array ( "Code" => 226, "Name" => "Equatorial Guinea", "Alpha2" => "GQ", "Alpha3" => "GNQ", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Middle Africa", "SubRegionCode" => 17, "ISO3166-2" => "GQ", "Currency" => 950),
    array ( "Code" => 231, "Name" => "Ethiopia", "Alpha2" => "ET", "Alpha3" => "ETH", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Eastern Africa", "SubRegionCode" => 14, "ISO3166-2" => "ET", "Currency" => 230),
    array ( "Code" => 232, "Name" => "Eritrea", "Alpha2" => "ER", "Alpha3" => "ERI", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Eastern Africa", "SubRegionCode" => 14, "ISO3166-2" => "ER", "Currency" => 232),
    array ( "Code" => 233, "Name" => "Estonia", "Alpha2" => "EE", "Alpha3" => "EST", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Northern Europe", "SubRegionCode" => 154, "ISO3166-2" => "EE", "Currency" => 978),
    array ( "Code" => 234, "Name" => "Faroe Islands", "Alpha2" => "FO", "Alpha3" => "FRO", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Northern Europe", "SubRegionCode" => 154, "ISO3166-2" => "FO", "Currency" => 208),
    array ( "Code" => 238, "Name" => "Falkland Islands (Malvinas)", "Alpha2" => "FK", "Alpha3" => "FLK", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "South America", "SubRegionCode" => 5, "ISO3166-2" => "FK", "Currency" => 238),
    array ( "Code" => 239, "Name" => "South Georgia and the South Sandwich Islands", "Alpha2" => "GS", "Alpha3" => "SGS", "Region" => "", "RegionCode" => 0, "SubRegion" => "", "SubRegionCode" => 0, "ISO3166-2" => "GS", "Currency" => 0),
    array ( "Code" => 242, "Name" => "Fiji", "Alpha2" => "FJ", "Alpha3" => "FJI", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Melanesia", "SubRegionCode" => 54, "ISO3166-2" => "FJ", "Currency" => 242),
    array ( "Code" => 246, "Name" => "Finland", "Alpha2" => "FI", "Alpha3" => "FIN", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Northern Europe", "SubRegionCode" => 154, "ISO3166-2" => "FI", "Currency" => 978),
    array ( "Code" => 248, "Name" => "Åland Islands", "Alpha2" => "AX", "Alpha3" => "ALA", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Northern Europe", "SubRegionCode" => 154, "ISO3166-2" => "AX", "Currency" => 978),
    array ( "Code" => 250, "Name" => "France", "Alpha2" => "FR", "Alpha3" => "FRA", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Western Europe", "SubRegionCode" => 155, "ISO3166-2" => "FR", "Currency" => 978),
    array ( "Code" => 254, "Name" => "French Guiana", "Alpha2" => "GF", "Alpha3" => "GUF", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "South America", "SubRegionCode" => 5, "ISO3166-2" => "GF", "Currency" => 978),
    array ( "Code" => 258, "Name" => "French Polynesia", "Alpha2" => "PF", "Alpha3" => "PYF", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Polynesia", "SubRegionCode" => 61, "ISO3166-2" => "PF", "Currency" => 953),
    array ( "Code" => 260, "Name" => "French Southern Territories", "Alpha2" => "TF", "Alpha3" => "ATF", "Region" => "", "RegionCode" => 0, "SubRegion" => "", "SubRegionCode" => 0, "ISO3166-2" => "TF", "Currency" => 978),
    array ( "Code" => 262, "Name" => "Djibouti", "Alpha2" => "DJ", "Alpha3" => "DJI", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Eastern Africa", "SubRegionCode" => 14, "ISO3166-2" => "DJ", "Currency" => 262),
    array ( "Code" => 266, "Name" => "Gabon", "Alpha2" => "GA", "Alpha3" => "GAB", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Middle Africa", "SubRegionCode" => 17, "ISO3166-2" => "GA", "Currency" => 950),
    array ( "Code" => 268, "Name" => "Georgia", "Alpha2" => "GE", "Alpha3" => "GEO", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Western Asia", "SubRegionCode" => 145, "ISO3166-2" => "GE", "Currency" => 981),
    array ( "Code" => 270, "Name" => "Gambia", "Alpha2" => "GM", "Alpha3" => "GMB", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Western Africa", "SubRegionCode" => 11, "ISO3166-2" => "GM", "Currency" => 270),
    array ( "Code" => 275, "Name" => "Palestine, State of", "Alpha2" => "PS", "Alpha3" => "PSE", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Western Asia", "SubRegionCode" => 145, "ISO3166-2" => "PS", "Currency" => 0),
    array ( "Code" => 276, "Name" => "Germany", "Alpha2" => "DE", "Alpha3" => "DEU", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Western Europe", "SubRegionCode" => 155, "ISO3166-2" => "DE", "Currency" => 978),
    array ( "Code" => 288, "Name" => "Ghana", "Alpha2" => "GH", "Alpha3" => "GHA", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Western Africa", "SubRegionCode" => 11, "ISO3166-2" => "GH", "Currency" => 936),
    array ( "Code" => 292, "Name" => "Gibraltar", "Alpha2" => "GI", "Alpha3" => "GIB", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Southern Europe", "SubRegionCode" => 39, "ISO3166-2" => "GI", "Currency" => 292),
    array ( "Code" => 296, "Name" => "Kiribati", "Alpha2" => "KI", "Alpha3" => "KIR", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Micronesia", "SubRegionCode" => 57, "ISO3166-2" => "KI", "Currency" => 36),
    array ( "Code" => 300, "Name" => "Greece", "Alpha2" => "GR", "Alpha3" => "GRC", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Southern Europe", "SubRegionCode" => 39, "ISO3166-2" => "GR", "Currency" => 978),
    array ( "Code" => 304, "Name" => "Greenland", "Alpha2" => "GL", "Alpha3" => "GRL", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Northern America", "SubRegionCode" => 21, "ISO3166-2" => "GL", "Currency" => 208),
    array ( "Code" => 308, "Name" => "Grenada", "Alpha2" => "GD", "Alpha3" => "GRD", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "GD", "Currency" => 951),
    array ( "Code" => 312, "Name" => "Guadeloupe", "Alpha2" => "GP", "Alpha3" => "GLP", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "GP", "Currency" => 978),
    array ( "Code" => 316, "Name" => "Guam", "Alpha2" => "GU", "Alpha3" => "GUM", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Micronesia", "SubRegionCode" => 57, "ISO3166-2" => "GU", "Currency" => 840),
    array ( "Code" => 320, "Name" => "Guatemala", "Alpha2" => "GT", "Alpha3" => "GTM", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Central America", "SubRegionCode" => 13, "ISO3166-2" => "GT", "Currency" => 320),
    array ( "Code" => 324, "Name" => "Guinea", "Alpha2" => "GN", "Alpha3" => "GIN", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Western Africa", "SubRegionCode" => 11, "ISO3166-2" => "GN", "Currency" => 324),
    array ( "Code" => 328, "Name" => "Guyana", "Alpha2" => "GY", "Alpha3" => "GUY", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "South America", "SubRegionCode" => 5, "ISO3166-2" => "GY", "Currency" => 328),
    array ( "Code" => 332, "Name" => "Haiti", "Alpha2" => "HT", "Alpha3" => "HTI", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "HT", "Currency" => 840),
    array ( "Code" => 334, "Name" => "Heard Island and McDonald Islands", "Alpha2" => "HM", "Alpha3" => "HMD", "Region" => "", "RegionCode" => 0, "SubRegion" => "", "SubRegionCode" => 0, "ISO3166-2" => "HM", "Currency" => 36),
    array ( "Code" => 336, "Name" => "Holy See", "Alpha2" => "VA", "Alpha3" => "VAT", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Southern Europe", "SubRegionCode" => 39, "ISO3166-2" => "VA", "Currency" => 978),
    array ( "Code" => 340, "Name" => "Honduras", "Alpha2" => "HN", "Alpha3" => "HND", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Central America", "SubRegionCode" => 13, "ISO3166-2" => "HN", "Currency" => 340),
    array ( "Code" => 344, "Name" => "Hong Kong", "Alpha2" => "HK", "Alpha3" => "HKG", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Eastern Asia", "SubRegionCode" => 30, "ISO3166-2" => "HK", "Currency" => 344),
    array ( "Code" => 348, "Name" => "Hungary", "Alpha2" => "HU", "Alpha3" => "HUN", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Eastern Europe", "SubRegionCode" => 151, "ISO3166-2" => "HU", "Currency" => 348),
    array ( "Code" => 352, "Name" => "Iceland", "Alpha2" => "IS", "Alpha3" => "ISL", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Northern Europe", "SubRegionCode" => 154, "ISO3166-2" => "IS", "Currency" => 352),
    array ( "Code" => 356, "Name" => "India", "Alpha2" => "IN", "Alpha3" => "IND", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Southern Asia", "SubRegionCode" => 34, "ISO3166-2" => "IN", "Currency" => 356),
    array ( "Code" => 360, "Name" => "Indonesia", "Alpha2" => "ID", "Alpha3" => "IDN", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "South-Eastern Asia", "SubRegionCode" => 35, "ISO3166-2" => "ID", "Currency" => 360),
    array ( "Code" => 364, "Name" => "Iran (Islamic Republic of)", "Alpha2" => "IR", "Alpha3" => "IRN", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Southern Asia", "SubRegionCode" => 34, "ISO3166-2" => "IR", "Currency" => 364),
    array ( "Code" => 368, "Name" => "Iraq", "Alpha2" => "IQ", "Alpha3" => "IRQ", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Western Asia", "SubRegionCode" => 145, "ISO3166-2" => "IQ", "Currency" => 368),
    array ( "Code" => 372, "Name" => "Ireland", "Alpha2" => "IE", "Alpha3" => "IRL", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Northern Europe", "SubRegionCode" => 154, "ISO3166-2" => "IE", "Currency" => 978),
    array ( "Code" => 376, "Name" => "Israel", "Alpha2" => "IL", "Alpha3" => "ISR", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Western Asia", "SubRegionCode" => 145, "ISO3166-2" => "IL", "Currency" => 376),
    array ( "Code" => 380, "Name" => "Italy", "Alpha2" => "IT", "Alpha3" => "ITA", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Southern Europe", "SubRegionCode" => 39, "ISO3166-2" => "IT", "Currency" => 978),
    array ( "Code" => 384, "Name" => "Côte d'Ivoire", "Alpha2" => "CI", "Alpha3" => "CIV", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Western Africa", "SubRegionCode" => 11, "ISO3166-2" => "CI", "Currency" => 952),
    array ( "Code" => 388, "Name" => "Jamaica", "Alpha2" => "JM", "Alpha3" => "JAM", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "JM", "Currency" => 388),
    array ( "Code" => 392, "Name" => "Japan", "Alpha2" => "JP", "Alpha3" => "JPN", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Eastern Asia", "SubRegionCode" => 30, "ISO3166-2" => "JP", "Currency" => 392),
    array ( "Code" => 398, "Name" => "Kazakhstan", "Alpha2" => "KZ", "Alpha3" => "KAZ", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Central Asia", "SubRegionCode" => 143, "ISO3166-2" => "KZ", "Currency" => 398),
    array ( "Code" => 400, "Name" => "Jordan", "Alpha2" => "JO", "Alpha3" => "JOR", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Western Asia", "SubRegionCode" => 145, "ISO3166-2" => "JO", "Currency" => 400),
    array ( "Code" => 404, "Name" => "Kenya", "Alpha2" => "KE", "Alpha3" => "KEN", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Eastern Africa", "SubRegionCode" => 14, "ISO3166-2" => "KE", "Currency" => 404),
    array ( "Code" => 408, "Name" => "Korea (Democratic People's Republic of)", "Alpha2" => "KP", "Alpha3" => "PRK", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Eastern Asia", "SubRegionCode" => 30, "ISO3166-2" => "KP", "Currency" => 408),
    array ( "Code" => 410, "Name" => "Korea (Republic of)", "Alpha2" => "KR", "Alpha3" => "KOR", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Eastern Asia", "SubRegionCode" => 30, "ISO3166-2" => "KR", "Currency" => 410),
    array ( "Code" => 414, "Name" => "Kuwait", "Alpha2" => "KW", "Alpha3" => "KWT", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Western Asia", "SubRegionCode" => 145, "ISO3166-2" => "KW", "Currency" => 414),
    array ( "Code" => 417, "Name" => "Kyrgyzstan", "Alpha2" => "KG", "Alpha3" => "KGZ", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Central Asia", "SubRegionCode" => 143, "ISO3166-2" => "KG", "Currency" => 417),
    array ( "Code" => 418, "Name" => "Lao People's Democratic Republic", "Alpha2" => "LA", "Alpha3" => "LAO", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "South-Eastern Asia", "SubRegionCode" => 35, "ISO3166-2" => "LA", "Currency" => 418),
    array ( "Code" => 422, "Name" => "Lebanon", "Alpha2" => "LB", "Alpha3" => "LBN", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Western Asia", "SubRegionCode" => 145, "ISO3166-2" => "LB", "Currency" => 422),
    array ( "Code" => 426, "Name" => "Lesotho", "Alpha2" => "LS", "Alpha3" => "LSO", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Southern Africa", "SubRegionCode" => 18, "ISO3166-2" => "LS", "Currency" => 710),
    array ( "Code" => 428, "Name" => "Latvia", "Alpha2" => "LV", "Alpha3" => "LVA", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Northern Europe", "SubRegionCode" => 154, "ISO3166-2" => "LV", "Currency" => 978),
    array ( "Code" => 430, "Name" => "Liberia", "Alpha2" => "LR", "Alpha3" => "LBR", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Western Africa", "SubRegionCode" => 11, "ISO3166-2" => "LR", "Currency" => 430),
    array ( "Code" => 434, "Name" => "Libya", "Alpha2" => "LY", "Alpha3" => "LBY", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Northern Africa", "SubRegionCode" => 15, "ISO3166-2" => "LY", "Currency" => 434),
    array ( "Code" => 438, "Name" => "Liechtenstein", "Alpha2" => "LI", "Alpha3" => "LIE", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Western Europe", "SubRegionCode" => 155, "ISO3166-2" => "LI", "Currency" => 756),
    array ( "Code" => 440, "Name" => "Lithuania", "Alpha2" => "LT", "Alpha3" => "LTU", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Northern Europe", "SubRegionCode" => 154, "ISO3166-2" => "LT", "Currency" => 978),
    array ( "Code" => 442, "Name" => "Luxembourg", "Alpha2" => "LU", "Alpha3" => "LUX", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Western Europe", "SubRegionCode" => 155, "ISO3166-2" => "LU", "Currency" => 978),
    array ( "Code" => 446, "Name" => "Macao", "Alpha2" => "MO", "Alpha3" => "MAC", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Eastern Asia", "SubRegionCode" => 30, "ISO3166-2" => "MO", "Currency" => 446),
    array ( "Code" => 450, "Name" => "Madagascar", "Alpha2" => "MG", "Alpha3" => "MDG", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Eastern Africa", "SubRegionCode" => 14, "ISO3166-2" => "MG", "Currency" => 969),
    array ( "Code" => 454, "Name" => "Malawi", "Alpha2" => "MW", "Alpha3" => "MWI", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Eastern Africa", "SubRegionCode" => 14, "ISO3166-2" => "MW", "Currency" => 454),
    array ( "Code" => 458, "Name" => "Malaysia", "Alpha2" => "MY", "Alpha3" => "MYS", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "South-Eastern Asia", "SubRegionCode" => 35, "ISO3166-2" => "MY", "Currency" => 458),
    array ( "Code" => 462, "Name" => "Maldives", "Alpha2" => "MV", "Alpha3" => "MDV", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Southern Asia", "SubRegionCode" => 34, "ISO3166-2" => "MV", "Currency" => 462),
    array ( "Code" => 466, "Name" => "Mali", "Alpha2" => "ML", "Alpha3" => "MLI", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Western Africa", "SubRegionCode" => 11, "ISO3166-2" => "ML", "Currency" => 952),
    array ( "Code" => 470, "Name" => "Malta", "Alpha2" => "MT", "Alpha3" => "MLT", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Southern Europe", "SubRegionCode" => 39, "ISO3166-2" => "MT", "Currency" => 978),
    array ( "Code" => 474, "Name" => "Martinique", "Alpha2" => "MQ", "Alpha3" => "MTQ", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "MQ", "Currency" => 978),
    array ( "Code" => 478, "Name" => "Mauritania", "Alpha2" => "MR", "Alpha3" => "MRT", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Western Africa", "SubRegionCode" => 11, "ISO3166-2" => "MR", "Currency" => 929),
    array ( "Code" => 480, "Name" => "Mauritius", "Alpha2" => "MU", "Alpha3" => "MUS", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Eastern Africa", "SubRegionCode" => 14, "ISO3166-2" => "MU", "Currency" => 480),
    array ( "Code" => 484, "Name" => "Mexico", "Alpha2" => "MX", "Alpha3" => "MEX", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Central America", "SubRegionCode" => 13, "ISO3166-2" => "MX", "Currency" => 484),
    array ( "Code" => 492, "Name" => "Monaco", "Alpha2" => "MC", "Alpha3" => "MCO", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Western Europe", "SubRegionCode" => 155, "ISO3166-2" => "MC", "Currency" => 978),
    array ( "Code" => 496, "Name" => "Mongolia", "Alpha2" => "MN", "Alpha3" => "MNG", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Eastern Asia", "SubRegionCode" => 30, "ISO3166-2" => "MN", "Currency" => 496),
    array ( "Code" => 498, "Name" => "Moldova (Republic of)", "Alpha2" => "MD", "Alpha3" => "MDA", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Eastern Europe", "SubRegionCode" => 151, "ISO3166-2" => "MD", "Currency" => 498),
    array ( "Code" => 499, "Name" => "Montenegro", "Alpha2" => "ME", "Alpha3" => "MNE", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Southern Europe", "SubRegionCode" => 39, "ISO3166-2" => "ME", "Currency" => 978),
    array ( "Code" => 500, "Name" => "Montserrat", "Alpha2" => "MS", "Alpha3" => "MSR", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "MS", "Currency" => 951),
    array ( "Code" => 504, "Name" => "Morocco", "Alpha2" => "MA", "Alpha3" => "MAR", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Northern Africa", "SubRegionCode" => 15, "ISO3166-2" => "MA", "Currency" => 504),
    array ( "Code" => 508, "Name" => "Mozambique", "Alpha2" => "MZ", "Alpha3" => "MOZ", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Eastern Africa", "SubRegionCode" => 14, "ISO3166-2" => "MZ", "Currency" => 943),
    array ( "Code" => 512, "Name" => "Oman", "Alpha2" => "OM", "Alpha3" => "OMN", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Western Asia", "SubRegionCode" => 145, "ISO3166-2" => "OM", "Currency" => 512),
    array ( "Code" => 516, "Name" => "Namibia", "Alpha2" => "NA", "Alpha3" => "NAM", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Southern Africa", "SubRegionCode" => 18, "ISO3166-2" => "NA", "Currency" => 710),
    array ( "Code" => 520, "Name" => "Nauru", "Alpha2" => "NR", "Alpha3" => "NRU", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Micronesia", "SubRegionCode" => 57, "ISO3166-2" => "NR", "Currency" => 36),
    array ( "Code" => 524, "Name" => "Nepal", "Alpha2" => "NP", "Alpha3" => "NPL", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Southern Asia", "SubRegionCode" => 34, "ISO3166-2" => "NP", "Currency" => 524),
    array ( "Code" => 528, "Name" => "Netherlands", "Alpha2" => "NL", "Alpha3" => "NLD", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Western Europe", "SubRegionCode" => 155, "ISO3166-2" => "NL", "Currency" => 978),
    array ( "Code" => 531, "Name" => "Curaçao", "Alpha2" => "CW", "Alpha3" => "CUW", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "CW", "Currency" => 532),
    array ( "Code" => 533, "Name" => "Aruba", "Alpha2" => "AW", "Alpha3" => "ABW", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "AW", "Currency" => 533),
    array ( "Code" => 534, "Name" => "Sint Maarten (Dutch part)", "Alpha2" => "SX", "Alpha3" => "SXM", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "SX", "Currency" => 532),
    array ( "Code" => 535, "Name" => "Bonaire, Sint Eustatius and Saba", "Alpha2" => "BQ", "Alpha3" => "BES", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "BQ", "Currency" => 840),
    array ( "Code" => 540, "Name" => "New Caledonia", "Alpha2" => "NC", "Alpha3" => "NCL", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Melanesia", "SubRegionCode" => 54, "ISO3166-2" => "NC", "Currency" => 953),
    array ( "Code" => 548, "Name" => "Vanuatu", "Alpha2" => "VU", "Alpha3" => "VUT", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Melanesia", "SubRegionCode" => 54, "ISO3166-2" => "VU", "Currency" => 548),
    array ( "Code" => 554, "Name" => "New Zealand", "Alpha2" => "NZ", "Alpha3" => "NZL", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Australia and New Zealand", "SubRegionCode" => 53, "ISO3166-2" => "NZ", "Currency" => 554),
    array ( "Code" => 558, "Name" => "Nicaragua", "Alpha2" => "NI", "Alpha3" => "NIC", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Central America", "SubRegionCode" => 13, "ISO3166-2" => "NI", "Currency" => 558),
    array ( "Code" => 562, "Name" => "Niger", "Alpha2" => "NE", "Alpha3" => "NER", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Western Africa", "SubRegionCode" => 11, "ISO3166-2" => "NE", "Currency" => 952),
    array ( "Code" => 566, "Name" => "Nigeria", "Alpha2" => "NG", "Alpha3" => "NGA", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Western Africa", "SubRegionCode" => 11, "ISO3166-2" => "NG", "Currency" => 566),
    array ( "Code" => 570, "Name" => "Niue", "Alpha2" => "NU", "Alpha3" => "NIU", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Polynesia", "SubRegionCode" => 61, "ISO3166-2" => "NU", "Currency" => 554),
    array ( "Code" => 574, "Name" => "Norfolk Island", "Alpha2" => "NF", "Alpha3" => "NFK", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Australia and New Zealand", "SubRegionCode" => 53, "ISO3166-2" => "NF", "Currency" => 36),
    array ( "Code" => 578, "Name" => "Norway", "Alpha2" => "NO", "Alpha3" => "NOR", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Northern Europe", "SubRegionCode" => 154, "ISO3166-2" => "NO", "Currency" => 578),
    array ( "Code" => 580, "Name" => "Northern Mariana Islands", "Alpha2" => "MP", "Alpha3" => "MNP", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Micronesia", "SubRegionCode" => 57, "ISO3166-2" => "MP", "Currency" => 840),
    array ( "Code" => 581, "Name" => "United States Minor Outlying Islands", "Alpha2" => "UM", "Alpha3" => "UMI", "Region" => "", "RegionCode" => 0, "SubRegion" => "", "SubRegionCode" => 0, "ISO3166-2" => "UM", "Currency" => 840),
    array ( "Code" => 583, "Name" => "Micronesia (Federated States of)", "Alpha2" => "FM", "Alpha3" => "FSM", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Micronesia", "SubRegionCode" => 57, "ISO3166-2" => "FM", "Currency" => 840),
    array ( "Code" => 584, "Name" => "Marshall Islands", "Alpha2" => "MH", "Alpha3" => "MHL", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Micronesia", "SubRegionCode" => 57, "ISO3166-2" => "MH", "Currency" => 840),
    array ( "Code" => 585, "Name" => "Palau", "Alpha2" => "PW", "Alpha3" => "PLW", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Micronesia", "SubRegionCode" => 57, "ISO3166-2" => "PW", "Currency" => 840),
    array ( "Code" => 586, "Name" => "Pakistan", "Alpha2" => "PK", "Alpha3" => "PAK", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Southern Asia", "SubRegionCode" => 34, "ISO3166-2" => "PK", "Currency" => 586),
    array ( "Code" => 591, "Name" => "Panama", "Alpha2" => "PA", "Alpha3" => "PAN", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Central America", "SubRegionCode" => 13, "ISO3166-2" => "PA", "Currency" => 840),
    array ( "Code" => 598, "Name" => "Papua New Guinea", "Alpha2" => "PG", "Alpha3" => "PNG", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Melanesia", "SubRegionCode" => 54, "ISO3166-2" => "PG", "Currency" => 598),
    array ( "Code" => 600, "Name" => "Paraguay", "Alpha2" => "PY", "Alpha3" => "PRY", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "South America", "SubRegionCode" => 5, "ISO3166-2" => "PY", "Currency" => 600),
    array ( "Code" => 604, "Name" => "Peru", "Alpha2" => "PE", "Alpha3" => "PER", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "South America", "SubRegionCode" => 5, "ISO3166-2" => "PE", "Currency" => 604),
    array ( "Code" => 608, "Name" => "Philippines", "Alpha2" => "PH", "Alpha3" => "PHL", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "South-Eastern Asia", "SubRegionCode" => 35, "ISO3166-2" => "PH", "Currency" => 608),
    array ( "Code" => 612, "Name" => "Pitcairn", "Alpha2" => "PN", "Alpha3" => "PCN", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Polynesia", "SubRegionCode" => 61, "ISO3166-2" => "PN", "Currency" => 554),
    array ( "Code" => 616, "Name" => "Poland", "Alpha2" => "PL", "Alpha3" => "POL", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Eastern Europe", "SubRegionCode" => 151, "ISO3166-2" => "PL", "Currency" => 985),
    array ( "Code" => 620, "Name" => "Portugal", "Alpha2" => "PT", "Alpha3" => "PRT", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Southern Europe", "SubRegionCode" => 39, "ISO3166-2" => "PT", "Currency" => 978),
    array ( "Code" => 624, "Name" => "Guinea-Bissau", "Alpha2" => "GW", "Alpha3" => "GNB", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Western Africa", "SubRegionCode" => 11, "ISO3166-2" => "GW", "Currency" => 952),
    array ( "Code" => 626, "Name" => "Timor-Leste", "Alpha2" => "TL", "Alpha3" => "TLS", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "South-Eastern Asia", "SubRegionCode" => 35, "ISO3166-2" => "TL", "Currency" => 840),
    array ( "Code" => 630, "Name" => "Puerto Rico", "Alpha2" => "PR", "Alpha3" => "PRI", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "PR", "Currency" => 840),
    array ( "Code" => 634, "Name" => "Qatar", "Alpha2" => "QA", "Alpha3" => "QAT", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Western Asia", "SubRegionCode" => 145, "ISO3166-2" => "QA", "Currency" => 634),
    array ( "Code" => 638, "Name" => "Réunion", "Alpha2" => "RE", "Alpha3" => "REU", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Eastern Africa", "SubRegionCode" => 14, "ISO3166-2" => "RE", "Currency" => 978),
    array ( "Code" => 642, "Name" => "Romania", "Alpha2" => "RO", "Alpha3" => "ROU", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Eastern Europe", "SubRegionCode" => 151, "ISO3166-2" => "RO", "Currency" => 946),
    array ( "Code" => 643, "Name" => "Russian Federation", "Alpha2" => "RU", "Alpha3" => "RUS", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Eastern Europe", "SubRegionCode" => 151, "ISO3166-2" => "RU", "Currency" => 643),
    array ( "Code" => 646, "Name" => "Rwanda", "Alpha2" => "RW", "Alpha3" => "RWA", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Eastern Africa", "SubRegionCode" => 14, "ISO3166-2" => "RW", "Currency" => 646),
    array ( "Code" => 652, "Name" => "Saint Barthélemy", "Alpha2" => "BL", "Alpha3" => "BLM", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "BL", "Currency" => 978),
    array ( "Code" => 654, "Name" => "Saint Helena, Ascension and Tristan da Cunha", "Alpha2" => "SH", "Alpha3" => "SHN", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Western Africa", "SubRegionCode" => 11, "ISO3166-2" => "SH", "Currency" => 654),
    array ( "Code" => 659, "Name" => "Saint Kitts and Nevis", "Alpha2" => "KN", "Alpha3" => "KNA", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "KN", "Currency" => 951),
    array ( "Code" => 660, "Name" => "Anguilla", "Alpha2" => "AI", "Alpha3" => "AIA", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "AI", "Currency" => 951),
    array ( "Code" => 662, "Name" => "Saint Lucia", "Alpha2" => "LC", "Alpha3" => "LCA", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "LC", "Currency" => 951),
    array ( "Code" => 663, "Name" => "Saint Martin (French part)", "Alpha2" => "MF", "Alpha3" => "MAF", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "MF", "Currency" => 978),
    array ( "Code" => 666, "Name" => "Saint Pierre and Miquelon", "Alpha2" => "PM", "Alpha3" => "SPM", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Northern America", "SubRegionCode" => 21, "ISO3166-2" => "PM", "Currency" => 978),
    array ( "Code" => 670, "Name" => "Saint Vincent and the Grenadines", "Alpha2" => "VC", "Alpha3" => "VCT", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "VC", "Currency" => 951),
    array ( "Code" => 674, "Name" => "San Marino", "Alpha2" => "SM", "Alpha3" => "SMR", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Southern Europe", "SubRegionCode" => 39, "ISO3166-2" => "SM", "Currency" => 978),
    array ( "Code" => 678, "Name" => "Sao Tome and Principe", "Alpha2" => "ST", "Alpha3" => "STP", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Middle Africa", "SubRegionCode" => 17, "ISO3166-2" => "ST", "Currency" => 930),
    array ( "Code" => 682, "Name" => "Saudi Arabia", "Alpha2" => "SA", "Alpha3" => "SAU", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Western Asia", "SubRegionCode" => 145, "ISO3166-2" => "SA", "Currency" => 682),
    array ( "Code" => 686, "Name" => "Senegal", "Alpha2" => "SN", "Alpha3" => "SEN", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Western Africa", "SubRegionCode" => 11, "ISO3166-2" => "SN", "Currency" => 952),
    array ( "Code" => 688, "Name" => "Serbia", "Alpha2" => "RS", "Alpha3" => "SRB", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Southern Europe", "SubRegionCode" => 39, "ISO3166-2" => "RS", "Currency" => 941),
    array ( "Code" => 690, "Name" => "Seychelles", "Alpha2" => "SC", "Alpha3" => "SYC", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Eastern Africa", "SubRegionCode" => 14, "ISO3166-2" => "SC", "Currency" => 690),
    array ( "Code" => 694, "Name" => "Sierra Leone", "Alpha2" => "SL", "Alpha3" => "SLE", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Western Africa", "SubRegionCode" => 11, "ISO3166-2" => "SL", "Currency" => 694),
    array ( "Code" => 702, "Name" => "Singapore", "Alpha2" => "SG", "Alpha3" => "SGP", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "South-Eastern Asia", "SubRegionCode" => 35, "ISO3166-2" => "SG", "Currency" => 702),
    array ( "Code" => 703, "Name" => "Slovakia", "Alpha2" => "SK", "Alpha3" => "SVK", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Eastern Europe", "SubRegionCode" => 151, "ISO3166-2" => "SK", "Currency" => 978),
    array ( "Code" => 704, "Name" => "Viet Nam", "Alpha2" => "VN", "Alpha3" => "VNM", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "South-Eastern Asia", "SubRegionCode" => 35, "ISO3166-2" => "VN", "Currency" => 704),
    array ( "Code" => 705, "Name" => "Slovenia", "Alpha2" => "SI", "Alpha3" => "SVN", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Southern Europe", "SubRegionCode" => 39, "ISO3166-2" => "SI", "Currency" => 978),
    array ( "Code" => 706, "Name" => "Somalia", "Alpha2" => "SO", "Alpha3" => "SOM", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Eastern Africa", "SubRegionCode" => 14, "ISO3166-2" => "SO", "Currency" => 706),
    array ( "Code" => 710, "Name" => "South Africa", "Alpha2" => "ZA", "Alpha3" => "ZAF", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Southern Africa", "SubRegionCode" => 18, "ISO3166-2" => "ZA", "Currency" => 710),
    array ( "Code" => 716, "Name" => "Zimbabwe", "Alpha2" => "ZW", "Alpha3" => "ZWE", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Eastern Africa", "SubRegionCode" => 14, "ISO3166-2" => "ZW", "Currency" => 932),
    array ( "Code" => 724, "Name" => "Spain", "Alpha2" => "ES", "Alpha3" => "ESP", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Southern Europe", "SubRegionCode" => 39, "ISO3166-2" => "ES", "Currency" => 978),
    array ( "Code" => 728, "Name" => "South Sudan", "Alpha2" => "SS", "Alpha3" => "SSD", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Eastern Africa", "SubRegionCode" => 14, "ISO3166-2" => "SS", "Currency" => 728),
    array ( "Code" => 729, "Name" => "Sudan", "Alpha2" => "SD", "Alpha3" => "SDN", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Northern Africa", "SubRegionCode" => 15, "ISO3166-2" => "SD", "Currency" => 938),
    array ( "Code" => 732, "Name" => "Western Sahara", "Alpha2" => "EH", "Alpha3" => "ESH", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Northern Africa", "SubRegionCode" => 15, "ISO3166-2" => "EH", "Currency" => 504),
    array ( "Code" => 740, "Name" => "Suriname", "Alpha2" => "SR", "Alpha3" => "SUR", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "South America", "SubRegionCode" => 5, "ISO3166-2" => "SR", "Currency" => 968),
    array ( "Code" => 744, "Name" => "Svalbard and Jan Mayen", "Alpha2" => "SJ", "Alpha3" => "SJM", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Northern Europe", "SubRegionCode" => 154, "ISO3166-2" => "SJ", "Currency" => 578),
    array ( "Code" => 748, "Name" => "Swaziland", "Alpha2" => "SZ", "Alpha3" => "SWZ", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Southern Africa", "SubRegionCode" => 18, "ISO3166-2" => "SZ", "Currency" => 748),
    array ( "Code" => 752, "Name" => "Sweden", "Alpha2" => "SE", "Alpha3" => "SWE", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Northern Europe", "SubRegionCode" => 154, "ISO3166-2" => "SE", "Currency" => 752),
    array ( "Code" => 756, "Name" => "Switzerland", "Alpha2" => "CH", "Alpha3" => "CHE", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Western Europe", "SubRegionCode" => 155, "ISO3166-2" => "CH", "Currency" => 756),
    array ( "Code" => 760, "Name" => "Syrian Arab Republic", "Alpha2" => "SY", "Alpha3" => "SYR", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Western Asia", "SubRegionCode" => 145, "ISO3166-2" => "SY", "Currency" => 760),
    array ( "Code" => 762, "Name" => "Tajikistan", "Alpha2" => "TJ", "Alpha3" => "TJK", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Central Asia", "SubRegionCode" => 143, "ISO3166-2" => "TJ", "Currency" => 972),
    array ( "Code" => 764, "Name" => "Thailand", "Alpha2" => "TH", "Alpha3" => "THA", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "South-Eastern Asia", "SubRegionCode" => 35, "ISO3166-2" => "TH", "Currency" => 764),
    array ( "Code" => 768, "Name" => "Togo", "Alpha2" => "TG", "Alpha3" => "TGO", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Western Africa", "SubRegionCode" => 11, "ISO3166-2" => "TG", "Currency" => 952),
    array ( "Code" => 772, "Name" => "Tokelau", "Alpha2" => "TK", "Alpha3" => "TKL", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Polynesia", "SubRegionCode" => 61, "ISO3166-2" => "TK", "Currency" => 554),
    array ( "Code" => 776, "Name" => "Tonga", "Alpha2" => "TO", "Alpha3" => "TON", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Polynesia", "SubRegionCode" => 61, "ISO3166-2" => "TO", "Currency" => 776),
    array ( "Code" => 780, "Name" => "Trinidad and Tobago", "Alpha2" => "TT", "Alpha3" => "TTO", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "TT", "Currency" => 780),
    array ( "Code" => 784, "Name" => "United Arab Emirates", "Alpha2" => "AE", "Alpha3" => "ARE", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Western Asia", "SubRegionCode" => 145, "ISO3166-2" => "AE", "Currency" => 784),
    array ( "Code" => 788, "Name" => "Tunisia", "Alpha2" => "TN", "Alpha3" => "TUN", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Northern Africa", "SubRegionCode" => 15, "ISO3166-2" => "TN", "Currency" => 788),
    array ( "Code" => 792, "Name" => "Turkey", "Alpha2" => "TR", "Alpha3" => "TUR", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Western Asia", "SubRegionCode" => 145, "ISO3166-2" => "TR", "Currency" => 949),
    array ( "Code" => 795, "Name" => "Turkmenistan", "Alpha2" => "TM", "Alpha3" => "TKM", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Central Asia", "SubRegionCode" => 143, "ISO3166-2" => "TM", "Currency" => 934),
    array ( "Code" => 796, "Name" => "Turks and Caicos Islands", "Alpha2" => "TC", "Alpha3" => "TCA", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "TC", "Currency" => 840),
    array ( "Code" => 798, "Name" => "Tuvalu", "Alpha2" => "TV", "Alpha3" => "TUV", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Polynesia", "SubRegionCode" => 61, "ISO3166-2" => "TV", "Currency" => 36),
    array ( "Code" => 800, "Name" => "Uganda", "Alpha2" => "UG", "Alpha3" => "UGA", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Eastern Africa", "SubRegionCode" => 14, "ISO3166-2" => "UG", "Currency" => 800),
    array ( "Code" => 804, "Name" => "Ukraine", "Alpha2" => "UA", "Alpha3" => "UKR", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Eastern Europe", "SubRegionCode" => 151, "ISO3166-2" => "UA", "Currency" => 980),
    array ( "Code" => 807, "Name" => "Macedonia (the former Yugoslav Republic of)", "Alpha2" => "MK", "Alpha3" => "MKD", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Southern Europe", "SubRegionCode" => 39, "ISO3166-2" => "MK", "Currency" => 807),
    array ( "Code" => 818, "Name" => "Egypt", "Alpha2" => "EG", "Alpha3" => "EGY", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Northern Africa", "SubRegionCode" => 15, "ISO3166-2" => "EG", "Currency" => 818),
    array ( "Code" => 826, "Name" => "United Kingdom of Great Britain and Northern Ireland", "Alpha2" => "GB", "Alpha3" => "GBR", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Northern Europe", "SubRegionCode" => 154, "ISO3166-2" => "GB", "Currency" => 826),
    array ( "Code" => 831, "Name" => "Guernsey", "Alpha2" => "GG", "Alpha3" => "GGY", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Northern Europe", "SubRegionCode" => 154, "ISO3166-2" => "GG", "Currency" => 826),
    array ( "Code" => 832, "Name" => "Jersey", "Alpha2" => "JE", "Alpha3" => "JEY", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Northern Europe", "SubRegionCode" => 154, "ISO3166-2" => "JE", "Currency" => 826),
    array ( "Code" => 833, "Name" => "Isle of Man", "Alpha2" => "IM", "Alpha3" => "IMN", "Region" => "Europe", "RegionCode" => 150, "SubRegion" => "Northern Europe", "SubRegionCode" => 154, "ISO3166-2" => "IM", "Currency" => 826),
    array ( "Code" => 834, "Name" => "Tanzania, United Republic of", "Alpha2" => "TZ", "Alpha3" => "TZA", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Eastern Africa", "SubRegionCode" => 14, "ISO3166-2" => "TZ", "Currency" => 834),
    array ( "Code" => 840, "Name" => "United States of America", "Alpha2" => "US", "Alpha3" => "USA", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Northern America", "SubRegionCode" => 21, "ISO3166-2" => "US", "Currency" => 840),
    array ( "Code" => 850, "Name" => "Virgin Islands (U.S.)", "Alpha2" => "VI", "Alpha3" => "VIR", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "Caribbean", "SubRegionCode" => 29, "ISO3166-2" => "VI", "Currency" => 840),
    array ( "Code" => 854, "Name" => "Burkina Faso", "Alpha2" => "BF", "Alpha3" => "BFA", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Western Africa", "SubRegionCode" => 11, "ISO3166-2" => "BF", "Currency" => 952),
    array ( "Code" => 858, "Name" => "Uruguay", "Alpha2" => "UY", "Alpha3" => "URY", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "South America", "SubRegionCode" => 5, "ISO3166-2" => "UY", "Currency" => 858),
    array ( "Code" => 860, "Name" => "Uzbekistan", "Alpha2" => "UZ", "Alpha3" => "UZB", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Central Asia", "SubRegionCode" => 143, "ISO3166-2" => "UZ", "Currency" => 860),
    array ( "Code" => 862, "Name" => "Venezuela (Bolivarian Republic of)", "Alpha2" => "VE", "Alpha3" => "VEN", "Region" => "Americas", "RegionCode" => 19, "SubRegion" => "South America", "SubRegionCode" => 5, "ISO3166-2" => "VE", "Currency" => 928),
    array ( "Code" => 876, "Name" => "Wallis and Futuna", "Alpha2" => "WF", "Alpha3" => "WLF", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Polynesia", "SubRegionCode" => 61, "ISO3166-2" => "WF", "Currency" => 953),
    array ( "Code" => 882, "Name" => "Samoa", "Alpha2" => "WS", "Alpha3" => "WSM", "Region" => "Oceania", "RegionCode" => 9, "SubRegion" => "Polynesia", "SubRegionCode" => 61, "ISO3166-2" => "WS", "Currency" => 882),
    array ( "Code" => 887, "Name" => "Yemen", "Alpha2" => "YE", "Alpha3" => "YEM", "Region" => "Asia", "RegionCode" => 142, "SubRegion" => "Western Asia", "SubRegionCode" => 145, "ISO3166-2" => "YE", "Currency" => 886),
    array ( "Code" => 894, "Name" => "Zambia", "Alpha2" => "ZM", "Alpha3" => "ZMB", "Region" => "Africa", "RegionCode" => 2, "SubRegion" => "Eastern Africa", "SubRegionCode" => 14, "ISO3166-2" => "ZM", "Currency" => 967)
  ));
  install_add_db_data ( "CountryCodes", array (
    array ( "Country" => 4, "Prefix" => "93", "Code" => "93"),
    array ( "Country" => 8, "Prefix" => "355", "Code" => "355"),
    array ( "Country" => 10, "Prefix" => "672", "Code" => "672"),
    array ( "Country" => 12, "Prefix" => "213", "Code" => "213"),
    array ( "Country" => 16, "Prefix" => "1684", "Code" => "1684"),
    array ( "Country" => 20, "Prefix" => "376", "Code" => "376"),
    array ( "Country" => 24, "Prefix" => "244", "Code" => "244"),
    array ( "Country" => 28, "Prefix" => "1268", "Code" => "1268"),
    array ( "Country" => 31, "Prefix" => "994", "Code" => "994"),
    array ( "Country" => 32, "Prefix" => "54", "Code" => "54"),
    array ( "Country" => 36, "Prefix" => "61", "Code" => "61"),
    array ( "Country" => 40, "Prefix" => "43", "Code" => "43"),
    array ( "Country" => 44, "Prefix" => "1242", "Code" => "1242"),
    array ( "Country" => 48, "Prefix" => "973", "Code" => "973"),
    array ( "Country" => 50, "Prefix" => "880", "Code" => "880"),
    array ( "Country" => 51, "Prefix" => "374", "Code" => "374"),
    array ( "Country" => 52, "Prefix" => "1246", "Code" => "1246"),
    array ( "Country" => 56, "Prefix" => "32", "Code" => "32"),
    array ( "Country" => 60, "Prefix" => "1441", "Code" => "1441"),
    array ( "Country" => 64, "Prefix" => "975", "Code" => "975"),
    array ( "Country" => 68, "Prefix" => "591", "Code" => "591"),
    array ( "Country" => 70, "Prefix" => "387", "Code" => "387"),
    array ( "Country" => 72, "Prefix" => "267", "Code" => "267"),
    array ( "Country" => 74, "Prefix" => "47", "Code" => "47"),
    array ( "Country" => 76, "Prefix" => "55", "Code" => "55"),
    array ( "Country" => 84, "Prefix" => "501", "Code" => "501"),
    array ( "Country" => 86, "Prefix" => "246", "Code" => "246"),
    array ( "Country" => 90, "Prefix" => "677", "Code" => "677"),
    array ( "Country" => 92, "Prefix" => "1284", "Code" => "1284"),
    array ( "Country" => 96, "Prefix" => "673", "Code" => "673"),
    array ( "Country" => 100, "Prefix" => "359", "Code" => "359"),
    array ( "Country" => 104, "Prefix" => "95", "Code" => "95"),
    array ( "Country" => 108, "Prefix" => "257", "Code" => "257"),
    array ( "Country" => 112, "Prefix" => "375", "Code" => "375"),
    array ( "Country" => 116, "Prefix" => "855", "Code" => "855"),
    array ( "Country" => 120, "Prefix" => "237", "Code" => "237"),
    array ( "Country" => 124, "Prefix" => "1", "Code" => "1"),
    array ( "Country" => 132, "Prefix" => "238", "Code" => "238"),
    array ( "Country" => 136, "Prefix" => "1345", "Code" => "1345"),
    array ( "Country" => 140, "Prefix" => "236", "Code" => "236"),
    array ( "Country" => 144, "Prefix" => "94", "Code" => "94"),
    array ( "Country" => 148, "Prefix" => "235", "Code" => "235"),
    array ( "Country" => 152, "Prefix" => "56", "Code" => "56"),
    array ( "Country" => 156, "Prefix" => "86", "Code" => "86"),
    array ( "Country" => 158, "Prefix" => "886", "Code" => "886"),
    array ( "Country" => 162, "Prefix" => "61", "Code" => "61"),
    array ( "Country" => 166, "Prefix" => "61", "Code" => "61"),
    array ( "Country" => 170, "Prefix" => "57", "Code" => "57"),
    array ( "Country" => 174, "Prefix" => "269", "Code" => "269"),
    array ( "Country" => 175, "Prefix" => "262", "Code" => "262"),
    array ( "Country" => 178, "Prefix" => "242", "Code" => "242"),
    array ( "Country" => 180, "Prefix" => "243", "Code" => "243"),
    array ( "Country" => 184, "Prefix" => "682", "Code" => "682"),
    array ( "Country" => 188, "Prefix" => "506", "Code" => "506"),
    array ( "Country" => 191, "Prefix" => "385", "Code" => "385"),
    array ( "Country" => 192, "Prefix" => "53", "Code" => "53"),
    array ( "Country" => 196, "Prefix" => "357", "Code" => "357"),
    array ( "Country" => 203, "Prefix" => "420", "Code" => "420"),
    array ( "Country" => 204, "Prefix" => "229", "Code" => "229"),
    array ( "Country" => 208, "Prefix" => "45", "Code" => "45"),
    array ( "Country" => 212, "Prefix" => "1767", "Code" => "1767"),
    array ( "Country" => 214, "Prefix" => "1809", "Code" => "1809"),
    array ( "Country" => 214, "Prefix" => "1829", "Code" => "1829"),
    array ( "Country" => 214, "Prefix" => "1849", "Code" => "1849"),
    array ( "Country" => 218, "Prefix" => "593", "Code" => "593"),
    array ( "Country" => 222, "Prefix" => "503", "Code" => "503"),
    array ( "Country" => 226, "Prefix" => "240", "Code" => "240"),
    array ( "Country" => 231, "Prefix" => "251", "Code" => "251"),
    array ( "Country" => 232, "Prefix" => "291", "Code" => "291"),
    array ( "Country" => 233, "Prefix" => "372", "Code" => "372"),
    array ( "Country" => 234, "Prefix" => "298", "Code" => "298"),
    array ( "Country" => 238, "Prefix" => "500", "Code" => "500"),
    array ( "Country" => 239, "Prefix" => "500", "Code" => "500"),
    array ( "Country" => 242, "Prefix" => "679", "Code" => "679"),
    array ( "Country" => 246, "Prefix" => "358", "Code" => "358"),
    array ( "Country" => 248, "Prefix" => "358", "Code" => "358"),
    array ( "Country" => 250, "Prefix" => "33", "Code" => "33"),
    array ( "Country" => 254, "Prefix" => "594", "Code" => "594"),
    array ( "Country" => 258, "Prefix" => "689", "Code" => "689"),
    array ( "Country" => 260, "Prefix" => "262", "Code" => "262"),
    array ( "Country" => 262, "Prefix" => "253", "Code" => "253"),
    array ( "Country" => 266, "Prefix" => "241", "Code" => "241"),
    array ( "Country" => 268, "Prefix" => "995", "Code" => "995"),
    array ( "Country" => 270, "Prefix" => "220", "Code" => "220"),
    array ( "Country" => 275, "Prefix" => "970", "Code" => "970"),
    array ( "Country" => 276, "Prefix" => "49", "Code" => "49"),
    array ( "Country" => 288, "Prefix" => "233", "Code" => "233"),
    array ( "Country" => 292, "Prefix" => "350", "Code" => "350"),
    array ( "Country" => 296, "Prefix" => "686", "Code" => "686"),
    array ( "Country" => 300, "Prefix" => "30", "Code" => "30"),
    array ( "Country" => 304, "Prefix" => "299", "Code" => "299"),
    array ( "Country" => 308, "Prefix" => "1473", "Code" => "1473"),
    array ( "Country" => 312, "Prefix" => "590", "Code" => "590"),
    array ( "Country" => 316, "Prefix" => "1671", "Code" => "1671"),
    array ( "Country" => 320, "Prefix" => "502", "Code" => "502"),
    array ( "Country" => 324, "Prefix" => "224", "Code" => "224"),
    array ( "Country" => 328, "Prefix" => "592", "Code" => "592"),
    array ( "Country" => 332, "Prefix" => "509", "Code" => "509"),
    array ( "Country" => 334, "Prefix" => "672", "Code" => "672"),
    array ( "Country" => 336, "Prefix" => "379", "Code" => "379"),
    array ( "Country" => 340, "Prefix" => "504", "Code" => "504"),
    array ( "Country" => 344, "Prefix" => "852", "Code" => "852"),
    array ( "Country" => 348, "Prefix" => "36", "Code" => "36"),
    array ( "Country" => 352, "Prefix" => "354", "Code" => "354"),
    array ( "Country" => 356, "Prefix" => "91", "Code" => "91"),
    array ( "Country" => 360, "Prefix" => "62", "Code" => "62"),
    array ( "Country" => 364, "Prefix" => "98", "Code" => "98"),
    array ( "Country" => 368, "Prefix" => "964", "Code" => "964"),
    array ( "Country" => 372, "Prefix" => "353", "Code" => "353"),
    array ( "Country" => 376, "Prefix" => "972", "Code" => "972"),
    array ( "Country" => 380, "Prefix" => "39", "Code" => "39"),
    array ( "Country" => 384, "Prefix" => "225", "Code" => "225"),
    array ( "Country" => 388, "Prefix" => "1876", "Code" => "1876"),
    array ( "Country" => 392, "Prefix" => "81", "Code" => "81"),
    array ( "Country" => 398, "Prefix" => "7", "Code" => "7"),
    array ( "Country" => 400, "Prefix" => "962", "Code" => "962"),
    array ( "Country" => 404, "Prefix" => "254", "Code" => "254"),
    array ( "Country" => 408, "Prefix" => "850", "Code" => "850"),
    array ( "Country" => 410, "Prefix" => "82", "Code" => "82"),
    array ( "Country" => 414, "Prefix" => "965", "Code" => "965"),
    array ( "Country" => 417, "Prefix" => "996", "Code" => "996"),
    array ( "Country" => 418, "Prefix" => "856", "Code" => "856"),
    array ( "Country" => 422, "Prefix" => "961", "Code" => "961"),
    array ( "Country" => 426, "Prefix" => "266", "Code" => "266"),
    array ( "Country" => 428, "Prefix" => "371", "Code" => "371"),
    array ( "Country" => 430, "Prefix" => "231", "Code" => "231"),
    array ( "Country" => 434, "Prefix" => "218", "Code" => "218"),
    array ( "Country" => 438, "Prefix" => "423", "Code" => "423"),
    array ( "Country" => 440, "Prefix" => "370", "Code" => "370"),
    array ( "Country" => 442, "Prefix" => "352", "Code" => "352"),
    array ( "Country" => 446, "Prefix" => "853", "Code" => "853"),
    array ( "Country" => 450, "Prefix" => "261", "Code" => "261"),
    array ( "Country" => 454, "Prefix" => "265", "Code" => "265"),
    array ( "Country" => 458, "Prefix" => "60", "Code" => "60"),
    array ( "Country" => 462, "Prefix" => "960", "Code" => "960"),
    array ( "Country" => 466, "Prefix" => "223", "Code" => "223"),
    array ( "Country" => 470, "Prefix" => "356", "Code" => "356"),
    array ( "Country" => 474, "Prefix" => "596", "Code" => "596"),
    array ( "Country" => 478, "Prefix" => "222", "Code" => "222"),
    array ( "Country" => 480, "Prefix" => "230", "Code" => "230"),
    array ( "Country" => 484, "Prefix" => "52", "Code" => "52"),
    array ( "Country" => 492, "Prefix" => "377", "Code" => "377"),
    array ( "Country" => 496, "Prefix" => "976", "Code" => "976"),
    array ( "Country" => 498, "Prefix" => "373", "Code" => "373"),
    array ( "Country" => 499, "Prefix" => "382", "Code" => "382"),
    array ( "Country" => 500, "Prefix" => "1664", "Code" => "1664"),
    array ( "Country" => 504, "Prefix" => "212", "Code" => "212"),
    array ( "Country" => 508, "Prefix" => "258", "Code" => "258"),
    array ( "Country" => 512, "Prefix" => "968", "Code" => "968"),
    array ( "Country" => 516, "Prefix" => "264", "Code" => "264"),
    array ( "Country" => 520, "Prefix" => "674", "Code" => "674"),
    array ( "Country" => 524, "Prefix" => "977", "Code" => "977"),
    array ( "Country" => 528, "Prefix" => "31", "Code" => "31"),
    array ( "Country" => 531, "Prefix" => "599", "Code" => "599"),
    array ( "Country" => 533, "Prefix" => "297", "Code" => "297"),
    array ( "Country" => 534, "Prefix" => "1721", "Code" => "1721"),
    array ( "Country" => 535, "Prefix" => "599", "Code" => "599"),
    array ( "Country" => 540, "Prefix" => "687", "Code" => "687"),
    array ( "Country" => 548, "Prefix" => "678", "Code" => "678"),
    array ( "Country" => 554, "Prefix" => "64", "Code" => "64"),
    array ( "Country" => 558, "Prefix" => "505", "Code" => "505"),
    array ( "Country" => 562, "Prefix" => "227", "Code" => "227"),
    array ( "Country" => 566, "Prefix" => "234", "Code" => "234"),
    array ( "Country" => 570, "Prefix" => "683", "Code" => "683"),
    array ( "Country" => 574, "Prefix" => "6723", "Code" => "6723"),
    array ( "Country" => 578, "Prefix" => "47", "Code" => "47"),
    array ( "Country" => 580, "Prefix" => "1670", "Code" => "1670"),
    array ( "Country" => 581, "Prefix" => "1", "Code" => "1"),
    array ( "Country" => 583, "Prefix" => "691", "Code" => "691"),
    array ( "Country" => 584, "Prefix" => "692", "Code" => "692"),
    array ( "Country" => 585, "Prefix" => "680", "Code" => "680"),
    array ( "Country" => 586, "Prefix" => "92", "Code" => "92"),
    array ( "Country" => 591, "Prefix" => "507", "Code" => "507"),
    array ( "Country" => 598, "Prefix" => "675", "Code" => "675"),
    array ( "Country" => 600, "Prefix" => "595", "Code" => "595"),
    array ( "Country" => 604, "Prefix" => "51", "Code" => "51"),
    array ( "Country" => 608, "Prefix" => "63", "Code" => "63"),
    array ( "Country" => 612, "Prefix" => "64", "Code" => "64"),
    array ( "Country" => 616, "Prefix" => "48", "Code" => "48"),
    array ( "Country" => 620, "Prefix" => "351", "Code" => "351"),
    array ( "Country" => 624, "Prefix" => "245", "Code" => "245"),
    array ( "Country" => 626, "Prefix" => "670", "Code" => "670"),
    array ( "Country" => 630, "Prefix" => "1787", "Code" => "1787"),
    array ( "Country" => 630, "Prefix" => "1939", "Code" => "1939"),
    array ( "Country" => 634, "Prefix" => "974", "Code" => "974"),
    array ( "Country" => 638, "Prefix" => "262", "Code" => "262"),
    array ( "Country" => 642, "Prefix" => "40", "Code" => "40"),
    array ( "Country" => 643, "Prefix" => "7", "Code" => "7"),
    array ( "Country" => 646, "Prefix" => "250", "Code" => "250"),
    array ( "Country" => 652, "Prefix" => "590", "Code" => "590"),
    array ( "Country" => 654, "Prefix" => "290", "Code" => "290"),
    array ( "Country" => 659, "Prefix" => "1869", "Code" => "1869"),
    array ( "Country" => 660, "Prefix" => "1264", "Code" => "1264"),
    array ( "Country" => 662, "Prefix" => "1758", "Code" => "1758"),
    array ( "Country" => 663, "Prefix" => "590", "Code" => "590"),
    array ( "Country" => 666, "Prefix" => "508", "Code" => "508"),
    array ( "Country" => 670, "Prefix" => "1784", "Code" => "1784"),
    array ( "Country" => 674, "Prefix" => "378", "Code" => "378"),
    array ( "Country" => 678, "Prefix" => "239", "Code" => "239"),
    array ( "Country" => 682, "Prefix" => "966", "Code" => "966"),
    array ( "Country" => 686, "Prefix" => "221", "Code" => "221"),
    array ( "Country" => 688, "Prefix" => "381", "Code" => "381"),
    array ( "Country" => 690, "Prefix" => "248", "Code" => "248"),
    array ( "Country" => 694, "Prefix" => "232", "Code" => "232"),
    array ( "Country" => 702, "Prefix" => "65", "Code" => "65"),
    array ( "Country" => 703, "Prefix" => "421", "Code" => "421"),
    array ( "Country" => 704, "Prefix" => "84", "Code" => "84"),
    array ( "Country" => 705, "Prefix" => "386", "Code" => "386"),
    array ( "Country" => 706, "Prefix" => "252", "Code" => "252"),
    array ( "Country" => 710, "Prefix" => "27", "Code" => "27"),
    array ( "Country" => 716, "Prefix" => "263", "Code" => "263"),
    array ( "Country" => 724, "Prefix" => "34", "Code" => "34"),
    array ( "Country" => 728, "Prefix" => "211", "Code" => "211"),
    array ( "Country" => 729, "Prefix" => "249", "Code" => "249"),
    array ( "Country" => 732, "Prefix" => "212", "Code" => "212"),
    array ( "Country" => 740, "Prefix" => "597", "Code" => "597"),
    array ( "Country" => 744, "Prefix" => "47", "Code" => "47"),
    array ( "Country" => 748, "Prefix" => "268", "Code" => "268"),
    array ( "Country" => 752, "Prefix" => "46", "Code" => "46"),
    array ( "Country" => 756, "Prefix" => "41", "Code" => "41"),
    array ( "Country" => 760, "Prefix" => "963", "Code" => "963"),
    array ( "Country" => 762, "Prefix" => "992", "Code" => "992"),
    array ( "Country" => 764, "Prefix" => "66", "Code" => "66"),
    array ( "Country" => 768, "Prefix" => "228", "Code" => "228"),
    array ( "Country" => 772, "Prefix" => "690", "Code" => "690"),
    array ( "Country" => 776, "Prefix" => "676", "Code" => "676"),
    array ( "Country" => 780, "Prefix" => "1868", "Code" => "1868"),
    array ( "Country" => 784, "Prefix" => "971", "Code" => "971"),
    array ( "Country" => 788, "Prefix" => "216", "Code" => "216"),
    array ( "Country" => 792, "Prefix" => "90", "Code" => "90"),
    array ( "Country" => 795, "Prefix" => "993", "Code" => "993"),
    array ( "Country" => 796, "Prefix" => "1649", "Code" => "1649"),
    array ( "Country" => 798, "Prefix" => "688", "Code" => "688"),
    array ( "Country" => 800, "Prefix" => "256", "Code" => "256"),
    array ( "Country" => 804, "Prefix" => "380", "Code" => "380"),
    array ( "Country" => 807, "Prefix" => "389", "Code" => "389"),
    array ( "Country" => 818, "Prefix" => "20", "Code" => "20"),
    array ( "Country" => 826, "Prefix" => "44", "Code" => "44"),
    array ( "Country" => 831, "Prefix" => "441481", "Code" => "441481"),
    array ( "Country" => 832, "Prefix" => "441534", "Code" => "441534"),
    array ( "Country" => 833, "Prefix" => "441624", "Code" => "441624"),
    array ( "Country" => 834, "Prefix" => "255", "Code" => "255"),
    array ( "Country" => 840, "Prefix" => "1", "Code" => "1"),
    array ( "Country" => 850, "Prefix" => "1340", "Code" => "1340"),
    array ( "Country" => 854, "Prefix" => "226", "Code" => "226"),
    array ( "Country" => 858, "Prefix" => "598", "Code" => "598"),
    array ( "Country" => 860, "Prefix" => "998", "Code" => "998"),
    array ( "Country" => 862, "Prefix" => "58", "Code" => "58"),
    array ( "Country" => 876, "Prefix" => "681", "Code" => "681"),
    array ( "Country" => 882, "Prefix" => "685", "Code" => "685"),
    array ( "Country" => 887, "Prefix" => "967", "Code" => "967"),
    array ( "Country" => 894, "Prefix" => "260", "Code" => "260"),
    array ( "Country" => 654, "Prefix" => "247", "Code" => "247")
  ));

  /**
   * Return structured data
   */
  return $buffer;
}
?>
