<?php
/**   ___ ___       ___ _______     ______                        __
 *   |   Y   .-----|   |   _   |   |   _  \ .-----.--------.---.-|__.-----.
 *   |.  |   |  _  |.  |.  1   |   |.  |   \|  _  |        |  _  |  |     |
 *   |.  |   |_____|.  |.  ____|   |.  |    |_____|__|__|__|___._|__|__|__|
 *   |:  1   |     |:  |:  |       |:  1    /
 *    \:.. ./      |::.|::.|       |::.. . /
 *     `---'       `---`---'       `------'
 *
 * Copyright (C) 2016-2025 Ernani José Camargo Azevedo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * VoIP Domain Yealink equipments module install script.
 *
 * @author     Ernani José Camargo Azevedo <azevedo@voipdomain.io>
 * @version    1.0
 * @package    VoIP Domain
 * @subpackage Equipments Yealink
 * @copyright  2016-2025 Ernani José Camargo Azevedo. All rights reserved.
 * @license    https://www.gnu.org/licenses/gpl-3.0.en.html
 */

/**
 * Hook to create Equipments database
 */
framework_add_hook ( "install_db", "equipments_yealink_install_db");

/**
 * Function to create Yealink equipments database structure.
 *
 * @global array $_in Framework global configuration variable
 * @param string $buffer Buffer from plugin system if processed by other function
 *                       before
 * @param array $parameters Optional parameters to the function
 * @return string Output of the generated page
 */
function equipments_yealink_install_db ( $buffer, $parameters)
{
  global $_in;

  /**
   * Add basic system data
   */
  install_add_db_data ( "Equipments", array (
    array ( "UID" => "cp920", "Vendor" => "Yealink", "Model" => "CP920", "Type" => "IPCP", "SupportLevel" => "Basic", "Description" => "Touch-sensitive HD IP Conference Phone. Note: Product reached EOL.", "Image" => "yealink-cp920.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "https://www.yealink.com/en/product-detail/conference-phone-cp920", "VideoSupport" => 0, "AutoProvision" => 1, "BLFSupport" => 0, "Accounts" => 1, "Shortcuts" => 0, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"G726\",\"OPUS\",\"G723\",\"ILBC\",\"SIREN7\",\"SIREN14\",\"G722\",\"ULAW\",\"ALAW\",\"G729\"]", "AudioCodecs" => "[\"G729\",\"G722\",\"ULAW\",\"ALAW\"]", "SupportedVideoCodecs" => "[]", "VideoCodecs" => "[]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"78.86.0.160\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"78.86.0.160.rom\",\"SHA256\":\"a81f16e5f2af2bb0945c914f82708b11187577368e9edd7101e551c9f65cb957\",\"Size\":22316864,\"Available\":false}]}]", "Active" => 0),
    array ( "UID" => "t19pe2", "Vendor" => "Yealink", "Model" => "SIP-T19(P) E2", "Type" => "IPP", "SupportLevel" => "Basic", "Description" => "Entry-level IP Phone with 1 line. Note: Product reached EOL.", "Image" => "yealink-t19pe2.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "https://www.yealink.com/en/product-detail/ip-phone-t19pe2", "VideoSupport" => 0, "AutoProvision" => 1, "BLFSupport" => 0, "Accounts" => 1, "Shortcuts" => 0, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"G722\",\"ULAW\",\"ALAW\",\"G729\",\"ILBC\",\"G726\",\"OPUS\"]", "AudioCodecs" => "[\"G729\",\"ALAW\",\"ULAW\",\"G722\"]", "SupportedVideoCodecs" => "[]", "VideoCodecs" => "[]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"53.84.0.160\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"53.84.0.160.rom\",\"SHA256\":\"3cc074a609817601df1d7e2e186958fddb101b60957d95df6ddeb51c36108d7f\",\"Size\":8189344,\"Available\":false}]}]", "Active" => 0),
    array ( "UID" => "t21pe2", "Vendor" => "Yealink", "Model" => "SIP-T21(P) E2", "Type" => "IPP", "SupportLevel" => "Basic", "Description" => "Entry-level IP Phone with 2 lines. Note: Product reached EOL.", "Image" => "yealink-t21pe2.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "https://www.yealink.com/en/product-detail/ip-phone-t21pe2", "VideoSupport" => 0, "AutoProvision" => 1, "BLFSupport" => 1, "Accounts" => 2, "Shortcuts" => 2, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"ALAW\",\"ULAW\",\"G729\",\"G722\",\"ILBC\",\"G726\",\"OPUS\"]", "AudioCodecs" => "[\"ALAW\",\"ULAW\",\"G729\",\"G722\"]", "SupportedVideoCodecs" => "[]", "VideoCodecs" => "[]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"52.84.0.160\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"52.84.0.160.rom\",\"SHA256\":\"3ffd44222b0f882339d3cd7daed63e24b504e82bd52c1363f84f01459203733f\",\"Size\":8250784,\"Available\":false}]}]", "Active" => 0),
    array ( "UID" => "t22p", "Vendor" => "Yealink", "Model" => "SIP-T22P", "Type" => "IPP", "SupportLevel" => "Basic", "Description" => "Entry-level IP Phone with 2 lines. Note: Product reached EOL.", "Image" => "yealink-t22p.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "https://www.yealink.com/en/product-detail/ip-phone-t22p", "VideoSupport" => 0, "AutoProvision" => 1, "BLFSupport" => 1, "Accounts" => 2, "Shortcuts" => 3, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\",\"G723\",\"ILBC\",\"G726\"]", "AudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\"]", "SupportedVideoCodecs" => "[]", "VideoCodecs" => "[]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"7.73.0.50\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"7.73.0.50.rom\",\"SHA256\":\"a63c48a39af823de86cbb8445ea663c8ac800401fe700bdcc76474560cff223c\",\"Size\":7321150,\"Available\":false}]}]", "Active" => 0),
    array ( "UID" => "t26p", "Vendor" => "Yealink", "Model" => "SIP-T26P", "Type" => "IPP", "SupportLevel" => "Basic", "Description" => "Entry-level IP Phone with 2 lines. Note: Product reached EOL.", "Image" => "yealink-t26p.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "https://www.yealink.com/en/product-detail/ip-phone-t26p", "VideoSupport" => 0, "AutoProvision" => 1, "BLFSupport" => 1, "Accounts" => 2, "Shortcuts" => 10, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"G722\",\"ULAW\",\"ALAW\",\"G729\",\"G723\",\"ILBC\",\"G726\"]", "AudioCodecs" => "[\"G722\",\"ULAW\",\"ALAW\",\"G729\"]", "SupportedVideoCodecs" => "[]", "VideoCodecs" => "[]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"6.73.0.50\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"6.73.0.50.rom\",\"SHA256\":\"e1ee545ebf337be62ec4d7a2e019cb4ce16c0a150d6d96ea12c5f157eeec5d08\",\"Size\":7337534,\"Available\":false}]}]", "Active" => 0),
    array ( "UID" => "t29g", "Vendor" => "Yealink", "Model" => "SIP-T29G", "Type" => "IPP", "SupportLevel" => "Basic", "Description" => "Entry-level IP Phone with 2 lines. Note: Product reached EOL.", "Image" => "yealink-t29g.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "https://www.yealink.com/en/product-detail/ip-phone-t29g", "VideoSupport" => 0, "AutoProvision" => 1, "BLFSupport" => 1, "Accounts" => 16, "Shortcuts" => 10, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"ALAW\",\"ULAW\",\"G729\",\"G722\",\"G723\",\"ILBC\",\"G726\"]", "AudioCodecs" => "[\"ALAW\",\"ULAW\",\"G729\",\"G722\"]", "SupportedVideoCodecs" => "[]", "VideoCodecs" => "[]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"46.83.0.160\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"46.83.0.160.rom\",\"SHA256\":\"dcde198c1426fc54a072c728455ac1a418bafe9726b2c9c68c284d02f821246b\",\"Size\":23320080,\"Available\":false}]}]", "Active" => 0),
    array ( "UID" => "t30p", "Vendor" => "Yealink", "Model" => "SIP-T30(P)", "Type" => "IPP", "SupportLevel" => "Basic", "Description" => "Single line entry level IP Phone.", "Image" => "yealink-t30p.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "https://www.yealink.com/en/product-detail/ip-phone-t30p", "VideoSupport" => 0, "AutoProvision" => 1, "BLFSupport" => 0, "Accounts" => 1, "Shortcuts" => 0, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"ILBC\",\"ALAW\",\"ULAW\",\"G726\",\"G723\",\"G729\",\"G722\",\"OPUS\",\"G729A\"]", "AudioCodecs" => "[\"ILBC\",\"ALAW\",\"ULAW\",\"G726\",\"G723\",\"G729\",\"G722\"]", "SupportedVideoCodecs" => "[]", "VideoCodecs" => "[]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"124.86.0.40\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"124.86.0.40.rom\",\"SHA256\":\"4b62531528191a0032bc2d7461227350455d71d9fbc29b5e72a2954b67dfb520\",\"Size\":11951664,\"Available\":false}]}]", "Active" => 0),
    array ( "UID" => "t40p", "Vendor" => "Yealink", "Model" => "SIP-T40P", "Type" => "IPP", "SupportLevel" => "Basic", "Description" => "Cost-effective Enterprise IP Phone.", "Image" => "yealink-t40p.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "https://www.yealink.com/en/product-detail/ip-phone-t40p", "VideoSupport" => 0, "AutoProvision" => 1, "BLFSupport" => 1, "Accounts" => 3, "Shortcuts" => 3, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"ALAW\",\"ULAW\",\"G729\",\"G722\",\"ILBC\",\"G726\",\"OPUS\"]", "AudioCodecs" => "[\"ALAW\",\"ULAW\",\"G729\",\"G722\"]", "SupportedVideoCodecs" => "[]", "VideoCodecs" => "[]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"54.84.0.160\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"54.84.0.160.rom\",\"SHA256\":\"211febd6c17102c8542cfaaca748d6f77d69c6585c2dfcc1895690101f653bec\",\"Size\":8275360,\"Available\":false}]}]", "Active" => 0),
    array ( "UID" => "t46s", "Vendor" => "Yealink", "Model" => "SIP-T46S", "Type" => "IPP", "SupportLevel" => "Basic", "Description" => "Ultra-elegant business IP Phone with 2 lines. Note: Product reached EOL.", "Image" => "yealink-t46s.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "https://www.yealink.com/en/product-detail/ip-phone-t46s", "VideoSupport" => 0, "AutoProvision" => 1, "BLFSupport" => 1, "Accounts" => 16, "Shortcuts" => 10, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"G722\",\"ULAW\",\"ALAW\",\"G729\",\"G723\",\"ILBC\",\"G726\",\"OPUS\"]", "AudioCodecs" => "[\"G722\",\"ULAW\",\"ALAW\",\"G729\"]", "SupportedVideoCodecs" => "[]", "VideoCodecs" => "[]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"66.86.0.160\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"66.86.0.160.rom\",\"SHA256\":\"8df13696b3367b42bd099029fa7f7c65896283a39315b87e6c38dedb3de93d38\",\"Size\":23332560,\"Available\":false}]}]", "Active" => 0),
    array ( "UID" => "t20p", "Vendor" => "Yealink", "Model" => "SIP-T20P", "Type" => "IPP", "SupportLevel" => "Basic", "Description" => "Entry-level IP Phone with 2 lines. Note: Product reached EOL.", "Image" => "yealink-t20p.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "https://www.yealink.com/en/product-detail/ip-phone-t20p", "VideoSupport" => 0, "AutoProvision" => 1, "BLFSupport" => 1, "Accounts" => 2, "Shortcuts" => 2, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\",\"G723\",\"ILBC\",\"G726\"]", "AudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\"]", "SupportedVideoCodecs" => "[]", "VideoCodecs" => "[]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"9.73.0.50\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"9.73.0.50.rom\",\"SHA256\":\"2fdeb0fbe5a4116e62b870344481c21ba8483e951f70f839960756fbc10f09ed\",\"Size\":7067198,\"Available\":false}]}]", "Active" => 0),
    array ( "UID" => "t27g", "Vendor" => "Yealink", "Model" => "SIP-T27G", "Type" => "IPP", "SupportLevel" => "Basic", "Description" => "Cost-effective Multi-line IP Phone. Note: Product reached EOL.", "Image" => "yealink-t27g.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "https://www.yealink.com/en/product-detail/ip-phone-t27g", "VideoSupport" => 0, "AutoProvision" => 1, "BLFSupport" => 1, "Accounts" => 6, "Shortcuts" => 8, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\",\"G723\",\"ILBC\",\"G726\",\"OPUS\"]", "AudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\"]", "SupportedVideoCodecs" => "[]", "VideoCodecs" => "[]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"69.86.0.160\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"69.86.0.160.rom\",\"SHA256\":\"0f9c32c66f01ffdf8ec1c4665a9705cb8768f089c083e2e1e1671da4f034c3e6\",\"Size\":17164960,\"Available\":false}]}]", "Active" => 0),
    array ( "UID" => "t38g", "Vendor" => "Yealink", "Model" => "SIP-T38G", "Type" => "IPP", "SupportLevel" => "Basic", "Description" => "Cost-effective Multi-line IP Phone. Note: Product reached EOL.", "Image" => "yealink-t38g.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "https://www.yealink.com/en/product-detail/ip-phone-t38g", "VideoSupport" => 0, "AutoProvision" => 1, "BLFSupport" => 1, "Accounts" => 6, "Shortcuts" => 16, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\",\"G723\",\"ILBC\",\"G726\",\"OPUS\"]", "AudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\"]", "SupportedVideoCodecs" => "[]", "VideoCodecs" => "[]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"38.70.0.221\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"38.70.0.221.rom\",\"SHA256\":\"03db1f2e0e70e68f7f1a189dcb282aab4509775f5668c9b6224f25bf188381c1\",\"Size\":24924432,\"Available\":false}]}]", "Active" => 0),
    array ( "UID" => "t23p", "Vendor" => "Yealink", "Model" => "SIP-T23P", "Type" => "IPP", "SupportLevel" => "Basic", "Description" => "Cost-effective HD voice IP Phone. Note: Product reached EOL.", "Image" => "yealink-t23p.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "https://www.yealink.com/en/product-detail/ip-phone-t23p", "VideoSupport" => 0, "AutoProvision" => 1, "BLFSupport" => 1, "Accounts" => 2, "Shortcuts" => 3, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\",\"G723\",\"ILBC\",\"G726\",\"OPUS\"]", "AudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\"]", "SupportedVideoCodecs" => "[]", "VideoCodecs" => "[]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"44.84.0.160\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"44.84.0.160.rom\",\"SHA256\":\"bac96fd0e8385521e607fd38b5a9b2e5bf7008761a256632ddfe74080495c1fe\",\"Size\":8218016,\"Available\":false}]}]", "Active" => 0),
    array ( "UID" => "t23g", "Vendor" => "Yealink", "Model" => "SIP-T23G", "Type" => "IPP", "SupportLevel" => "Basic", "Description" => "Cost-effective HD voice IP Phone. Note: Product reached EOL.", "Image" => "yealink-t23g.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "https://www.yealink.com/en/product-detail/ip-phone-t23g", "VideoSupport" => 0, "AutoProvision" => 1, "BLFSupport" => 1, "Accounts" => 2, "Shortcuts" => 3, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\",\"G723\",\"ILBC\",\"G726\",\"OPUS\"]", "AudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\"]", "SupportedVideoCodecs" => "[]", "VideoCodecs" => "[]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"44.84.0.160\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"44.84.0.160.rom\",\"SHA256\":\"bac96fd0e8385521e607fd38b5a9b2e5bf7008761a256632ddfe74080495c1fe\",\"Size\":8218016,\"Available\":false}]}]", "Active" => 0),
    array ( "UID" => "t27p", "Vendor" => "Yealink", "Model" => "SIP-T27P", "Type" => "IPP", "SupportLevel" => "Basic", "Description" => "Cost-effective Multi-line IP Phone. Note: Product reached EOL.", "Image" => "yealink-t27p.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "https://www.yealink.com/en/product-detail/ip-phone-t27p", "VideoSupport" => 0, "AutoProvision" => 1, "BLFSupport" => 1, "Accounts" => 6, "Shortcuts" => 8, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\",\"G723\",\"ILBC\",\"G726\",\"OPUS\"]", "AudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\"]", "SupportedVideoCodecs" => "[]", "VideoCodecs" => "[]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"45.83.0.160\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"45.83.0.160.rom\",\"SHA256\":\"fd44d59a0fc1e869a5e451822b792f9e1523ab8893e94dde5d21e2001c59b5f8\",\"Size\":8360272,\"Available\":false}]}]", "Active" => 0),
    array ( "UID" => "t48s", "Vendor" => "Yealink", "Model" => "SIP-T48S", "Type" => "IPP", "SupportLevel" => "Basic", "Description" => "Ultra-elegant business IP Phone. Note: Product reached EOL.", "Image" => "yealink-t48s.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "https://www.yealink.com/en/product-detail/ip-phone-t48s", "VideoSupport" => 0, "AutoProvision" => 1, "BLFSupport" => 1, "Accounts" => 16, "Shortcuts" => 29, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\",\"G723\",\"ILBC\",\"G726\",\"OPUS\"]", "AudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\"]", "SupportedVideoCodecs" => "[]", "VideoCodecs" => "[]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"66.86.0.160\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"66.86.0.160.rom\",\"SHA256\":\"8df13696b3367b42bd099029fa7f7c65896283a39315b87e6c38dedb3de93d38\",\"Size\":23332560,\"Available\":false}]}]", "Active" => 0),
    array ( "UID" => "t31", "Vendor" => "Yealink", "Model" => "SIP-T31", "Type" => "IPP", "SupportLevel" => "Basic", "Description" => "Classic business IP Phone.", "Image" => "yealink-t31.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "https://www.yealink.com/en/product-detail/ip-phone-t31", "VideoSupport" => 0, "AutoProvision" => 1, "BLFSupport" => 1, "Accounts" => 2, "Shortcuts" => 2, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\",\"G723\",\"ILBC\",\"G726\",\"OPUS\",\"G729A\"]", "AudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\"]", "SupportedVideoCodecs" => "[]", "VideoCodecs" => "[]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"124.86.0.40\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"124.86.0.40.rom\",\"SHA256\":\"4b62531528191a0032bc2d7461227350455d71d9fbc29b5e72a2954b67dfb520\",\"Size\":11951664,\"Available\":false}]}]", "Active" => 0),
    array ( "UID" => "t31p", "Vendor" => "Yealink", "Model" => "SIP-T31P", "Type" => "IPP", "SupportLevel" => "Basic", "Description" => "Classic business IP Phone.", "Image" => "yealink-t31.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "https://www.yealink.com/en/product-detail/ip-phone-t31p", "VideoSupport" => 0, "AutoProvision" => 1, "BLFSupport" => 1, "Accounts" => 2, "Shortcuts" => 2, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\",\"G723\",\"ILBC\",\"G726\",\"OPUS\",\"G729A\"]", "AudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\"]", "SupportedVideoCodecs" => "[]", "VideoCodecs" => "[]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"124.86.0.40\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"124.86.0.40.rom\",\"SHA256\":\"4b62531528191a0032bc2d7461227350455d71d9fbc29b5e72a2954b67dfb520\",\"Size\":11951664,\"Available\":false}]}]", "Active" => 0),
    array ( "UID" => "t31g", "Vendor" => "Yealink", "Model" => "SIP-T31G", "Type" => "IPP", "SupportLevel" => "Basic", "Description" => "Classic business IP Phone.", "Image" => "yealink-t31.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "https://www.yealink.com/en/product-detail/ip-phone-t31g", "VideoSupport" => 0, "AutoProvision" => 1, "BLFSupport" => 1, "Accounts" => 2, "Shortcuts" => 2, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\",\"G723\",\"ILBC\",\"G726\",\"OPUS\",\"G729A\"]", "AudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\"]", "SupportedVideoCodecs" => "[]", "VideoCodecs" => "[]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"124.86.0.40\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"124.86.0.40.rom\",\"SHA256\":\"4b62531528191a0032bc2d7461227350455d71d9fbc29b5e72a2954b67dfb520\",\"Size\":11951664,\"Available\":false}]}]", "Active" => 0),
    array ( "UID" => "t28p", "Vendor" => "Yealink", "Model" => "SIP-T28P", "Type" => "IPP", "SupportLevel" => "Basic", "Description" => "Cost-effective Multi-line IP Phone. Note: Product reached EOL.", "Image" => "yealink-t28p.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "https://www.yealink.com/en/product-detail/ip-phone-t28p", "VideoSupport" => 0, "AutoProvision" => 1, "BLFSupport" => 1, "Accounts" => 6, "Shortcuts" => 16, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\",\"G723\",\"G726\"]", "AudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\"]", "SupportedVideoCodecs" => "[]", "VideoCodecs" => "[]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"2.73.0.50\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"2.73.0.50.rom\",\"SHA256\":\"eb264dfe4a76f0777e2825287e5f3bb0ef0785768313e2419f2fb6f728fcb26c\",\"Size\":7358014,\"Available\":false}]}]", "Active" => 0),
    array ( "UID" => "vp530", "Vendor" => "Yealink", "Model" => "VP530", "Type" => "IPVP", "SupportLevel" => "Basic", "Description" => "Business IP Video Phone. Note: Product reached EOL.", "Image" => "yealink-vp530.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "https://www.yealink.com/en/product-detail/ip-phone-vp530", "VideoSupport" => 1, "AutoProvision" => 1, "BLFSupport" => 1, "Accounts" => 4, "Shortcuts" => 22, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\",\"G723\",\"ILBC\"]", "AudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\"]", "SupportedVideoCodecs" => "[\"H264\",\"H263\",\"MPEG4\"]", "VideoCodecs" => "[\"H264\",\"H263\",\"MPEG4\"]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"23.70.0.63\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"23.70.0.63.rom\",\"SHA256\":\"07f43b32b04e5ed0a977270ad6c4c36a5411e8331a0322445bd77687e1dcd88b\",\"Size\":33627392,\"Available\":false}]}]", "Active" => 0),
    array ( "UID" => "t18p", "Vendor" => "Yealink", "Model" => "SIP-T18(P)", "Type" => "IPP", "SupportLevel" => "Basic", "Description" => "Basic simple IP phone. Note: Product reached EOL.", "Image" => "yealink-t18p.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "", "VideoSupport" => 0, "AutoProvision" => 1, "BLFSupport" => 0, "Accounts" => 1, "Shortcuts" => 0, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\",\"G723\",\"G726\"]", "AudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\"]", "SupportedVideoCodecs" => "[]", "VideoCodecs" => "[]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"18.0.0.162\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"18.0.0.162.rom\",\"SHA256\":\"\",\"Size\":0,\"Available\":false}]}]", "Active" => 0),
    array ( "UID" => "t21p", "Vendor" => "Yealink", "Model" => "SIP-T21(P)", "Type" => "IPP", "SupportLevel" => "Basic", "Description" => "Entry-level IP Phone with 2 lines. Note: Product reached EOL.", "Image" => "yealink-t21p.png", "VendorLink" => "https://yealink.com/", "ModelLink" => "", "VideoSupport" => 0, "AutoProvision" => 1, "BLFSupport" => 1, "Accounts" => 2, "Shortcuts" => 2, "Extensions" => 0, "ShortcutsPerExtension" => 0, "SupportedAudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\",\"G723\",\"G726\",\"ILBC\"]", "AudioCodecs" => "[\"ULAW\",\"ALAW\",\"G729\",\"G722\"]", "SupportedVideoCodecs" => "[]", "VideoCodecs" => "[]", "ExtraSettings" => "{\"User\":{\"Name\":\"user\",\"Password\":\"vduser\"},\"Admin\":{\"Name\":\"admin\",\"Password\":\"vdadmin\"}}", "SupportedFirmwares" => "[{\"Version\":\"34.72.0.200\",\"Priority\":0,\"Available\":false,\"Files\":[{\"Filename\":\"34.72.0.200.rom\",\"SHA256\":\"65027df558b231e121ac9da8279e08cb5517d1b9490e06d36b1e3795589dff7d\",\"Size\":7833280,\"Available\":false}]}]", "Active" => 0)
  ));

  /**
   * Return structured data
   */
  return $buffer;
}
?>
